[BE] chore: H2를 테스트에서만 사용하도록 설정, 외부 의존성 버전 명시
woowacourse-teams/2024-review-me pull request #1010
Opened 2024-12-15 07:52 UTC by donghoony

- resolves #1009 

---

### 🚀 어떤 기능을 구현했나요 ?
- 기능 구현한 사항은 없습니다.

### 🔥 어떻게 해결했나요 ?
- 각각의 외부 의존성에 버전을 명시했습니다.
- `openapi-starter-webmvc`를 제거했습니다 (swagger의 잔재 ㅋㅋ)

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 불필요한 의존성이 있는지만 확인해주세요!

### 📚 참고 자료, 할 말
- Springboot 관련 의존성은 plugin으로 되어 따로 작성하지 않는 것이 권장됩니다. [이곳](https://docs.spring.io/spring-boot/reference/using/build-systems.html)을 확인해 주세요
> Each release of Spring Boot is associated with a base version of the Spring Framework. We highly recommend that you do not specify its version.

2024-12-15 09:33 UTC, nayonsoso approved these changes
왜 이걸 지금 알았을까요^^ 머쓱..

그런데 일부 라이브러리 버전은 왜 명시하도록 바뀐건가요?
그리고 나머지 라이브러리에는 버전을 명시하지 않은 이유가 있나요?

2024-12-15 10:54 UTC, donghoony commented
> 그런데 일부 라이브러리 버전은 왜 명시하도록 바뀐건가요? 그리고 나머지 라이브러리에는 버전을 명시하지 않은 이유가 있나요?

참고 자료, 할 말을 확인해주세용~

2024-12-15 13:32 UTC, skylar1220 commented
외부 의존성 역시 스프링이 호환되는 버전을 자동으로 관리해주고 있는 것으로 알아서 버전 명시가 없어도 될 것 같아요~
https://docs.spring.io/spring-boot/appendix/dependency-versions/coordinates.html

2024-12-15 13:33 UTC, hyeonji1220 requested changes
외부 의존성 역시 스프링이 호환되는 버전을 자동으로 관리해주고 있는 것으로 알아서 버전 명시가 없어도 될 것 같아요~
https://docs.spring.io/spring-boot/appendix/dependency-versions/coordinates.html

2024-12-17 05:53 UTC, skylar1220 approved these changes

2024-12-18 07:45 UTC, Kimprodp approved these changes

2024-12-18 07:46 UTC, merged