[BE] docs: GitHub 연동, 자신이 만든 리뷰 그룹 목록 조회 API 문서 작성
woowacourse-teams/2024-review-me pull request #1014
Opened 2024-12-19 05:55 UTC by donghoony

- resolves #1013 

---

## 아직 안 됐습니다~
우선 나의 리뷰 그룹 목록 보기만 만들어두었어요

### 🚀 어떤 기능을 구현했나요 ?
- 

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 더 나은 네이밍이 있다면 말씀해주세요 ~

2024-12-19 18:22 UTC, nayonsoso reviewed
아루를 위한 보충 설명

2024-12-19 18:22 UTC, nayonsoso commented on backend/src/main/java/reviewme/auth/controller/AuthController.java
> +    }
API docs 에 로그아웃 시 헤더에`SetCookie:JSESSIONID="";` 가 반환된다는 것을 나타내려다보니
로그아웃 구현을 다 하게 되었습니다...

2024-12-19 18:22 UTC, nayonsoso commented on backend/src/main/java/reviewme/member/controller/MemberController.java
> +    }
profile 에 s 를 붙일까말까 고민했는데, 리소스라기보다 특성에 가깝다 생각해서 안붙였습니다.
e.g. profile 이 reviews/detail 에서 detail 과 비슷하다 생각했어요!

2024-12-19 18:22 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
> +    }
이 URL 도 /v2/members/groups 혹은 /v2/members/groups/mine 으로 바꾸고,
reviewgroup 패키지 하위에 MemberReviewGroupController 를 만든 다음 거기로 매핑 함수를 옮기는게 어떨지 제안해봅니다..! 

근거는 이 코멘트에 남겨뒀어요 https://github.com/woowacourse-teams/2024-review-me/pull/1017#discussion_r1892949613

2024-12-20 09:21 UTC, skylar1220 requested changes
아루 산쵸 몇개 질문 남겨요~~🔎

2024-12-20 09:21 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupDetailResponse.java
> +public record ReviewGroupDetailResponse(
이전에 내가 받은 리뷰 보기에서는 
목록을 List, 목록의 각 카드를 element라고 네이밍했던 것 같은데 통일은 필요없을까요? 
저는 Detail이라고 하니까 클릭해서 들어가면 뜨는 상세 화면을 떠올리게 돼서요!

2024-12-20 09:21 UTC, skylar1220 commented on backend/src/main/java/reviewme/auth/controller/AuthController.java
> +        session.invalidate();
session이 null인 경우는 없을까요?

2024-12-20 09:21 UTC, skylar1220 commented on backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupListResponse.java
> +        boolean isLastPage,
내가 받은 리뷰와 동일하게 무한스크롤 구현을 생각해서요~ lastReviewId 필드는 필요하지 않을까요?

2024-12-20 09:21 UTC, skylar1220 commented on backend/src/main/java/reviewme/auth/controller/AuthController.java
> +    }
산초가 올려준 디스커션의 인증 과정중 아래의 1~3번을 이 메서드에서 모두 하는것인지 궁금해요!(아직 구현이 안해서 헷갈려서 물어봅니당)
1. auth code를 받음 
2. 그걸로 깃헙에 accessToken을 요청함
3. 받은 accessToken으로 깃헙에 사용자의 정보를 요청해서 세션을 설정해 응답함

2024-12-20 09:23 UTC, skylar1220 commented on backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
> +    }
요거 저희쪽 api랑 함께 쫌만 더 생각해볼게요..

2024-12-20 17:28 UTC, nayonsoso commented on backend/src/main/java/reviewme/auth/controller/AuthController.java
> +    }
네 맞아요👍

2024-12-21 13:48 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupDetailResponse.java
> +public record ReviewGroupDetailResponse(
오~ 네이밍 통일! 좋은 지적이네요! 

지금 목록을 응답하는 곳은 [내가 받은 리뷰] 밖에 없는데, 여기랑 통일해주면 좋을 것 같아요.
[내가 받은 리뷰] 에서는 아래와 같이 되어있는데,,,,
- 목록 : ReceivedReviewsResponse
- 목록의 각 요소 : ReviewListElementResponse

 사실 이것도 수정하면 좋겠거든요..? 😅
목록을 응답하는 dto 네이밍을 아래와 같이 통일하는게 어떤가요?

- 목록 : ___**_List_** Response
  - 내가 받은 리뷰 목록 : ReceivedReviewListResponse
  - 내가 만든 리뷰 그룹 목록 : ReviewGroupListResponse
- 목록의 각 요소 : ___**_ListElement_** Response
  - 내가 받은 리뷰의 각 요소 : ReceivedReviewElementResponse
  - 내가 만든 리뷰 그룹의 각 요소 : ReviewGroupListElementResponse

2024-12-21 13:58 UTC, nayonsoso commented on backend/src/main/java/reviewme/auth/controller/AuthController.java
> +        session.invalidate();
![image](https://github.com/user-attachments/assets/5d3cc1bc-3126-4963-9702-6ff8f381c3e6)

httpRequest.getSession() 는 세션이 있으면 그것을 반환하고, 없으면 만들어서 반환하기에 NPE 가 발생할 일은 없다고 합니다!
그런데 더 찾아보니 로그아웃 api 에서는 '세션이 없으면 만드는 것'을 할 필욘 없으니
`getSession(boolean create)` 함수를 사용해서, 새로 세션을 만들지 않도록 변경해주었습니다!

당연하게 세션이 null 일 경우는 없을것이라 생각했는데, 짚어줘서 고맙습니다😊

2024-12-21 14:02 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupListResponse.java
> +        boolean isLastPage,
사실 일반적인 사용자가 무한 스크롤이 필요할 정도로 많은 리뷰 그룹을 만들 것이라고 생각되진 않는데요..! 🤔
그럼에도 [통일성 / 악의적인 무리한 요청 방지]를 위해서 무스를 추가해줘야 하려나요!
일단 다른 분들의 의견도 들어보겠습니다

2024-12-21 14:52 UTC, donghoony commented on backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
> +    }
URI는 리소스를 찾습니다. 나의 **그룹**을 찾고 싶다면, `groups` 아래로 들어가는 것이 더 괜찮다고 생각해요.

2024-12-21 14:53 UTC, donghoony commented on backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupDetailResponse.java
> +public record ReviewGroupDetailResponse(
페이지네이션이니까 `Page`가 들어가면 어떨까요..? `PageElement`와 같이요

2024-12-21 14:53 UTC, donghoony commented on backend/src/main/java/reviewme/auth/controller/AuthController.java
> +        session.invalidate();
구현 사항이라 리뷰하지 않을게요~

2024-12-21 14:54 UTC, donghoony commented on backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupListResponse.java
> +        boolean isLastPage,
무한 스크롤 / 페이징을 여러 군데에서 사용할 것으로 보이는데, 따로 함수로 빼야할 것 같기도 하고.. 🤔

2024-12-21 15:49 UTC, nayonsoso commented on backend/src/main/java/reviewme/auth/controller/AuthController.java
> +        session.invalidate();
지금은 롤백했습니다 👍

2024-12-23 07:29 UTC, Kimprodp requested changes
리뷰 몇 개 남깁니다!

2024-12-23 07:29 UTC, Kimprodp commented on backend/src/main/java/reviewme/member/controller/MemberController.java
> +    }
URI 다시 한번 논의해보자고 말 했지만, 기록상 남깁니다.

사용자의 프로필을 조회하는데 uri 계층이 너무 길다고 생각해요.
그리고 mine 이라는 표현이 자원보다 호출자에게 조금 더 집중된 표현이라고 생각해서 `/v2/members/profile`가 더 적절해 보입니다.

2024-12-23 07:29 UTC, Kimprodp commented on backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupListResponse.java
> +        boolean isLastPage,
페이징 적용해서 나쁠건 없다고 생각합니다~ 
현재 내용은 한번에 보내주는 걸로 설계한 것으로 보이는데  `isLastPage `는 다른 용도가 있나요?

2024-12-23 07:29 UTC, Kimprodp commented on backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupDetailResponse.java
> +) {
프로젝트 목록에서 해당 프로젝트에 리뷰가 몇 개 작성되어있는지도 같이 제공하면 어떨까요?

2024-12-23 11:29 UTC, nayonsoso commented on backend/src/main/java/reviewme/member/controller/MemberController.java
> +    }
1. 나중 일이긴 하지만, '다른 사람의 프로필 조회'와 같은 기능이 추가된다면 `/v2/members/profile` 가 헷갈릴 거라 생각했어요😓

2. 자원에 완전 집중한다면 차라리 `/v2/members/{memberId}/profile` 가 적합할 수도 있겠지만,,
이 api 는 세션으로만 호출하는 것이기 때문에 클라이언트가 id 를 모를것이라,
호출자를 고려할 수 밖에 없는 것 같아요.


하지만 이 uri 자체에 대해서 주장이 강한건 아니라, 다른 사람들도 테드의 의견에 동의하면 그대로 따라갈게요!
빠른 의견 취합을 위해서 디코에 바로 올리겠습니다 💁🏻‍♀️

2024-12-23 11:30 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupDetailResponse.java
> +public record ReviewGroupDetailResponse(
@donghoony 그럼 
목록 : PageResponse / 요소 : PageElement 말씀인가요?

이것도 사실 엄청 논의할건 아니라 생각해서, 빠른 취합을 위해 다수결로 결정하는게 좋을 것 같네요!

2024-12-23 11:59 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupListResponse.java
> +        boolean isLastPage,
그럼 페이징 적용하는 것으로 하겠습니다👍

@Kimprodp 
isLastPage 를 내려주면 클라이언트 측에서 '이게 마지막 페이지이구나, 더 이상 요청을 보내면 안되겠구나'를 알 수 있습니다.
따라서 더 이상 로딩이 안되게 하거나 / ui 면에서 차이를 둘 수 있습니다.
이를 위해서 내려주고 있습니다!

2024-12-23 11:59 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupDetailResponse.java
> +) {
오~ 괜찮은데요? 이건 프론트 분들이랑 이야기를 해봐야 할 것 같아요!

2024-12-24 01:14 UTC, Kimprodp requested changes
리뷰 확인 및 추가 코멘트 남겼어요 확인 부탁합니다(__)

2024-12-24 01:14 UTC, Kimprodp commented on backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupListResponse.java
> +        boolean isLastPage,
아 제가 물어본건 페이징이 안되어있는데 저 필드가 있어서 물어본거였슴당

2024-12-24 01:14 UTC, Kimprodp commented on backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupListResponse.java
> +public record ReviewGroupListResponse(
어떤 회원의 그룹 목록인지 확인할 수 있도록 memberId 필드에 추가하는 건 어떻게 생각하시나요?

https://github.com/woowacourse-teams/2024-review-me/pull/1017#discussion_r1893667815
저희가 작업한 dto와 같은 이유입니다~

2024-12-24 01:14 UTC, Kimprodp commented on backend/src/main/java/reviewme/auth/controller/AuthController.java
> +    }
혹시 이때 사용자 정보나 로그인 정보같은 것은 안내려줘도 괜찮나요?

2024-12-27 15:27 UTC, nayonsoso commented on backend/src/main/java/reviewme/member/controller/MemberController.java
> +    }
🗳️ 투표 결과 : **/v2/members/profile** 로 결정 완!

2024-12-27 15:28 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupDetailResponse.java
> +public record ReviewGroupDetailResponse(
🗳️ 투표 결과 : PageResponse / PageElementResponse 로 결정되었음

2024-12-27 15:35 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupListResponse.java
> +        boolean isLastPage,
@Kimprodp 
페이징될 수 있게 `long lastReviewGroupId` 도 추가해줬습니다 👍

2024-12-27 15:39 UTC, nayonsoso commented on backend/src/main/java/reviewme/auth/controller/AuthController.java
> +    }
@Kimprodp 
사용자 정보를 따로 넘겨주기보다, 클라이언트와는 JSESSION_ID로만 로그인한 사용자에 대한 통신을 하면 된다 생각해요!

2024-12-27 15:51 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/service/dto/ReviewGroupListResponse.java
> +public record ReviewGroupListResponse(
음 이거에 대해서 다시 생각해봤는데, 불필요한 응답 같다고 다시 생각을 바꾸게 되었어요///😔
https://github.com/woowacourse-teams/2024-review-me/pull/1017#discussion_r1898592548
여기에 코멘트 달아놨습니다!

2024-12-27 17:29 UTC, donghoony commented on backend/src/main/java/reviewme/auth/controller/AuthController.java
> +    }
정보를 1회성으로 내려주는 게 좋을까요, 프론트에서 정보를 확인할 수 있는 API를 뚫어두는 게 좋을까요?

2024-12-29 18:53 UTC, nayonsoso approved these changes

2024-12-30 01:30 UTC, Kimprodp requested changes
이전에 수정한 케이스랑 동일한게 있어서 하나만 더 확인해주십쇼

2024-12-30 01:30 UTC, Kimprodp commented on backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
> +    public ResponseEntity<ReviewGroupPageResponse> getMyReviewGroups() {
https://github.com/woowacourse-teams/2024-review-me/pull/1014#discussion_r1895335285
같은 이유입니다~

getReviewGroupSummary의 api를 `/groups/summary`로 하고,
여기에는 mine을 빼고 `/groups` 까지만 하는 것이 괜찮아 보입니다.

2024-12-30 05:03 UTC, skylar1220 approved these changes

2024-12-30 05:05 UTC, skylar1220 commented on backend/src/main/java/reviewme/auth/controller/AuthController.java
> +    }
1. 1회성이라는 건: 어떤 뜻인지 잘 모르겠어요
2. 프론트에서 정보를 확인할 수 있는 API: 사용자 세션을 갖고 프로필 api를 찌르게 하는 것
을 말하는 게 맞을까요? 그렇다면 저는 2번을 생각했었어요~

2025-01-07 17:01 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
> +    public ResponseEntity<ReviewGroupPageResponse> getMyReviewGroups() {
GET `/groups` 는 그룹 자체에 대한 정보에 더 가깝다고 생각합니다.
'내가 만든 리뷰 그룹'을 나타내기에는 조금 부족하다는 생각이 드는데,
`/v2/groups/authored` 는 어떤가요?

2025-01-09 01:15 UTC, Kimprodp requested changes

2025-01-09 01:15 UTC, Kimprodp commented on backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
> +    public ResponseEntity<ReviewGroupPageResponse> getMyReviewGroups() {
GET /groups 복수 이기 때문에 목록에 대한 의미가 더 가깝지 않나요?
만약 개별 그룹 자체에 대한 의미라면 GET /groups/{id} 형식이 된다고 생각해요.
그리고 그룹 목록을 조회하는데 /groups/authored 까지 하면 불필요하게 뎁스가 하나 더 추가 된다고 생각해요.
세션을 통해 로그인 사용자는 식별되니 /groups 만으로 충분하다 생각합니다.

2025-01-09 03:15 UTC, skylar1220 commented on backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
> +    public ResponseEntity<ReviewGroupPageResponse> getMyReviewGroups() {
현재는 내가 만든 리뷰 그룹밖에 없는데 리뷰 그룹과 관련한 다른 api가 추가될지 몰라요. (예: 내가 참여한 리뷰 그룹)
그렇다면 기존 api uri까지 바꿔야하는 상황(이번에 내가 받은 리뷰만 있었는데 내가 작성한 리뷰가 생겨서 기존 api의 uri도 바뀜)을 지양하려면 구체적인 맥락을 uri에 추가해줘야한다고 생각해요

2025-01-09 05:01 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
> +    public ResponseEntity<ReviewGroupPageResponse> getMyReviewGroups() {
커비 의견에 완전 동의하구요! 덧붙이자면 내가 작성한 리뷰를 /reviews/authored 로 하면, 내가 생성란 리뷰도 /groups/authored  가져가는게 더 통일감있다 느껴집니다.

2025-01-10 06:53 UTC, Kimprodp commented on backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
> +    public ResponseEntity<ReviewGroupPageResponse> getMyReviewGroups() {
api를 한 번 정하면 수정할 때 많은 협의가 필요하니 신중하네요..
사실 자원의 계층을 나타내는 것이 아니라, 동일한 자원인데 조건에 따라서 뎁스가 늘어나는 것 같아서 맞는건지 조금 헷갈려요. 자원의 계층적 구조를 명확하게 나타내려면 `/me/authored/reviews` 와 같은 형식으로 가는게 맞다고 생각하는데.. 이미 다른 api들이 이렇게 되어있으니 일단은 통일성 있게 가져가는 것을 우선시 하겠습니다.

2025-01-10 07:04 UTC, Kimprodp approved these changes

2025-01-10 08:49 UTC, donghoony commented on backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
> +    public ResponseEntity<ReviewGroupPageResponse> getMyReviewGroups() {
동감해요. 리소스 측면에서 바라보면 /groups가 그룹들을 가져올 것을 이미 충분히 기대할 수 있다고 생각해요. 더 specific한 건 쿼리 파라미터로 나타내면 되고요.

2025-01-12 08:59 UTC, merged