[BE] docs: 작성한 리뷰 목록 조회, 회원용 리뷰 그룹 생성, 리뷰 그룹 정보, 리뷰 등록 API 문서를 작성한다.
woowacourse-teams/2024-review-me pull request #1017
Opened 2024-12-19 12:26 UTC by Kimprodp

- resolves #1015 

---

### 🚀 어떤 기능을 구현했나요 ?
다음과 같은 API 문서를 작성했습니다.
- 작성한 리뷰 목록 조회
- 회원용 리뷰 그룹 생성
- 리뷰 그룹 정보
- 리뷰 등록

### 🔥 어떻게 해결했나요 ?
- **리뷰 그룹 정보 api**의 경우, 이전에 요구사항은 응답에 그룹의 주인이 회원/비회원인지와 요청에 전달된 회원이 리뷰 그룹의 주인인지를 같이 응답하도록 하는 것으로 합의했습니다.
- 하지만 리뷰 그룹 정보 응답과 요청으로 전달된 회원의 리뷰 그룹 소유 권한을 확인하는 것은 하나의 기능이 여러 책임을 가지게 된다고 생각했습니다.
- 따라서 리뷰 그룹 응답에 단순히 리뷰 그룹의 주인 ID(필드명 : revieweeId)를 nullable로 제공하는 것으로 했습니다.
-> 회원이 생성한 리뷰 그룹인 경우, 회원ID가 함께 제공
-> 비회원이 생성한 리뷰 그룹인 경우, 회원ID는 null로 제공

클라이언트는 회원 ID가 null인 경우 비회원의 그룹으로 판단할 수 있고, ID가 존재하는 경우 로그인 사용자의 ID와 비교하여 리뷰 그룹의 주인인지를 확인하면 됩니다.

- 추후 필요한 것 : 프론트가 로그인 사용자의 정보를 따로 저장하지 않는다면, 로그인 세션을 통해 회원 정보(memberId)를 응답하는 API 구현

[백엔드 추가 전달 사항]
- 기존에 있던 api와 사용 주체(회원/비회원)에 따라서 URI를 통일하여 구분해야 할 것 같아요. 이 부분은 다시 얘기해봅죠.
- 세션을 어떻게 처리해야할지도 고민이 필요하겠습니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 

### 📚 참고 자료, 할 말
- 이해 안가면 디코주세요.

2024-12-19 18:07 UTC, nayonsoso requested changes
제가 리뷰한 내용이 다소 급진적이라 느껴질 수도 있을 것 같아 배경을 적어봅니다... 😓

---

이번 api 를 설계하며, **계층적 / 독립적 리소스**에 대해서 생각해봤습니다.

- 계층적 리소스는 '상위 계층이 없으면 존재할 수 없는 것'
- 독립적 리소스는 '상위 계층과 관계 없이 존재할 수 있는 것'

그런데 review 와 group는 여기에 걸쳐있습니다.

- 리뷰를 작성할 때의 리뷰는 회원/비회원과 관계 없이 존재할 수 있습니다.
이 맥락에서는 member 가 review 의 특성이 됩니다.
- 하지만 내가 작성한 리뷰를 볼 때는 반드시 회원이 존재해야 리뷰가 존재할 수 있습니다.
이 맥락에서는 member 가 review 의 상위 계층이 됩니다.

이런 계층적 리소스들을 uri 에서 드러내어 아래와 같이 설계하는게 어떨까 제안합니다.

- 리뷰 작성 : 회원,비회원과 독립적으로 리뷰가 생성되므로 → `POST /reviews`
- 작성한 리뷰 보기 : 회원이 있어야 리뷰가 존재할 수 있으므로 → `GET /members/reviews/authored`
- 받은 리뷰 보기 : 회원, 비회원과 독립적으로 리뷰를 볼 수 있으므로 → `GET /reviews`

---

그리고 이 제안에는 '그게 좋은 uri 설계니까 이걸 지키자!'는 취지만 있는 것은 아닙니다.
코드 상에서도 이들을 구분하는게 더 좋겠다 생각했습니다.
예를 들어, 순수한 Review 도메인과 Member과 반드시 관계를 맺는 Review 도메인은 그 성질이 다르기 때문에 ReviewController 와 MemberReviewController 를 분리하는게 좋지 않을까? 싶었습니다.

자유롭게 의견 남겨주세요... 🙇🏻‍♀️

2024-12-19 18:07 UTC, nayonsoso commented on backend/src/docs/asciidoc/create-review.adoc
> +operation::create-review-by-member[snippets="curl-request,request-fields,http-response"]
하나의 api 를 사용하되, 세션에 따라서 회원과 비회원을 구분한다는 선택지도 있었을 것 같아요.
그것을 선택하지 않고 이렇게 api 를 분리한 이유가 있나요?

2024-12-19 18:07 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +            @RequestParam(required = false) Long lastReviewId,
uri 를 /member/reviews/authored 로 바꾸고, review.controller 패키지 하위에 MemberReviewController 를 만든 다음, 이 함수를 위치시키는게 어떨지 제안해요🙋🏻‍♀️

1)) `/member` 를 맨 앞에 두어야 한다고 생각한 이유
 url 는 계층적이어야 해요.
'받은 리뷰 보기'와 달리, '작성한 리뷰 보기'는 member 라는 리소스 없이는 존재할 수 없어요.
그래서 uri 로 계층을 명시하는게 좋을것 같아요.

2)) MemberReviewController 의 필요성
회원이라는 개념이 들어오면서, 리뷰가 두가지 측면을 갖게 되었어요.
회원과 관련된 리뷰과 회원과 관련 없이 비회원에게도 동일하게 작동하는 리뷰.
MemberReviewController를 만들어서 이들을 구분하면 좋겠다 생각했어요.

3)) MemberReviewController 를 member 패키지가 아니라 review 패키지에 위치하려는 이유
핵심은 역시나 리뷰가 만들어지는 것이라 생각했어요.
그저 순수한 Review 객체가 아니라 Member 과 관여하는 Review일 뿐이니 여전히 위치는 review 패키지가 맞을 것 같아요.

4)) written -> authored 로 바꾸려는 이유
처음에 written 이라는 형용사를 봤을 때, '작성된' 으로 해석되어서 누군가가 작성해줬다는 느낌을 받았어요. 
authored 를 쓰면 내가 주체가 되어 작성했다는 의미가 더 담길 것 같아요!

2024-12-19 18:07 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +            // TODO: 세션을 활용한 권한 체계에 따른 추가 조치 필요
동의합니다 👍

2024-12-19 18:07 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/ReviewListLookupService.java
> +
클래스 시작 개행을 없앤 이유가 있나요..? 😳

2024-12-19 18:07 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/dto/response/list/WrittenReviewsResponse.java
> +}
이 dto 는 내가 작성한 리뷰들을 보여준다 생각하는데,
여기서 long memberId 를 포함하는 이유가 있나요?
어차피 자기 자신일거란 생각이 들어서요!

2024-12-19 18:07 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
>      }
회원이 만드는 그룹 uri도  /member/groups 로 하고, reviewgroup.controller 패키지 하위에 MemberReivewGroupController 를 만들고 거기로 위치하면 좋을 것 같아요. 이유는 [위 코멘트](https://github.com/woowacourse-teams/2024-review-me/pull/1017#discussion_r1892851396)와 동일해요!

2024-12-19 18:07 UTC, nayonsoso commented on backend/src/test/java/reviewme/api/ReviewApiTest.java
> +//        };
이 부분은 왜 주석처리 했나요? 자신이 작성한 것을 볼 때도 session 을 사용하지 않나요?

2024-12-19 18:12 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +            @RequestParam(required = false) Long lastReviewId,
제가 리뷰한 내용이 다소 급진적이라 느껴질 수도 있을 것 같아 배경을 적어봅니다... 😓

이번 api 를 설계하며, **계층적 / 독립적 리소스**에 대해서 생각해봤습니다.

- 계층적 리소스는 '상위 계층이 없으면 존재할 수 없는 것'
- 독립적 리소스는 '상위 계층과 관계 없이 존재할 수 있는 것'

그런데 review 와 group는 여기에 걸쳐있습니다.

- 리뷰를 작성할 때의 리뷰는 회원/비회원과 관계 없이 존재할 수 있습니다.
이 맥락에서는 member 가 review 의 특성이 됩니다.
- 하지만 내가 작성한 리뷰를 볼 때는 반드시 회원이 존재해야 리뷰가 존재할 수 있습니다.
이 맥락에서는 member 가 review 의 상위 계층이 됩니다.

이런 계층적 리소스들을 uri 에서 드러내어 아래와 같이 설계하는게 어떨까 제안합니다.

- 리뷰 작성 : 회원,비회원과 독립적으로 리뷰가 생성되므로 → `POST /reviews`
- 작성한 리뷰 보기 : 회원이 있어야 리뷰가 존재할 수 있으므로 → `GET /members/reviews/authored`
- 받은 리뷰 보기 : 회원, 비회원과 독립적으로 리뷰를 볼 수 있으므로 → `GET /reviews`

---

그리고 이 제안에는 '그게 좋은 uri 설계니까 이걸 지키자!'는 취지만 있는 것은 아닙니다.
코드 상에서도 이들을 구분하는게 더 좋겠다 생각했습니다.
예를 들어, 순수한 Review 도메인과 Member과 반드시 관계를 맺는 Review 도메인은 그 성질이 다르기 때문에 ReviewController 와 MemberReviewController 를 분리하는게 좋지 않을까? 싶었습니다.

자유롭게 의견 남겨주세요... 🙇🏻‍♀️

2024-12-20 08:48 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/ReviewListLookupService.java
> +
앗 실수입니다 반영했어요!

2024-12-20 08:53 UTC, skylar1220 commented on backend/src/test/java/reviewme/api/ReviewApiTest.java
> +//        };
자신이 작성한 것을 볼때는 기존의 리뷰그룹세션이 아닌 로그인 세션이 쓰이고, 아직 해당 세션을 구현 안했으니까 주석처리를 했어요. 그런데 생각해보니 어차피 cookie의 name은 jsessionid로 동일할테니 주석 해제해도 되겠네요!
근데 description은 우리가 기존의 비회원용 reviewGroupSession과 새로 생길 회원용 로그인 session을 구분하지 않고 동일하게 세션 ID로 써도 될까 고민입니다. 프론트에게 비회원 리뷰 그룹 세션 ID / 회원용 로그인 세션 ID 이렇게 구분하지 않아도 될까요?

2024-12-20 09:05 UTC, skylar1220 commented on backend/src/docs/asciidoc/create-review.adoc
> +operation::create-review-by-member[snippets="curl-request,request-fields,http-response"]
회원/비회원 리뷰 생성 API를 하나로 했을때를 생각해보았는데요.
```java
    @PostMapping("/v2/reviews")
    public ResponseEntity<Void> createReview(
            @Valid @RequestBody ReviewRegisterRequest request,
            @MemberSession Member member
    ) {
        long savedReviewId = reviewRegisterService.registerReview(request, member);
        return ResponseEntity.created(URI.create("/reviews/" + savedReviewId)).build();
    }
```
이때, 비회원일 경우 세션이 없지만, resolver에서 예외를 터뜨리거나 하지 않고 컨트롤러까지 다시 member 객체를 null로 반환하는 형식으로 처리를 해줘야합니다. 그리고 서비스에서 이를 확인해서 비회원용 로직으로 처리하게 되겠죠. 이렇게, 하나의 API에서 세션이 null인 것을 예외가 아닌 비회원임으로 인식하고 처리하기 위해서 예외를 터뜨려야하는데 다르게 처리하는 등으로 로직이 복잡해진다고 생각했어요.

2024-12-20 09:08 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/dto/response/list/WrittenReviewsResponse.java
> +}
memberId를 내려줌으로써 좋은 점들이 있다고 생각했어요. 
1 .프론트는 본인들이 요청을 한대로 제대로 내려줬는지 확인 가능
2. 오류가 생겼을 때 memberId를 뭐로 잘못 내려줬는지 확인 가능
내려줘서 나쁠 것 없는 고유한 정보라고 생각해서 추가해보았습니다~

2024-12-20 17:15 UTC, nayonsoso commented on backend/src/docs/asciidoc/create-review.adoc
> +operation::create-review-by-member[snippets="curl-request,request-fields,http-response"]
지난 회의에서 이야기 나온 것처럼, 하나의 api를 여러곳에서 쓰고, 권한으로 세부적인 비지니스 로직을 나누기 위한 우리의 취지를 생각해봤어요. 그럼 하나의 api에서 처리하는게 맞는 것 같아요.

그리고 저도 확실하지 않아서 지피티 & 클로드에게 물어보니, 회원/비회원 기능을 하나의 api에서 제공하고 내부적으로 분기하는 것은 일반적인 패턴이라고 합니다. 아래의 예시 코드처럼요.

```java
@Service
public class ProductService {
    public ProductResponse getProduct(Long id, User user) {
        Product product = productRepository.findById(id);
        
        ProductResponse response = new ProductResponse(product);
        
        if (user != null) {
            // 회원용 추가 정보 설정
            response.setPersonalizedPrice(calculatePersonalPrice(product, user));
            response.setUserSpecificData(getUserData(product, user));
        } else {
            // 비회원용 기본 정보만 설정
            response.setDefaultPrice(product.getPrice());
        }
        
        return response;
    }
}
```

2024-12-20 17:20 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/dto/response/list/WrittenReviewsResponse.java
> +}
납득했습니다👍

2024-12-20 17:26 UTC, nayonsoso commented on backend/src/test/java/reviewme/api/ReviewApiTest.java
> +//        };
> 그런데 생각해보니 어차피 cookie의 name은 jsessionid로 동일할테니 주석 해제해도 되겠네요!

😁👍 
그리고 api 문서에서도 이를 드러낼 수 있게 스정 부탁해요~

---

그리고 jsessionid 를 회원/비회원 모두 사용해도 되는지에 대한 제 의견은,
저는 동일하게 jsession id 를 사용해도 된다고 생각해요. 그게 오히려 복잡도를 줄이는 일이고, 따로 객체를 만들어서 권한을 관리하는게 좋겠다고 생각했어요.

2024-12-21 01:18 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +            @RequestParam(required = false) Long lastReviewId,
위의 코멘트랑 의견이랑 매치가 안되니 조금 헷갈리는데요.
회원/비회원 하나의 api를 사용하면 MemberController를 사용할 필요가 없지 않을까요?
만약 같이 사용을 못하는 api가 있다고 해도, 어떤 api는 같이 사용하고 어떤 api는 MemberController에서 가서 확인해야 하고 조금 헷갈리지 않을까 합니다.

이 부분은 전체적으로 api 구성 확정되면 나누는 게 좋을지 그대로 갈지 그때 다시 이야기해보는 것이 좋아보여요.(uri도 함께)

2024-12-21 13:31 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +            @RequestParam(required = false) Long lastReviewId,
> 위의 코멘트랑 의견이랑 매치가 안되니 조금 헷갈리는데요.
회원/비회원 하나의 api를 사용하면 MemberController를 사용할 필요가 없지 않을까요?

위 코멘트가 "회원/비회원 리뷰 생성 **API를 하나로 했으면 좋겠다**"는 코멘트이고,
"내가 작성한 리뷰를 볼 때는 **/members/ 를 붙이는게 좋겠다**"는 의견이 맞나요?

전자는 회원 여부와 관계 없이 리뷰가 생성되니 하나의 api 가 좋겠다 생각했고,
후자는 반드시 회원이 존재해야 '작성한 리뷰 확인'이 가능하니 /members/ 로 이를 명시하면 좋겠다는 의견이었어요.

---

> 만약 같이 사용을 못하는 api가 있다고 해도, 어떤 api는 같이 사용하고 어떤 api는 MemberController에서 가서 확인해야 하고 조금 헷갈리지 않을까 합니다.

맞아요, 헷갈릴 수도 있을 것 같아요🥲
그래도 종속성을 확실히 이해한다면 큰 어려움 없을 것 같아요.
혹시 제 설명을 읽었을 때, 무엇을 말하는건지 이해가 되었나요? 아니면 이해는 되었으나 여전히 헷갈리는 상태인가요?

2024-12-21 14:49 UTC, donghoony commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +            @RequestParam(required = false) Long lastReviewId,
`/member`로 시작한다면 멤버를 찾게 된다고 느껴집니다. 그룹을 찾고 싶다면 `/groups`가 더 타당해 보여요.

2024-12-23 12:44 UTC, skylar1220 commented on backend/src/docs/asciidoc/create-review.adoc
> +operation::create-review-by-member[snippets="curl-request,request-fields,http-response"]
1. 위의 코드로 구현할 수 있지만 앞에서 언급한 문제가 여전히 존재한다고 생각해요.
> 하나의 API에서 세션이 null인 것을 예외가 아닌 비회원임으로 인식하고 처리하기 위해서, resolver에서 예외를 터뜨려야하는데 다르게 처리하는 등으로 로직이 복잡해진다고 생각했어요.

2. api 재사용 논의와 관련해서는, 구현하면서 아직 하나의 api를 재사용하고 세션 권한 체계로 구분한다는 것의 상세구현이 그려지지 않았어요. 그래서 일단 세션을 나눠서 적용했을 때 문제가 없게 두가지 api로 나눠 구현했습니다..!

2024-12-23 12:44 UTC, skylar1220 commented on backend/src/test/java/reviewme/api/ReviewApiTest.java
> +//        };
반완!

2024-12-24 02:08 UTC, Kimprodp reviewed
@skylar1220 의견 남겼는데 확인 부탁합니다.
- 의견 통일되면 반영하고 검토받고,
- 갈린다면 디코 스레드에서 투표하는걸로 합시다요

2024-12-24 02:08 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +        // 회원 세션 추후 추가해야 함
다시 보니, 이 api는 /v2/reviews api 하나로 처리해도 상관없어 보여요.
- 세션 유무에 따라서 내부 로직은 분기하면 됩니다.
- 근데 요청 dto가 동일한데, 세션을 받아야 하는 이유가 있었나요? (생각이 안납니다..)

2024-12-24 02:08 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +    @GetMapping("/v2/written")
이 api의 url에서 "written"만 있는 것은 어떤 자원을 찾는지 명확하지 않아보여서 변경이 필요해 보이네요.
1. 기존 보완 -> /reviews/written
1. 신초의 의견을 반영한 authored 사용 -> /reviews/authored
2. 특정 회원의 작성된 리뷰 목록 -> /users/{userId}/written-reviews (세션과 id 검증 필요)

2024-12-24 02:08 UTC, Kimprodp commented on backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
> +    public ResponseEntity<ReviewGroupCreationResponse> createReviewGroup(
요것도 마찬가지로 groups랑 합칠 수 있을 것 같습니다
- 세션 유무에 따른 분기처리

2024-12-27 15:46 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +        // 회원 세션 추후 추가해야 함
> 근데 요청 dto가 동일한데, 세션을 받아야 하는 이유가 있었나요?

회원이 리뷰를 작성할 땐, '내가 작성한 리뷰'에 추가해줘야 하니깐요!

2024-12-27 15:50 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/dto/response/list/WrittenReviewsResponse.java
> +}
납득 취소합니다.. (죄송 ㅠㅠ)
클라이언트 - 서버간에 로그인한 회원을 식별하는 정보는 JSESSION_ID 만 있게 하는게 맞다 생각합니다.

> 1. 프론트는 본인들이 요청을 한대로 제대로 내려줬는지 확인 

이 전제는 프론트가 로그인한 사용자의 memberId 가 뭔지를 기억하고 있어야 한다는건데.. 
그렇다면 클라이언트에 의존적인 구조라고 할 수 있습니다.

> 2. 오류가 생겼을 때 memberId를 뭐로 잘못 내려줬는지 확인 가능

이건 프론트에서 확인해야할게 아니라는 생각이 드네요!

2024-12-27 19:33 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/dto/response/list/WrittenReviewsResponse.java
> +}
멤버 관련 사항은 세션에서 관리하지 않은가용? 우리는 그냥 정보만 내려주면 되지 않나 해서요 (인증 관련이 프로그램 내부에서 일어난다)

2024-12-28 01:42 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/service/dto/response/list/WrittenReviewsResponse.java
> +}
> 이 전제는 프론트가 로그인한 사용자의 memberId 가 뭔지를 기억하고 있어야 한다는건데..
그렇다면 클라이언트에 의존적인 구조라고 할 수 있습니다.

> 멤버 관련 사항은 세션에서 관리하지 않은가용? 우리는 그냥 정보만 내려주면 되지 않나 해서요 (인증 관련이 프로그램 내부에서 일어난다)

우리가 멤버 관련 인증이나 저장을 위해서 memberId를 포함시키는 것이 아니라, 
요청에 대한 응답이 올바르게 되었는지, 이 응답이 이 요청에 대한 응답인지 알 수 있도록 신뢰의 수단으로 포함시켰습니다.

클라이언트가 응답에 있는 memberId를 사용하던 사용하지 않던 서버는 알 지 못하고 몰라고 됩니다. 
그래서 memberId를 클라이언트가 기억하고 있던 아니던 서버는 신경 안써도 됩니다.

다만, 정보 제공자이니 요청에 대한 응답임을 알 수 있게 최소한은 해야한다고 생각해요.
만약 클라이언트에서 이 api를 여러번 보내서 응답이 여러개 온다면 어떤 응답이 어떤 요청에 대한 응답인지 알 수 없습니다. 이건 클라이언트가 누군지 어떻게 쓰는지에 따라서 다를 수 있다고 생각해요.

지금은 클라이언트가 당연히 한번에 하나의 요청을 보내고 어떻게 쓸지 유추가 가능하니까 서버가 신경쓰고 그거에 맞춘다는 생각드는데, 오히려 이게 클라이언트에 의존적인 구조라고 생각합니다. 


> 이건 프론트에서 확인해야할게 아니라는 생각이 드네요!

오류가 생겼다는 건 프론트가 잘못된 응답을 그대로 사용했다는 거고, 프론트 쪽에서 그걸 방지하려면 응답에 있는 데이터를 사용해서 검증할 수도 있겠죠.
반대로 서버에서도 로깅해두면 요청에 대한 응답이 잘 나갔는지 확인도 가능하다는 말 같습니다.

2024-12-28 18:44 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/dto/response/list/WrittenReviewsResponse.java
> +}
저는 솔직히 memberId 를 포함하냐에 대해서 크게 중요하게 생각하진 않아요.
두 분이 강하게 주장하시면 그 의견을 따라가려 합니다.
하지만 계속 생각해봐도 부자연스럽다는 생각이 들어서..😓 
마지막으로 설득해보겠습니다.

---

커비도 "요청에 대한 응답임을 알 수 있게" 를 말하고 있고,
테드도 핵심적인 부분은 "이 응답이 이 요청에 대한 응답인지 알 수 있도록"인 것 같아요.

두 분이 응답에 반드시 들어가야 한다고 생각하는 것은 
**요청을 한 나 자신에 대한 응답이 맞는지** 인가요?

그럼 JSESSION_ID를 사용한 인증 체계, 그 자체를 불신하고 있는 것인지... 😵‍💫
이런 부분이 부자연스럽게 느껴집니다.

그리고 memberId는 templateId 나 sectionId 처럼 노출되어도 별 문제 없는게 아니라
사용자를 식별하기 위한 내부 식별자라 노출이 더욱 불필요하게 느껴지는 것 같아요.

---

이 생각을 보고도 여전히 같은 의견이시면 저는 그것을 따르도록 하겠습니다.

2024-12-29 02:01 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/service/dto/response/list/WrittenReviewsResponse.java
> +}
음 내용에 납득했습니다 로그인 요청에서는 불필요할 수도 있겠네요!

2024-12-29 02:13 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/service/dto/response/list/WrittenReviewsResponse.java
> +}
음 내용에 납득했습니다 로그인 세셔이 있는 요청에서는 불필요할 수도 있겠네요!

2024-12-29 03:06 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +    @GetMapping("/v2/written")
1번 방법이 좋아보여요. 내가 받은 리뷰가 /v2/reviews인데 이것도 함께 변경하면 좋을 것 같아요.
받은 리뷰는 /v2/reviews/receive , 작성한 리뷰는 /v2/reviews/authored 이런 식으로요!

2024-12-29 03:07 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +        // 회원 세션 추후 추가해야 함
https://github.com/woowacourse-teams/2024-review-me/pull/1017#discussion_r1895715637
위의 코멘트에 분리하는 것이 낫다고 생각하는 이유를 적었는데 테드의 생각은 어떤가요?

2024-12-29 03:16 UTC, skylar1220 commented on backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
> +    public ResponseEntity<ReviewGroupCreationResponse> createReviewGroup(
/v2/groups의 요청 필드에는 groupAccessCode가 필요하고, /v2/groups/member의 요청 필드에는 groupAccessCode가 필요없는데 어떻게 합칠 수 있나요? null을 허용하는 방법일까요? 복잡하지 않은 분기처리 로직이 어떻게 될지 잘 안떠올라서요...

둘을 합칠때의 장점이 뭘까요? 어차피 요청 dto 형태도 다르고, 호출하는 서비스 메서드도 다른데 말이지요!

2024-12-29 06:18 UTC, Kimprodp reviewed
커비 코멘트 답완

2024-12-29 06:18 UTC, Kimprodp commented on backend/src/docs/asciidoc/create-review.adoc
> +operation::create-review-by-member[snippets="curl-request,request-fields,http-response"]
회원/비회원의 동작 차이가 크지 않으면 동일한 비즈니스 로직을 하나로 사용하는 것이 좋다고 생각해요.
- '리뷰 등록' 이라는 비즈니스 로직은 동일하고
- 권한에 따라서 추가적인 차이는 리뷰 작성 후 회원의 '내가 작성한 리뷰'에 추가하는 것 뿐
- 이는 컨트롤러나 컨트롤러와 서비스의 중간 계층에서 충분히 분기 할 수 있고(분기 위치, 이 부분을 정해야 할듯), 서비스는 비즈니스 로직에만 집중해서 권한 체계와 비즈니스 로직이 분리됨

서버는 단순히 로그인 세션이 존재하면 회원이 요청한 것으로 알고 처리, 없으면 비회원이 요청한 것으로 알고 처리. 이렇게 구현하면 리졸버에서 null을 반환하는 것이 자연스러워 보입니다.
오히려 같은 동작인데 api를 분리하면 권한 중심으로 설계된다고 생각해요.

2024-12-29 06:18 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +        // 회원 세션 추후 추가해야 함
코멘트 남겼어요 확인 부탁합니다~

2024-12-29 06:18 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +    @GetMapping("/v2/written")
> 1번 방법이 좋아보여요.
> 작성한 리뷰는 /v2/reviews/authored 이런 식으로요!

어떤걸 선택한거죠??  😮😮

2024-12-29 06:18 UTC, Kimprodp commented on backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
> +    public ResponseEntity<ReviewGroupCreationResponse> createReviewGroup(
요청은 하나로 합칠 수 있고, 리뷰 그룹이라는 동일한 엔티티를 생성하고 DB에 저장하는 로직은 동일해요.
다만 회원의 경우 리뷰 등록처럼 회원의 리뷰 그룹 목록에 생성된 리뷰 그룹을 추가하는 등의 추가적인 작업만 필요해 보입니다.

리뷰 등록의 코멘트처럼 분리 처리되는 곳의 위치나 방법만 정하면 가능하지 않을까요..?

비회원
- 요청 : 리뷰이명, 리뷰그룹명, 비밀번호
- 로직 : 리뷰 그룹 생성
- 응답 : 생성된 리뷰 그룹 정보

회원
- 요청 : 리뷰이명, 리뷰그룹명, 로그인 세션
- 로직 : 리뷰 그룹 생성, 회원의 리뷰 그룹에 생성된 리뷰 그룹 추가
- 응답 : 생성된 리뷰 그룹 정보

2024-12-29 18:37 UTC, nayonsoso commented on backend/src/docs/asciidoc/create-review.adoc
> +operation::create-review-by-member[snippets="curl-request,request-fields,http-response"]
저도 테드와 같은 생각입니다.
덧붙이자면 우리는 **_한가지 api에 대해서 권한에 따라 다르게 기능하기_** 로 합의했고,
지금은 api 설계 단계이니, 이 목표에 맞게 구현을 맞춰야 하지
구현이 되지 않았으므로 두개로 나누어 둘 필요는 없다 생각해요!

2024-12-29 18:38 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/dto/response/list/WrittenReviewsResponse.java
> +}
기분 나빴을 수도 있었을텐데 유연한 주장.. 감사합니당🙇🏻‍♀️

2024-12-29 18:52 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
> +    public ResponseEntity<ReviewGroupCreationResponse> createReviewGroup(
(( 종류에 따라 요청 형식이 다른데 / 로직은 동일하다는 점에서
textAnswerRequest 와 checkboxAnswerRequest 가 떠오르는군요... ))

종류에 따라 비지니스 로직이 크게 다르지 않으므로, 하나의 api 를 사용하는 쪽에 한표요!

2025-01-05 08:45 UTC, skylar1220 commented on backend/src/docs/asciidoc/create-review.adoc
> +operation::create-review-by-member[snippets="curl-request,request-fields,http-response"]
중간 계층을 두거나 하는 방식으로 복잡도를 줄이고 '한가지 api에 대해서 권한에 따라 다르게 기능하기'를 최대한 활용해보는 것에 동의합니다! 반영 완료!

2025-01-05 09:00 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +    @GetMapping("/v2/written")
이 메서드, 내가 **작성한** 리뷰는 `/v2/reviews/authored` 로 하고요.
더불어 내가 **받은** 리뷰는 현재 '/v2/reviews'인데 얘도 함께 '`v2/reviews/receive`로 바꾸면 어떨까였어요!

왜냐면 
내가 받은 리뷰: /v2/reviews
내가 작성한 리뷰: /v2/reviews/authored
이렇게 되면 `내가 작성한 리뷰`가 `내가 받은 리뷰`의 하위 api 처럼 느껴져서요~

2025-01-05 09:27 UTC, skylar1220 commented on backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
> +    public ResponseEntity<ReviewGroupCreationResponse> createReviewGroup(
위의 리뷰 작성 api를 통합한 것과 같은 이유로 서비스나 별도 레이어에서 분기해보는 방식에 동의합니다~
따라서 해당 방식으로 반영해보았는데 적용하다보니 request의 groupAccessCode가 nullable이 되는 것이 살짝 걸리네요. 
이건 비즈니스 로직에서 검증을 구현해보면서 다시 확인해봐야겠습니다!

2025-01-07 17:00 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +    @GetMapping("/v2/written")
> 내가 받은 리뷰: /v2/reviews
내가 작성한 리뷰: /v2/reviews/authored
이렇게 되면 내가 작성한 리뷰가 내가 받은 리뷰의 하위 api 처럼 느껴져서요~

동의합니다만!

내가 받은 리뷰 : v2/reviews/received 로 형용사로 통일하는건 어떤가요?

2025-01-09 01:17 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +    @GetMapping("/v2/written")
받은 리뷰 : v2/reviews/received
작성한 리뷰: /v2/reviews/authored
동읩합니다

2025-01-12 01:52 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +    @GetMapping("/v2/written")
형용사 통일 좋네요 반영완료!

2025-01-12 03:00 UTC, nayonsoso requested changes

2025-01-12 03:00 UTC, nayonsoso commented on backend/src/test/java/reviewme/api/ReviewGroupApiTest.java
> +
여기 /groups/summary 로 바꿔야 합니다!

2025-01-12 08:31 UTC, skylar1220 commented on backend/src/test/java/reviewme/api/ReviewGroupApiTest.java
> +
반완!

2025-01-12 08:34 UTC, nayonsoso approved these changes

2025-01-13 07:35 UTC, skylar1220 approved these changes

2025-01-13 09:52 UTC, donghoony approved these changes

2025-01-14 01:28 UTC, merged