Be/feat/99 create review
woowacourse-teams/2024-review-me pull request #102
Opened 2024-07-24 15:48 UTC by Kimprodp

- resolves #99 

---

### 🚀 어떤 기능을 구현했나요 ?
- 리뷰 작성 기능을 구현했습니다.

### 🔥 어떻게 해결했나요 ?
- 리뷰 작성 api 에 맞춰 리뷰 작성 기능을 구현했습니다.
- 구현하는 과정에서 몇 가지 이슈 사항을 같이 반영했습니다.
1) `ReivewGroup` 생성 시, `GithubIdReviewerGroup`를 생성하지만 따로 데이터베이스에 저장 하지 않아  `GithubIdReviewerGroup`이 저장이 되지 않습니다.  cascade 룰을 추가하여 부모 엔티티가 저장될 때, 함께 저장되도록 변경했습니다.

2) `Review` 생성 시, `ReviewGroup`이 `nullable = false` 설정되어 있지만 생성자에서 초기화되지 않아 발생하는 문제를 해결했습니다.

3) `ReviewerGroupGithubIds`의 `doesNotContain()` 메서드를 통해 `GithubId `를 비교하는 과정에서 `GithubId`의 `equals 및 hascode` 재정의가 되어있지 않아 `false`를 반환하기 때문에, 재정의 하는 어노테이션을 추가하였습니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 구현 기능과 문제 해결 방식에 문제가 없는지 확인해주세요.

### 📚 참고 자료, 할 말
- `ReviewContentTest `에서 테스트 시, `ReviewContent`를 생성하는 과정에서 `Review`에 `null` 값이 들어가서 테스트가 통과하지 않는 부분은 일단 두었습니다. (추후 해당 수정 PR 머지 선행)

2024-07-24 16:52 UTC, donghoony requested changes
우선 보이는 것만 진행하고, 내일 다시 Cascade 부분 확인할게요! 아자아자 ✨

2024-07-24 16:52 UTC, donghoony commented on backend/src/main/java/reviewme/member/domain/GithubId.java
> +@EqualsAndHashCode
`@EqualsAndHashCode` 안의 `of`로 ID 명시하는 게 좋겠습니다~!

2024-07-24 16:52 UTC, donghoony commented on backend/src/main/java/reviewme/member/domain/GithubIdReviewerGroup.java
> +@Table(name = "github_id_reviewer_group")
테이블 명시 👍🏻

2024-07-24 16:52 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/ReviewService.java
> +        Member reviewee = memberRepository.getMemberById(reviewerGroup.getReviewee().getId());
reviewee는 reviewerGroup 통해서 받아올 수 있지 않은가요 ?

2024-07-24 16:52 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/ReviewService.java
전반적으로 쿼리가 많이 보이기는 하는데 이건 추후에 봐야겠네요 🙄

2024-07-24 16:52 UTC, donghoony commented on backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
> +        Long savedReviewId = reviewService.createReview(createReviewRequest);
할당한 변수 사용하지 않으면 그대로 두는 게 낫지 않을까요?

2024-07-24 16:52 UTC, donghoony commented on backend/src/main/java/reviewme/review/repository/QuestionRepository.java
> +    default Question getQuestionById(Long id) {
널 올 게 아니니 `long`으로 작성 고고..?

2024-07-25 04:08 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/service/ReviewService.java
> +        Member reviewee = memberRepository.getMemberById(reviewerGroup.getReviewee().getId());
과정을 순서대로 나열하려 했는데 아무래도 .getId()를 안써도 되니 이게 좋을 것 같네요!

2024-07-25 04:08 UTC, Kimprodp commented on backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
> +        Long savedReviewId = reviewService.createReview(createReviewRequest);
지우는걸 깜빡했네요 ┗( T﹏T )┛

2024-07-25 04:10 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/repository/QuestionRepository.java
> +    default Question getQuestionById(Long id) {
좋슴니다👍

2024-07-25 04:10 UTC, Kimprodp commented on backend/src/main/java/reviewme/member/domain/GithubId.java
> +@EqualsAndHashCode
좋슴니다👍

2024-07-25 04:16 UTC, Kimprodp reviewed
피드백 반영했습니다 확인 부탁해요~

2024-07-25 04:22 UTC, skylar1220 approved these changes
연관관계 까다로웠을텐데 수고 많았습니당 테드~~

2024-07-25 04:31 UTC, donghoony approved these changes
좋와요 몇가지만 짚고 가면 돼서 어프루브 남깁니다 코멘트 확인 필수~!!

2024-07-25 04:31 UTC, donghoony commented on backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
> +        CreateReviewRequest createReviewRequest = new CreateReviewRequest(reviewer.getId(), reviewerGroup.getId(),
개행 파라미터만 모아서 해주세요!

2024-07-25 04:31 UTC, donghoony commented on backend/src/main/java/reviewme/member/domain/ReviewerGroupGithubIds.java
> +    @OneToMany(mappedBy = "reviewerGroup", cascade = CascadeType.ALL)
등록할 때에만 동작하면 되니, 모든 CascadeType을 넣어두는 것보다 PERSIST만 넣어두는 게 좋지 않을까요? 🤔

2024-07-25 05:07 UTC, Kimprodp commented on backend/src/main/java/reviewme/member/domain/ReviewerGroupGithubIds.java
> +    @OneToMany(mappedBy = "reviewerGroup", cascade = CascadeType.ALL)
부모(리뷰그룹)이 삭제되면 매핑 컬럼도 같이 삭제되어야 할 것 같은데 우선 아직 등록기능만 있으니 PERSIST만 넣어둘게요! 
나중에 리팩터링 때 다같이 엔티티 전체적으로 cascade와 orphanRemoval 설정에 대해서 고려해보면 좋을 것 같아요~

2024-07-25 05:09 UTC, Kimprodp commented on backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
> +        CreateReviewRequest createReviewRequest = new CreateReviewRequest(reviewer.getId(), reviewerGroup.getId(),
반영 완료 👍

2024-07-25 05:29 UTC, nayonsoso reviewed
테드 고생했습니다~ PR 메세지가 가독성이 너무 좋네요!!!

2024-07-25 05:29 UTC, nayonsoso commented on backend/src/main/java/reviewme/member/domain/GithubId.java
> +@EqualsAndHashCode(of = "id")
👍

2024-07-25 05:29 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/ReviewService.java
> +        Review savedReview = reviewRepository.save(review);
리뷰이 부분에 들어갈 인자를 reviewerGroup 에서 빼서 넣어주셨는데요! 그런데 그렇게 한다면, 리뷰를 리뷰어 그룹에 추가할 때 검증하는 함수인 addReview 에서 '추가될 리뷰의 리뷰이와 리뷰어 그룹의 리뷰이가 같은지 검증하는' 부분이 무용지물이 될 것 같아요!

그러니 MemverRepository 로부터 찾아서 넣어주는건 어떨까요?

```java
// ReviwerGroup.class
public void addReview(Review review) {

    Member reviewer = review.getReviewer();
    if (isDeadlineExceeded(review.getCreatedAt())) {
        throw new DeadlineExpiredException();
    }
    if (hasSubmittedReviewBy(reviewer)) {
        throw new ReviewAlreadySubmittedException();
    }
    if (reviewerGithubIds.doesNotContain(reviewer)) {
        throw new GithubReviewerGroupUnAuthorizedException();
    }
    if (!review.getReviewee().equals(reviewee)) {   // ❗️이부분
        throw new RevieweeMismatchException();
    }
    reviews.add(review);
}
```

2024-07-25 05:54 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/service/ReviewService.java
> +        Review savedReview = reviewRepository.save(review);
```java
Member reviewer = memberRepository.getMemberById(request.reviewerId());
Member reviewee = memberRepository.getMemberById(reviewerGroup.getReviewee().getId());
```

이전에 위의 방식으로 했었는데요, 어차피 리뷰이를 따로 받는게 아니라 사실상 리뷰어 그룹에 있는 리뷰이를 사용할거라면 두 방식에 차이가 없어 보여요. 차라리 리뷰 생성자로 리뷰이를 받지 않고, 리뷰 그룹에서 꺼내 쓰는게 나을 것 같기도 하고, 어떤 방식이든 사실 순환참조 때문에  '추가될 리뷰의 리뷰이와 리뷰어 그룹의 리뷰이가 같은지 검증하는' 부분이 의미가 없긴 할 것 같아요.

2024-07-25 06:58 UTC, donghoony approved these changes

2024-07-25 07:26 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/ReviewService.java
> +        Review savedReview = reviewRepository.save(review);
오 동의합니다.
저도 코드를 보다보니 '이 코드가 쓰이지 않는 것 같으니 사용되도록 데이터를 세탕' 하라는 식으로 리뷰했었었는데,
다시 생각해보니 주객이 전도되었네요😓
리뷰어그룹으로부터 리뷰어를 받아오게 하는게 더 간단할 것 같아요.

2024-07-25 07:27 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/ReviewService.java
> +        Review savedReview = reviewRepository.save(review);
'리뷰어 그룹으로부터 리뷰이를 받아오도록 리팩터링하는건 어떨까?' 라는 생각이 든다!

2024-07-25 07:28 UTC, nayonsoso approved these changes

2024-07-25 07:30 UTC, donghoony approved these changes

2024-07-25 07:30 UTC, merged