[FE] 사이드바 및 모달 사용성 개선
woowacourse-teams/2024-review-me pull request #139
Opened 2024-07-27 13:12 UTC by ImxYJL

- resolves #137 

---

### 🚀 어떤 기능을 구현했나요 ?
- 사이드바 리팩토링
  - 사이드바가 열릴 때는 등장 애니메이션이 여전히 존재함, 단 더 빠르게 등장 (0.2초)
  - 닫힐 때의 애니메이션 제거
- 모달 닫는 기능 추가
  - 모달 배경 클릭, esc 키를 누른 경우 모달 닫힘
- 사이드바 메뉴의 아이템을 선택해 특정 페이지로 이동한 경우에도 사이드바 닫힘

### 🔥 어떻게 해결했나요 ?
- `useModalClose` 훅 생성: 모달이 공통 컴포넌트인 만큼 모달을 esc 또는 배경 클릭으로 닫는 기능을 반복적으로 사용할 것 같아 별도의 훅으로 분리했습니다.
  - 이렇게 훅을 사용하는 쪽에서 모달 컴포넌트를 전달해주면 됩니다.
  ```ts
    const modalRef = useRef<HTMLDivElement>(null);
    useModalClose(closeModal, modalRef);

    ...

    <S.SidebarWrapper ref={modalRef} $isSidebarHidden={isSidebarHidden}>
   ``` 

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- handler 네이밍 규칙이 잘 지켜졌는지 궁금합니다. 
- `useModalClose` 훅을 hooks 폴더 내부에 만들었는데, 모달 폴더 안에 있어야 할까요?
- `useModalClose` 훅에서 어떤 if문은 (가독성을 위해 사용하는 게 좋다고 생각해서)중괄호를 사용했고, 어떤 것은 사용하지 않았는데 판단이 적절했는지에 대한 의견을 듣고 싶습니다.

### 📚 참고 자료, 할 말
- 리팩토링할 때 코드를 혼자 요상하게 읽고 삽질하지 말고 코드를 작성했던 사람에게 질문을 해봅시다... 내 2시간...

2024-07-28 04:14 UTC, BadaHertz52 requested changes
올리 모달 애니메이션 고치고 거기에 더해서 배경화면,esc를 통한 닫기 기능까지 추가하느라 고생했어요.!! 다른 모달에도 사용할 수 있도록 훅으로 닫기 기능을 뺀거 아주 좋아요! 👍

더 좋은 코드,재사용성을 위한 제안을 코멘트로 남겨두었어요. 확인 부탁드리고 남은 주말 잘 쉬고 월요일에 봐요! 😊

2024-07-28 04:14 UTC, BadaHertz52 commented on frontend/src/hooks/useModalClose.ts
> +    const handleBackgroundClick = (event: MouseEvent) => {
dependency 의 변형이 있으면 handleBackgroundClick, handleKeyDown이 다시 생성될 것 같고, 두 함수가 useEffect안에 있으니 useEffect의 문이 길어져요.

그래서 두 함수를 useEffect 밖으로 뺐으면 하는데 올리 생각은 어떤가요?

2024-07-28 04:14 UTC, BadaHertz52 commented on frontend/src/components/common/modals/SideModal/index.tsx
> +  useModalClose(closeModal, modalRef);
배경화면, esc를 눌렀을때 모달이 닫히는 기능이 모달마다 사용하니 훅으로 만드는 방식 좋아요!

올리의 useCloseModal을 좀 더 편하게 사용하고 관리할 수 없을까 고민해봤어요.
아래처럼 한다면 배경화면,esc를 통한 모달 닫히는 기능을 ModalBackground에서 관리할 수 있고, 모달들은 closeModal을 props로 받아서 이를 ModalBackground에게 전달해주기만 하면 돼요. 

개인적으로는 이 방법인 모달 닫히는 과정을 파악하고 관리하기에 쉽다고 느껴지는데 올리는 어떤가요? 

```tsx
// ModalBackgroud.tsx
interface ModalBackgroundProps {
  closeModal: () => void;
}

const ModalBackground: React.FC<PropsWithChildren<ModalBackgroundProps>> = ({ children, closeModal }) => {
  const modalRef = useRef<HTMLDivElement>(null);
  useModalClose(closeModal, modalRef);

  return (
    <S.ModalBackground>
      <div ref={modalRef}>{children}</div>
    </S.ModalBackground>
  );
};
```
```tsx
// SideModal.tsx
interface SideModalProps {
  isSidebarHidden: boolean;
  closeModal: () => void;
}

const SideModal: React.FC<PropsWithChildren<SideModalProps>> = ({ children: Sidebar, isSidebarHidden, closeModal }) => {
  return (
    <ModalPortal id="sidebarModal-portal">
      <ModalBackground closeModal={closeModal}>
        <S.SidebarWrapper $isSidebarHidden={isSidebarHidden}>{Sidebar}</S.SidebarWrapper>
      </ModalBackground>
    </ModalPortal>
  );
};
```

2024-07-28 04:14 UTC, BadaHertz52 commented on frontend/src/hooks/useModalClose.ts
> +    document.addEventListener('click', handleBackgroundClick, true);
click , keydown 이벤트의 대상이 document로 설정되어서 이벤트 영역이 우리가 원하는 것보다 넓은 것 같고 이벤트 캡쳐링과 버블링에 의한 오버헤드가 걱정이 돼요.

이벤트의 대상을 document보다 모달로 제한하는 것은 어떨까요?

2024-07-28 09:00 UTC, ImxYJL commented on frontend/src/hooks/useModalClose.ts
> +    const handleBackgroundClick = (event: MouseEvent) => {
전 이런 이유로 useEffect 안에 뒀습니다~!

1. 두 함수가 그리 복잡하지 않기 때문에 재할당되더라도 오버헤드가 적음
2. 두 함수를 밖으로 뺄 경우 추가 인수를 받아야 하고, 결국 useEffect 안에서 별도로 호출해줘야 함. 반면 useEffect 안에서 사용하면 클로저를 통해 이벤트 객체만 받으면 되고 정의해서 바로 사용할 수 있음
```ts
// 함수들을 밖으로 뺐을 때의 코드
const handleBackgroundClick = (event: MouseEvent, closeModal: () => void, isModalChildren: (targetElement: Node | null) => boolean) => {
    if (isNodeElement(event.target) && !isModalChildren(event.target)) {
      closeModal();
    }
  };

  const handleKeyDown = (event: KeyboardEvent, closeModal: () => void) => {
    if (event.key === 'Escape') closeModal();
  };

  useEffect(() => {
    const backgroundClickListener = (event: MouseEvent) => handleBackgroundClick(event, closeModal, isModalChildren);
    const keyDownListener = (event: KeyboardEvent) => handleKeyDown(event, closeModal);

   ....

```
4. 이 useEffect가 어떤 상황에서 동작하는지(클릭, esc)를 보다 직관적으로 나타낼 수 있음

요 정도인데 이 의견에 대한 바다의 생각이 궁금합니다 ㅎㅎ

2024-07-28 09:01 UTC, ImxYJL commented on frontend/src/hooks/useModalClose.ts
> +    document.addEventListener('click', handleBackgroundClick, true);
앗 애초에 document 대신 모달에 달면 해결되는 문제였는데 괜히 복잡하게 만들었네요 😂 바로 반영할게요!

2024-07-28 12:50 UTC, ImxYJL commented on frontend/src/components/common/modals/SideModal/index.tsx
> +  useModalClose(closeModal, modalRef);
'모달 닫기'가 SideModal만의 로직이 아니니까 SideModal에서 훅을 호출하는 것보다 바다 말대로 모든 모달의 공통 최상위 컴포넌트인 ModalBackground에서 닫기 로직을 담당하는 게 더 역할과 책임이 두드러지는 것 같네요! 수정 완료했습니다~!

2024-07-30 08:11 UTC, ImxYJL commented on frontend/src/hooks/useModalClose.ts
> +    const handleBackgroundClick = (event: MouseEvent) => {
지금 확인해보니까 추가 리팩토링을 진행한 뒤에는 함수들을 밖으로 뺐을 때 추가 매개변수를 받아야 하는 문제는 없어졌습니다. 리뷰할 때 참고 부탁드려요~~

2024-07-30 13:31 UTC, BadaHertz52 commented on frontend/src/hooks/useModalClose.ts
> +    const handleBackgroundClick = (event: MouseEvent) => {
2번의 경우는 해결되었으니 1번과 3번에 대해서 이야기를 해볼게요.

### useEffect 안의 선언으로 인한 오버헤드
코드를 짜면서 오버헤드가 날 것 같으면 미리 이를 피하느냐,  아니면 구현 후 성능을 보면서 이를 구현하느냐에 대해 묻는다면 저는 전자인 것 같아요. (useMemory, useCallback처럼 메모리와 성능 향상을 비교해보는 것을 제외하자면요.) 

이전 프로젝트의 리팩토링 경험 상, 구현 후에 어느 부분에서 성능을 개선할 수 있는가를 찾는 것도 일이고 실제로 잘 보이지 않았었요. 그래서 구현 시 성능에 더 좋은 것 같다면 그때그때 개선해나가요. 

그래서 useEffect 밖으로 함수들을 꺼내보는 것을 제안드렸어요.

### useEffect의 dependency에 함수를 인자로 넣어야하는가?
만약 useEffect 밖으로 함수들을 뺀다면 함수를 dependency에 넣어야하냐?라면 저는 이 함수들은 event 핸들러이고  외부에서 받는 파라미터에 의해서 실행 결과가 바뀌지 않느 함수가 useEffect에 넣지 않아도 된다고 봐요.

###  가독성 부분
'useEffect안에 넣으면 직관적으로 볼 수 있다.'라는 말은 결국 코드의 가독성 부분을 의미하는 거겠죠? 

가독성 측면에서 useEffect안에서 사용하는 것을 파악하기 쉬운 것과 useEffect의 길이가 간결해 흐름을 파악하기 쉬운 것 사이에서 어느 것이 더 챙겨야하냐를 생각한다면 저는 후자에요. 

useEffect 밖으로 함수를 빼더라도 함수명을 통해서 useEffect의 코드만으로 흐름을 파악할 수 있어요.  useEffect와 관련된 함수들이 많아진다면 hook으로 빼서 관계성을 부여할 수 있을 것 같아요.

2024-07-30 13:41 UTC, BadaHertz52 approved these changes
올리! 수정된 내용 확인했어요.
저의 제안을 긍정적으로 받아줘서 고마워요🥰

useEffect에 대한 올리의 생각 잘 봤어요. 그에 대한 저의 의견도 코멘트로 달아놨어요.
useEffect밖으로 함수를 빼냐 아니냐에 대해서 분명한 정답이 있는게 아니라서 이만 approve할게요. 

만약 수정하고 싶다면 수정 후 다시 pr 요청 부탁드려요!!!

2024-07-30 21:54 UTC, soosoo22 approved these changes
사이드 바 모달에 열림과 닫힘을 관리하는 `useSidebar`라는 훅으로 분리하셨군요! 확실히 훅으로 분리하니까 코드가 훨씬 깔끔하네요!

2024-07-30 21:54 UTC, soosoo22 commented on frontend/src/hooks/useSidebar.ts
> +  const OPEN_TIME = 0.2;
사이드 바 모달이 열릴 때, 백그라운드가 먼저 나오고 그 이후에 모달이 나오는데 그 텀이 길다 보니까 답답하다는 느낌을 받았어요. 센스있게 `setTimeout` 시간을 줄여주셨군요!! 👍👍👍

2024-07-31 01:26 UTC, ImxYJL commented on frontend/src/hooks/useModalClose.ts
> +    const handleBackgroundClick = (event: MouseEvent) => {
사실 매개변수가 추가돼서 함수가 비교적 읽기 힘들어지는 문제(2번 문제)가 메인이었고 나머지는 부수적인 이야기긴 했습니다! 그래서 2번이 해결 된 이상 바다가 제시해준 방향대로 전부 고쳐도 될 것 같아요.

궁금한 점은 저 두 함수 정도의 크기가 오버헤드를 걱정할 정도로 크지 않다고 생각하는데, 바다는 나중에 이런 코드들이 쌓였을 때의 성능 저하를 걱정하는 거겠죠? 
별개로 바다가 남겨준 코멘트들은 왜 이렇게 생각하는지가 잘 드러나서 읽을 때 무척 수월한 것 같아요. 자세한 리뷰 고마워용~~

2024-07-31 01:26 UTC, ImxYJL commented on frontend/src/hooks/useSidebar.ts
> +  const OPEN_TIME = 0.2;
useSidebar는 제가 작업한 게 아니랍니다...ㅋㅋㅋㅋㅋ 전 추가적으로 닫는 기능을 훅으로 분리했어요~

2024-07-31 02:28 UTC, chysis approved these changes
코드 잘 읽었어요 올리! 저도 핸들러를 useEffect 내부에 넣은 것에 대해 코멘트 남기려고 했는데, 바다와의 의견 공유로 어느 정도 해결된 것 같아 별도로 남기지는 않았어요.
사소한 부분에서 코멘트 남겼는데, 확인해주시고 Approve 할게요! 👍👍

2024-07-31 02:28 UTC, chysis commented on frontend/src/hooks/useModalClose.ts
> +      modalBackgroundElement?.removeEventListener('click', handleBackgroundClick);
추후 JS element 오류 처리 함수가 완성되면 적용 가능할 것 같은데, 반복되는 optional chaining을 줄이기 위해, `modalBackgroundElement`가 없는 경우 early return을 적용해보는 것은 어떨까요?  사소한 부분입니다 :)

```tsx
const modalBackgroundElement = modalBackgroundRef.current;
if(!modalBackgroundElement) return;

modalBackgroundElement.addEventListener( ... )
// ...

return () => {
  modalBackgroundElement.removeEventListener( ... )
// ...
```

2024-07-31 02:35 UTC, ImxYJL commented on frontend/src/hooks/useModalClose.ts
> +      modalBackgroundElement?.removeEventListener('click', handleBackgroundClick);
요 부분은 해당 유틸 함수가 만들어지면 적용할게요 ㅎㅎ 꼼꼼하게 봐 줘서 고마워요!

2024-07-31 02:36 UTC, soosoo22 approved these changes
`useEffect` 를 수정했군요~~~👍

2024-07-31 05:17 UTC, merged