[FE] 존재하지 않는 element에 대한 에러를 출력하는 훅 제작
woowacourse-teams/2024-review-me pull request #150
Opened 2024-07-30 10:26 UTC by ImxYJL

- resolves #148 

---

### 🚀 어떤 기능을 구현했나요 ?
- Element를 찾지 못한 경우 에러 문구를 띄우는 훅 제작

### 🔥 어떻게 해결했나요 ?
- ref 객체 및 해당 요소의 이름을 받고, useEffect를 사용해 해당 요소의 존재 여부를 파악해 존재하지 않는 경우 콘솔 에러를 출력합니다. 

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- console에 에러를 출력할 때 어떤 요소에 대한 에러인지 보여주기 위해 `ref`나 `ref.current`를 출력하면 null이나 undefined로 뜨는 문제(해당 element가 없을 때만 에러를 출력하므로 무조건 저 둘 중 하나가 뜹니다)가 있어서 아예 컴포넌트 이름을 필수로 받게끔 만들었습니다. 이 방법에 대해 어떻게 생각하시는지 궁금합니다.

```ts
const useExistentElement = <T extends HTMLElement>(ref: RefObject<T>, elementName: string) => ...
```

### 📚 참고 자료, 할 말
리뷰미 짱

2024-07-30 10:37 UTC, BadaHertz52 requested changes

2024-07-30 10:37 UTC, BadaHertz52 commented on frontend/src/hooks/useExistentElement.ts
> +const useExistentElement = <T extends HTMLElement>(ref: RefObject<T>, elementName: string) => {
위 코드는 ref.current의  존재 여부를 확인하는 기능이네요
ref가 아닌 `const element =document.querySelector('#contents')`인 element에는 적용할 수 없어요

ref보다는 HTMLElement|Element|null|undefined 인 요소를 훅의 props로 받고 HTMLElement,Element 인지를 판단한다면
사용범위가 넓어질 것 같아요

2024-07-31 02:30 UTC, chysis approved these changes
커스텀 훅으로 만들었을 때 발생했던 문제들이 있었는데, 유틸 함수로 깔끔하게 구현된 것 같아요. 고생했어요!👍

2024-07-31 02:43 UTC, soosoo22 approved these changes
유틸 함수 야무지네요~~😊

2024-07-31 02:43 UTC, soosoo22 commented on frontend/src/utils/isExistentElement.ts
> +  }
존재 여부 뿐만 아니라 `Element` 이하 타입도 확인해줘서 좀 더 구체적으로 검증하는 것 같아서 좋은 것 같아요!

2024-07-31 05:19 UTC, BadaHertz52 approved these changes
아직 오류가 나지 않은 상황을 가정해서 이에 대응하는코드를 짜는 것은 어려운일인데, 올리 깔끔하게 코드 짜느라 고생했어요.👏👏👏👏👏👏👏

2024-07-31 05:31 UTC, merged