[FE] 리뷰 상세 페이지에 react-query 추가 및 리팩토링
woowacourse-teams/2024-review-me pull request #161
Opened 2024-07-31 08:13 UTC by BadaHertz52

- resolves #138

---

### 🚀 어떤 기능을 구현했나요 ?
#### Error 관련 변경 사항
- ErrorSection 을 page/ErrorPage/component 에서 src/components/error로 이동했습니다.
- ErrorBoundary의 FallbackComponent에 사용할 ErrorFallback을 추가했습니다.

#### API 요청 상태에 따른 에러 페이지, 로딩 페이지 
-` useSuspenseQuery`를 사용해 api 상태에 따라 에러 페이지, 로딩 페이지를 연동했습니다.
- 로딩 시 api를 요청하는 페이지를 위해서 ` QueryErrorResetBoundary, ErrorBoundary, Suspense`를 사용하는 `ErrorSuspenseContainer`를 만들어서 Outlet에 감싸주었습니다. 
   
- #### 기타
- 리뷰 그룹의 설명이 없을 경우, 기본값을 보여주는 것으로 수정했습니다.
- 3치-1주차 시현에 맞게 리뷰 상세 페이지에 리뷰이 이름을 추가했습니다.

### 🔥 어떻게 해결했나요 ?
- react-router v5에서 바뀐 suspense, errorBoundary 연동 부분을 공부한 후 useSuspenseQuery, QueryErrorResetBoundary를 적용했습니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 아직 API가 리팩토링 중이라 3차-1주차 시현의 디자인에 맞게 변경되었는지 확인해주세요.
-  QueryErrorResetBoundary, ErrorBoundary, Suspense`를 사용하는 `ErrorSuspenseContainer`를 Outlet에 감싸줬어요. [코멘트]()에 자세한 내용을 써놨으니 이를 참고해 `ErrorSuspenseContainer`를 제가 구현한대로 Outlet을 감싸는 방향으로 앞으로도 사용할 것 인지에 대한 의견이 궁금해요.

### 📚 참고 자료, 할 말
- 왜 gpt는 react-router 최신 버전을 모르지?

2024-07-31 08:17 UTC, BadaHertz52 commented on frontend/src/App.tsx
> +          <Outlet />
렌더링 시 API를 불러오는 페이지가 있고 그렇지 못한 페이지가 있을 수 있어요.
 그래서  `ErrorBoundary, Suspense`를  렌더링 시 API를 요청하는 페이지에만 적용하는 것을 시도해봤어요. 렌더링 시 API를 요청하는 페이지에서 아래처럼 시도를 해봤는데 `Suspense`가 Loading을 잡지 못했어요. 그레서` Outlet`을` ErrorSuspenseContainer`로 감싸는 방식을 선택하게 되었어요. 

```
//Page.tsx
// PageContents: 렌더링 시 API 요청으로 데이터를 받아와 이를 화면에 보여줌
const Page =()=>{
return (
<ErrorSuspsensContainer>
  <PageContents/>
</ErrorSuspenseContainer>
)
}
```

2024-08-01 02:30 UTC, chysis approved these changes
React query를 적용하고 리팩토링 할 것이 많았을 텐데, 고생 많았어요👍
추가로 리팩토링 하면 좋을 것 같은 부분에 코멘트를 남겼어요. 당장은 반영되지 않아도 좋다고 판단해서 Approve할게요!

2024-08-01 02:30 UTC, chysis commented on frontend/src/apis/endpoints.ts
> +    `${process.env.API_BASE_URL}/${DETAILED_REVIEW_API_PARAMS.resource}/${reviewId}?${DETAILED_REVIEW_API_PARAMS.queryString.memberId}=${memberId}`,
추후에 필요한 queryString을 위와 같이 객체 형태로 받아, 요청 URL을 만들어주는 유틸 함수를 만들어도 좋을 것 같아요!

2024-08-01 02:30 UTC, chysis commented on frontend/src/apis/review.ts
> +  const data: DetailReviewData = await response.json();
(단순 궁금증) data의 타입이 자동으로 추론되지 않아서 추가한 부분인가요?

2024-08-01 02:30 UTC, chysis commented on frontend/src/components/error/ErrorFallback/index.tsx
> +  };
errorBoundary에 전달되는 `reset`이 이렇게 사용되는군요! 👍

2024-08-01 02:30 UTC, chysis commented on frontend/src/mocks/handlers/review.ts
> +  );
에러가 발생했을 때의 핸들러도 만들어주셨네요👍

2024-08-01 02:30 UTC, chysis commented on frontend/src/pages/DetailedReviewPage/index.tsx
> +  if (!detailedReview) throw new Error(' 상세보기 리뷰 데이터를 가져올 수 없어요.');
당장은 안 해도 상관없지만, `useSuspenseQuery`로 데이터를 불러오고, 에러 처리하는 로직을 별도의 훅으로 분리해도 좋을 것 같네요!

2024-08-01 03:23 UTC, BadaHertz52 commented on frontend/src/apis/review.ts
> +  const data: DetailReviewData = await response.json();
네 맞습니다

2024-08-01 05:10 UTC, soosoo22 approved these changes
`useSuspenseQuery` 신기하네요!
리액트 쿼리뿐만 아니라 리팩도 같이 진행하느라 힘들었을텐데 고생했어요! 바다!

2024-08-01 05:10 UTC, soosoo22 commented on frontend/src/apis/review.ts
> +  const data: DetailReviewData = await response.json();
단순 궁금증인데 저는 두 번째 방법을 주로 사용해요. 첫 번째 방법으로 사용하신 이유가 있을까요

```tsx
// 첫 번째 방법
 const data: DetailReviewData = await response.json();
  return data;
```

```tsx
// 두 번째 방법
 const data = await response.json();
  return data as DetailReviewData;
```

2024-08-01 05:10 UTC, soosoo22 commented on frontend/src/mocks/handlers/review.ts
> +  );
잘못된 요청에 대한 에러를 반환하는 핸들러를 만들었군요!

2024-08-01 05:31 UTC, ImxYJL requested changes
바다~~ 이것저것 리팩토링하느라 고생 많았어요!
특히 상수화랑 comment 단어 확인해서 수정해준 게 인상깊었습니다ㅎㅎ
suspense 적용 관련해서 제안이 있어서 일단 RC 보낼게용

2024-08-01 05:31 UTC, ImxYJL commented on frontend/src/App.tsx
> +          <Outlet />
라우팅 페이지에서 아래처럼 개별로 감싸 줘도 작동하지 않나요? 리액트 라우터 버전이 예전 거긴 하지만 혹시나 해서 가져왔습니다!
```tsx
 <Route
        path="/lazy-one"
        element={(
          <Suspense fallback={<div>Loading...</div>}>
            <LazyOne />
          </Suspense>
        )}
      />
```
[참고한 글](https://stackoverflow.com/questions/76276162/how-to-selectively-apply-lazy-loading-and-suspense-to-specific-routes-with-react)

2024-08-01 05:31 UTC, ImxYJL commented on frontend/src/apis/review.ts
> +//리뷰 작성
이 주석이 추가된 이유가 있을까용?

2024-08-01 05:31 UTC, ImxYJL commented on frontend/src/components/common/RevieweeComments/index.tsx
> +import * as S from './styles';
comments 👍👍 전혀 몰랐읍니다

2024-08-01 05:31 UTC, ImxYJL commented on frontend/src/components/error/ErrorSection/index.tsx
> +            key={button.text}
key에 button.text가 들어간 이유가 궁금합니다! 인덱스보다 더 안정적으로 렌더링하기 위해서인가요?

2024-08-01 05:31 UTC, ImxYJL commented on frontend/src/mocks/mockData/detailedReviewMockData.ts
> +export const DETAILED_PAGE_ERROR_API_VALUES = {
상수화가 잘 되어있어서 아래 모킹 핸들러에서 의도를 파악하기가 더 쉬웠어요~~ 굿굿

2024-08-01 05:31 UTC, ImxYJL commented on frontend/src/mocks/mockData/detailedReviewMockData.ts
> +    description: '',
ㅋㅋㅋㅋㅋㅋ

2024-08-01 05:31 UTC, ImxYJL commented on frontend/src/pages/DetailedReviewPage/components/ReviewDescription/styles.ts
> +// 6rem :깃헙 로고 사이즈
컨벤션에 있는 내용은 아니긴 한데 이렇게 주석을 달 때 NOTE나 TODO prefix를 사용하는 걸 제안해봅니당

2024-08-01 05:55 UTC, BadaHertz52 commented on frontend/src/App.tsx
> +          <Outlet />
오! 😮 router의 element안에서 필요한 페이지마다 적용하도록 하면 되네요!!

2024-08-01 06:01 UTC, BadaHertz52 commented on frontend/src/apis/review.ts
> +  const data: DetailReviewData = await response.json();
올리의 질문을 받고 첫 번째와 두 번째 방법의 차이와 어느 쪽이 더 나은 방향인지 찾아봤어요.

둘 다 타입 강제이지만 첫 번째 방법은 타입 추론이 정확하지 않을 수도 있다고 하네요. 타입을 강제하는 방면에서는 두 번째 코드가 나아서 두 번째 코드로 수정했어요.

2024-08-01 06:03 UTC, BadaHertz52 commented on frontend/src/apis/review.ts
> +//리뷰 작성
develop 받을 때 부터 있던 거라 누군가의 의도일거라 생각했는데  충돌 과정에서 제거되어야하는 주석이 살아있었나보네요. 삭제했어요.

2024-08-01 06:07 UTC, BadaHertz52 commented on frontend/src/components/error/ErrorSection/index.tsx
> +            key={button.text}
네 맞아요. index를 사용하지 않을 수 있다면 이거를 최대한 피하려고 해요. 

한글로도 key를 사용할 수 있지만 일반된 사용을 아니라서, key를 추가했고 buttons의 네이밍을 buttonList로 변경했어요.

2024-08-01 06:08 UTC, BadaHertz52 commented on frontend/src/mocks/mockData/detailedReviewMockData.ts
> +    description: '',
vite 쓰게 해주세요.

2024-08-01 06:08 UTC, BadaHertz52 commented on frontend/src/pages/DetailedReviewPage/components/ReviewDescription/styles.ts
> +// 6rem :깃헙 로고 사이즈
이것도 컨벤션 회의 때 다뤄보면 좋겠어요.

2024-08-01 06:13 UTC, ImxYJL approved these changes
jjang jjang~~

2024-08-01 06:13 UTC, ImxYJL commented on frontend/src/index.tsx
> +        element: (
무사히 적용돼서 다행입니다!!

2024-08-01 06:28 UTC, merged