[BE] refactor: 리뷰 작성을 위한 정보 요청 기능 리팩터링
woowacourse-teams/2024-review-me pull request #162
Opened 2024-07-31 08:34 UTC by Kimprodp

- resolves #159 

---

### 🚀 어떤 기능을 구현했나요 ?
- 리뷰 작성 기능의 컨트롤러 구현을 완료했습니다.
- 리뷰 작성을 위한 정보 요청 기능을 구현했습니다.
- Swagger 노출 항목을 일부 향상시켰습니다.

### 🔥 어떻게 해결했나요 ?
- 재정의된 도메인 로직에 유의하여 해결했습니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- Swagger는 일시적일 수 있으니(변경 가능성), 구현된 기능에 집중하여 리뷰 부탁합니다.

### 📚 참고 자료, 할 말
ㅎㅎ

2024-07-31 11:15 UTC, donghoony requested changes
테드 고생했어요! 이야기할 것이 많지 않아 다음번에 바로 어푸룹 할 듯합니다..! 스웨거 참 고민되네요 🤔

2024-07-31 11:15 UTC, donghoony commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +        Long savedReviewId = reviewService.createReview(request);
이전 리뷰에서 확인하지 못햇는데, 서비스에서는 반드시 만들어서 내어주니 `long`을 반환하도록 변경하는 게 더 알맞아 보입니다 👍🏻

2024-07-31 11:15 UTC, donghoony commented on backend/src/main/java/reviewme/review/dto/response/ReviewSetupResponse.java
> +        @Schema(description = "리뷰이")
`리뷰이 이름`이라고 명세하면 `String` 타입과 호응이 맞을 듯해요.

2024-07-31 11:15 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/ReviewService.java
> +                .toList();
나중에 꼭 Question/Keyword는 뽑아냅시다 👊🏻

2024-07-31 11:15 UTC, donghoony commented on backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
> +        Question question2 = questionRepository.save(기술역량이_어떤가요.create());
사용하지 않을 변수라면 그냥 `save`만 해 둬도 좋을 것 같아요. 개인적이지만 언젠간 쓰일 거니 기억해두는 습관이 있어서.. 다른 사람들의 의견도 궁금하긴 합니다. @nayonsoso @skylar1220

2024-07-31 11:15 UTC, donghoony commented on backend/src/main/java/reviewme/review/dto/request/CreateReviewRequest.java
> +        @NotNull(message = "선택된 키워드가 없습니다.")
검증 내용에 대한 메시지를 `-요`체로 해달라는 프론트의 요청이 있었어요. 아직 바꿔야 할 게 산더미긴 한데, 지금 담당한 것만이라도 살짝 변경해주시면 좋겠습니다 😁

2024-07-31 11:15 UTC, skylar1220 requested changes
수고 많았어요 테드! 코드가 깔꼼해서 좋네요!
꼼꼼 테드
깔끔 테드
꼼깔테 굳

2024-07-31 11:15 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/keyword/dto/response/KeywordResponse.java
> +@Schema(name = "키워드 응답")
이게 그 swagger에 한글 이름으로 표시되는 역할이군요👍

2024-07-31 11:15 UTC, skylar1220 commented on backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
> +        ReviewSetupResponse reviewCreationSetup = reviewService.findReviewCreationSetup(reviewRequestCode);
(단순 궁금증💭) 변수명을 클래스명과 다르게 reviewCreationSetup로 해준 이유가 있을까요?

2024-07-31 11:15 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/controller/ReviewApi.java
> +    ResponseEntity<Void> createReview(@RequestBody CreateReviewRequest request);
이전 방식(@Operation에 다 넣는 것)이 더 간단해보이는데 해당 방식으로 수정한 이유가 있을까요?
(swagger 관련 리뷰라 변경 가능성을 고려한 시도였다면 넘기셔도 됩니다~)
```java
@Operation(
        summary = "리뷰 작성 정보 조회",
        description = "리뷰 생성 시 필요한 정보를 조회한다.",
        responses = {
                @ApiResponse(responseCode = "200", description = "리뷰 폼 응답 성공"),
                @ApiResponse(responseCode = "400", description = "응답 실패 : 올바르지 않은 리뷰 요청 코드")
        }
)
```

2024-07-31 11:15 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/ReviewService.java
> +    }
조회 메서드라 트랜잭션이 필요없다고 생각하는데 트랜잭션을 붙인 다른 이유가 있는지 궁금합니다!
또는 작업 단위 명시용이라면 성능을 위해 트랜잭션에 read only를 적용해보는 방법도 있을 것 같아요!
(아직 성능을 생각할 단계는 아니지만, 조회 메서드라는 명시 효과가 있기도 하고 붙여도 본전이라는 생각이 있습니다..ㅎㅎ)

2024-07-31 15:35 UTC, nayonsoso requested changes

2024-07-31 15:35 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/domain/Review.java
> +    @JoinColumn(name = "review_id", nullable = false, updatable = false)
👍

2024-07-31 15:35 UTC, nayonsoso commented on backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
> +        Question question2 = questionRepository.save(기술역량이_어떤가요.create());
아루 의견에 동의합니다!🧑🏻‍⚖️

2024-07-31 15:35 UTC, nayonsoso commented on backend/src/main/java/reviewme/keyword/dto/response/KeywordResponse.java
>  public record KeywordResponse(
지난 논의에서 'dto는 요청 별 하나씩 새로 만들어주기. 그리고 의미를 잘 전달하기 위해 이름을 구체적으로 적기'로 했었던 것 같아요.

그래서 재사용 방지를 위해 ReviewSetUpKeyword 같이 이름을 바꿔줄 필요가 있어 보여요.

(사실, 우리가 처음 정한 원칙을 지키면 dto가 무더기로 생기지 않을까 싶은 생각도 들긴 하는데....🫠 일단 우리가 하기로 했으니 그렇게 해보고! 나중에 필요성을 느껴면 바꿔보는게 좋을 것 같아요!)

2024-07-31 15:37 UTC, nayonsoso commented
고생했습니당 테드~~
그리고 확실히 그냥 클래스 이름 있는 것보다 
아래처럼 한글로 되어있는게 프론트가 보기 편하긴 하겠네요 ㅎㅎ
![image](https://github.com/user-attachments/assets/44c7795f-e1fe-4b5e-bfcf-4d12bdaf3a20)

2024-08-01 00:36 UTC, skylar1220 commented on backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
> +        Question question2 = questionRepository.save(기술역량이_어떤가요.create());
아동아동👍

2024-08-01 02:01 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +        Long savedReviewId = reviewService.createReview(request);
익숙하지 않다보니 자꾸 까먹네요 ..ㅎ 꼼체 👍

2024-08-01 02:02 UTC, Kimprodp commented on backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
> +        Question question2 = questionRepository.save(기술역량이_어떤가요.create());
동의합니다~

2024-08-01 02:04 UTC, Kimprodp commented on backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
> +        ReviewSetupResponse reviewCreationSetup = reviewService.findReviewCreationSetup(reviewRequestCode);
그냥 만들어진 작성 폼이라는 의미를 담고 싶었습니다..ㅎ

2024-08-01 02:05 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/controller/ReviewApi.java
> +    ResponseEntity<Void> createReview(@RequestBody CreateReviewRequest request);
```java
    @Operation(summary = "리뷰 작성 정보 조회", description = "리뷰 생성 시 필요한 정보를 조회한다.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "리뷰 폼 응답 성공",
                    content = @Content(schema = @Schema(implementation = ReviewSetupResponse.class))),
            @ApiResponse(responseCode = "400", description = "응답 실패 : 올바르지 않은 리뷰 요청 코드",
                    content = @Content)
    })
```

반환 값이 있는 경우 이렇게 content 설정을 해야하는데요, Operation 하나에서 하면 코드가 엄청 지져분해져서 ApiResponse 부분을 따로 분리하는게 더 가독성에 좋다고 생각해요. 따라서 나머지 부분들도 형식을 통일했습니다~

2024-08-01 02:06 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/service/ReviewService.java
> +    }
엇 실수 반영했씀니다 🙌

2024-08-01 02:08 UTC, donghoony commented on backend/src/main/java/reviewme/review/controller/ReviewApi.java
> +    ResponseEntity<Void> createReview(@RequestBody CreateReviewRequest request);
Swagger 어노테이션 컨벤션도 같이 이야기해보아야 하겠네요. 우선순위는 낮습니다 😢

2024-08-01 02:09 UTC, donghoony approved these changes
제가 남긴 부분은 모두 반영돼 어프룹합니다 👍🏻 고생했어요~!

2024-08-01 02:13 UTC, Kimprodp commented on backend/src/main/java/reviewme/keyword/dto/response/KeywordResponse.java
>  public record KeywordResponse(
조하요 ~ 반영햇슴니다

2024-08-01 02:15 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/controller/ReviewApi.java
> +    ResponseEntity<Void> createReview(@RequestBody CreateReviewRequest request);
아하.. 저렇게 content 설정을 안하면 성공, 실패 경우 모두 성공시 응답 객체로 swagger에서 보여지게 되는군요..!

2024-08-01 02:16 UTC, skylar1220 approved these changes
어푸푸푸룹🏊

2024-08-01 02:17 UTC, nayonsoso approved these changes
🆙prove

2024-08-01 02:17 UTC, merged