[BE] feat: 리뷰 그룹 생성 API 구현
woowacourse-teams/2024-review-me pull request #163
Opened 2024-07-31 08:37 UTC by donghoony

- resolves #158 

---

### 🚀 어떤 기능을 구현했나요 ?
- 리뷰 그룹 생성
- 그룹 생성에 필요한 코드 랜덤 생성

### 🔥 어떻게 해결했나요 ?
- 일단 빈 등록 및 MockBean으로 테스트했습니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 이해가 잘 되는지 정도면 좋겠어요

2024-07-31 12:17 UTC, skylar1220 requested changes
산초아루 조합은 역시 실패하지 않는군요
여러분의 토론의 결과 잘봤습니다! 수고 많았어요!!

2024-07-31 12:17 UTC, skylar1220 commented on backend/src/main/java/reviewme/reviewgroup/dto/ReviewGroupCreationRequest.java
리뷰 생성 요청 객체는 네이밍이 CreateReviewRequest로 create~ 형식인데 
해당 DTO는 ReviewGroupCreationRequest인 이유가 궁금합니다!

2024-07-31 12:17 UTC, skylar1220 commented on backend/src/main/java/reviewme/reviewgroup/service/RandomCodeGenerator.java
> +    }
오오오 깔끔한 intstream 사용.. 나도 써먹고싶다

2024-07-31 14:41 UTC, Kimprodp approved these changes
코드 너무 깔꼼하게 잘 구현했네요 👍👍👍 고생했습니다~

2024-07-31 14:41 UTC, Kimprodp commented on backend/src/main/java/reviewme/reviewgroup/service/RandomCodeGenerator.java
> +    private static final Random random = new Random();
지금은 상관없겠지만 `Random`이 멀티 쓰레드 환경에서는 성능 문제가 발생할 수 있다고 하니, 나중에는 좀 더 안전한 `ThreadLocalRandom`을 고려해 볼 수도 있을 것 같네요!

2024-07-31 14:41 UTC, Kimprodp commented on backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupService.java
> +    }
깔꼼하네요 👍👍

2024-07-31 15:09 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/dto/ReviewGroupCreationRequest.java
오! 제가 기존 코드를 살피지 못했었네요😓
우선 뭐가 되었든 통일해야 한다는 것은 동의합니다!

그런데 문법 자체는 `ReviewGroupCreationRequest`가 맞는 것 같은데, `CreateReviewGroupRequest`는 Create 가 앞에 있어서 생성한다는 의미가 더 잘 드러난다고 느껴져요🤔

Dto 컨벤션도 논의&문서화할 필요가 있겠네요!
개인적인 의견으로는 `CreateReviewGroupRequest`가 더

2024-07-31 15:14 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/service/RandomCodeGenerator.java
> +    }
나도...

2024-07-31 15:19 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/service/RandomCodeGenerator.java
> +    private static final Random random = new Random();
오 멀티 쓰레드 환경을 고려하는것! 좋네요.
찾아보니 Random 대신 ThreadLocalRandom 을 사용해야 할 이유가 충분해보여 수정하겠습니다! (내일 아루의 동의를 구하고 수정해볼게요)

https://velog.io/@sojukang/Random-대신-ThreadLocalRandom을-써야-하는-이유

2024-07-31 16:13 UTC, donghoony commented on backend/src/main/java/reviewme/reviewgroup/service/RandomCodeGenerator.java
> +    }
?? 산초가 쓴겁니다

2024-07-31 16:14 UTC, donghoony commented on backend/src/main/java/reviewme/reviewgroup/service/RandomCodeGenerator.java
> +    private static final Random random = new Random();
ThreadLocalRandom보다 더 강한 랜덤성을 부여하기 위해서 SecureRandom을 고려하고 있어요. 이 친구도 Thread-safe한 친구라 나중에 같이 이야기해보죠!
키워드: Pseudo-random

2024-08-01 01:56 UTC, donghoony commented on backend/src/main/java/reviewme/reviewgroup/dto/ReviewGroupCreationRequest.java
앞쪽 Create 좋네요

2024-08-01 02:00 UTC, donghoony commented on backend/src/main/java/reviewme/reviewgroup/service/RandomCodeGenerator.java
> +    private static final Random random = new Random();
우선 그대로 두겠습니다 👍🏻  (구두로 이야기 완!)

2024-08-01 02:02 UTC, skylar1220 approved these changes
어푸루루룹

2024-08-01 02:03 UTC, nayonsoso approved these changes
짱

2024-08-01 02:03 UTC, merged