[BE] feat: 헤더 존재 여부 검증
woowacourse-teams/2024-review-me pull request #207
Opened 2024-08-02 13:44 UTC by donghoony

- resolves #205 

---

### 🚀 어떤 기능을 구현했나요 ?
- Header에 원하는 필드가 존재하지 않으면, request.getHeader(name)은 null을 리턴합니다. 해당 값이 서비스와 도메인단까지 내려가 실제 쿼리로 이어집니다. 이는 의도한 것이 아니므로, 만약 존재하지 않으면 예외를 발생하게 합니다.

### 🔥 어떻게 해결했나요 ?
- 커스텀 어노테이션 및 밸리데이터를 추가했습니다.
- `Advice`에서 예외를 적절히 처리하도록 변경하고, 메시지가 클라이언트에 전달되도록 합니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 클라이언트까지 메시지를 보내기 위해서 `HandlerMethodValidationException`을 따로 뽑았습니다. 이 방법이 최선인지 확인해줘요!

### 할 말
- 예외 내부의 모든 곳에 로깅이 필요해 보여요. 어떤 메서드에서 걸리는지 확인하는 게 어려웠습니다.

2024-08-02 18:25 UTC, donghoony commented on backend/src/main/java/reviewme/review/controller/validator/ContainsHeaderName.java
> +    String headerName() default "";
`@AliasFor`는 어노테이션 내부에 `headerName=`을 적지 않고 바로 적용할 수 있도록 합니다. 기본적으로 아무것도 적지 않으면 `value`와 같은데, 이를 매핑한 것이라고 보면 돼요.

2024-08-02 18:25 UTC, donghoony commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +            @ContainsHeaderName(GROUP_ACCESS_CODE_HEADER) HttpServletRequest request
범용적으로 사용할 것을 대비해 `@ContainsHeaderName`이라고 지었어요. 만약 단순 헤더 이름이 `GroupAccessCode`였다면 그렇게도 할 수 있었겠지만.. 이 부분은 따로 빼서 값을 넣어주는 식으로 하는 게 나아 보였습니다.

2024-08-02 18:25 UTC, donghoony commented on backend/src/main/java/reviewme/review/controller/validator/ContainsHeaderValidator.java
> +        }
request에 null이 오는 상황은 통상적으로 존재하지 않지만, 테스트(직접 메서드 호출) / Request Mocking 등의 상황에서 충분히 발생할 수 있는 상황이라 원천봉쇄하는 게 낫다고 생각했어요.

2024-08-05 01:47 UTC, skylar1220 requested changes
어노테이션을 만들고.. @AliasFor를 사용하고.. 신기방기합니다🤩🤩🤩

2024-08-05 01:47 UTC, skylar1220 commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +    }
권한에 해당하는 헤더 정보가 없이 온 경우에 대해서 HandlerMethodValidationException를 내려주는 게 적절한지 궁금합니다!
권한에 해당하는 헤더 정보가 없는 경우는 인증의 문제 느낌이 있기도 해서요!

2024-08-05 01:47 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +            @Valid @ContainsHeaderName(GROUP_ACCESS_CODE_HEADER) HttpServletRequest request
사실 어노테이션을 만들고, 그 안에 validator를 연관시켜서 검증을 하는 방식을 처음봐서 이해중입니다만..😁
똑같이 어노테이션을 만들어서 ArgumentResolver가 그걸 인식해서 검증하는 방식이 처음에 떠올랐는데 
그와 비교했을 때 해당 방식의 장점이 궁금해요!

2024-08-05 12:37 UTC, donghoony commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +    }
원복했습니다 👍🏻

2024-08-05 12:38 UTC, donghoony commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +            @Valid @ContainsHeaderName(GROUP_ACCESS_CODE_HEADER) HttpServletRequest request
확실히 너무 빠졌네요, Resolver에서 `@HeaderProperty`를 찾도록 변경하는 게 나아 보입니다 !

2024-08-05 13:04 UTC, skylar1220 approved these changes
발벗고 코드 개선에 힘쓰는 아루... 저 자세 배우고만다...🦶

2024-08-05 13:04 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +            @HeaderProperty(GROUP_ACCESS_CODE_HEADER) String groupAccessCode) {
이렇게 컨트롤러에서 헤더 이름을 넣어주고 어노테이션을 만들어서 value로 관리하니까 컨트롤러 한 곳만 headerName을 알고있게되어 좋군요!

근데 다른 컨트롤러에서도 이 헤더를 확인해야하는 경우가 생긴다면 별도의 클래스 등으로 빼야할 수도 있겠다는 생각이 듭니다!

2024-08-05 13:04 UTC, skylar1220 commented on backend/src/test/java/reviewme/global/HeaderPropertyArgumentResolverTest.java
오호 이렇게 ArgumentResolver를 테스트할 때 MethodParameter와 HeaderProperty를 mock 처리해서 테스트를 한다라... 저도 따라 쳐보겠습니다👋

2024-08-06 00:24 UTC, nayonsoso reviewed
한사랑 산악회 컨셉으로 리뷰 달아봤습니다 ㅎㅎ
argumentResolver 를 테스트하는 방법을 보고 진짜 깜짝 놀랐습니다!!
저렇게 테스트 코드를 짤 수도 있군요🤩 배워갑니당~~

![image](https://github.com/user-attachments/assets/1f36b684-4d5a-4691-9a72-59e31b7d9e45)

2024-08-06 00:24 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/HeaderPropertyArgumentResolver.java
> +    }
은제 바도 멋진 코드.. 🌹

지정한 이름의 헤더가 Blank 일 때는 예외를 던지지 않고, null 일 때만 예외처리를 하게 한 것에는 어떤 의도가 있으신지 궁금헙니다...

2024-08-06 00:24 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/controller/ReviewApi.java
> +    ResponseEntity<Void> createReview(@Valid @RequestBody CreateReviewRequest request);
왜 api 문서에도 valid 를 다신건지.. 궁금헙니다.. <--@

2024-08-06 00:24 UTC, nayonsoso commented on backend/src/test/java/reviewme/global/HeaderPropertyArgumentResolverTest.java
> +    }
```suggestion
        // given
        String headerName = "test";
        String headerValue = "1234";
        NativeWebRequest request = mock(NativeWebRequest.class);
        MockHttpServletRequest mockRequest = (new MockHttpServletRequest());
        mockRequest.addHeader(headerName, headerValue);
        given(request.getNativeRequest()).willReturn(mockRequest);
        given(headerProperty.headerName()).willReturn(headerName);

        // when
        String actual = resolver.resolveArgument(parameter, null, request, null);

        // then
        assertThat(actual).isEqualTo(headerValue);
```

테스트 코드에서는 변수명을 통해 의미 전달을 하는게 좋을 것 같읍니다..

2024-08-06 01:05 UTC, donghoony commented on backend/src/main/java/reviewme/global/HeaderPropertyArgumentResolver.java
> +    }
문제가 되는 부분이 헤더가 존재하지 않을 때 `null`이 쿼리까지 들어가는 거라서, 이를 방지하고자 했습니다.

2024-08-06 01:05 UTC, donghoony commented on backend/src/main/java/reviewme/review/controller/ReviewApi.java
> +    ResponseEntity<Void> createReview(@Valid @RequestBody CreateReviewRequest request);
이거 없으니까 안 돌아가던데요 !?

2024-08-06 01:07 UTC, donghoony commented on backend/src/main/java/reviewme/review/controller/ReviewApi.java
> +    ResponseEntity<Void> createReview(@Valid @RequestBody CreateReviewRequest request);
뭐지 없어도 되었네요..? 🤔 Validator 추가할 때 어딘가 꼬였나봐요, 다시 돌려놓겠습니다 👍🏻

2024-08-06 04:33 UTC, donghoony commented on backend/src/test/java/reviewme/global/HeaderPropertyArgumentResolverTest.java
> +    }
반영할게요~

2024-08-06 04:35 UTC, nayonsoso approved these changes
은제바도 머찐 코두입니다

2024-08-06 04:35 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/controller/ReviewApi.java
> +    ResponseEntity<Void> createReview(@RequestBody CreateReviewRequest request);
👍

2024-08-06 04:35 UTC, nayonsoso commented on backend/src/test/java/reviewme/global/HeaderPropertyArgumentResolverTest.java
> +    }
👍

2024-08-06 07:41 UTC, Kimprodp approved these changes
고생햇슴니다. swagger 사용을 위한 @RequestHeader 는 같이 좀 더 고민해봅시당~

2024-08-06 07:50 UTC, merged