[BE] feat: 리뷰 단건 조회 API 업데이트
woowacourse-teams/2024-review-me pull request #294
Opened 2024-08-10 16:24 UTC by donghoony

- resolves #287 

---

### 🚀 어떤 기능을 구현했나요 ?
- 리뷰 단건 조회를 새로운 API 기능 사양에 맞게 변경했습니다.

### 🔥 어떻게 해결했나요 ?
- 다양한 Native query를 사용할 수밖에 없었습니다.
- `@CollectionTable`으로 생성되는 테이블은 데이터베이스 격리가 불가능해 이를 빼냈습니다.
- 추가적인 사항들은 코드에 담아두겠습니다

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 미처 확인하지 못한 예외 사항
- 요구 사항을 잘 충족했는지 파악해 주세요-

### 📚 참고 자료, 할 말
- 와 해냈다 과연?

2024-08-10 16:33 UTC, donghoony commented on backend/src/main/java/reviewme/question/repository/OptionItemRepository.java
> +            nativeQuery = true)
여러 개를 Join해올 때에는 id가 겹쳐서, `SELECT o.*`와 같이 앞쪽 와일드카드를 사용해야 해요

2024-08-10 16:33 UTC, donghoony commented on backend/src/main/java/reviewme/review/domain/TextAnswers.java
> +public class TextAnswers {
서비스에서 낼 수 있는 예외를 도메인 클래스를 생성해 위임했습니다. 따로 엔티티는 아니예요!

2024-08-10 16:33 UTC, donghoony commented on backend/src/main/java/reviewme/review/domain/CheckboxAnswer.java
> +    private List<CheckBoxAnswerSelectedOptionId> selectedOptionIds;
- `@CollectionTable`을 사용하면 `DatabaseCleaner`가 이를 찾아내지 못합니다 (`Table` 어노테이션 활용)
- 나아가 저희가 이야기한 `@CollectionTable`의 단점들도 있기에 (전체 삭제 등), 이를 `@OneToMany` + `@JoinColumn(updatable = false)`로 해결할 수 있다고 보았어요.

2024-08-10 16:33 UTC, donghoony commented on backend/src/main/java/reviewme/template/domain/SectionQuestionId.java
> +    private long sectionId;
FK를 가지지 않아도 되지만, 네이티브 쿼리로 짤 일이 많다보니 테이블 열과 일치할 필요가 있었어요.
찾아보니 이런 식으로 작성하면 직접 생성할 때 값이 없어도, 포함하는 테이블에서 Persist할 때 함께 등록됩니다.

2024-08-10 16:33 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/ReviewDetailService.java
> +            questionResponses.add(getTextAnswerResponse(question, textAnswers));
이런 식으로 분기하는 게 적절할까요? 어쩔 수 없었을까요?

2024-08-10 16:33 UTC, donghoony commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +    }
임시로 V2로 두었는데, 이거 기존 API를 두고 컨트롤러를 사악 올려도 될 것 같아요 😋

2024-08-11 03:22 UTC, skylar1220 requested changes
테스트 격리 문제가 중간 테이블 적용으로 해결되었군요👍👍👍

2024-08-11 03:22 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/review/service/dto/response/detail/TemplateAnswerResponse.java
> +        List<SectionAnswerResponse> sections
LocalDate createAt이 추가되어야 하겠네요!

2024-08-11 03:22 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/review/service/dto/response/detail/TemplateAnswerResponse.java
> +        long formId,
템플릿은 말그대로 템플릿으로서의 의미가 크게 느껴지기도 해서 TemplateAnswer라는 DTO명이 낮설게 느껴지기도 합니다!
id명도 formId니까 FormAnswerResponse은 어떤가요?

2024-08-11 03:22 UTC, hyeonji1220 commented on backend/src/test/java/reviewme/review/domain/TextAnswersTest.java
> +        assertThat(actual.getContent()).isEqualTo("답변");
given, when, then 개행이 필요합니다~

2024-08-11 03:33 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/dto/response/detail/TemplateAnswerResponse.java
> +        List<SectionAnswerResponse> sections
이거 우선 생성자에서 `now()`를 하고, JPA Audit을 쓰는 게 깔끔할 것 같아요

2024-08-11 03:33 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/dto/response/detail/TemplateAnswerResponse.java
> +        long formId,
전체 네이밍을 바꾸자는 제안인가요 ? Template -> Form?

2024-08-11 03:34 UTC, donghoony commented on backend/src/test/java/reviewme/review/domain/TextAnswersTest.java
> +        assertThat(actual.getContent()).isEqualTo("답변");
👍🏻

2024-08-11 04:41 UTC, Kimprodp requested changes
오우..... 고생했어요 일단 코멘트 확인 북탁함니다~

2024-08-11 04:41 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/service/ReviewDetailLookupService.java
> +                .orElseThrow(() -> new ReviewGroupNotFoundByGroupAccessCodeException(groupAccessCode));
리뷰 그룹을 찾고 난 후 조회하려는 리뷰와 일치하지 않는 경우 인 것 같아요. (그룹 액세스 코드는 검증했지만, 볼 수 없는 리뷰인 경우?)
ReviewGroupNotFoundByGroupAccessCodeException 보다는 다른 메세지가 담긴 예외가 나을 것 같아요

2024-08-11 04:41 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/service/ReviewDetailLookupService.java
> +        List<SectionAnswerResponse> sectionResponses = sectionRepository.findAllByTemplateId(templateId)
template 레포에서 template를 찾고 sectionIds 로 찾는 것과 네이티브 쿼리로 한방에 찾는 것 중 어떤 방법이 더 좋을지 고민되네요..

2024-08-11 04:41 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/service/ReviewDetailLookupService.java
> +                .filter(section -> section.isVisibleBySelectedOptionIds(selectedOptionItemIds))
always와 작성된 섹션만 가져오는 것 좋네요👍👍

2024-08-11 04:41 UTC, Kimprodp commented on backend/src/main/java/reviewme/question/repository/OptionGroupRepository.java
> +    default OptionGroup getByQuestionId(long questionId) {
default 메서드명 컨벤션을 어떻게 통일하면 좋을까요..
지금 get000By000Id 로 되어있는 것들도 있고 이런 경우도 있는 것 같아요.
개인적으로는 findByIdorThrow 처럼 안에 검증이 포함되어있다 라는 것을 명시한 네이밍도 좋다고 생각해요

2024-08-11 04:45 UTC, nayonsoso reviewed
아루 고생 많았어요~~🥳
어려운 부분을 맡았었네요! 고생한 흔적이 보입니다🥹
궁금한 부분들 코멘트 남겼으니 확인 부탁해요!

2024-08-11 04:45 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/dto/response/detail/QuestionAnswerResponse.java
> +) {
질문이 있습니다!
@Nullable 어노테이션이 있고 없고가 무슨 차이가 있나요?

2024-08-11 04:45 UTC, nayonsoso commented on backend/src/main/java/reviewme/template/domain/Section.java
> +    }
Collection 으로 받아서 List 와 Set 모두 받을 수 있게 한것 좋네용🥹👏

2024-08-11 04:45 UTC, nayonsoso commented on backend/src/main/java/reviewme/template/repository/SectionRepository.java
> +    List<Section> findAllByTemplateId(long templateId);
```
    @Query(value = """
            SELECT s.* FROM section s LEFT JOIN template_section ts
            ON ts.section_id = s.id
            WHERE ts.template_id = :templateId
            ORDER BY s.position ASC
            """,
            nativeQuery = true
    )
```

요렇게 안하신 이유가 있으신가용? (이렇게 하라는 것 아님. 모든 것에 뜻이 있는 아루상은 왜 이렇게 했는지 궁금했을 뿐)

2024-08-11 04:45 UTC, nayonsoso commented on backend/src/main/java/reviewme/template/repository/SectionRepository.java
> +    List<Section> findAllByTemplateId(long templateId);
template이 `List<Long>sectionId` 를 갖게 하니 이런 쿼리를 많이 작성해야 했군요ㅠ 왜 아래처럼 말했는지 알것 같습니당..

![image](https://github.com/user-attachments/assets/d7e78261-337e-4f09-96cc-0fa1e1d52a00)

2024-08-11 04:45 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/repository/QuestionRepository2.java
> +            "ORDER BY q.position ASC",
위치 신경쓴거 굳굳~~

2024-08-11 04:45 UTC, nayonsoso commented on backend/src/main/java/reviewme/question/domain/exception/OptionGroupNotFoundException.java
> +    }
`OptionGroupNotFoundException` 보다 더 구체적인 이름이면 좋겠어요. 지금 `{도메인이름}NotFoundException` 으로 구성된 예외는 레포지토리의 default getXXXById 에서 발생시키는 것들이라,!

2024-08-11 04:45 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/domain/exception/TextAnswerNotFoundException.java
> +}
이것도 예외 이름 더 구체적으로 해주세요! (이유는 앞에 말한 것과 동일)

2024-08-11 04:45 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/domain/CheckBoxAnswerSelectedOptionId.java
> +public class CheckBoxAnswerSelectedOptionId {
CheckBoxAnswerSelectedOptionId -> `CheckBoxAnswerSelectedOption` 로 가볼까용~?
CheckBoxAnswer도 id 만 저장하고 SelectedOption도 id 만 저장하니까 개념상 중간테이블이고, 중간 테이블이라면 두 도메인 이름을 연결하는게 자연스럽네용!

그리고 도메인 이름이 Id 로 끝나는게 어색하기도 하네용!

(~것 같아요 안쓰기 힘드네용..)

2024-08-11 04:45 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/domain/CheckboxAnswer.java
> +    private List<CheckBoxAnswerSelectedOptionId> selectedOptionIds;
식별자 없는 테이블보다 이게 더 좋다고 생각됩니다 👍

2024-08-11 04:45 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/domain/CheckboxAnswer.java
> +    private List<CheckBoxAnswerSelectedOptionId> selectedOptionIds;
그리고 이 부분도 필드명을 selectedOptions 로 가는게 좋겠네요!

2024-08-11 04:45 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/ReviewDetailService.java
> +                .orElseThrow(() -> new ReviewGroupNotFoundByGroupAccessCodeException(groupAccessCode));
이 경우 그룹 엑세스 코드는 일치하지만, 그 그룹에 리뷰가 해당하지 않는데 조회하려 하므로 "그룹에 존재하지 않는 리뷰입니다"와 같은 예외가 있으면 좋겠네요. 지난 번에도 그렇게 했던 것 같고요!

2024-08-11 04:45 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/domain/TextAnswers.java
> +    }
이 객체는 무엇을 목적으로 만드신 건지 궁금해요! 🙋🏻‍♀️

서비스 코드와 함께 봤을 때, (제가 이해하기로는 )

- Template 안의 Section 안의 `questionIds` 에 대응하는
- Review 안의 TextQuestion 안의 `questionId` 가 있는지

검증하기 위함 같은데, 그럼 저장 과정 중에 questionId 가 잘못 저장되는 경우를 염두에 두신 건가요?

2024-08-11 04:45 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/ReviewDetailService.java
> +            questionResponses.add(getTextAnswerResponse(question, textAnswers));
상속이나 인터페이스를 만들지 않은 지금은 이 방법밖에 업다 생각합니다

2024-08-11 04:45 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +    }
좋은 생각입니당~

2024-08-11 07:17 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/ReviewDetailLookupService.java
> +                .orElseThrow(() -> new ReviewGroupNotFoundByGroupAccessCodeException(groupAccessCode));
기존에 존재하는 ReviewIsNotInReviewException으로 바꿨습니다

2024-08-11 07:19 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/ReviewDetailLookupService.java
> +                .orElseThrow(() -> new ReviewGroupNotFoundByGroupAccessCodeException(groupAccessCode));
사용자 입장에서는 존재하지 않는 예외로 내보내는 게 좋겠습니다

2024-08-11 07:20 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/ReviewDetailLookupService.java
> +        List<SectionAnswerResponse> sectionResponses = sectionRepository.findAllByTemplateId(templateId)
쿼리 개수로 따지면 이 쪽이 훨씬 효율적이라고 느낍니다. 한 번에 가져오는 게 낫다고 판단했어요

2024-08-11 07:20 UTC, donghoony commented on backend/src/main/java/reviewme/question/repository/OptionGroupRepository.java
> +    default OptionGroup getByQuestionId(long questionId) {
오? `getOrElseThrow()`로 바깥에서 예외를 넣어주는 것도 좋겠는데요 ㅋㅋ

2024-08-11 07:21 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/dto/response/detail/QuestionAnswerResponse.java
> +) {
단순한 명시입니다, 이런 게 주석보다 훨씬 의미있다고 생각했어요. 나아가 스웨거와 같은 문서화 작업에서도 도움될 것이예요

2024-08-11 07:21 UTC, donghoony commented on backend/src/main/java/reviewme/template/repository/SectionRepository.java
> +    List<Section> findAllByTemplateId(long templateId);
오잉 저거 안 되는 줄 알았습니다 반영할게요

2024-08-11 07:26 UTC, donghoony commented on backend/src/main/java/reviewme/question/domain/exception/OptionGroupNotFoundException.java
> +    }
`MissingOptionGroupForQuestionException`으로 변경합니다, 아래도 마찬가지요~

2024-08-11 07:28 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/ReviewDetailService.java
> +                .orElseThrow(() -> new ReviewGroupNotFoundByGroupAccessCodeException(groupAccessCode));
반영했는데, 기존 예외 클래스명이 다가오지 않아서 함께 수정했습니다

2024-08-11 07:39 UTC, donghoony commented on backend/src/main/java/reviewme/review/domain/TextAnswers.java
> +    }
- 가져오는 걸 get get 하는 것이 별로라고 생각했어요
- 넣을 때 검증도 있지만, 빼낼 때의 검증을 하지 않아서 나쁠 게 없다고 생각했어요 🤔 
-

2024-08-11 07:59 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/review/service/dto/response/detail/TemplateAnswerResponse.java
> +        long formId,
아니요 이 DTO 이름만 해당하는 제안이었습니다~
https://github.com/woowacourse-teams/2024-review-me/pull/296#discussion_r1712914545 
이 코멘트와도 연결이 되어있어요!

2024-08-11 08:30 UTC, Kimprodp commented on backend/src/main/java/reviewme/question/repository/OptionGroupRepository.java
> +    default OptionGroup getByQuestionId(long questionId) {
통일성 있게 사용 가능하면 이 방법도 논의 해보면 좋겠네요

2024-08-11 08:32 UTC, Kimprodp approved these changes

2024-08-11 15:45 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/dto/response/detail/QuestionAnswerResponse.java
> +) {
오 좋은 생각이네요! 사용한다면 다 통일하는게 좋을 것 같으니 이슈로 만들어둘게요!

2024-08-11 16:02 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/domain/TextAnswers.java
> +    }
그렇다면 이때 발생하는 예외는 ERROR 레벨이어야 하겠네요, 
제약조건 준수가 되지 않는 데이터가 들어가있는 상황이니까요😲

2024-08-12 04:10 UTC, skylar1220 approved these changes
일프로브!!

2024-08-12 04:10 UTC, nayonsoso approved these changes
어푸푸푸푸르루브 🏊🏻

2024-08-12 04:17 UTC, merged