[BE] 변경된 도메인 구조가 적용된 리뷰 작성 API 를 구현한다.
woowacourse-teams/2024-review-me pull request #296
Opened 2024-08-10 20:56 UTC by nayonsoso

- resolves #292 

---

### 🚀 어떤 기능을 구현했나요 ?
- 리뷰 작성 기능을 구현했습니다.

### 🔥 어떻게 해결했나요 ?
- 충돌이 나는 것을 피하기 위해 & 서비스 분리가 필요하다 생각해서 CreateReviewService 를 만들어서 거기서 작업했습니다.
- dto 도 패키지 별 분리를 하면 좋겠다 생각해서 create 라는 패키지를 파서 거기에 dto 추가 생성했습니다.
- 서술형 질문, 객관식 질문에 대해서 저장을 할 때 검증이 많아서 객체를 분리했습니다.
- 특히 객관식 질문 검증 짱마늠

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 이번에 서비스도 분리하고 dto 패키지도 분리하는 등 제가 주관대로 한 부분들이 조금 있는데, 혹시 마음에 안들면 코멘트 남겨주세용~

### 📚 참고 자료, 할 말

- 다음에 도메인 엎고 역할 분배할 순간이 다시 온다면, "생성자와 레포지토리 & default 함수 정도"는 만들고 분배해야 할 듯🤯

### 공통 코드에서 리팩터링 필요하다 느낀 부분
1. 선택지를 뜻하는 checkbox 와 option 이라는 단어를 통일해서 하나만 사용해야 한다.
2. Review 가 templateId 를 갖는게 아니라 ReviewGroup 이 갖게 해야 한다.
3. 테스트 코드를 작성할 때, Template 이 SessionId 를 List<Long> sessionIds 으로 참조하고 있는 상태에서, template.getSesstionIds() 를 호출하니 lazily initialize exception 이 발생했다. ElementCollection으로 참조하는 것도 **순전히 자바 객체처럼 참조하는 것은 아니고, 내부적으로 트랜잭션을 신경써야 하는 것 같다.** 일단 테스트코드에서 그런 상황이 발생하지 않게끔 갯수만 검증하는 식으로 구현하긴 했다.

2024-08-11 03:11 UTC, donghoony requested changes
밤까지 고생했습니다 👍🏻

2024-08-11 03:11 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/exception/CheckBoxAnswerIncludedNotProvidedOptionItemException.java
> +    public CheckBoxAnswerIncludedNotProvidedOptionItemException(List<Long> providedOptionIds, List<Long> submittedOptionIds) {
이 로그 받았을 때 문맥이 부족할 것 같아요

2024-08-11 03:11 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/CreateCheckBoxAnswerRequestValidator.java
> +@Service
`@Component`?

2024-08-11 03:11 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/CreateTextAnswerRequestValidator.java
> +@Service
여기도요~!

2024-08-11 03:11 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/exception/TextAnswerIncudedOptionException.java
> +public class TextAnswerIncudedOptionException extends BadRequestException {
오타 있습니다!

2024-08-11 03:11 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/exception/RequiredQuestionMustBeAnsweredException.java
> +    public RequiredQuestionMustBeAnsweredException(long questionId) {
해야 한다~ 라는 뉘앙스로 예외 클래스 이름을 작성하기보다는 현재 상태를 나타내는 게 나을 것 같아요.
`MissingRequiredQuestionAnswerException` 정도는 어떨까요

2024-08-11 03:11 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/exception/SelectedCheckBoxAnswerCountOutOfRange.java
> +    public SelectedCheckBoxAnswerCountOutOfRange(int selectedCount, int minSelectionCount, int maxSelectionCount) {
어떤 질문에서 발생했는지 문맥이 필요해요

2024-08-11 03:11 UTC, donghoony commented on backend/src/test/java/reviewme/review/service/CreateCheckBoxAnswerRequestValidatorTest.java
> +                null);
개행 통일해주세요!

2024-08-11 03:11 UTC, donghoony commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
>          return ResponseEntity.created(URI.create("/reviews/" + savedReviewId)).build();
해당 부분이 머지되면 순간 프론트 쪽에서 접근이 어려울 것 같은데, `/v2/reviews/`와 같이 엔드포인트를 따로 열면 어떨까요?

2024-08-11 03:11 UTC, donghoony commented on backend/src/main/java/reviewme/review/domain/Review2.java
> +    @OneToMany(cascade = CascadeType.PERSIST, fetch = FetchType.EAGER)
👍🏻 생명주기 일치하는 친구들끼리만 연관관계 이었으니 EAGER 해도 된다고 생각해요

2024-08-11 03:11 UTC, donghoony commented on backend/src/main/java/reviewme/template/domain/Section.java
> +    public Section(VisibleType visibleType, List<Long> questionIds, Long onSelectedOptionId, String header,
논리적 개행 부탁합니다~ position만 덩그러니 있는 것보다는 몇 개 같이 내려와도 될 듯해요

2024-08-11 05:13 UTC, Kimprodp approved these changes
전체적으로 좋네요 급하게 수정되어야 할 부분은 없을 것 같고, 논의가 필요한 부분만 다 같이 논의해보면 좋을듯!

참고로 로깅 너무 잘해놔서 내 기능 구현할때 편했어요 (●'◡'●)👍

2024-08-11 05:13 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/domain/Review2.java
> +    private long templateId; // todo: templateId 를 여기가 아니라 reviewGroup 안에 둬야 함
이 부분 다시 논의 해보면 좋겠지만, 중간에 템플릿이 변경되면 리뷰 그룹을 다시 생성해야 하나요?
리뷰 그룹이 templateId를 가지고 있으면 리뷰 그룹 하나는 하나의 템플릿만 사용하지 못할 것 같은데..

2024-08-11 05:13 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +    private final CreateReviewService createReviewService;
크리서 분리 👍👍👍

2024-08-11 05:13 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/service/CreateReviewService.java
> +    private ReviewGroup validateReviewGroupByRequestCode(String reviewRequestCode) {
메서드 분리 👍👍👍

2024-08-11 06:42 UTC, skylar1220 requested changes
검증 수고했어여🥲👏

2024-08-11 06:42 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/template/domain/exception/OptionItemNotFoundException.java
> +        super("옵션 아이템이 존재하지 않아요.");
'옵션 아이템'은 백엔드 입장에서의 엔티티 명칭이라 클라이언트 입장에서는 컨텍스트가 충분하지 않을 수 있겠네요!
떠오르는 건 '선택지가 존재하지 않아요' 정도인데 더 나은 대안이 있을지! (항상 네이밍은 어렵네요🙄)

+ 만약 이 부분이 변경된다면 '옵션 그룹'도 컨텍스트가 충분한지 같이 생각될 부분이네요!

2024-08-11 06:42 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/template/domain/exception/OptionItemNotFoundException.java
> +        log.info("OptionItemNotFoundException is occurred - id: {}", id);
예외의 info / warn / error를 책정하는 기준이 있어야겠네요!
이 예외도 일어날 가능성이 적다는 측면이라면 warn 정도도 괜찮을 것 같아요!

2024-08-11 06:42 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/CreateReviewService.java
> +    private void validateSubmittedQuestionAndProvidedQuestionMatch(CreateReviewRequest request, Template template) {
`validateFormAndTemplateQuestionMatch`
응답한 폼은 Form, 양식은 Template 으로 명칭을 통일해서 이름을 간략화하는 건 어떨까요? 
다른 pr에도 코멘트로 남겼는데, 이 명칭이 혼용되고 있는 것에 대해 문제를 느꼈었어서요!
이건 전체 논의가 필요할 것 같네요!

@Kimprodp @donghoony

2024-08-11 06:42 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/CreateCheckBoxAnswerRequestValidator.java
> +                .orElseThrow(() -> new OptionGroupNotFoundException(question.getId()));
해당 예외는 '옵션 그룹이 존재하지 않아요.' 메시지를 보여주고 있어요!
`question에 해당하는` optionGroup이 없다의 컨텍스트가 담긴 예외가 필요해보입니다~ 
(예: `OptionGroupNotFoundByQuestionException`)

2024-08-11 06:42 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/CreateCheckBoxAnswerRequestValidator.java
> +        }
(수정사항 아님! 논의할점!)
그리고 `request.selectedOptionIds() == null` 이 부분 리스트인데 null 검증을 하고있는 상황을 보면서 생각이 들었는데요!
현재 api 문서에는 주관식인경우 selectedOptionIds가 null로 오고있는데 null 위험성을 경계하자면 프론트에게 빈 list로 보내달라고 요청하는 건 어떨까? 하는 생각이 들어서 논의해보고 싶네요!

2024-08-11 06:42 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/CreateCheckBoxAnswerRequestValidator.java
> +        OptionGroup optionGroup = validateOptionGroupExists(question);
validate 메서드가 리턴값이 있는게 이해하는데 혼선을 줄 수 있다고 생각해요!
처음부터 변수로 빼는 건 어떨까요?
```suggestion
        OptionGroup optionGroup = optionGroupRepository.findByQuestionId(question.getId())
                .orElseThrow(() -> new OptionGroupNotFoundException(question.getId()));
        Question2 question = question2Repository.getQuestionById(questionId)
```

2024-08-11 06:42 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/CreateReviewService.java
> +                .orElseThrow(() -> new ReviewGroupNotFoundByRequestReviewCodeException(reviewRequestCode));
createService를 분리하여 관심사도 분리하고, 응집도 up! 서비스 가벼워지는 것 좋아요~
다만 이런 부분이 reviewService(분리 후에는 조회에 집중되어있음)에도 중복 로직이 있어서 이런 부분을 아예 조회 서비스에서 불러와서 쓰게해야할지, 중복을 감수할지 고민이네요!

2024-08-11 06:42 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/CreateTextAnswerRequestValidator.java
> +    }
이 부분은 선택형 validator, 서술형 validator에 중복으로 들어있는 로직이네요.
만약 수정사항이 생기면 두 부분의 검증 메서드의 정합성을 신경써야한다는 점이 걸려요!
1. 완전 공통 validate 부분은 서비스에서 검증하기
2. 공통 검증 validator를 하나 만들기
두개정도 떠오르는데 2번은 과하니 1번 방법은 어떤가요?

2024-08-11 13:38 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/exception/CheckBoxAnswerIncludedNotProvidedOptionItemException.java
> +    public CheckBoxAnswerIncludedNotProvidedOptionItemException(List<Long> providedOptionIds, List<Long> submittedOptionIds) {
수정했습니다!

2024-08-11 13:39 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/CreateCheckBoxAnswerRequestValidator.java
> +@Service
반영했습니다~

2024-08-11 13:39 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/CreateTextAnswerRequestValidator.java
> +@Service
ditto!

2024-08-11 13:48 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/exception/TextAnswerIncudedOptionException.java
> +public class TextAnswerIncudedOptionException extends BadRequestException {
수정했습니다!👍

2024-08-11 13:49 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/exception/RequiredQuestionMustBeAnsweredException.java
> +    public RequiredQuestionMustBeAnsweredException(long questionId) {
동의합니다, 수정했어요!

2024-08-11 13:51 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/exception/SelectedCheckBoxAnswerCountOutOfRange.java
> +    public SelectedCheckBoxAnswerCountOutOfRange(int selectedCount, int minSelectionCount, int maxSelectionCount) {
로그에 문맥!! 동의합니다, 수정했어요!

2024-08-11 13:53 UTC, nayonsoso commented on backend/src/test/java/reviewme/review/service/CreateCheckBoxAnswerRequestValidatorTest.java
> +                null);
해당 클래스 전반적으로 다 통일해줬어요!

2024-08-11 13:57 UTC, nayonsoso commented on backend/src/main/java/reviewme/template/domain/Section.java
> +    public Section(VisibleType visibleType, List<Long> questionIds, Long onSelectedOptionId, String header,
반영했습니다~

2024-08-11 14:00 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/domain/Review2.java
> +    private long templateId; // todo: templateId 를 여기가 아니라 reviewGroup 안에 둬야 함
> 리뷰 그룹이 templateId를 가지고 있으면 리뷰 그룹 하나는 하나의 템플릿만 사용하지 못할 것 같은데..

하나의 리뷰 그룹은 하나의 템플릿을 사용하는게 자연스럽다고 생각해요!
'리뷰 그룹'이라고 함은, 리뷰를 작성하는 대상들을 정의하는 것인데,
작성자들마다 다른 템플릿을 보여주진 않을 것 같아요.
혹시 테드가 다르게 생각하고 있는 부분이 있다면 알려주세용~

> 중간에 템플릿이 변경되면 리뷰 그룹을 다시 생성해야 하나요?

이건 다 같이 논의되지 않았긴 했는데, 제 생각에는 중간에 템플릿이 바뀌지 않을 것 같습니다

2024-08-11 14:16 UTC, nayonsoso commented on backend/src/main/java/reviewme/template/domain/exception/OptionItemNotFoundException.java
> +        super("옵션 아이템이 존재하지 않아요.");
> '옵션 아이템'은 백엔드 입장에서의 엔티티 명칭이라 클라이언트 입장에서는 컨텍스트가 충분하지 않을 수 있겠네요!

그렇겠네요 ㅇ0ㅇ

옵션 아이템이 존재하지 않아요. => 선택지가 존재하지 않아요.
옵션 그룹이 존재하지 않아요 => 응답한 질문과 대응하는 선택형 문항이 존재하지 않아요. 

로 바꿨습니다!

2024-08-11 14:17 UTC, nayonsoso commented on backend/src/main/java/reviewme/template/domain/exception/OptionItemNotFoundException.java
> +        log.info("OptionItemNotFoundException is occurred - id: {}", id);
> 예외의 info / warn / error를 책정하는 기준이 있어야겠네요!

동의합니다~
서버가 내려준 대로 응답하면 발생하지 않을 예외들은 warn 으로 두는게 좋을 것 같아요.
누군가 사이트를 통하지 않고 이상한 형식으로 리뷰를 제출하려 한다는 거니까요.
이건 지금 고칠건 아닌 것 같고, 나중에 상의할 필요가 있다는 생각이 들어 이슈에 추가해뒀습니다!

2024-08-11 14:24 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/CreateReviewService.java
> +    private void validateSubmittedQuestionAndProvidedQuestionMatch(CreateReviewRequest request, Template template) {
> 응답한 폼은 Form, 양식은 Template 으로 명칭을 통일해서 이름을 간략화하는 건 어떨까요?

이 문장에서

> 응답한 폼은 Form, 양식은 Template 으로 명칭을 통일

하는 것은 좋은 의견같습니다!

> 이름을 간략화하는 건 어떨까요?

하지만 이 검증 함수는 '질문의 id'를 검증한다는 뜻이 들어갔으면 해서 길더라도 지금의 이름이 의미를 잘 드러낸다고 생각해요. 그래서 일단 이렇게 두겠습니다 ㅎㅎ

2024-08-11 14:26 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/CreateCheckBoxAnswerRequestValidator.java
> +                .orElseThrow(() -> new OptionGroupNotFoundException(question.getId()));
반영했습니다!

2024-08-11 14:30 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/CreateCheckBoxAnswerRequestValidator.java
> +        OptionGroup optionGroup = validateOptionGroupExists(question);
사실 저도 validate 함수가 리턴을 하게 할까, 말까 고민이 되었는데,
validate 가 촤르륵 적혀있으면 각 줄에 뭘 검증하는지 보기가 편해서 저렇게 해뒀었습니다 ㅎㅎ
그런데 혼선을 줄 수 있다면 커비가 제안하는 방향으로 변경하겠습니다!

2024-08-11 14:33 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/CreateReviewService.java
> +                .orElseThrow(() -> new ReviewGroupNotFoundByRequestReviewCodeException(reviewRequestCode));
> 응집도 up! 서비스 가벼워지는 것 좋아요~

🥰

> 다만 이런 부분이 reviewService(분리 후에는 조회에 집중되어있음)에도 중복 로직이 있어서 이런 부분을 아예 조회 서비스에서 불러와서 쓰게해야할지, 중복을 감수할지 고민이네요!

서비스를 각각 분리한다면 충분히 생길만한 고민이네요! 그런 순간이 왔을 때 해결책을 찾아보는 것도 좋을 것 같아요~

2024-08-11 14:54 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/CreateTextAnswerRequestValidator.java
> +    }
예리하게 보셨네요... 
그런데 더욱 놀라운 사실은 이미 1번을 서비스에서 하고 있습니다.!

![image](https://github.com/user-attachments/assets/f4066383-9e43-4c6b-80d7-f2cdf18fe3b9)

그래서 왜 서비스에서 검증하는 것을 XXXAnswerRequestValidator에도 검증하느냐 한다면,
저는 XXXAnswerRequestValidator 그 자체로 "검증해주는 객체"로 생각했어요. 그래서 앞에서 어떤 함수를 선언했는지에 상관 없이 그 안에서 QuestionId에 대한 검증을 하게 해줬어요. 제출된 응답에 대해 검증을 하는 객체이니까, 그 응답이 존재하는 questionId에 대한것인지 검증하는 책임을 갖는게 당연하다 생각했지요!

> 수정사항이 생기면 두 부분의 검증 메서드의 정합성을 신경써야한다는 점이 걸려요!

그와 별개로 이 부분에는 동의를 하는데요, 상속을 사용하면 참 좋겠다는 생각을 했습니다. 이건 나중에 더 이야기해봐요!

2024-08-11 14:55 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
>          return ResponseEntity.created(URI.create("/reviews/" + savedReviewId)).build();
기존것 그대로 두고 v2 만들어주었습니다 😊

2024-08-12 04:40 UTC, donghoony approved these changes

2024-08-12 04:40 UTC, skylar1220 approved these changes
궈궈

2024-08-12 04:41 UTC, merged