[BE] docs: Swagger를 활용한 API 문서 자동화
woowacourse-teams/2024-review-me pull request #31
Opened 2024-07-17 07:23 UTC by skylar1220

- resolves #29 

---

### 🚀 어떤 기능을 구현했나요 ?
- Swagger를 활용하여 API 문서를 자동화하였습니다.

### 🔥 어떻게 해결했나요 ?
- Swagger 라이브러리 추가 및 yml 설정 추가
- SwaggerConfig 구현
- 컨트롤러에 swagger 어노테이션 적용

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 문서가 잘 나오는지 확인해주세요.
- 커밋 메시지의 prefix가 적절한지 확인해주세요.

2024-07-18 01:34 UTC, nayonsoso requested changes

2024-07-18 01:34 UTC, nayonsoso commented on backend/src/main/java/reviewme/member/controller/ReviewerGroupController.java
> +    responses = {@ApiResponse(content = @Content(schema = @Schema(implementation = ReviewerGroupResponse.class)))})
호호 안녕하세요~ 제가 잘못된 예시를 드린 것 같슴당 ㅠㅠ
여기서 responses 부분을 제거해야할 것 같아요!

제거하기 전에는, Code 가 default 로 나오는데
제거하니 Code가 200 으로 뜨네요!!

2024-07-18 01:45 UTC, donghoony requested changes
아자아자 변경해주세요 👐🏻

2024-07-18 01:45 UTC, donghoony commented on backend/src/main/java/reviewme/config/SwaggerConfig.java
> +                        .version("1.0.0"));
- info 변수로 뽑는 건 어떨까요?
- 버전을 낮춰 주세요. Gradle에 명시된 버전까지는 아니더라도, 메이저 버전을 사용하는 것은 Api가 확벙된 다음 배포가 이루어지고 진행해도 될 듯해요

2024-07-18 01:47 UTC, donghoony commented on backend/src/main/java/reviewme/member/controller/ReviewerGroupController.java
> +    responses = {@ApiResponse(content = @Content(schema = @Schema(implementation = ReviewerGroupResponse.class)))})
논리적으로 개행해주세요~

2024-07-18 02:01 UTC, skylar1220 commented on backend/src/main/java/reviewme/member/controller/ReviewerGroupController.java
> +    responses = {@ApiResponse(content = @Content(schema = @Schema(implementation = ReviewerGroupResponse.class)))})
해당 부분이 불필요해서 삭제합니다!

2024-07-18 03:52 UTC, donghoony requested changes
의견 나눠보고자 RC 드립니다~!

2024-07-18 03:52 UTC, donghoony commented on backend/src/main/java/reviewme/config/SwaggerConfig.java
> +public class SwaggerConfig {
`@ConfigurationProperties`를 사용해보면 좋겠습니다. 설정 책임을 가지는 클래스를 분리하면 명확할 것 같아요.

```
@ConfigurationProperties(prefix = "docs.info")
public record SwaggerProperties(String title, String description, String version) {

    public Info swaggerInfo() {
        return new Info()
                .title(title)
                .description(description)
                .version(version);
    }
}
```

```

@EnableConfigurationProperties(SwaggerProperties.class)
@RequiredArgsConstructor
public class SwaggerConfig {

    private final SwaggerProperties swaggerProperties;

    @Bean
    public OpenAPI openAPI() {
        return new OpenAPI()
                .info(swaggerProperties.swaggerInfo());
    }
}
```

`swagger-docs.yml`:
```
docs:
  info:
    title: "리뷰미 API"
    description: "이 문서는 리뷰미 API 구현 방법을 소개합니다."
    version: "0.0.1"
```

2024-07-18 03:52 UTC, donghoony commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +    @ApiResponse(responseCode = "201")
Operation 하나로 가져가면 어떤가요? 가독성 측면은 원래 코드가 나으려나요? 
```suggestion
    @Operation(
            summary = "리뷰 등록",
            description = "리뷰 작성 정보를 받아 리뷰를 등록한다.",
            responses = @ApiResponse(responseCode = "201")
    )
```

2024-07-18 03:52 UTC, donghoony commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +@Tag(name = "리뷰 관리")
Swagger의 프로덕션 코드 침범을 좋게 볼 수 없다고 생각해요. 그 대안으로 인터페이스를 생각했는데, 이 방향은 어떤가요? 

```java
@Tag(name = "리뷰 관리")
public interface ReviewApi {

    @Operation(
            summary = "리뷰 등록",
            description = "리뷰 작성 정보를 받아 리뷰를 등록한다.",
            responses = @ApiResponse(responseCode = "201")
    )
    ResponseEntity<Void> createReview(CreateReviewRequest request);

    @Operation(summary = "리뷰 조회", description = "단일 리뷰를 조회한다.")
    ResponseEntity<ReviewResponse> findReview(long id);
}
```

이후 `ReviewController`가 `ReviewApi`를 implement하면 어떨까요?

2024-07-18 03:52 UTC, donghoony commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +@Tag(name = "리뷰 관리")
이것도 Swagger가 실제 컨트롤러 코드를 침범하지 않는 대신, `Controller`에 문서 코드가 붙지 않는다는 장점이 있겠네요 🤔

2024-07-18 03:52 UTC, donghoony commented on backend/src/main/resources/application-API-DOCS.yml
> +api:
`docs`가 조금 더 적절할 것 같습니다. 파일 이름도 `application`을 붙이지 않아도 될 듯해요 (아직은?). `api-docs.yml`은 어떨까요?

2024-07-18 03:52 UTC, donghoony commented on backend/src/main/resources/application.yml
> +    include: API-DOCS
`ConfigurationProperties`를 사용하면 해당 구문이 필요하지 않습니다.

2024-07-18 07:48 UTC, Kimprodp commented on backend/src/main/resources/application.yml
> +    include: API-DOCS
1. `profiles.include`를 사용하지 않으면 `api-docs.yml` 파일을 인식하지 못함
2. `@PropertySources`로 classpath를 지정할 수 있으나, 해당 어노테이션은 yml 파일 로드를 하지 못함
3. 위 문제를 해결하기 위해서는 `YamlLoadFactory`와 같은 클래스를 추가적으로 필요로 하기 때문에 profiles.include를 사용하는 것으로 유지하기로 했습니다.

2024-07-18 07:49 UTC, Kimprodp commented on backend/src/main/resources/application-API-DOCS.yml
> +api:
docs가 더 적절한 것 같아 반영했습니다~

2024-07-18 07:50 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +@Tag(name = "리뷰 관리")
아직은 컨트롤러가 많지 않아 Controller에 문서 코드가 붙지 않는 것이 더 큰 장점인 것 같아요. 해당 내용으로 적용했습니다

2024-07-18 07:50 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +    @ApiResponse(responseCode = "201")
가독성이 훨씬 좋네요👍

2024-07-18 07:51 UTC, Kimprodp commented on backend/src/main/java/reviewme/config/SwaggerConfig.java
> +public class SwaggerConfig {
설정 책임을 가지는 클래스와 프로퍼티 정보를 저장하고 있는 클래스 분리 좋네요 👍

2024-07-18 07:59 UTC, donghoony commented on backend/src/main/resources/application.yml
> +    include: API-DOCS
하나 배웠습니다 🔥🔥🔥

2024-07-18 08:27 UTC, donghoony approved these changes
코드 확인했습니다 최고다 최고~!

2024-07-18 23:13 UTC, nayonsoso commented on backend/src/main/java/reviewme/config/SwaggerConfig.java
> +public class SwaggerConfig {
@donghoony @Kimprodp 
아이 해브 어 퀘스티옹~

API 문서와 관련된 것을 yml 로 뺀 이유가 있는지 궁금합니다!

2024-07-18 23:29 UTC, nayonsoso approved these changes
스웨거 확인했습니다~ ㅎㅎ
그런데 해결되지 않는 의문...
스웨거로 POST 호출하니 DB에 반영이 되던데 이거 막아야겠죠,,? 
그런데 어떻게 막을 수 있을지 모르겠네요.. 이슈로 올려두겠습니다!😵

2024-07-18 23:29 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
>      public ResponseEntity<Void> createReview(@RequestBody CreateReviewRequest request) {
흑흑 왜 스웨거가 created를 자동으로 인식하지 못하는 걸까요 ㅠㅠ 
지금은 이게 최선이겠지만,.. 혹시 다른 방법이 더 있는지 찾아보겠습니다!

2024-07-19 01:16 UTC, Kimprodp approved these changes

2024-07-19 01:16 UTC, Kimprodp commented on backend/build.gradle
> +    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
`configuration-processor` 참고 : https://perfectacle.github.io/2021/11/21/spring-boot-configuration-processor/

2024-07-19 01:16 UTC, merged