[FE] refactor: 랜딩 페이지 리팩토링 및 서비스 소개 section 제작
woowacourse-teams/2024-review-me pull request #371
Opened 2024-08-15 14:05 UTC by ImxYJL

- resolves #354 

---

### 🚀 어떤 기능을 구현했나요 ?
- 기존 `URLGeneratorForm`을 리팩토링했습니다.
  - 비밀번호 `Input` 추가
- `ReviewAccessCode`를 사용하는 부분을 제거했습니다.
- URL 생성 후 등장하는 모달을 리팩토링했습니다.
- 페이지의 이름을 `Landing`에서 `Home`으로 변경했습니다.
- 리뷰미 프로세스를 소개하는 `Section`을 만들었습니다.

### 🔥 어떻게 해결했나요 ?
- 비밀번호에 4~20자 제한이 있는데, 현재 코드에서 에러 메세지를 띄울 때 길이 검사를 하면 페이지에 처음 들어왔을 때부터 `input`이 0자이므로 길이 에러가 뜬다는 문제점이 있었습니다.
- 이를 위해 포커스 된 이후에 에러 메세지를 띄우도록 `onFocus`와 `onBlur` 관련 이벤트를 처리해야 하지만 현재 시급한 부분은 아니라고 생각해서 다음과 같이 코드를 작성했습니다.
  - URL 생성 버튼이 활성화되는 유효성 검사에서는 4~20자 검사를 수행
  - 에러 메세지를 띄우는 검사에서는 20자 이하인지만 체크
  - 이와 관련된 기능은 추후 `textarea`처럼 별도의 훅으로 관리할 예정입니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- css는 적당히 깎았는데 크게 거슬리는 부분이 있다면 말씀해주세용

### 📚 참고 자료, 할 말

2024-08-16 08:42 UTC, BadaHertz52 commented on frontend/src/components/common/EyeButton/styles.ts
> +  width: 1.6rem;
추후에 width, height를 상수로 빼도 좋을 듯!

2024-08-16 08:44 UTC, BadaHertz52 commented on frontend/src/pages/HomePage/components/OverviewItem/styles.ts
> +  background-color: white;
background-color 에서 theme에 있는 white를 사용하는 것은 어떨까요?

2024-08-16 08:46 UTC, BadaHertz52 commented on frontend/src/pages/HomePage/components/ReviewAccessForm/index.tsx
> +            // styleType={isValidAccessCodeInput(groupAccessCode) ? 'primary' : 'disabled'}
이 부분을 주석처리한 이유가 뭘까요?

2024-08-16 08:49 UTC, BadaHertz52 commented on frontend/src/pages/HomePage/components/ReviewMeOverview/index.tsx
> +          direction="column"
OvervieItem 이라는 멋진 컴포넌트를 만들었내요.

추후에 리팩토링을 한다면, OverviewItem 에 사용하는 내용들을 객체로 관리하면 좋을 듯해요.

2024-08-16 08:55 UTC, soosoo22 requested changes

2024-08-16 08:55 UTC, soosoo22 commented on frontend/src/pages/HomePage/components/ReviewAccessForm/index.tsx
> +            // styleType={isValidAccessCodeInput(groupAccessCode) ? 'primary' : 'disabled'}
주석 지워주면 좋을 것 같아요!

2024-08-16 08:59 UTC, soosoo22 reviewed
지금 홈 페이지에서 세로로 스크롤이 생기는데, 처음 화면에 들어왔을 때 스크롤이 생기는 것 보다는 이미지와 글씨가 작더라도 한 화면에 다 나오는 게 좋다고 생각하는데 올리는 어떻게 생각하시나요???

2024-08-17 06:11 UTC, ImxYJL commented on frontend/src/pages/HomePage/components/ReviewAccessForm/index.tsx
> +            // styleType={isValidAccessCodeInput(groupAccessCode) ? 'primary' : 'disabled'}
아마 groupAccessCode를 사용하지 않으니 제거하고 무언의 테스트를 해보려다가 다시 살린 것 같네요..ㅋㅋㅋ 이제 사용하지 않는 컴포넌트라 아예 삭제했습니다.

2024-08-17 06:15 UTC, ImxYJL commented on frontend/src/pages/HomePage/components/ReviewAccessForm/index.tsx
> +            // styleType={isValidAccessCodeInput(groupAccessCode) ? 'primary' : 'disabled'}
사용하지 않는 컴포넌트라 아예 삭제했습니당

2024-08-17 10:53 UTC, BadaHertz52 approved these changes
올리 페이지 작성하느라 고생했어요

코멘트 남겼지만, 아직은 문제될 사항은 아니라서 approve할게요
onFocus,onBlur  시 에레메세지는 데모데이안에 구현해야할 것 같아서 이 부분은 월요일 프론트회의에서 다뤄봐요

2024-08-17 10:53 UTC, BadaHertz52 commented on frontend/src/pages/HomePage/components/OverviewItem/index.tsx
> +const OverviewItem: React.FC<OverviewItemProps> = ({ direction, imageSrc, title, description }) => {
```suggestion
const OverviewItem: = ({ direction, imageSrc, title, description }:OverviewItemProps) => {
```
이라고 하지 않고  `React.FC<OverviewItemProps> `을 사용한 이유가 있나요?

2024-08-17 10:53 UTC, BadaHertz52 commented on frontend/src/pages/HomePage/components/ReviewURLModal/index.tsx
> +    return;
return 을 한 이유가 있나요?

2024-08-17 10:53 UTC, BadaHertz52 commented on frontend/src/pages/HomePage/components/ReviewURLModal/index.tsx
> +              id="is-confirmed-checkbox"
`is-confrimed-checkbox` id는 어디서 사용하는 건가요?

id는 유일한 값이여아하는데 'is-confrimed-checkbox' 는 어디선가 또 쓸 수 있어서 useId를 사용해보는 것도 좋을 것 같아요

2024-08-17 10:53 UTC, BadaHertz52 commented on frontend/src/pages/HomePage/components/URLGeneratorForm/index.tsx
> +const URLGeneratorForm = () => {
input개수 만큼 state가 있고 URLGeneratorForm 의 태그가 현재는 section이네요

리뷰생성을 위한 데이터를 하나의 state에서 관리할 수 있는 방법도 있고 input 개수 만큼의 state로  관리하는 방법이 있는데
각 방법의 장단점이 있죠

이 부분이  어떻게  리팩토링 될지 (좋은 방향으로) 기대됩니다! 😆

2024-08-17 11:15 UTC, ImxYJL commented on frontend/src/pages/HomePage/components/ReviewURLModal/index.tsx
> +              id="is-confirmed-checkbox"
id를 따로 사용하는 곳은 없고 checkbox에서 id를 필수로 받고 있어서 기입했던 것 같아요
useId는 무엇일까요?!

2024-08-17 11:24 UTC, ImxYJL commented on frontend/src/pages/HomePage/components/URLGeneratorForm/index.tsx
> +const URLGeneratorForm = () => {
`URLGeneratorForm`은 section이고, 그 자식 컴포넌트인 `FormLayout`이 form인 상태입니다. 

예전 레이아웃에서는 URL 생성, 리뷰 확인의 폼 배치가 달라서  `FormLayout`에 폼 정렬 속성(row, col)을 받을 수 있는 컴포넌트로 특화시키고, 그 `FormLayout`을 사용하는 최상위 컴포넌트(Container 느낌)로 `URLGeneratorForm`을 뒀었는데 폼이 하나만 있는 지금은 불필요한 코드일 수 있겠다는 생각이 들었어요. 
하지만 일단은 업보로 달아두는 것으로..,😶

2024-08-17 11:24 UTC, ImxYJL commented on frontend/src/pages/HomePage/components/ReviewURLModal/index.tsx
> +    return;
FC랑 쓸데없는 리턴 지웠어요~!

2024-08-17 12:29 UTC, soosoo22 approved these changes
랜딩 페이지 한층 업그레이드~ 됐네요!  수고했어요!!

2024-08-17 12:45 UTC, soosoo22 approved these changes
올리 수고했어요!

2024-08-17 12:45 UTC, soosoo22 commented on frontend/src/pages/HomePage/components/ReviewMeOverview/styles.ts
> +export const OverviewTitle = styled.h2`
저번에 바다가 말해줬던 것 처럼 현재 `h1` 태그가 사용되고 있지 않아서 `h2` 보다는 `span`으로 변경해주시면 좋을 것 같아요!

2024-08-17 12:45 UTC, soosoo22 commented on frontend/src/pages/HomePage/components/ReviewURLModal/index.tsx
> +        </S.WarningWrapper>
코드컨벤션보면 `Wrapper`가 하나의 요소를 감쌀 때 사용되고, `Container`가 여러 개의 요소를 감쌀 때 사용된다고 적혀있어요. `Wrapper`가 `Container`보다 상위에 있어서 조금 어색한 것 같아요!

2024-08-17 12:45 UTC, soosoo22 commented on frontend/src/pages/HomePage/styles.ts
> +`;
지금 첫 화면 들어왔을 때 세로 스크롤이 생기는 이유 중 하나가 `min-hiehgt: 100vh` 인 것 같다는 느낌이? 살짝 드네요.

2024-08-17 12:45 UTC, soosoo22 commented on frontend/src/pages/HomePage/components/URLGeneratorForm/index.tsx
> +  };
리뷰 작성 경로를 `constants/routes.ts` 에 정의되어 있는 상수들을 활용해보는 건 어떨까요

2024-08-17 12:45 UTC, soosoo22 commented on frontend/src/pages/index.tsx
> +export { default as HomePage } from './HomePage';
와우! 랜딩에서 홈으로 바로 변경해주셨네요👍

2024-08-17 14:29 UTC, ImxYJL commented on frontend/src/pages/HomePage/components/URLGeneratorForm/index.tsx
> +  };
상수 도입 전에 작성한 코드라 하드코딩이 남아있네요 수정할게요~~

2024-08-17 14:33 UTC, ImxYJL commented on frontend/src/pages/HomePage/styles.ts
> +`;
`min-hiehgt: 100vh`가 없으면 보라색 배경이 화면 끝까지 닿지 못하고 잘리는 문제가 있었는데, 지금 코드에서는 없애도 잘 동작하네요~
하지만 스크롤바가 생기는 이유는 해당 section 안의 요소 크기 때문인거라 이 요소들의 크기를 줄여야 하는데 스크롤바가 없을 정도로 줄이면 안내의 의미가 없어질 정도로 작아져야 해서 문제입니다 😢

2024-08-17 14:47 UTC, ImxYJL commented on frontend/src/pages/HomePage/components/ReviewURLModal/index.tsx
> +        </S.WarningWrapper>
반영했습니다~

2024-08-17 14:49 UTC, ImxYJL commented on frontend/src/pages/HomePage/components/ReviewMeOverview/styles.ts
> +export const OverviewTitle = styled.h2`
타이틀은 제목인 만큼 줄바꿈 및 강조가 있어야 한다고 생각해서 `p`태그로 수정했습니다~~

2024-08-17 16:11 UTC, chysis approved these changes
리뷰만 달아놓고 Finish를 안 했었네요😅 고생했어요!

2024-08-17 16:11 UTC, chysis commented on frontend/src/pages/HomePage/utils/validateInput.test.ts
input 유효성 검사 테스트까지 진행하셨네요👍

2024-08-18 05:45 UTC, BadaHertz52 commented on frontend/src/pages/HomePage/components/URLGeneratorForm/index.tsx
> +    return `${window.location.origin}/user/review-writing/${reviewRequestCode}`;
이제 url이 리뷰 작성 페이지가 아니라 리뷰 연결 페이지로 이동하게 해서 수정해야겠어요.!

2024-08-18 07:43 UTC, merged