[BE] 로그를 레벨에 따라 다르게 분류한다.
woowacourse-teams/2024-review-me pull request #394
Opened 2024-08-16 11:18 UTC by nayonsoso

- resolves #300 

---

### 🚀 어떤 기능을 구현했나요 ?
- 예외가 발생하는 상황에 따라서 다르게 예외를 분류했습니다.

### 🔥 어떻게 해결했나요 ?
- 예외를 발생하는 상황에 맞게 로그 레벨을 분류했습니다.
https://gravel-cymbal-942.notion.site/c09548615963418193eb6bafb7686541

- 사용하지 않는 예외를 삭제했습니다.

- 몇몇 예외 이름을 변경했습니다.

- 데이터 정합성 예외의 경우, DataConsistencyError 로 바로 검색할 수 있도록 예외 메세지에 "DataConsistencyError" 를 추가해두었습니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 로그 레벨이 적절한지 리뷰 부탁드립니다!

### 📚 참고 자료, 할 말
- 로그 레벨을 나눈 김에, ERROR 로그가 몇개 이상 쌓인다면 알림을 주는 기능을 만들면 좋겠다는 생각을 했습니다.
- 이슈로 만들어두었습니다. #393

2024-08-16 18:44 UTC, donghoony requested changes
산초 모든 예외 깎아내느라 고생했습니다 몇가지 수정사항 반영해주세요~!

2024-08-16 18:44 UTC, donghoony commented on backend/src/main/java/reviewme/global/exception/DataConsistencyException.java
> +public abstract class DataConsistencyException extends ReviewMeException {
정합성 예외 좋네요! 그래도 예외는 해당 상태를 나타내야 하니 `DataInconsistencyException`정도는 어떨까요?

2024-08-16 18:44 UTC, donghoony commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +        log.error("Initial server error is occurred", ex);
`Initial server error`가 무엇일까요? `Internal server error has occurred`를 의도했을까요?

2024-08-16 18:44 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/exception/CheckBoxAnswerOutOfRangeException.java
> +public class CheckBoxAnswerOutOfRangeException extends BadRequestException {
`SelectedAnswerCountOutOfRangeException`? 선택했다는 의미를 주고 싶긴 한데요... 🤔

2024-08-16 18:44 UTC, donghoony commented on backend/src/main/java/reviewme/template/domain/exception/TemplateNotFoundException.java
> +        log.warn("TemplateNotFoundException is occurred - id: {}", id);
`has occurred`가 문법적으로는 맞겠습니다 👍🏻

2024-08-17 15:38 UTC, Kimprodp requested changes
코멘트에 남기긴 했는데, 사용자의 잘못이 아닌 서버 내부 문제로 인해 사용자가 정상적인 액션을 했을 때 정상적인 서비스 이용이 불가능 할 경우 발생하는 예외는 error 로 처리하고 바로 대응해야 할 것 같아요.

이 과정에서 다른 곳에서 같이 사용되는 예외들이 있어서 겹칠 수 있을 것 같은데, 이런 경우의 에러는 따로 추가해서 관리해야 할지 고민이 필요한 부분인 것 같아요.

우선 코멘트 확인 후 산초의 생각을 남겨주십쇼~

2024-08-17 15:38 UTC, Kimprodp commented on backend/src/main/java/reviewme/question/domain/exception/QuestionNotFoundException.java
> +        log.warn("Question not found - questionId: {}", questionId);
해당 예외가 존재하지 않는 자원에 대한 접근이긴 하지만,
리뷰 작성을 위한 템플릿을 만들 때와 작성된 리뷰 등록을 할 때 사용하고 있어요.
이 과정에서 id에 해당하는 질문을 찾지 못하는 경우는 서버 내부적인 오류로 error로 처리하고 바로 해결해야 할 것 같아요. (템플릿을 내려줄 때 오류가 나면 사용자는 리뷰 작성을 계속 할 수 없으니)

이러한 유형으로 바로 처리해야 하는 것들은 error 레벨로 관리해야 할 것 같은데,  `QuestionNotFoundException`을 단순하게 존재하지 않는 자원에 대한 접근으로 사용한다면 다른 예외를 만드는 것이 나을까요?

비슷한 case로 `SectionNotFoundException`도 warn이 맞는지? 아니면 추가적엔 커스텀 예외가 필요할지 고려해봐야 할 것 같아요!

2024-08-18 06:49 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/exception/DataConsistencyException.java
> +public abstract class DataConsistencyException extends ReviewMeException {
오 동의합니다~ 반영해두겠습니다🫡

2024-08-18 06:52 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +        log.error("Initial server error is occurred", ex);
앗 부끄럽네요🙄
Internal 로 바꾸겠습니다....

2024-08-18 06:57 UTC, nayonsoso commented on backend/src/main/java/reviewme/template/domain/exception/TemplateNotFoundException.java
> +        log.warn("TemplateNotFoundException is occurred - id: {}", id);
앗 그렇네요! occurred 는 보통 수동태로 사용되지 않는 다는 것을 새로 배우고 갑니다😲👏

2024-08-18 07:09 UTC, nayonsoso commented on backend/src/main/java/reviewme/question/domain/exception/QuestionNotFoundException.java
> +        log.warn("Question not found - questionId: {}", questionId);
> 사용자의 잘못이 아닌 서버 내부 문제로 인해 사용자가 정상적인 액션을 했을 때 정상적인 서비스 이용이 불가능 할 경우 발생하는 예외는 error 로 처리하고 바로 대응해야 할 것 같아요.

> 이 과정에서 다른 곳에서 같이 사용되는 예외들이 있어서 겹칠 수 있을 것 같은데, 이런 경우의 에러는 따로 추가해서 관리해야 할지 고민이 필요한 부분인 것 같아요.

사실 저도 이 부분에 대해 고민이 되었는데, 변경의 범위가 너무 많아질까봐 선뜻 바꾸지 못했어요..😞

언급하신 QuestionNotFoundException 와 SectionNotFoundException 같은 예외는
레포지토리에서 id 로 조회할 때 **default 함수에서 발생시키는 예외**이기 때문에 발생할 수 있는 맥락이 다양해요.

이런 예외가 있다는것의 장점은 ⭐️간편하다⭐️ 라는 점일텐데, 
당연한 말이겠지만 이것을 포기하고 간다면 불편함을 얻겠죠?
이를테면 지금 QuestionNotFoundException 을 발생시키는 곳이 4군데인데, 
각각을 해체해서 모두 다른 예외를 만들어야 하는 등...

---

다 찾아보니 TemplateNotFoundException 는 1곳에서 쓰이고 /
QuestionNotFoundException 이 4곳에서 쓰이고 / SectionNotFoundException 이 1곳에서 쓰이니
엄청 해체할게 많진 않겠네요! 
여기에 대해 다른 분들의 의견도 들어보고 싶습니다~

2024-08-18 07:27 UTC, skylar1220 requested changes
엄청난 file change네요... 고생했다 산쵸😂

2024-08-18 07:27 UTC, skylar1220 commented on backend/src/main/java/reviewme/question/domain/exception/MissingOptionItemsInOptionGroupException.java
> +        log.error("OptionGroup has no OptionItems - optionGroupId: {}", optionGroupId);
커밋 기록을 보니 이런 맥락을 넣어줬다가 다시 제거한 것으로 보이는데요~
`while looking up detailed review.`
어떤 상황인지 함께 제시해준 게 좋다고 느껴졌거든요!
범용적으로 쓰이지 않는 상황이기때문에 위와 같은 맥락을 담는 게 괜찮다고 생각하는데 어떤 이유로 빼기로 최종 결정했는지 궁금해요!

2024-08-18 07:27 UTC, skylar1220 commented on backend/src/main/java/reviewme/global/exception/UnexpectedRequestException.java
프론트의 입력 검증을 뚫고 들어온 것을 좁은 의미의 badRequest로 정의하고
`정상 작동된 상황이라면 알 수 없는 정보로 요청됨`을 분리한 것 멋져요👍👍

2024-08-18 08:27 UTC, skylar1220 commented on backend/src/main/java/reviewme/question/domain/exception/QuestionNotFoundException.java
> +        log.warn("Question not found - questionId: {}", questionId);
테드 의견에 공감이 가요. 같은 getQuestionById에서 발생한 예외지만 TemplateMapper에서 난다면 error 수준의 문제가 맞다고 생각합니다!
기존의 경우들은 두고(리뷰 생성시 예외는 기존 warn레벨의 QuestionNotFoundException 사용) 
TemplateMapper 과 같은 경우에 대해서만 error 수준 예외를 만들어 서비스에서 findBy().orElseThrow해주는 것은 어떨까 생각합니다!

2024-08-18 08:28 UTC, donghoony commented on backend/src/main/java/reviewme/question/domain/exception/QuestionNotFoundException.java
> +        log.warn("Question not found - questionId: {}", questionId);
error성 비즈니스 로직은 default 쓰지 말고, 서비스에서 사용하면 어떨까요?

2024-08-19 05:11 UTC, nayonsoso commented on backend/src/main/java/reviewme/question/domain/exception/MissingOptionItemsInOptionGroupException.java
> +        log.error("OptionGroup has no OptionItems - optionGroupId: {}", optionGroupId);
사실 너무 고봉밥인가 싶어서 뺐었어요😅
다른 분들도 넣는게 괜찮아보인다면 다시 넣는걸로 할까요??????

2024-08-19 06:10 UTC, donghoony approved these changes

2024-08-19 06:10 UTC, skylar1220 approved these changes
테생축

2024-08-19 06:10 UTC, Kimprodp approved these changes
고
생
산
초

2024-08-19 06:11 UTC, merged