[BE] refactor: 335 리뷰 상세 조회 시, 답변이 있는 리뷰만 보여주도록 변경
woowacourse-teams/2024-review-me pull request #395
Opened 2024-08-16 14:10 UTC by Kimprodp

- resolves #335

---

### 🚀 어떤 기능을 구현했나요 ?
- 위 관련 이슈 내용에 따라 선택형 질문의 경우 리뷰어가 작성하지 않을 경우 null이 반환되어 오류가 발생했습니다.
- 리뷰 상세 조회 시, 리뷰어가 답변한 리뷰로만 구성하여 보여줄 수 있도록 변경했습니다.

### 🔥 어떻게 해결했나요 ?
- 섹션의 visible과 질문의 required에 관계 없이, 리뷰어가 답변한 리뷰로만 템플릿을 구성하여 반환할 수 있도록 변경했습니다.
- 현재는 checkbox 질문은 모두 필수이지만, 추후 질문 유형에 관계없이 필수/선택이 들어올 수 있으므로 확장성을 고려하여 단순하게 '답변이 있는 질문' 으로만 구성하여 조회할 수 있도록 했습니다. 이 과정에서 불필요한 로직은 제거되었습니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 구현된 내용이 괜찮은가?
- CheckboxAnswer에 reviewId 필드가 사용되지 않는 것 같아 제거했습니다. 필요한 경우라면 말씀해주세요~

### 📚 참고 자료, 할 말
- !!

2024-08-17 16:09 UTC, donghoony approved these changes
궁금한 점: 정답을 불러올 때, 내부 데이터 검증은 진행하지 않나요? (Required에 대한 답변이 들어있는지?)

2024-08-17 16:09 UTC, donghoony commented on backend/src/main/java/reviewme/review/domain/CheckboxAnswer.java
> -
이부분은 사용하지는 않지만, 테이블 필드와 맞춰주기 위해서 사용했어요. 네이티브 쿼리를 작성할 때 테이블을 옮겨가면서 보는데, FK가 있어야할 곳에 존재하지 않아서 인지부하가 꽤 되더라고요 😢

2024-08-17 16:09 UTC, donghoony commented on backend/src/main/java/reviewme/review/domain/exception/MissingCheckboxAnswerForQuestionException.java
> +    }
이쪽은 산초 PR 먼저 머지된 뒤에 살펴보겠습니다 😁

2024-08-17 16:09 UTC, donghoony commented on backend/src/main/java/reviewme/review/domain/exception/MissingCheckboxAnswerForQuestionException.java
> +    }
#394

2024-08-17 16:36 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/domain/CheckboxAnswer.java
> -
CheckboxAnswer 테이블에 reviewId 필드가 있나요..? 이 부분 잘 이해가 안가는데 TextAnswer 에는 없고 여기엔 있어서 좀 헷갈리네요..

2024-08-17 16:38 UTC, Kimprodp commented
@donghoony 
>궁금한 점: 정답을 불러올 때, 내부 데이터 검증은 진행하지 않나요? (Required에 대한 답변이 들어있는지?)

`Required에 대한 답변이 들어있는지`와 같은 데이터 검증은 데이터 등록(리뷰 저장)의 책임이라 생각해서,
조회에서는 단순히 저장된 내용(정답이 있는 답변)만 응답하는 것으로 했습니다!

2024-08-17 16:43 UTC, donghoony commented on backend/src/main/java/reviewme/review/domain/CheckboxAnswer.java
> -
`Review`에서 1:N 단방향으로 들고 있습니다
```java
    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.PERSIST)
    @JoinColumn(name = "review_id", nullable = false, updatable = false)
    private List<CheckboxAnswer> checkboxAnswers;
```

네이티브 SQL을 짤 때 엔티티의 필드들을 확인하면서 어떤 열들이 있나 보고는 하는데요, Answer 쪽에 `reviewId`가 있다는 걸 명시할 수 있어요 (실제로 getter로만 쓸 수도 있어요)

2024-08-18 07:30 UTC, nayonsoso approved these changes
다시 봐도 복잡한 로직이네요😖
작성하시느라 수고 많으셨습니다!!

2024-08-18 07:30 UTC, nayonsoso commented on backend/src/test/java/reviewme/review/domain/CheckboxAnswersTest.java
> +    void 질문_ID로_서술형_답변을_반환한다() {
선택형 답변을 반환한다고 바꿔야 할 것 같아용~

2024-08-18 08:18 UTC, skylar1220 requested changes
디코에 올렸던 코드에서 예뻐졌네요!!

2024-08-18 08:18 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/ReviewDetailLookupService.java
>          }
이렇게 분기하는 건 어떨까요? 가독성을 위한 소소한 제안입니다ㅎ
```java
        for (Question question : questionRepository.findAllBySectionId(section.getId())) {
            if (question.isSelectable()) {
                addCheckboxQuestionResponse(review, reviewGroup, question, questionResponses);
            }
            if (!question.isSelectable()) {
                addTextQuestionResponse(review, reviewGroup, question, questionResponses);
            }
        }
```

2024-08-18 08:18 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/domain/exception/MissingCheckboxAnswerForQuestionException.java
MissingCheckboxAnswerForQuestionException라는 이름에서
For 보다는 By가 어떨까요? 질문에 의한 예외라는 의미에서요! 다른 곳에서도 by로 써왔던 것 같아서 제안합니다~

2024-08-18 08:18 UTC, skylar1220 commented on backend/src/test/java/reviewme/review/service/ReviewDetailLookupServiceTest.java
> +                .doesNotContain(section3.getId());
답변이 없는 경우 섹션 자체가 생성되지 않는 게 아니라 해당 question-answer만 생성되지 않게 하는 걸 검증해야한다고 생각해요!
예: 객관식은 필수응답이고 주관식은 선택응답이라 빈문자열인 섹션 같은 경우!

2024-08-18 08:18 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/ReviewDetailLookupService.java
>          }
차라리 `else`를 쓰는게 낫지 않을까요? 🤔

2024-08-18 15:04 UTC, Kimprodp commented on backend/src/test/java/reviewme/review/domain/CheckboxAnswersTest.java
> +    void 질문_ID로_서술형_답변을_반환한다() {
헉 감사요 👍

2024-08-18 15:05 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/domain/CheckboxAnswer.java
> -
흐음 흐음 흐음 인지부하 명시용.. 고민되네용 살리는 것이 나을까요? 우선은 살려둘게요!

2024-08-18 15:12 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/domain/exception/MissingCheckboxAnswerForQuestionException.java
`MissingTextAnswerForQuestionException`이 이미 있어서 답변 종류만 변경했는데요.
현재 Missing ~ 으로 시작하는 예외에서 모두 for을 사용하고 있어서 바꾸면 다 바꿔야 할 것 같은데..
현재 산초가 진행중인 로깅 레벨 리팩터링 결판 후에 커스텀 예외명들도 한번 싹 리팩해보죠

2024-08-18 15:13 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/service/ReviewDetailLookupService.java
>          }
else가 코드량 대비 가독성이 더 좋은 것 같아 else로 반영했습니다. 두 의견 모두 감사👍

2024-08-18 15:19 UTC, donghoony commented on backend/src/main/java/reviewme/review/domain/exception/MissingCheckboxAnswerForQuestionException.java
질문을 위한 체크박스 답변이 존재하지 않아서 상태만 놓고 보았을 때에는 `for`가 적절하다고 생각해요

2024-08-18 15:30 UTC, Kimprodp commented on backend/src/test/java/reviewme/review/service/ReviewDetailLookupServiceTest.java
> +                .doesNotContain(section3.getId());
예시 좋네요 👍 반영했습니다!

2024-08-19 05:02 UTC, skylar1220 approved these changes

2024-08-19 05:02 UTC, merged