[BE] feat: 리뷰 그룹 정보 조회 api 구현
woowacourse-teams/2024-review-me pull request #396
Opened 2024-08-16 14:53 UTC by Kimprodp

- resolves #375 

---

### 🚀 어떤 기능을 구현했나요 ?
- 리뷰 그룹 정보 조회 api를 구현했습니다.

### 🔥 어떻게 해결했나요 ?
- ReviewGroupController에 findReviewGroup 기능 추가

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- ㅎㅎ

### 📚 참고 자료, 할 말
- api 문서 : https://www.notion.so/API-a13c266ee66444eba5b94a5787eb4d56?p=804c7d99e88446da866b671b7d52ec82&pm=s

2024-08-16 18:48 UTC, donghoony approved these changes
금방 수정할 수 있는 사항이라 어프룹 달겠습니다, 확인해주세요~

2024-08-16 18:48 UTC, donghoony commented on backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
> +    private final ReviewGroupFindService findService;
변수명 줄이지 않는 게 헷갈리지 않겠습니다 😁

2024-08-16 18:48 UTC, donghoony commented on backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupFindService.java
> +public class ReviewGroupFindService {
detail에 대한 건 LookupService로 했으니 통일하면 어떨까요?

2024-08-16 18:48 UTC, donghoony commented on backend/src/test/java/reviewme/reviewgroup/service/ReviewGroupFindServiceTest.java
> +    }
존재하지 않는 경우의 테스트도 한 개만 작성해주세요!

2024-08-17 01:36 UTC, Kimprodp commented on backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
> +    private final ReviewGroupFindService findService;
반영 완료 👍

2024-08-17 01:36 UTC, Kimprodp commented on backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupFindService.java
> +public class ReviewGroupFindService {
반영 완료 👍

2024-08-17 01:36 UTC, Kimprodp commented on backend/src/test/java/reviewme/reviewgroup/service/ReviewGroupFindServiceTest.java
> +    }
반영 완료 👍👍

2024-08-18 07:51 UTC, nayonsoso requested changes
수고하셨습니당~☺️
아주 사소한 부분 RC 드렸어요!

2024-08-18 07:51 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupLookupService.java
> +    public ReviewGroupResponse findReviewGroup(String reviewRequestCode) {
함수명이 구체화되면 좋겠어요!
지금은 repository 에 있는 함수들과 크게 구분이 되지 않는 것 같아요😳

2024-08-18 08:39 UTC, skylar1220 approved these changes

2024-08-18 14:57 UTC, Kimprodp commented on backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupLookupService.java
> +    public ReviewGroupResponse findReviewGroup(String reviewRequestCode) {
`findReviewGroupByRequestCode` 로 변경했습니다!  저는 그냥 최대한 직관적인 것을 선호하는데, 추천 의견이 있다면 말해주세요..

---
현재 다른 서비스들에서 조회하는 메서드에 대한 네이밍이 get, find 모두 사용되고 있어 [리팩터링](https://github.com/woowacourse-teams/2024-review-me/issues/384) 시, 반영할 예정이라 서비스 메서드의 네이밍에 대해서 한번 이야기 해봐도 좋을 것 같습니다!

2024-08-18 14:58 UTC, donghoony commented on backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupLookupService.java
> +    public ReviewGroupResponse findReviewGroup(String reviewRequestCode) {
충분해 보입니다~

2024-08-19 05:05 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupLookupService.java
> +    public ReviewGroupResponse findReviewGroup(String reviewRequestCode) {
findReviewGroupPreview / findReviewGroupBasicInfo

2024-08-19 05:07 UTC, nayonsoso approved these changes
생일축하합니다~ 👏🥳

2024-08-19 05:11 UTC, merged