[BE] feat: 키워드 도메인 구체화, 정책 구현
woowacourse-teams/2024-review-me pull request #40
Opened 2024-07-18 06:47 UTC by donghoony

- resolves #35

---

### 🚀 어떤 기능을 구현했나요 ?
- 키워드에 들어갈 수 있는 정책을 구현했습니다.

### 🔥 어떻게 해결했나요 ?
- 키워드 추가 시, **기존에 리뷰에 붙어있는 키워드를 모두 삭제한 뒤 다시 저장합니다.**
- `SelectedKeywords`라는 일급 컬렉션을 서비스단에서 사용하게 해, 도메인 쪽으로 검증 책임을 넘겨 보았습니다.
- 중복되는 테스트 코드를 Fixture를 활용해 해소했습니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 키워드 저장 로직이 적절한지 확인해주세요.
- 전반적으로 코드가 이해하기 쉬운지 확인해주세요!

### 📚 참고 자료, 할 말
- 아자아자 화이팅

2024-07-18 12:18 UTC, nayonsoso requested changes
아루짱!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
아루 무조건 대박 천재임

2024-07-18 12:18 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/ReviewKeywordService.java
> +        reviewKeywordRepository.removeAllByReview(review);
키워드를 수정하는 것을 염두에 두어 이 라인을 넣었다고 하셨는데요!
솔직히 처음에는 조금 헷갈렸지만, 의도(수정을 위한 함수와 너무 중복될 것 같다는 것)를 이해하고 나니 잘 만든 함수라는 생각이 듭니다 ㅎㅎ👍

2024-07-18 12:18 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/repository/ReviewKeywordRepository.java
> +    void removeAllByReview(Review review);
removeAll 이라는 함수는 JpaRepository에서 제공하는 함수 같지는 않던데 [공식문서](https://docs.spring.io/spring-data/jpa/docs/current/api/org/springframework/data/jpa/repository/JpaRepository.html)

신기하게도 deleteAll 로 바꿔서도 실행한 것과 removeAll 로 실행한 것이 sql 문이 동일하게 나가더라고요!🫨
어디서 등장한 놈이길래 그런진 모르겠지만, 그래도 JpaRepository 에서 제공하는 deleteAll 을 쓰는게 더 좋을 것 같아요!

2024-07-18 12:18 UTC, nayonsoso commented on backend/src/test/java/reviewme/fixture/KeywordFixture.java
> +}
enum 으로 만든 이유가 따로 있나요?
public static List<Keyword> 로 미리 만들어둔 것을 가져다 쓴다면 그때그때 생성하지 않아도 될 것 같아서요!

2024-07-18 12:18 UTC, nayonsoso commented on backend/src/main/java/reviewme/keyword/domain/SelectedKeywords.java
> +    }
지금 상황에서는 주어진 키워드 목록에서 선택을 하는 것이니, 
Detail이 동일한 키워드를 사용자가 선택하는 일은 없을 것 같습니다😓

추후 `사용자가 직접 키워드를 추가하는` 경우를 염두에 두신 건가요?
그렇다면 요 검증은 나중에 추가해도 될 것 같아요!
(물론 있어서 나쁠것은 없긴 함)

2024-07-18 12:18 UTC, nayonsoso commented on backend/src/test/java/reviewme/review/repository/ReviewKeywordRepositoryTest.java
> +        Review review = reviewRepository.save(new Review(kirby, group));
함수에 '기존에 키워드가 있다면 수정하는' 기능도 있는 만큼, 그 기능도 테스트할 필요가 있어 보여요!

2024-07-18 12:25 UTC, donghoony commented on backend/src/main/java/reviewme/review/repository/ReviewKeywordRepository.java
> +    void removeAllByReview(Review review);
좋네요~!

2024-07-18 12:27 UTC, donghoony commented on backend/src/test/java/reviewme/fixture/KeywordFixture.java
> +}
다른 Fixture와의 통일성이 한몫합니다. 추가적인 필드가 들어오면 대응하기에도 훨씬 수월하다고 생각했어요.

2024-07-18 12:30 UTC, donghoony commented on backend/src/main/java/reviewme/keyword/domain/SelectedKeywords.java
> +    }
사용자를 중심으로 생각하기보다는, API Request로 생각해야 한다고 봅니다. 사용자 입장에서는 Http request를 통해 잘못된 요청을 보낼 수 있고, 그때 저희 서버에서 이를 정말 정직하게 계산하므로 막아둘 필요가 있다고 생각해요.

2024-07-18 12:30 UTC, donghoony commented on backend/src/test/java/reviewme/review/repository/ReviewKeywordRepositoryTest.java
> +        Review review = reviewRepository.save(new Review(kirby, group));
`Service`단에 추가할게요~

2024-07-19 00:58 UTC, skylar1220 requested changes
아루루루루 많이 배워가요!!

2024-07-19 00:58 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/keyword/domain/SelectedKeywords.java
> +        }
아직은 메서드 분리를 하지 않는 것이 더 나을까요?

2024-07-19 00:58 UTC, skylar1220 commented on backend/src/main/java/reviewme/keyword/domain/exception/DuplicateKeywordException.java
https://github.com/woowacourse-teams/2024-review-me/pull/43#discussion_r1683616304 산초의 코멘트에 남겼던 부분인데 수동형으로 예외 상황이 발생'했'음을 나타내고자 하는 것이라면 (NotFoundExceptionc처럼) duplicated가 적절하지 않을까 생각합니다!

2024-07-19 00:58 UTC, skylar1220 commented on backend/src/test/java/reviewme/fixture/ReviewerGroupFixture.java
> +    }
아하 이렇게 하면 리뷰이를 그 때 그 때 넣어줄 수 있겠군요!! 얻어갑니다😋

2024-07-19 00:58 UTC, skylar1220 commented on backend/src/test/java/reviewme/review/service/ReviewKeywordServiceTest.java
> +        // when
개행이 필요하겠네요!
```suggestion
        List<Keyword> selectedKeywords = List.of(keywords.get(1), keywords.get(2));
        
        // when
```

2024-07-19 01:04 UTC, nayonsoso commented on backend/src/test/java/reviewme/fixture/KeywordFixture.java
> +}
익숙하진 않지만, 정적인 Fixture 와 동적인 Fixture 를 모두 커버할 수 있어 좋은 아이디어라 생각합니다!
그런데 정말로 익숙하진 않음! 
다른 사람들의 의견도 들어보고 싶습니다~

2024-07-19 01:09 UTC, nayonsoso commented on backend/src/main/java/reviewme/keyword/domain/SelectedKeywords.java
> +    }
음 API Request 라고 생각하더라도 우리 DB 에는 키워드가 중복되게 있지 않을 것이니 문제가 없을 것이라는 생각이 드는데요!
다른 분들의 의견도 궁금합니다~

2024-07-19 01:21 UTC, donghoony commented on backend/src/main/java/reviewme/keyword/domain/SelectedKeywords.java
> +    }
정책 상 방어선으로 `unique` 제약이 들어있는 것이지, 그 책임은 여전히 어플리케이션에게 있다고 생각합니다. 직접 찔러보기 전에 어플리케이션단에서 검증하는 게 일관성 측면에서도 나을 것 같아요.

2024-07-19 01:30 UTC, skylar1220 commented on backend/src/main/java/reviewme/keyword/domain/SelectedKeywords.java
> +    }
선택된 키워드를 받아서 이 검증으로 들어오는 경우가 일반적일 것 같은데, (즉, 키워드의 id가 있는 상태로 들어오는 경우)
id가 아니라 detail을 갖고 비교하기로한 이유가 궁금해요!

2024-07-19 01:34 UTC, donghoony commented on backend/src/main/java/reviewme/keyword/domain/exception/DuplicateKeywordException.java
ㅎㅎ 네이밍 어렵죠,, `DuplicateKeyword`는 중복된 키워드가 있는 상태를 나타내서 추가 작업이 필요없다고 생각해요. 
![Uploading image.png…]()

2024-07-19 01:36 UTC, donghoony commented on backend/src/test/java/reviewme/review/service/ReviewKeywordServiceTest.java
> +        // when
👍🏻

2024-07-19 01:37 UTC, donghoony commented on backend/src/main/java/reviewme/keyword/domain/SelectedKeywords.java
> +    }
이거 equals로 가져가는 게 낫겠네요 🤔 겹치는 키워드의 가능성을 생각했는데, 그런 상황은 발생하지 않겠씁니다~

2024-07-19 01:39 UTC, donghoony commented on backend/src/main/java/reviewme/keyword/domain/SelectedKeywords.java
> +    }
사실 이건 도메인 쪽이라, 엔티티를 신경쓰지 않고 작성해서 이렇습니다. 엔티티 관련된 코드가 하나도 없어서 Id를 배제하고 생각했어요. Equals가 Keyword쪽에 존재하니 그냥 `distinct`로 해도 되려나 모르겠네요.

2024-07-19 01:40 UTC, donghoony commented on backend/src/main/java/reviewme/keyword/domain/SelectedKeywords.java
> +        }
검증은 한 줄로 이루어져야 읽기 편하다고 생각해서 분리해 두었습니다.

2024-07-19 01:56 UTC, nayonsoso commented on backend/src/main/java/reviewme/keyword/domain/exception/DuplicateKeywordException.java
오 중복에 대한 예외는 DuplicateXXX 를 쓰는군요! 👍

2024-07-19 02:18 UTC, donghoony commented on backend/src/main/java/reviewme/keyword/domain/SelectedKeywords.java
> +    }
ID 기반 비교로 수정했습니다.

2024-07-19 02:31 UTC, Kimprodp approved these changes
죠슴니다 🙌

2024-07-19 02:31 UTC, Kimprodp commented on backend/build.gradle
> +    testImplementation 'org.projectlombok:lombok'
👍

2024-07-19 02:31 UTC, Kimprodp commented on backend/src/main/java/reviewme/keyword/domain/Keyword.java
> +    }
equals, hashCode에서 엔티티가 영속화 되지 않으면 id가 null 일텐데 괜찮을까요?

2024-07-19 02:31 UTC, Kimprodp commented on backend/src/main/java/reviewme/keyword/domain/SelectedKeywords.java
> +        return Collections.unmodifiableList(keywords);
좋네요👍

2024-07-19 02:40 UTC, donghoony commented on backend/src/main/java/reviewme/keyword/domain/Keyword.java
> +    }
`detail`로 비교합니다! 최고~!

2024-07-19 03:58 UTC, nayonsoso approved these changes
아루 짱짱~
테드도 잘 짚어줬네요👏👏

2024-07-19 04:09 UTC, skylar1220 commented on backend/src/main/java/reviewme/keyword/domain/exception/DuplicateKeywordException.java
아하 자바에서도 예외 클래스 이름이 저렇게 되어있었군요😅

2024-07-19 04:13 UTC, skylar1220 commented on backend/src/main/java/reviewme/keyword/domain/SelectedKeywords.java
> +        }
앗 제가 얘기한 건 validateSize, validateDuplicate 등으로 메서드 분리를 하지 않은 이유가 검증 로직이 많지 않아서인지의 궁금증이었습니다!

2024-07-19 04:21 UTC, donghoony commented on backend/src/main/java/reviewme/keyword/domain/SelectedKeywords.java
> +        }
네 아직 읽기 불편하지 않았습니다

2024-07-19 04:28 UTC, skylar1220 commented on backend/src/main/java/reviewme/keyword/domain/SelectedKeywords.java
> +    }
Http request를 통해 잘못된 요청을 보내는 상황이 일어날 수 있겠네요. 
이 중복된 키워드와 Review를 ReviewKeyword 객체로 만들어서 DB로 보내니 중복 키워드에 대한 검증이 DB에서 되는 부분도 아니고요. 그렇다면 현재 검증 유지가 맞다고 생각해요!

2024-07-19 04:49 UTC, skylar1220 approved these changes

2024-07-19 04:54 UTC, merged