[BE] RestDocs 도입, Swagger 어노테이션 삭제
woowacourse-teams/2024-review-me pull request #407
Opened 2024-08-17 14:54 UTC by donghoony

- resolves #382 

---

### 🚀 어떤 기능을 구현했나요 ?
- 기존 API 문서를 Swagger에서 RestDocs로 전환합니다.

### 🔥 어떻게 해결했나요 ?
- RestAssured를 쓰는 방식이 익숙해서, `RestAssuredMockMvc`를 활용했습니다. Service layer는 모두 Mocking하고 Request/Response에 신경썼어요.
- 빌드 후 http://localhost:8080/docs/index.html 에서 html을 확인할 수 있습니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 현재 Swagger API를 토대로 작성했습니다. 다른 부분이 있는지 확인해주세요.

### 📚 참고 자료, 할 말
https://github.com/rest-assured/rest-assured/wiki/Spring#bootstrapping-restassuredmockmvc

2024-08-17 14:56 UTC, donghoony commented
이거 머지되고 나서 SwaggerUI 전환을 고민해볼게요, 해본 적 없어서 러닝커브를 고려해야 합니다 😢

2024-08-17 15:49 UTC, donghoony commented
Swagger 코드 삭제도 이 Pr에서 하는게 좋을까요? 컨플릭 무서워서..

2024-08-18 06:46 UTC, Kimprodp requested changes
레독 도입 고생많았어요 아루~ 👍

근데 어플리케이션 실행했을 때,  http://localhost:8080/docs/index.html 에 접속하면 404가 뜨는데 추가적인 설정이 또 필요한가요?

우선은 file change 만 보고 리뷰 남깁니다. 코멘트 확인 부탁해요~
그리고 지금 모든 예외 케이스 별로 정의되어 있진 않은 것 같은데, 에러 형식 보여주기용으로 하나씩만 해도 괜찮을까요?

2024-08-18 06:46 UTC, Kimprodp commented on backend/src/test/java/reviewme/api/ReviewApiTest.java
> +                fieldWithPath("revieweeName").description("리뷰어 이름"),
'리뷰이 이름' 이 되어야 할 것 같아요!

2024-08-18 06:46 UTC, Kimprodp commented on backend/src/test/java/reviewme/api/ReviewApiTest.java
> +
노션 api 문서에는 가이드라인과 관련된 항목이 있는데 여긴 없는 것 같아요.
상세 조회 때 가이드라인은 보여주지 않나요? (안 보여줘도 될 것 같다는 생각. 그럼 노션 문서 수정이 필요할 듯 합니다.)

2024-08-18 06:46 UTC, Kimprodp commented on backend/src/test/java/reviewme/api/ReviewApiTest.java
> +                fieldWithPath("answers[].text").description("텍스트 답변").optional()
'서술형 답변' 어떤가요? 리뷰 상세 조회에서 사용한 워딩으로 통일해도 좋을 것 같슴다

2024-08-18 06:46 UTC, Kimprodp commented on backend/src/test/java/reviewme/api/ReviewApiTest.java
> +                fieldWithPath("createdAt").description("리뷰 생성 날짜"),
다른 곳에서 `createAt`이 '리뷰 작성 날짜'로 되어있는데 통일하는 것이 좋을 것 같습니다!
개인적으로는 '생성 날짜' 보다는 '작성 날짜'가 더 어울릴 것 같아요!

2024-08-18 06:46 UTC, Kimprodp commented on backend/src/test/java/reviewme/api/ReviewGroupApiTest.java
> +                fieldWithPath("revieweeName").description("리뷰어 이름"),
여기두 '리뷰이 이름'

2024-08-18 06:46 UTC, Kimprodp commented on backend/src/test/java/reviewme/api/TemplateApiTest.java
> +                fieldWithPath("revieweeName").description("리뷰어 이름"),
여기두 '리뷰이 이름'

2024-08-18 06:46 UTC, Kimprodp commented on backend/src/test/java/reviewme/api/TemplateApiTest.java
> +                fieldWithPath("sections[].visible").description("섹션 표시 여부"),
'섹션 표시 여부' 보단 '섹션 노출 조건' 또는 '섹션 표시 조건' 과 같은 워딩은 어떤가요?
'섹션 표시 여부'는 말 그대로 표시 or 표시하지 않음 만을 나타내는 의미 같아요.

2024-08-18 06:46 UTC, Kimprodp commented on backend/src/test/java/reviewme/api/TemplateApiTest.java
> +
여기 `options`는 없어도 상관없나요??
위에는 `optionGroup`이 있어서요

2024-08-18 07:57 UTC, donghoony commented on backend/src/test/java/reviewme/api/ReviewApiTest.java
> +                fieldWithPath("revieweeName").description("리뷰어 이름"),
모두 고쳤습니다 👍🏻

2024-08-18 07:57 UTC, donghoony commented on backend/src/test/java/reviewme/api/ReviewApiTest.java
> +
네, 상세 조회 때 가이드라인은 보여주지 않아요 !

2024-08-18 07:58 UTC, donghoony commented on backend/src/test/java/reviewme/api/ReviewApiTest.java
> +
노션 수정 완 👍🏻

2024-08-18 07:58 UTC, donghoony commented on backend/src/test/java/reviewme/api/ReviewApiTest.java
> +                fieldWithPath("answers[].text").description("텍스트 답변").optional()
좋습니다!

2024-08-18 07:59 UTC, donghoony commented on backend/src/test/java/reviewme/api/ReviewApiTest.java
> +                fieldWithPath("createdAt").description("리뷰 생성 날짜"),
반영 완료!

2024-08-18 08:05 UTC, donghoony commented on backend/src/test/java/reviewme/api/TemplateApiTest.java
> +                fieldWithPath("sections[].visible").description("섹션 표시 여부"),
설명을 추가했습니다. `ALWAYS` `CONDITIONAL` 둘 중 하나라서 표시 여부로 충분하다고 생각해요

2024-08-18 08:17 UTC, donghoony commented on backend/src/test/java/reviewme/api/TemplateApiTest.java
> +
배열에 대한 설명을 추가했습니다.

2024-08-18 08:20 UTC, donghoony commented
@Kimprodp RestDocs 생성은 실행이 아니라 `build` task 앞에 진행돼서, `./gradlew build`를 사용하면 보일 거예요

2024-08-18 14:35 UTC, Kimprodp approved these changes
반영 사항 확인 완료 approve ~

2024-08-18 16:50 UTC, nayonsoso approved these changes
아루 고생이 진짜로.. 많았어요😭
노동 작업이 많았네요😭😭😭
진짜 수고 많았습니다!!!

+) 레스트 독스로 저도 코드를 작성할 일이 있을테니 공부를 하고 리뷰를 해보고 있는데요,
다 터득을 하고 리뷰를 하기엔 너무 늦을 것 같아서,.. 😓
기본적은 작동 원리정도만 공부를 하고, html 파일로 쭉쭉 읽어나갔습니다.
(그런데 위에서 테드가 말한대로 docs/index.html 로 하면 안열리더라고요, 
그냥 html 파일을 브라우저로 열어서 확인했습니다)

다음에 제가 기능 구현하는 것에 대해서는 레스트 독스로 테스트코드 작성할 수 있게끔 계속 공부해보겠습니다! 
정말 수고 많았습니다.

![image](https://github.com/user-attachments/assets/13dc99ce-6584-4146-93fd-2e738a3b1874)

2024-08-18 16:50 UTC, nayonsoso commented on backend/build.gradle
> +    testImplementation 'io.rest-assured:rest-assured:5.4.0'
[진짜 몰라서 하는 질문]
restAssured 는 왜 포함한건가요?

2024-08-18 16:50 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/dto/request/CreateReviewAnswerRequest.java
>  }
스웨거 없앤거 잘했다 생각합니다 ㅎㅎ

2024-08-18 16:51 UTC, donghoony commented on backend/build.gradle
> +    testImplementation 'io.rest-assured:rest-assured:5.4.0'
제가 이번에 테스트를 작성하면서 사용한 게 `RestAssuredMockMvc`라서 그렇습니다..ㅎㅎ `RestAssured`가 익숙해서 이 방법으로 문서를 만들어보고 싶었는데 확인해보니 이런 라이브러리의 도움을 받을 수 있더라고요

2024-08-19 04:05 UTC, skylar1220 approved these changes
어떻게 작동하는지만 대충 이해했는데 시간이 없다요...🥲
머지를 위해 일단 어프룹 날리고 계속 공부할게요!!
고생 많았다 아루!!!

2024-08-19 07:33 UTC, merged