[BE] 픽스처를 만들고, 이를 기존 테스트 코드에 적용한다
woowacourse-teams/2024-review-me pull request #409
Opened 2024-08-17 18:20 UTC by nayonsoso

- resolves #377 

---

### 🚀 어떤 기능을 구현했나요 ?
- Fixture 를 만들었습니다.

### 🔥 어떻게 해결했나요 ?
- 기존에 사용했던 enum fixture 방법을 사용했습니다.
- 각각의 인자가 중요하지 않은 상황에는 `create()` 로 생성합니다.
- 특정한 인자가 필요한 상황에서는 `createWithXXX()` 로 생성합니다.
- Template과 관련된 데이터 세팅이 필요한 경우에는 
(예를 들어 OptionItem, OptionGroup, Question, Section, Template 이 전부 세팅이 필요한 경우) 
`TestDataInitializer` 라는 testComponent 를 import 해서 사용합니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 커밋대로 읽으며 리뷰해주세요.
- 특히, 커밋 메세지에 어떤 부분을 바꿨는지 적혀있으니, 커밋 메세지의 본문 부분을 잘 봐주세요!
- `TestDataInitializer` 라는 템플릿을 한번에 설정할 수 있는 클래스를 만들었는데, 유용하게 쓰일 것 같은지 확인해주세요.

### 📚 참고 자료, 할 말

2024-08-17 18:42 UTC, donghoony requested changes
싼초 테스트 매만지느라 고생했습니다~ 몇가지 이야기 나누어보아요

2024-08-17 18:42 UTC, donghoony commented on backend/src/test/java/reviewme/fixture/OptionItemFixture.java
> +    }
메서드 체이닝을 사용하면 중복을 더 줄일 수 있겠네요! `createWithOptionGroupIdAndPosition`을 활용하도록 모두 바꿔도 좋겠어요, 다른 Fixture들도 마찬가지입니다~

2024-08-17 18:42 UTC, donghoony commented on backend/src/test/java/reviewme/fixture/QuestionFixture.java
> +    }
`withGuideline`은 필요하지 않을까요? 테스트할 때 필요없었다면 안 쓴 이유가 있겠죠 ?

2024-08-17 18:42 UTC, donghoony commented on backend/src/test/java/reviewme/review/service/CreateReviewServiceTest.java
> +                                tuple(reviewGroup.getId(), savedTemplate.getId())
`tuple`을 넣어주지 않아도 동작하지 않나요?

2024-08-17 18:42 UTC, donghoony commented on backend/src/test/java/reviewme/review/service/ReviewDetailLookupServiceTest.java
> +        );
이 부분은 조금 의문이 드는데요, 테스트하고자 하는 것이 `섹션을_보이게_하는_옵션을_선택하지_않은_경우_해당_섹션을_제외하고_보여준다`입니다. 그렇다면 섹션이 보이지 않는 것만으로도 충분히 검증이 완료되었고, 그 이외의 것을 검증하는 것은 불필요한 검증이라고 생각돼요. 순서나 각각의 내용이 어떠한지는 아래쪽에서 검증돼있으니, `hasSize(1)`로 충분하다고 생각합니다~

2024-08-17 18:42 UTC, donghoony commented on backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
> +                        Tuple.tuple(review2.getId(), List.of(categoryOptionItem2.getId()))
이부분도 Tuple이 필요한 이유를 알려주세요~

2024-08-17 18:42 UTC, donghoony commented on backend/src/test/java/reviewme/template/service/TemplateMapperTest.java
> +    private TemplateMapper templateMapper;
👍🏻

2024-08-18 12:31 UTC, skylar1220 commented on backend/src/test/java/reviewme/fixture/OptionGroupFixture.java
> +    꼬리_질문_선택지_그룹(1, 10),
꼬리 질문 선택지 그룹 max를 3으로 수정 필요합니당!

2024-08-18 13:40 UTC, skylar1220 approved these changes
소소한 질문이라 우선 approve 해둘게요!

그리고 TestDataInitializer 좋습니다! 처음 봤을 때는 헷갈렸던 부분이 있었는데 금방 이해가서 괜찮았습니당!
예: 저장된_꼬리_질문_선택형1 과 저장된_꼬리_질문1_선택지1 이 연관된 항목이라는 걸 이해하는데 조금 시간이 걸림

어떻게 다 fixture로 뺐는지 + 꼼꼼하게 변수 추출, then 부분 보강한 것 보고 감탄했어요...
나도 산초의 꼼꼼함 배워야겠다🤔

2024-08-18 13:40 UTC, hyeonji1220 commented on backend/src/test/java/reviewme/fixture/OptionItemFixture.java
다양한 경우에의 사용 👍👍

2024-08-18 13:40 UTC, hyeonji1220 commented on backend/src/test/java/reviewme/review/service/CreateReviewServiceTest.java
> +                                tuple(reviewGroup.getId(), savedTemplate.getId())
containsExactlyInAnyOrder도 그냥 containsExactly로 해도 되지 않나싶어요!

2024-08-18 13:40 UTC, skylar1220 commented on backend/src/test/java/reviewme/question/repository/OptionItemRepositoryTest.java
> +                .containsExactlyInAnyOrder(categoryOptionItemId1, categoryOptionItemId2, followingOptionItemId1);
여기도 containsExactly여도 되지 않을까요?

2024-08-18 13:40 UTC, skylar1220 commented on backend/src/test/java/reviewme/review/service/ReviewServiceTest.java
> +                        Tuple.tuple(review2.getId(), List.of(categoryOptionItem2.getId()))
훨씬 깔끔해졌네요👍👍

2024-08-19 03:34 UTC, nayonsoso commented on backend/src/test/java/reviewme/fixture/OptionItemFixture.java
> +    }
> 메서드 체이닝을 사용하면 중복을 더 줄일 수 있겠네요!

메서드 체이닝을 사용하면 중복을 줄일 수는 있겠지만,
한 줄에 점 하나 원칙에 따라서 코드 라인이 늘어날 것이라 생각합니다~
그럼 테스트 코드가 더 읽기 어려울 것 같아요.

---

> createWithOptionGroupIdAndPosition을 활용하도록 모두 바꿔도 좋겠어요

왜 이렇게 생각하셨는지 근거를 더 제시해주세용🥹

2024-08-19 03:34 UTC, nayonsoso commented on backend/src/test/java/reviewme/fixture/OptionItemFixture.java
> +    }
메서드 체이닝을 사용해서 테스트 코드를 개선했던 지난 기수의 글을 읽어보았습니다만
(https://velog.io/@gudonghee2000/읽기-좋은-테스트-코드는-소설-같지-않을까)
여기서도 어떠한 동작의 연속을 드러내기 위해 메서드 체이닝을 활용했더라고요!

Fixture 객체 생성은 위 함수로 하되,
연속적 동작에서의 메서드 채이닝은 가독성을 높일 수 있을 것 같아요.

2024-08-19 03:38 UTC, nayonsoso commented on backend/src/test/java/reviewme/fixture/QuestionFixture.java
> +    }
> withGuideline은 필요하지 않을까요?

가이드라인 유뮤에 따라서 결과가 달라지는 테스트는 없어서 만들지 않았습니다!

---

> 테스트할 때 필요없었다면 

> 안 쓴 이유가 있겠죠 ?

네 그래서 테스트 할 때 필요가 없어서 안썼는데용..!

2024-08-19 05:36 UTC, donghoony commented on backend/src/test/java/reviewme/fixture/OptionItemFixture.java
> +    }
```suggestion
    public OptionItem create() {
        return createWithOptionGroupIdAndPosition(this.optionGroupId, this.position);
    }

    public OptionItem createWithOptionGroupId(long optionGroupId) {
        return createWithOptionGroupIdAndPosition(optionGroupId, this.position);
    }

    public OptionItem createWithPosition(int position) {
        return createWithOptionGroupIdAndPosition(this.optionGroupId, position);
    }
```

2024-08-19 06:14 UTC, donghoony commented on backend/src/test/java/reviewme/fixture/QuestionFixture.java
> +    }
ㅜㅜ 필요없었다는 이야기만 들었으면 되었습니다 👍🏻

2024-08-26 16:35 UTC, donghoony commented
#538 에서 진행합니다 👍🏻

2024-08-26 16:35 UTC, closed without merging