[BE] dto 에 Nullable, validation 어노테이션 적용
woowacourse-teams/2024-review-me pull request #410
Opened 2024-08-17 18:43 UTC by nayonsoso

- resolves #301 

---

### 🚀 어떤 기능을 구현했나요 ?
- 어노테이션을 추가했습니다.

### 🔥 어떻게 해결했나요 ?
- 리뷰 생성시 요청 데이터 (`CreateReviewRequest`)에 검증하는 validation 을 추가했습니다.
- 리뷰 생성 시 요청 데이터 안의 답변 내용 (`CreateReviewAnswerRequest`)에 Nullable 어노테이션을 추가했습니다.
서술형 답변 시, 옵션 아이템 id 가 null 일 것이며
선택형 답변 시, 텍스트 내용이 null 일 것이기 때문입니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?

### 📚 참고 자료, 할 말
- 이번에 '초간단' 이라는 라벨을 만들어봤습니다

2024-08-17 18:44 UTC, donghoony approved these changes
👍🏻

2024-08-18 00:26 UTC, Kimprodp approved these changes
초간단👍

2024-08-18 07:36 UTC, skylar1220 requested changes
제 작업 내용인줄 알고 추가했다가 충돌 날까봐 다시 후다닥 뺌..ㅋㅋㅋ

2024-08-18 07:36 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/dto/request/CreateReviewAnswerRequest.java
>          long questionId,
questionId에 notNull이 들어가야하지 않을까요?🤔

2024-08-19 04:51 UTC, skylar1220 approved these changes

2024-08-19 04:51 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/dto/request/CreateReviewAnswerRequest.java
>          long questionId,
커비 말대로 long 이 아니라 Long 으로 두고 NotNull 을 붙여주는게 맞겠네요!🙇🏻‍♀️

2024-08-19 04:54 UTC, donghoony approved these changes

2024-08-19 04:58 UTC, merged