[BE] GroupAccessCode 와 ReviewRequestCode 를 받아 확인하는 API 구현
woowacourse-teams/2024-review-me pull request #412
Opened 2024-08-18 06:29 UTC by nayonsoso

- resolves #376 

---

### 🚀 어떤 기능을 구현했나요 ?
- GroupAccessCode 와 ReviewRequestCode 를 받아 확인하는 API를 구현했습니다.

### 🔥 어떻게 해결했나요 ?
- 단순히 확인을 하는 것이기 때문에 서버의 상태를 바꾸지 않으므로 POST가 아니라 GET 함수를 사용하게 했습니다.
- 쉽게 노출될 수 있는 ReviewRequestCode 는 URL 에 RequestParam 으로
- 숨겨야 할 GroupAccessCode 는 헤더에 담게 했습니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 

### 📚 참고 자료, 할 말

2024-08-18 12:29 UTC, skylar1220 approved these changes
그애코, 리리코 비교 👍

2024-08-18 15:38 UTC, donghoony requested changes
간단한 RC입니다~ 반영해주세용

2024-08-18 15:38 UTC, donghoony commented on backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
> +    @GetMapping("/v2/groups/code")
`code`를 `GET` 메서드로 가져오니 `code`라는 자원이 있을 것이라고 느껴져요. `check`와 같은 동사를 써도 괜찮겠습니다. 그래서 POST와도 어울린다고 생각하긴 해요.

2024-08-18 15:38 UTC, donghoony commented on backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupService.java
> +                reviewGroupRepository.existsByReviewRequestCodeAndGroupAccessCode(reviewRequestCode, groupAccessCode)
변수로 뽑는 게 가독성있을 것이라고 생각하지만.. 이건 그대로 둬도 괜찮습니다 😁

2024-08-18 15:38 UTC, donghoony commented on backend/src/main/java/reviewme/reviewgroup/service/dto/CheckGroupAccessCodeResponse.java
> +        boolean isValidAccess
`hasValidAccess`는 어떨까요? 접근 권한이 존재하는지를 확인하기 위함이라서 `is`보다는 `has`가 적절해 보여요. 같은 맥락으로 `hasAccess`를 이야기했었습니다.

2024-08-19 02:46 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
> +    @GetMapping("/v2/groups/code")
> code를 GET 메서드로 가져오니 code라는 자원이 있을 것이라고 느껴져요. 

그렇게 보일 수도 있겠네요😓
uri 를 `/groups/check` 로 바꾸겠습니다~

> 그래서 POST와도 어울린다고 생각하긴 해요.

서버에 변화가 생기지 않으니 GET 은 유지하겠습니다!

2024-08-19 03:16 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/service/dto/CheckGroupAccessCodeResponse.java
> +        boolean isValidAccess
제가 hasAccess 가 직역하자면 '접근을 갖는다' 가 되니 어색했다고 말씀드렸던 것 기억하시나요?
그것과 같은 의미로, hasValidAccess 도 직역하자면 '유효한 접근을 갖는다' 가 되니 어색하게 느껴져요🤔

'접근 권한을 갖는지' 를 드러내면셔 has 를 사용하려려면 `hasAccessPermission` 정도가 적절할 것 같은데, 이건 어떠신가요?

2024-08-19 03:30 UTC, donghoony commented on backend/src/main/java/reviewme/reviewgroup/service/dto/CheckGroupAccessCodeResponse.java
> +        boolean isValidAccess
access는 명사형으로 접근 권한이라는 의미를 가집니다. 이 쪽에 들어가도 어색하지 않다고 생각해요!

> the ability, right, or permission to approach, enter, speak with, or use;

[ref](https://www.dictionary.com/browse/access)

2024-08-19 04:54 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/service/dto/CheckGroupAccessCodeResponse.java
> +        boolean isValidAccess
이것을 보고 납득을 했습니다

2024-08-19 07:23 UTC, donghoony approved these changes

2024-08-19 07:24 UTC, Kimprodp approved these changes
산고

2024-08-19 07:25 UTC, merged