[BE] refactor: 리뷰 등록시 검증 보완
woowacourse-teams/2024-review-me pull request #414
Opened 2024-08-18 06:59 UTC by skylar1220

- resolves #383 

---

### 🚀 어떤 기능을 구현했나요 ?
- 리뷰 등록시 검증을 추가하고 오류를 수정했습니다.

### 🔥 어떻게 해결했나요 ?
- 서술형 답변 길이 검증 추가
- 필수가 아닌 서술형 응답 생성되지 않도록 로직 수정
- dto에 valid 추가

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 검증해야하는 내용이 기존에 더해서 많이 떠오르지 않아서 일단 떠오르는 것만 추가했어요~ 혹시 더 있다면 알려주세요!

### 📚 참고 자료, 할 말

2024-08-18 15:40 UTC, donghoony requested changes
생각할 점을 남겨둡니다!

2024-08-18 15:40 UTC, donghoony commented on backend/src/main/java/reviewme/review/domain/TextAnswer.java
> +    public static final int MAX_LENGTH = 1_000;
- `private`으로 할까요?
- 하나의 정책처럼 보입니다. 도메인에 있어야 하는 값이 맞을까요? 다른 답변이 500자 제한이라면, 도메인을 재사용할 수 없을 듯해요.

2024-08-18 15:40 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/CreateReviewService.java
> +            if (questionType == QuestionType.TEXT && !answerRequests.text().isBlank()) {
객체에게 물어볼까요 ? 😁

2024-08-19 02:42 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/CreateReviewService.java
> +            if (questionType == QuestionType.TEXT && !answerRequests.text().isBlank()) {
반영 완료!

2024-08-19 03:10 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/CreateReviewService.java
> +            if (questionType == QuestionType.TEXT && !answerRequests.text().isBlank()) {
반영 완료!

2024-08-19 03:11 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/domain/TextAnswer.java
> +    public static final int MAX_LENGTH = 1_000;
각 텍스트 형 답변마다 서로 다른 최소 최대글자수를 갖는 상황이 있을 수 있겠네요. 
그렇다면 도메인이 아니라 검증 객체로 빼야 하겠습니다!

더불어 컬럼에 글자수 제한이 원래 있었는데 이것도 같은 맥락으로 
텍스트 답변마다 다른 글자수 제한을 가질 수 있기 때문에 제거하였습니다~~

2024-08-19 03:17 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/CreateReviewService.java
> +            if (questionType == QuestionType.TEXT && !answerRequests.text().isBlank()) {
반영을 두번 하셨나요? 😲

2024-08-19 03:20 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/CreateReviewService.java
> +            if (questionType == QuestionType.TEXT && answerRequests.isNotBlank()) {
[제대로 이해한게 맞는지 질문]
추가하신 부분이 '필수가 아닌 서술형 질문은 저장하지 않기 위함' 이 맞나요?

2024-08-19 03:20 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/domain/TextAnswer.java
> +    public static final int MAX_LENGTH = 1_000;
> 텍스트 답변마다 다른 글자수 제한을 가질 수 있기 때문에

그렇다면 서술형 질문에 대해서 Question 객체를 바로 사용하지 않고,
최대 최소 길이를 컬럼으로 갖게 하는 새로운 엔티티가 필요해질 수도 있겠네요!
다만 아직 정말로 필요한 것은 아니라 하나의 가능성만 제시해봅니다

2024-08-19 03:22 UTC, nayonsoso requested changes

2024-08-19 03:22 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/exception/CheckBoxAnswerIncludedTextException.java
>          log.info("Text type answer cannot have option items");
웁스 ㅎㅎ 제가 복붙하며 실수했던 것 같아용
로그 메세지 부분도 수정해주실 수 있나요?

2024-08-19 03:31 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/CreateReviewService.java
> +            if (questionType == QuestionType.TEXT && !answerRequests.text().isBlank()) {
앗ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-08-19 03:36 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/review/service/CreateReviewService.java
> +            if (questionType == QuestionType.TEXT && answerRequests.isNotBlank()) {
약간 달라요..!
text 타입이면서 내용이 빈문자열이 아닌 경우만 저장 로직을 실행하게 하기위해서입니다~

2024-08-19 03:36 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/exception/CheckBoxAnswerIncludedTextException.java
>          log.info("Text type answer cannot have option items");
하하 제가 하나만 수정하고 둘은 수정하지 않았네요😇

2024-08-19 03:37 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/domain/TextAnswer.java
> +    public static final int MAX_LENGTH = 1_000;
> 최대 최소 길이를 컬럼으로 갖게 하는 새로운 엔티티가 필요해질 수도 있겠네요! 

오호 생각해봐야겠네요!

2024-08-19 05:27 UTC, Kimprodp approved these changes

2024-08-19 05:28 UTC, donghoony approved these changes
👍🏻

2024-08-19 05:32 UTC, nayonsoso approved these changes
테드 생일 축하해!!

2024-08-19 05:32 UTC, merged