[BE] feat: 리뷰 도메인 구체화, 정책 구현
woowacourse-teams/2024-review-me pull request #43
Opened 2024-07-18 08:24 UTC by nayonsoso

- resolves #36 

---

### 🚀 어떤 기능을 구현했나요 ?
- 리뷰에 들어갈 정책을 구현했습니다.
- 리뷰 작성 요청(CreateReviewContentRequest와 CreateReviewRequest)에 대해 검증하고, 핸들링했습니다.

### 🔥 어떻게 해결했나요 ?
- dto 검증에서 발생할 수 있는 예외를 핸들링하기 위해서 요런 코드를 작성했어요.
```java
@ExceptionHandler(MethodArgumentNotValidException.class)
public ProblemDetail handleMethodArgumentNotValidException(MethodArgumentNotValidException ex) {
    List<FieldErrorResponse> fieldErrors = ex.getBindingResult()
            .getFieldErrors()
            .stream()
            .map(fieldError -> new FieldErrorResponse(
                    fieldError.getField(),
                    fieldError.getRejectedValue(),
                    fieldError.getDefaultMessage()))
            .toList();

    ProblemDetail problemDetail = ProblemDetail.forStatus(HttpStatus.BAD_REQUEST);
    Map<String, Object> properties = Map.of("fieldErrors", fieldErrors);
    problemDetail.setProperties(properties);
    return problemDetail;
}
```

- ProblemDetail 형식을 지키며, 발생한 검증에 대한 모든 리뷰를 보여주고 싶었습니다.
- ProblemDetail 에서는 미리 정의된 필드가 아닌 다른 필드를 추가하려면 setProperties 를 사용해야 합니다.
- 그래서 예외를 야기한 목록을 리스트 형태로 넣어주었습니다.
- 예외 응답은 아래와 같이 됩니다.
```
{
    "type": "about:blank",
    "title": "Bad Request",
    "status": 400,
    "instance": "/reviews",
    "fieldErrors": [
        {
            "field": "reviewerId",
            "value": null,
            "message": "리뷰어 아이디를 입력해주세요."
        },
        {
            "field": "selectedKeywordIds",
            "value": [],
            "message": "키워드를 최소 1개, 최대 5개 입력해주세요."
        },
        {
            "field": "contents[1].question",
            "value": "  ",
            "message": "질문을 입력해주세요."
        }
    ]
}
```

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 호호 Dto 의 validation이 실패할 때의 예외 핸들링에 대해 제가 작성을 했봤는데요...
- 이게 괜찮은지? 이해가 되지 않는 부분은 없는지? 피드백해주세요!
- 그리고 여기에 대해 테스트 코드를 작성하려 했다가 '이걸 테스트하면, 앞으로 모든 요청의 검증에 대해 테스트해야 하는건가? 그것은 너무 많은데?' 요런 생각이 들어서 스킵했습니다! 테스트를 한다면, MovkMvcTest 로 할수는 있을 것 같아요. Dto 검증 로직을 테스트해야 할 것 같은지 생각하는지 알려주세요!

### 📚 참고 자료, 할 말
-

2024-07-18 08:35 UTC, donghoony commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +                .toList();
저도 모든 것을 보여주면 좋겠다는 생각을 했는데요, [리뷰어에게서 받은 이야기](https://github.com/woowacourse/spring-roomescape-member/pull/61#discussion_r1590768371)가 있어 공유합니다. 사용자 입장에서는 한 가지만 보이도록 해서 빠르게 해당 오류를 고치는 것이 더 좋을 것 같다는 의견이예요.

2024-07-18 11:20 UTC, donghoony requested changes
산초 고생했습니다~!~!~~!!~ 몇가지 수정할 곳 언급하고 넘어갈게요 😁

2024-07-18 11:20 UTC, donghoony commented on backend/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-validation'
이 커밋 메시지는 `build:`로 시작했으면 좋았겠네요 😄

2024-07-18 11:20 UTC, donghoony commented on backend/src/main/java/reviewme/review/dto/request/CreateReviewRequest.java
> +        @Size(min = 1, message = "리뷰 내용을 하나 이상 입력해주세요.")
요건 나중에 리뷰 개수가 정해지면 서비스 쪽에서 검증해도 되겠네요 🤔, 리뷰 개수가 3개인데 1개 이상이면 Dto쪽에서 넘어갈 수 있으니깐요

2024-07-18 11:20 UTC, donghoony commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +        Map<String, Object> properties = Map.of("fieldErrors", fieldErrors);
`fieldError`라는 필드 이름보다는 `details`와 같이 뷰 친화적인 이름은 어떨까요?

2024-07-18 11:20 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/ReviewService.java
> +    private void validateIsDeadlinePassed(ReviewerGroup reviewerGroup) {
긍정문으로 검증합시다! `not`이 붙지 않는 뉘앙스의 긍정문보다는 문장 자체가 참인 경우 검증된다는 것을 내포했어요. 검증을 하려는 쪽이 긍정이 되도록 메서드 이름을 바꾸면 어떨까요? `validateBeforeDeadline` 정도요!

2024-07-18 11:20 UTC, donghoony commented on backend/src/test/java/reviewme/review/ReviewServiceTest.java
> +                List.of(keyword.getId())
이정도는 개행하지 않아도 될 것 같네요 👀

2024-07-18 11:20 UTC, donghoony commented on backend/src/main/java/reviewme/review/domain/exception/DeadlineExceedException.java
> +public class DeadlineExceedException extends BadRequestException {
문법 조금 잡을게요 👍🏻 
```suggestion
public class DeadlineExceededException extends BadRequestException {
```

2024-07-18 11:20 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/ReviewService.java
> +    private void validateIsDeadlinePassed(ReviewerGroup reviewerGroup) {
이거 도메인으로 내리고 싶긴 하네요 👀

2024-07-18 22:21 UTC, skylar1220 requested changes
역시 꼼꼼한 산초초초초 궁금한 것 남겼습니당🥳

2024-07-18 22:21 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +                .toList();
저는 FieldErrorResponse라는 형태를 처음봐서 신기하게 봤는데요! (이런 것도 있었군요..😳)

1. field는 에러메시지와 중복 컨텍스트 제공의 느낌이 있는 것 같아요.(예: "field": "reviewerId", "message": "리뷰어 아이디를 입력해주세요.")
2. rejectedValue는 제공하면 좋고, 아님 말고?의 느낌이라 

결국 남는 게 메시지라면 아루의 의견과 비슷한 결론이 나는 것 같습니다!

2024-07-18 22:21 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/dto/request/CreateReviewRequest.java
> +        List<Long> selectedKeywordIds
기억하기론 이전 논의에서 null만 DTO에서 검증하고 길이 등의 속성은 도메인에서 검증하기로 했던 것 같은데 맞을까요?
양 쪽에서 다하면 양 쪽 검증을 항상 일치시켜줘야하는 문제가 있을 것 같아서요!

2024-07-18 22:21 UTC, skylar1220 commented on backend/src/test/java/reviewme/review/ReviewServiceTest.java
> +        );
```suggestion
        // given
        memberRepository.save(new Member("산초"));
        Member reviewee = memberRepository.save(new Member("아루"));
        LocalDateTime createdAt = LocalDateTime.now().minusDays(7).minusMinutes(1);
        reviewerGroupRepository.save(
                new ReviewerGroup(reviewee, "그룹A", "그룹 설명", createdAt)
        );
        
        Keyword keyword = keywordRepository.save(new Keyword("꼼꼼해요"));
        CreateReviewContentRequest contentRequest = new CreateReviewContentRequest(
                1L, "소프트스킬이 어떤가요?", "소통을 잘해요"
        );
        CreateReviewRequest createReviewRequest = new CreateReviewRequest(
                1L,
                1L,
                List.of(contentRequest),
                List.of(keyword.getId())
        );
```
아예 레포지토리에 필요한 데이터 저장 부분과 요청을 위한 데이터 생성 부분으로 나눠지는 부분을 개행하는 건 어떨까요?

2024-07-18 22:21 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/ReviewService.java
> +        // todo: 모든 리뷰는 기본적으로 익명이므로, 이것을 리턴하면 안된다! ReviewReponse에서 MemberResponse 자체를 없애야 한다.
아하 놓쳤던 포인트네요🤔

2024-07-18 23:48 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +                .toList();
@donghoony 
링크해주신 리뷰가 지금 제 코드와 같은 상황이네요 ㅎㅎ
그런데 지금은 백엔드로만 구성된 것이 아니라, "프론트와 같이 협업을 하니" 조금 다른 상황인 것 같아요.
발생한 예외를 원인과 함께, 여러개를 한번에 보여주는게 프론트에게 더 편할 것 같단 생각을 했어요!
그리고 사용자에게 보여줄 때는 프론트에서 한번 걸러주고, 사용자에게 보여주고요.
그런데 이건 제 생각일 뿐이니.. 어떤 형태가 더 편한지 프론트분들께 여쭤보겠습니다🫡

---

@skylar1220 FieldErrorResponse 는 제가 만든 것이랍니다 ㅎㅎ
이 예외는 요청형식에 대한 검증이므로 `어떤 JSON 필드에서 예외가 발생했는지`를 알려주면
프론트쪽에서 디버깅하기 쉬울것이라는 생각에 이렇게 만들어봤는데요!
이것 역시 프론트분들의 의견을 들어보겠습니다🫡

2024-07-18 23:48 UTC, nayonsoso commented on backend/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-validation'
헉.. 동의합니다. 다음부터는 build 로 하겠습니다😥

2024-07-18 23:48 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/dto/request/CreateReviewRequest.java
> +        @Size(min = 1, message = "리뷰 내용을 하나 이상 입력해주세요.")
수정하겠습니다~

2024-07-19 00:00 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/domain/exception/DeadlineExceedException.java
> +public class DeadlineExceedException extends BadRequestException {
@donghoony 두 개의 차이점이 어떤 것인가요? 다른 예외들은 다 exceed로 한 것 같아서요!

2024-07-19 00:13 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/ReviewService.java
> +    private void validateIsDeadlinePassed(ReviewerGroup reviewerGroup) {
오! 다시 생각하니 지금 하려고 하는게 
"데드라인이 지나지 않았으므로 리뷰를 작성할 수 있다"이니
validateBeforeDeadline 가 맞겠네요! 꼼꼼 아루 감사합니다☺️

2024-07-19 00:16 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/ReviewService.java
> +    private void validateIsDeadlinePassed(ReviewerGroup reviewerGroup) {
그리고 요 함수를 보면 아시겠지만, 
사실 '데드라인이 지났는지'를 boolean 으로 체크하는 함수는 이미 도메인으로 내려가있는데요!
예외를 던지기 위해서 private 함수로 만들어둔 것 입니다!

```java
private void validateIsDeadlinePassed(ReviewerGroup reviewerGroup) {
    if (reviewerGroup.isDeadlineExceeded(LocalDateTime.now())) {
        throw new DeadlineExceedException();
    }
}
```

2024-07-19 00:20 UTC, nayonsoso commented on backend/src/test/java/reviewme/review/ReviewServiceTest.java
> +                List.of(keyword.getId())
오호 그렇겠네요
위에 있는 `리뷰를_작성한다()`에도 동일한 코드가 있는데, 
conflict 날까봐 일단 이 부분만 고쳐두겠습니다!

2024-07-19 00:28 UTC, donghoony commented on backend/src/main/java/reviewme/review/domain/exception/DeadlineExceedException.java
> +public class DeadlineExceedException extends BadRequestException {
예외에는 상태를 담고 있어야 합니다. 전자는 동사라 일반 클래스 이름으로도 어울리지 않아요. 예외를 보고 '데드라인을 지난 상태이구나'를 알 수 있습니다. 'NotFound'라고 하지 'NotFind'라고 하지 않는 것처럼요.

2024-07-19 00:28 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/domain/exception/DeadlineExceedException.java
> +public class DeadlineExceedException extends BadRequestException {
앗 Not"Found" 나 Un"Authorized" 처럼 예외에서는 과거형을 쓰는게 더 적합하겠네요😓
DescriptionLengthExceedException도 DescriptionLength"Exceeded"Exception 로 변경하겠습니다

그런데 다시 생각해보니 이건 기한에 대한 것이라 Expired 가 더 적합하다는 생각이 듭니다!
일단 Expired 로 수정해두겠습니다🫡

2024-07-19 00:36 UTC, nayonsoso commented on backend/src/test/java/reviewme/review/ReviewServiceTest.java
> +        );
오! 제가 봤을 때는 지금도 데이터 저장 부분과 요청을 위한 데이터 생성 부분이 잘 나누어져있는 것 같은데요!
Keyword 를 미리 저장해둬야 하기 때문에 다른 save 와 붙여둔 것입니다!
그리고 요청에서는 '저장된 Keyword의 id를 사용'하기 때문에 Keyword 크게 연관이 없다고 생각했어요.

2024-07-19 00:38 UTC, donghoony commented on backend/src/main/java/reviewme/review/domain/exception/DeadlineExceedException.java
> +public class DeadlineExceedException extends BadRequestException {
마감 기한이 만료되었다보다 지났다를 많이 사용하지 않나요 ? 저는 Exceeded 가 더 어울린다고 생각해요

2024-07-19 01:32 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/dto/request/CreateReviewRequest.java
> +        List<Long> selectedKeywordIds
해당 로직 삭제했습니다 감사합니다!☺️

2024-07-19 01:33 UTC, skylar1220 commented on backend/src/test/java/reviewme/review/ReviewServiceTest.java
> +        );
아하 keyword도 저장이네요! 제가 놓쳤습니당..ㅎ

2024-07-19 01:33 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +                .toList();
### 🧑🏻‍⚖️ 프론트 분들의 답변에 의해...
여러개의 에러를 한번에 응답하는 것이 편하다고 하시니 이 코드 유지하겠습니다!

2024-07-19 01:35 UTC, skylar1220 approved these changes
궁금증 해소! 시원해요 산초 🌊

2024-07-19 01:48 UTC, nayonsoso commented
ProblemDetails 가 준수하는 RFC 9457 형식을 지키면서, 추가 정보를 줄 수 있도록 형식을 변경해봤습니다. 
이 부분도 검토해주세요! 🙇🏻‍♀️

```json
{
    "type": "about:blank",
    "title": "Bad Request",
    "status": 400,
    "detail": "요청 형식이 올바르지 않습니다.",
    "instance": "/reviews",
    "fieldErrors": [
        {
            "field": "contents",
            "value": null,
            "message": "리뷰 내용을 입력해주세요."
        },
        {
            "field": "reviewerId",
            "value": null,
            "message": "리뷰어 아이디를 입력해주세요."
        },
        {
            "field": "reviewerGroupId",
            "value": null,
            "message": "리뷰어 그룹 아이디를 입력해주세요."
        },
        {
            "field": "selectedKeywordIds",
            "value": null,
            "message": "키워드를 입력해주세요."
        }
    ]
}
```

2024-07-19 01:59 UTC, skylar1220 approved these changes

2024-07-19 02:12 UTC, Kimprodp approved these changes
크게 수정할 부분 없어서 코멘트 확인하고 머지하면 될 것 같아요!

추가적으로 리뷰 등록 시, 작성자가 리뷰 그룹에 포함되어 있는지 검증하는 로직은 추가되어야 할 것 같네요.

2024-07-19 02:12 UTC, Kimprodp commented on backend/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-validation'
혹시.. 저희 커밋 구글 컨벤션으로 하기로 했는데 빌드 관련 커밋은 chore가 아니라 build로 하나요?

2024-07-19 02:12 UTC, Kimprodp commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
>  @RestControllerAdvice
ProblemDetail을 반환하면 `@ControllerAdvice` 만으로도 될 것 같습니다!
아니면 혹시  `@RestControllerAdvice`를 사용한 이유가 있을까요?

2024-07-19 02:12 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/service/ReviewService.java
> +        // todo: 모든 리뷰는 기본적으로 익명이므로, 이것을 리턴하면 안된다! ReviewReponse에서 MemberResponse 자체를 없애야 한다.
공개용 리뷰 response는 따로 만드나요?

2024-07-19 02:16 UTC, nayonsoso commented on backend/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-validation'
![image](https://github.com/user-attachments/assets/d493f161-0dd1-441b-9743-cc75885dce9b)

구글 커밋 컨벤션에는 build 가 없군요!
그런데 저희 회의록에 의하면 build 쓰기로 했어서 그냥 써도 될 것 같아요 ㅎㅎ

2024-07-19 02:18 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/domain/exception/DeadlineExceedException.java
> +public class DeadlineExceedException extends BadRequestException {
### 🧑🏻‍⚖️ 지피티의 추천에 의해.. 

- 참관인 : 아루
- 일반적으로 "타임아웃이 됐다"는 뜻으로 Exceeded 를 쓰고
- "시간이 지났다"는 뜻으로 Expired 를 쓴다고 하여 Expired 로 가겠습니다

2024-07-19 02:19 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/ReviewService.java
> +        // todo: 모든 리뷰는 기본적으로 익명이므로, 이것을 리턴하면 안된다! ReviewReponse에서 MemberResponse 자체를 없애야 한다.
오 그것도 고려해야겠네요...
그건 공개 리뷰 만들 때 생각해보죠! ㅎㅎ

2024-07-19 02:40 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
>  @RestControllerAdvice
딱히 없습니다
이게 마음이 편하지 않나요? 하하

2024-07-19 02:51 UTC, donghoony approved these changes

2024-07-19 02:52 UTC, merged