[FE] fix: 비밀번호 검증 훅 분리 및 비밀번호 길이 유효성 검사 문구 추가
woowacourse-teams/2024-review-me pull request #434
Opened 2024-08-19 07:45 UTC by ImxYJL

- resolves #431 

---

### 🚀 어떤 기능을 구현했나요 ?
- 비밀번호 유효성 검증 훅을 분리했습니다.
- 비밀번호 Input에 onBlur 이벤트를 통해 사용자가 유효하지 않은 길이의 입력을 한 뒤 포커스를 옮기면 길이에 대한 에러 문구가 뜨도록 만들었습니다. 
- Input 컴포넌트에 onBlur 이벤트를 optional로 추가했습니다.

### 🔥 어떻게 해결했나요 ?
- 비밀번호 유효성 검증 훅
  - 역할/책임의 분리 측면도 있지만 비밀번호 검증을 다른 페이지에서도 사용하기 때문에 분리했습니다.
  - Input의 onBlur 이벤트 핸들러와 비밀번호 관련 에러 문구를 리턴합니다.
  - 비밀번호 입력이 변하고 블러 상태가 true일 때만 유효성 검증을 통해 에러 문구를 설정합니다.
 
### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 비밀번호 확인 모달에서도 onBlur를 사용해서 유효성 검증을 할까요?

### 📚 참고 자료, 할 말
- HomePage 폼 리팩토링 언제 하지

2024-08-19 08:14 UTC, chysis requested changes
고생했어요! 에러 메시지 문체를 수정하는 건 지금 변경이 필요할 것 같아서 RC 남깁니다!👍

2024-08-19 08:14 UTC, chysis commented on frontend/src/hooks/usePasswordValidation.ts
> +const PASSWORD_LENGTH_ERROR_MESSAGE = `${MIN_PASSWORD_INPUT}자부터 ${MAX_PASSWORD_INPUT}자까지 입력할 수 있습니다`;
에러 메시지도 `~요`체로 사용하고 있어서, 통일해주세요!

2024-08-19 08:14 UTC, chysis commented on frontend/src/pages/HomePage/components/URLGeneratorForm/index.tsx
> +const GROUP_DATA_LENGTH_ERROR_MESSAGE = `최대 ${MAX_VALID_REVIEW_GROUP_DATA_INPUT}자까지 입력할 수 있습니다`;
이 부분도 `~요`체로 수정해주세요!

2024-08-19 08:14 UTC, chysis commented on frontend/src/hooks/usePasswordValidation.ts
> +  const [hasBlurred, setHasBlurred] = useState(false);
blur 여부를 상태로 두어서 처음부터 에러 메시지가 뜨는 현상을 방지한 것 같아요. hasBlurred를 false로 만드는 코드가 현재 없는데(onFocus를 사용하고 있지 않기 때문) 위 현상을 방지하기 위한 목적으로만 사용한 것인지 궁금해요.

2024-08-19 08:34 UTC, soosoo22 approved these changes
훅 분리하느라 수고했어요!! 올리!

2024-08-19 08:36 UTC, BadaHertz52 commented on frontend/src/hooks/usePasswordValidation.ts
> +} from '../../src/pages/HomePage/utils/validateInput';
```suggestion
} from '@/pages/HomePage/utils/validateInput';
```
절대 경로 추천해요

2024-08-19 08:38 UTC, BadaHertz52 commented on frontend/src/hooks/usePasswordValidation.ts
> +  const [hasBlurred, setHasBlurred] = useState(false);
코드 컨벤션 회의때 boolean 타입인 변수는 is~로 시작하기로 했어요.

2024-08-19 08:39 UTC, BadaHertz52 commented on frontend/src/hooks/usePasswordValidation.ts
> +      setPasswordErrorMessage(PASSWORD_LENGTH_ERROR_MESSAGE);
```suggestion
      return setPasswordErrorMessage(PASSWORD_LENGTH_ERROR_MESSAGE);
```
요롷게 early return을 사용할 수 있어요.

2024-08-19 08:40 UTC, BadaHertz52 requested changes
has~로 시작하는 코드 컨벤션 관련 이슈가 있어서 request change 해요

2024-08-19 10:11 UTC, ImxYJL commented on frontend/src/hooks/usePasswordValidation.ts
> +} from '../../src/pages/HomePage/utils/validateInput';
오 아까 절대경로가 page를 못찾길래 한땀한땀 찾아갔는데... 🙃🙃 수정할게용

2024-08-19 10:20 UTC, ImxYJL commented on frontend/src/hooks/usePasswordValidation.ts
> +  const [hasBlurred, setHasBlurred] = useState(false);
초기값이 false고 이후에 true만 존재하는 이유가 인풋이 한 번 이상 blur됐는지만 처리하기 때문입니당
변수 이름이 hasBlurred인 것도 위와 같은 이유에서였습니다.(is~면 계속 변하는 상태 같아서) 
변수명은 has를 더 풀어서 isBlurredOnce정도로 바꿔보면 될 것 같은데 더 좋은 방법이 있을까요?

2024-08-19 12:50 UTC, BadaHertz52 commented on frontend/src/pages/HomePage/components/URLGeneratorForm/index.tsx
> +  //const [passwordErrorMessage, setPasswordErrorMessage] = useState('');
이 부분은 삭제할 예정인가요?

2024-08-19 12:50 UTC, BadaHertz52 commented on frontend/src/hooks/usePasswordValidation.ts
> +  const [hasBlurred, setHasBlurred] = useState(false);
한번 이상 블러됐는지 여부라면 isBlurredOnce가 더 좋아요

2024-08-20 02:06 UTC, BadaHertz52 commented on frontend/src/pages/HomePage/components/URLGeneratorForm/index.tsx
> +import { usePasswordValidation } from './../../../../hooks/usePasswordValidation';
리팩토링 할 예정이라면 리팩토링 시에 절대 경로 쓰는 것을 추천드려요

2024-08-20 02:07 UTC, BadaHertz52 approved these changes
올리 고생했어 🚀🚀🚀

2024-08-20 02:07 UTC, chysis approved these changes
변경 내용 확인했어요! `passwordValidation`을 훅으로 분리한 것 좋네요 👍

2024-08-20 02:07 UTC, merged