[BE] feat: 리뷰어 그룹 도메인 구체화, 정책 구현
woowacourse-teams/2024-review-me pull request #45
Opened 2024-07-18 10:32 UTC by skylar1220

- resolves #37 

---

### 🚀 어떤 기능을 구현했나요 ?
- 리뷰 작성과 관련한 리뷰어 그룹 검증을 추가했어요.
- 비회원이지만 리뷰어 그룹에 추가된 경우를 위한 깃헙 사용자 리뷰 그룹 엔티티를 생성했어요.
- 회원 엔티티에 깃헙 아이디 컬럼을 추가했어요.

### 🔥 어떻게 해결했나요 ?

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 생성한 커스텀 예외들이 적절한지 궁금해요.

### 📚 참고 자료, 할 말
- 리뷰 서비스가 점점 커져서 분리할 필요가 있어보여요.
- 테스트 given절도 점점 길어집니다..! Fixture 도입이 필요해요!

2024-07-18 11:48 UTC, donghoony requested changes
커비 고생했습니다 몇가지 제안사항 드립니다요 👍🏻

2024-07-18 11:48 UTC, donghoony commented on backend/src/main/java/reviewme/member/domain/Member.java
> +    @Column(name = "git_hub_id", nullable = false)
`github`는 하나의 고유명사니 붙여씁시다!
(찾아보니 `GitHub`라고 표현하는 게 기본인데, 하나의 단어로 취급하기도 하고, `gitHub`와 같이 한 곳만 대문자되어있는 게 어우러져보이지는 않네요 🤨)
모든 곳에서 `github`라고 작성하는 것을 제안해요.

2024-07-18 11:48 UTC, donghoony commented on backend/src/main/java/reviewme/member/domain/GitHubReviewGroup.java
> +public class GitHubReviewGroup {
적절한 테이블 도출 👍🏻 리뷰어가 여기에 대응될 테니 `GithubReviewerGroup`은 어떨까요?

2024-07-18 11:48 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/ReviewService.java
> +        }
이 로직 도메인에 내려가도 좋겠네요 🤔 (객체 관점에서 본다면요)
현재 상황이 Repo에게서 같은 그룹 정보인지를 확인한다 (getter와 같다고 보여요) -> 확인한 값이 `false`면 예외를 발생한다 와 같은 플로우라서,
`GithubReviewerGroup`에 존재하는가? 를 메서드로 물어보면 좋겠다고 생각해요. 다만 이 경우에는 일대다 매핑이 필요해 보이네요 😢

2024-07-18 11:48 UTC, donghoony commented on backend/src/main/java/reviewme/review/exception/GitHubReviewGroupNotFoundException.java
> +public class GitHubReviewGroupNotFoundException extends NotFoundException {
리뷰 그룹에 속하지 않는 사람이 그룹에 리뷰를 남기려고 하는 것은 `NotFound`를 내려주기보다는 `BadRequest`나 `UnAuthorized`에 가깝지 않을까요? (인증은 되었으나 인가의 문제)
메시지도 조금 보안과 관련되게 보수적으로 작성하면 좋겠어요 😁

2024-07-18 11:48 UTC, donghoony commented on backend/src/main/java/reviewme/review/exception/ReviewContentExistException.java
> +    public ReviewContentExistException() {
`ReviewAlreadySubmittedException` ?

2024-07-18 22:55 UTC, nayonsoso requested changes
수고했어요 커비~😘
테이블 추가하는게 복잡한 작업일 수 있었을 것 같은데 잘 해냈내요!! 👏👏

2024-07-18 22:55 UTC, nayonsoso commented on backend/src/main/java/reviewme/member/domain/GitHubReviewGroup.java
> +    private String gitHubId;
필드들에 컬럼 어노테이션 붙여주세요! 😊

2024-07-18 22:55 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/domain/Review.java
> +    @ManyToOne
👍👍👍👍👍

2024-07-18 22:55 UTC, nayonsoso commented on backend/src/main/java/reviewme/member/domain/Member.java
이것은 TODO 일수도 있지만 이 부분도 나중에 깃허브 연동하면
github_nickname 요런식으로 바뀌어야 하겠군요!

2024-07-18 22:55 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/exception/GitHubReviewGroupNotFoundException.java
> +public class GitHubReviewGroupNotFoundException extends NotFoundException {
아루루 말에 동의합니당~ 레포지토리 관점에서는 NotFound 라고 생각할 수도 있겠지만, 이건 권한의 문제에 더 가깝다고 생각합니다 ㅎㅎ 그래서 UnAuthorized 예외로 처리할 수 있을 것 같아요!

그리고 예외 메세지도 조금 추상적으로 가도 될 것 같아요. 지금은 너무 상세한 느낌!

2024-07-18 22:55 UTC, nayonsoso commented on backend/src/test/java/reviewme/review/ReviewServiceTest.java
>      void 리뷰를_작성한다() {
이 테스트 깨지는 것 같은데 확인해주세요!

2024-07-19 03:17 UTC, skylar1220 reviewed
반영 사항 다시 봐주세요~~

2024-07-19 03:17 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/member/repository/GitHubReviewGroupRepository.java
레포지토리 테스트를 추가해야할 것 같네요!

2024-07-19 03:17 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/member/domain/Member.java
> +    @Column(name = "git_hub_id", nullable = false)
뭔가 이름지으면서 찝찝했는데 확실히 하나의 단어로 하는 것이 좋겠네요👍

2024-07-19 03:17 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/member/domain/GitHubReviewGroup.java
> +public class GitHubReviewGroup {
대응하게 변경하는 게 좋겠네요!

2024-07-19 03:17 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/member/domain/GitHubReviewGroup.java
> +    private String gitHubId;
아차차 확인 고마워요 산쵸 👍

2024-07-19 03:17 UTC, hyeonji1220 commented on backend/src/test/java/reviewme/review/ReviewServiceTest.java
>      void 리뷰를_작성한다() {
리뷰 작성 테스트 시, 깃헙 사용자 그룹 데이터 저장 부분을 추가하지 않았군요! 테스트 터지는 거 확인 꼭 하겠습니당..😂

2024-07-19 03:17 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/member/domain/Member.java
사용자의 프로필을 아예 깃헙과 연동으로 처리한다면 그렇겠네요!

1. id, 프로필 사진은 깃헙, 이름은 설정할 수 있게
2. id, 프로필 사진 + 이름까지도 깃헙 닉네임과 연동

어떤 방법이 나을지 함께 얘기해보면 좋을 것 같아요!

2024-07-19 03:17 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/review/exception/ReviewContentExistException.java
> +    public ReviewContentExistException() {
"이미 리뷰를 작성한 경우 리뷰를 작성할 수 없습니다."라는 메세지와 좀 더 맞겠네요! 

다만, 
1. ReviewContent가 이미 있는 경우의 예외라, 엔티티 이름상으로는 ReviewContentAlreadySubmittedException가 맞는데
2. 하지만 이미 작성한 '리뷰'가 있다는 것으로, 의미상으로는 ReviewAlreadySubmittedException가 맞네요.

2024-07-19 03:17 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/review/exception/GitHubReviewGroupNotFoundException.java
> +public class GitHubReviewGroupNotFoundException extends NotFoundException {
아하 UnAuthorizedException가 더 적절하겠군요! 
메시지도 "리뷰어 그룹에 등록되지 않은 github 사용자입니다."로 수정하였습니다!

2024-07-19 03:17 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/ReviewService.java
> +        }
도메인 로직으로 내려보내는 것의 필요성 동감합니다!
GithubReviewerGroup이 포함하는 githubId들을 갖고있어서 GithubReviewerGroup한테 '너 이 깃헙 아이디 있어?' 하고 물어보면 좋을텐데...
우선은 양방향을 현재 건들이기는 어려우니 이슈로 남겨놓을게요! https://github.com/woowacourse-teams/2024-review-me/issues/49

2024-07-19 04:20 UTC, donghoony requested changes
아자아자 🔥

2024-07-19 04:20 UTC, donghoony commented on backend/src/main/java/reviewme/review/repository/ReviewRepository.java
> +    boolean existsByReviewerAndReviewerGroup(Member reviewer, ReviewerGroup reviewerGroup);
`default` 메서드는 아래로 내리는 건 어떤가요? (항상 아래로 내리자는 거 아닙니다)
- JPA에서 이미 `findByXX`를 지원합니다.
- 전체적인 Repository에서 get-을 사용하며, 이 동작은 항상 같습니다.
- 중요도를 생각해보았을 때, 존재하는 지 여부를 확인하는 메서드가 더 높다고 판단됩니다.

2024-07-19 04:20 UTC, donghoony commented on backend/src/test/java/reviewme/review/ReviewServiceTest.java
> +        reviewService.createReview(createReviewRequest);
1. 검증하고자 하는 메서드가 `createReview`이므로, 이를 given절에서 사용하는 것이 적절하지 않다고 생각해요. (저는 given에서는 해당 서비스를 사용하지 않고, 바깥 서비스나 Repository를 활용합니다)
2. 리뷰 중복을 확인하기 위한 메서드인데, 키워드 두 개, 답변 두 개 등 불필요한 given 코드가 존재해요. 어떤 것을 테스트하고 싶은지에 집중해서 코드를 작성하면 깔끔해질 거예요. 위쪽 메서드도 마찬가지입니다. (복붙 지양합시다 😄)

2024-07-19 04:20 UTC, donghoony commented on backend/src/test/java/reviewme/review/ReviewServiceTest.java
> +        reviewService.createReview(createReviewRequest);
```suggestion
        githubReviewerGroupRepository.save(new         githubReviewerGroupRepository.save(new GithubReviewerGroup("ted", reviewerGroup));
        reviewRepository.save(new Review(reviewer, reviewerGroup));
        CreateReviewRequest request = new CreateReviewRequest(
                reviewer.getId(), reviewerGroup.getId(), List.of(), List.of()
        );
```

2024-07-19 04:20 UTC, Kimprodp approved these changes
고생했슴니다!

2024-07-19 04:20 UTC, Kimprodp commented on backend/src/main/java/reviewme/member/domain/GitHubReviewGroup.java
> +package reviewme.member.domain;
코드 수정 사항에 없어서 여기다 코멘트 남길게요.

ReviewerGroup 도메인에서 `isDeadlineExceeded()` 메서드에 단순시 현재 시간을 파라미터로 전달받고 있는데요. 단순히 메서드 내부에서 `LocalDateTime.now()`를 해도 되지 않을까요?

2024-07-19 04:20 UTC, Kimprodp commented on backend/src/main/java/reviewme/member/domain/Member.java
산초의 코멘트에 대한 의견 : 깃허브 아이디랑 닉네임이 똑같지 않나요? 그럼 둘 중 하나만 있어도 될 것 같은데, 실명 정보가 따로 필요할까요?

2024-07-19 04:33 UTC, skylar1220 commented on backend/src/main/java/reviewme/member/domain/Member.java
제 기준 skylar1220이라는 것은 깃헙 기준 username이고 숫자로 된 unique한 id가 따로 있군요!(by 아루)
그렇다면 githubId, githubUserName을 갖게 하는 게 맞겠네요!

2024-07-19 04:41 UTC, skylar1220 commented on backend/src/main/java/reviewme/member/domain/GitHubReviewGroup.java
> +package reviewme.member.domain;
산초 작업 사항으로 제 버전에서는 반영 전 사항인 것 같습니다!

2024-07-19 04:43 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/repository/ReviewRepository.java
> +    boolean existsByReviewerAndReviewerGroup(Member reviewer, ReviewerGroup reviewerGroup);
중요도에 따른 정렬 적용하겠습니다👍

2024-07-19 04:49 UTC, donghoony commented on backend/src/main/java/reviewme/review/exception/GitHubReviewGroupNotFoundException.java
> +public class GitHubReviewGroupNotFoundException extends NotFoundException {
`권한이 없습니다`는 어떨까요? 인가되지 않은 사용자의 요청에 대한 메시지를 구체적으로 작성할 필요를 못 느꼈어요!

2024-07-19 04:54 UTC, skylar1220 commented on backend/src/test/java/reviewme/review/ReviewServiceTest.java
> +        reviewService.createReview(createReviewRequest);
1. 반영했습니다!
2. 복붙.. 맞습니다😂 잘 살펴볼게요!

2024-07-19 05:00 UTC, donghoony approved these changes
고생했습니다 !

2024-07-19 05:28 UTC, nayonsoso commented on backend/src/main/java/reviewme/member/domain/Member.java
맞습니다! 저도 github_nickname 은 nayonsoso 인데, 고유한 id 는 1330909287 요런식이었어요

2024-07-19 05:34 UTC, nayonsoso approved these changes
고생하셨습니다~ 😊

2024-07-19 05:37 UTC, merged