[BE] feat: GroupAccessCode를 암호화
woowacourse-teams/2024-review-me pull request #456
Opened 2024-08-20 02:58 UTC by donghoony

- resolves #443 

---

### 🚀 어떤 기능을 구현했나요 ?
- 해싱을 활용해 평문을 DB에 저장하지 않도록 했습니다.

### 🔥 어떻게 해결했나요 ?
- SHA-256 해싱을 적용했습니다.
- 검증 책임을 인코더에게 넘겼습니다. 어색한가요?
- 이에 따라 Embedded가 사라지고, 다시 원복됐어요.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 이해하기 쉬운지 모르겠네요 😕

### 📚 참고 자료, 할 말
- 영어 대소문자와 숫자로만 이루어져 있어 Rainbow table attack에 취약할 수 있습니다. salt와 같은 보안 강화 대책이 필요해요.

2024-08-20 02:58 UTC, donghoony commented
(테스트 작성 중)

2024-08-20 05:07 UTC, nayonsoso requested changes
일단 예외 패키지 부분만 코멘트 드렸습니다~ 🙇🏻‍♀️

2024-08-20 05:07 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/domain/exception/InvalidProjectNameLengthException.java
> +package reviewme.reviewgroup.domain.exception;
좋아용~

2024-08-20 05:07 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/domain/exception/InvalidRevieweeNameLengthException.java
> +package reviewme.reviewgroup.domain.exception;
좋아용~~

2024-08-20 05:07 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/domain/exception/ReviewGroupNotFoundByReviewException.java
> +package reviewme.reviewgroup.domain.exception;
이친구는 서비스에서 발생하는 데이터 정합성 예외라 service 아래에 있어야 하지 않을까요?

2024-08-20 05:07 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/domain/exception/ReviewGroupNotFoundByReviewRequestCodeException.java
> +package reviewme.reviewgroup.domain.exception;
이 친구도 서비스에서 발생시키는 예외라 서비스 아래에 있어야 할 것 같아요!

2024-08-20 05:07 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/repository/ReviewGroupRepository.java
> +    boolean existsByReviewRequestCodeAndGroupAccessCode(String reviewRequestCode, String groupAccessCode);
귣귣 ㅎㅎ

2024-08-20 05:07 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/domain/exception/ReviewGroupUnAuthorizedException.java
> +}
이 친구도 서비스에서 던지는 예외인 것 같아요!

2024-08-20 05:13 UTC, donghoony commented on backend/src/main/java/reviewme/reviewgroup/domain/exception/ReviewGroupUnAuthorizedException.java
> +}
슥삭 옮길게요~

2024-08-20 09:11 UTC, Kimprodp requested changes
상호 서비스간에 의존을 하는 finder를 사용해야하는가에 대한 고민이 많아지네요.. RC 확인 부탁드립니다!

2024-08-20 09:11 UTC, Kimprodp commented on backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupFinder.java
> +public class ReviewGroupFinder {
`ReviewService` 에서는 `Group`을 찾기 위해서 사용되고 있지만,
`ReviewDetailLookupService` 에서는 사용되지 않고 있어요. `Review `패키지의 서비스에서 `group`을 찾을 때 어떤 경우에는 사용하고 어떤 경우에는 사용하지 않는지 헷갈릴 것 같아요..

단순히 `groupAccessCode`를 검증해서 찾는 것이 `Group`의 책임이라 느껴져서 사용하는 것이라면 두가지 방식에 대한 제안이 있습니다!
1. `ReviewGroup`에 직접 물어보는 방식
2. `ReviewGroup `패키지에 `ReviewGroupAuthService`를 두고, 인증이 필요한 경로에서 `ArgumentResolver` 가 `ReviewGroupAuthService`로 그룹을 검증해서 찾아서 컨트롤러에 파라미터로 전달하는 방식 (`Review` 쪽 `Service`에서는 `ReviewGroup `연관이 없어짐)

2024-08-20 11:42 UTC, donghoony commented on backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupFinder.java
> +public class ReviewGroupFinder {
이 부분은 제가 확인을 못 했네요. 제 의도는 `Review` 패키지에서 `ReviewGroup` repository를 참조하지 않게 하는 것이 목적입니다. 다른 패키지니 API와 같이 서비스 레이어에서 주고받으면 좋을 것이라고 생각했어요.

2024-08-21 00:29 UTC, skylar1220 requested changes
짱짱 암호화 방식 새로 배워갑니다 총총😋😋
repo 의존에 대한 건 얘기 더 나눠봐요!

2024-08-21 00:29 UTC, skylar1220 commented on backend/src/main/java/reviewme/reviewgroup/repository/ReviewGroupRepository.java
> +    Optional<ReviewGroup> findByReviewRequestCodeAndGroupAccessCode(String reviewRequestCode, String groupAccessCode);
사용하지 않는 메서드네요!

2024-08-21 00:29 UTC, skylar1220 commented on backend/src/main/java/reviewme/reviewgroup/repository/ReviewGroupRepository.java
> +    boolean existsByReviewRequestCodeAndGroupAccessCode(String reviewRequestCode, String groupAccessCode);
여기도 마찬가지로 사용하지 않는 메서드네요!

2024-08-21 00:29 UTC, skylar1220 commented on backend/src/main/java/reviewme/auth/Encoder.java
java의 MessageDigest를 이용해서 해시코드를 생성할 수 있군요 알아갑니당😋😋

2024-08-21 00:29 UTC, skylar1220 commented on backend/src/main/java/reviewme/reviewgroup/service/GroupAccessCodeEncoder.java
> +    }
encdoe 로직 내부에서 코드의 형식 검증을 하는 것이 적절한지 고민이에요.
현재 encode는 리뷰 그룹 생성할 때, 비밀번호 check 할 때 두 곳에서 쓰입니다.
1. 리뷰 그룹 생성할 때는 사용자가 입력해 저장되기 전이기때문에 형식 검증을 하는 것이 당연히 맞다고 생각해요.
2. 하지만 비밀번호 check 할 때는 형식을 틀리게 입력해도 상관없습니당. 어차피 일치하는 groupAccessCode가 있는지 확인하기 때문이죠. 그렇기에 형식 검증이 이 경우에는 없어도 된다고 생각해요!

따라서, 리뷰 그룹 생성할 때만 형식 검증이 필요하니 
검증 로직을 encode할 때가 아닌 리뷰 그룹 생성 로직에만 넣는 것은 어떨까요?

2024-08-21 04:13 UTC, donghoony commented
#489 으로 마무리합니다, 패키지 이야기는 의논을 꾸준히 해 볼게요

2024-08-21 04:13 UTC, closed without merging