[FE] refactor: 서술형 필수 질문에 최소/최대 문구 안내 추가
woowacourse-teams/2024-review-me pull request #566
Opened 2024-09-04 05:59 UTC by ImxYJL

- resolves #559 

---

### 🚀 어떤 기능을 구현했나요 ?
- 서술형 필수 질문에 최소/최대 문구 안내를 추가했습니다.
- 2곳 이상에서 사용하는 상수를 별도의 constant 폴더로 분리했습니다.

### 🔥 어떻게 해결했나요 ?
`!optionGroup` 이면 TEXT 타입(주관식)이긴 한데 

```ts
if (!optionGroup && ... question.required){
  return `(최소 ${TEXT_ANSWER_LENGTH.min}자 ~ 최대 ${TEXT_ANSWER_LENGTH.max}자)`;
}
```

이렇게 체크를 하는 것보다는 `questionType === 'TEXT'`처럼 명시적으로 질문 타입을 체크하는 게 나은 것 같아 `questionType`을 추가로 가져왔습니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 이상한 곳 없는지 봐주세요~~

### 📚 참고 자료, 할 말

2024-09-04 08:33 UTC, chysis approved these changes
🔥👍

2024-09-04 08:40 UTC, soosoo22 approved these changes
빠르게 반영해주셨네요 고생했어요! 올리!!!

2024-09-05 00:55 UTC, BadaHertz52 commented on frontend/src/pages/ReviewWritingPage/form/components/QnABox/index.tsx
> +    if (!optionGroup) return;
optionGroup은 주관식에서는 null이고 객관식은 null이 아니라서, 앞에 주관식 조건문이 생겨서 이제   ```if (!optionGroup) return;```은 삭제해도 돼요.

2024-09-05 00:59 UTC, BadaHertz52 requested changes
주관식 안내문구 조건이 생기면서 필요없어진 코드가  있어요. 
코멘트 달아놨으니 해당 부분 확인하고 삭제해주세요.

2024-09-05 00:59 UTC, BadaHertz52 commented on frontend/src/pages/ReviewWritingPage/form/components/QnABox/index.tsx
> +    if (!optionGroup) return;
optionGroup은 주관식은  null이고, 객관식은 null값이 아니에요.
주관식에 대한 if 문이 생겼기 때문에 ```if (!optionGroup) return;``` 은 삭제해주세요.

2024-09-05 00:59 UTC, BadaHertz52 commented on frontend/src/pages/ReviewWritingPage/form/components/QnABox/index.tsx
> +    // NOTE: 객관식일 경우의 안내 문구 처리
NOTE 다음은 주관식에 대한 내용이기 때문에 해당 주석 삭제하거나 객관식에 대한 안내문구 코드쪽으로 옮겨주세요.

2024-09-05 00:59 UTC, BadaHertz52 commented on frontend/src/pages/ReviewWritingPage/form/components/QnABox/index.tsx
>    const multipleLGuideline = (() => {
안내문구가 기존에는 객관식에 대해서만 있었는데, 주관식이 생겨서 함수로 분리해도 좋겠네요

2024-09-05 01:07 UTC, ImxYJL commented on frontend/src/pages/ReviewWritingPage/form/components/QnABox/index.tsx
> +    if (!optionGroup) return;
`if (!optionGroup) return;`을 지우면 `const { minCount, maxCount } = optionGroup;`에서 에러가 나서 지우지 않았습니다. 대신 `if (!optionGroup)`을 주관식 가이드라인 설정의 if문으로 돌릴 수 있는데, 이 if문이 주관식을 처리한다는 게 직관적으로 보이지 않아서 일부러 `questionType === 'TEXT'`로 체크했었습니다. 
그런데 if문에 주석을 단다면 가독성 문제를 해결할 수 있을 것 같아 `if (!optionGroup) return;`을 주관식 if문으로 두었습니다!

2024-09-05 01:11 UTC, BadaHertz52 approved these changes
꿋!! 👍👍👍👍👍👍👍👍👍

2024-09-05 01:11 UTC, merged