[BE] test: Fixture 가 적용되지 않은 테스트 반영
woowacourse-teams/2024-review-me pull request #582
Opened 2024-09-08 02:30 UTC by Kimprodp

- resolves #581 

---

### 🚀 어떤 기능을 구현했나요 ?
- Fixture가 반영되지 않은 테스트를 찾아 반영했습니다.

### 🔥 어떻게 해결했나요 ?
- 산초의 Test Fixture 적용

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 이제 더이상 없겠죠?

### 📚 참고 자료, 할 말

2024-09-08 07:57 UTC, skylar1220 approved these changes
단순 제안 하나만 남겨서 approve할게요!
알잘딱깔센으로 필요없는 데이터 저장도 함께 다 삭제해주었네요👍

2024-09-08 07:57 UTC, skylar1220 commented on backend/src/test/java/reviewme/template/service/TemplateMapperTest.java
> +        ReviewGroup reviewGroup = reviewGroupRepository.save(리뷰_그룹());
(단순 제안) 서술형 필수 질문, 섹션이 없어도 해당 테스트 의도, 작동이 되어서 더 간단하게 만들 수 있을 것 같아요!

2024-09-08 07:59 UTC, nayonsoso requested changes
아주 간단한 부분 RC 드립니다.
그리고 TemplateMapperTest / TemplateServiceTest 가 @AutoWired 부분이 private 이 아닌 것 같은데, 그 부분도 private 달아주심 좋을 것 같아요~

2024-09-08 07:59 UTC, nayonsoso commented on backend/src/test/java/reviewme/question/repository/QuestionRepositoryTest.java
> +        Question question3 = questionRepository.save(서술형_필수_질문(3));
세션에 해당하는 질문 vs 세션에 해당하지 않는 질문을 비교할거면 question3 는 없어도 될 것 같아요!

2024-09-08 14:33 UTC, donghoony approved these changes
이쪽 제 담당이었는데 우선순위가 낮아 계속 밀렸네요 😢 테드 챙겨줘서 고맙습니다..!

2024-09-08 15:05 UTC, Kimprodp commented on backend/src/test/java/reviewme/question/repository/QuestionRepositoryTest.java
> +        Question question3 = questionRepository.save(서술형_필수_질문(3));
오잉 말을 이해 못했어요.🫥
지금 테스트는 단순히 질문 순서에 대한 테스트인데 어떤 부분을 말씀하시는 건가요?

2024-09-08 15:05 UTC, Kimprodp commented on backend/src/test/java/reviewme/template/service/TemplateMapperTest.java
> +        ReviewGroup reviewGroup = reviewGroupRepository.save(리뷰_그룹());
반영 완료 👍

2024-09-09 03:50 UTC, nayonsoso approved these changes

2024-09-09 03:50 UTC, nayonsoso commented on backend/src/test/java/reviewme/question/repository/QuestionRepositoryTest.java
> +        Question question3 = questionRepository.save(서술형_필수_질문(3));
앗차차 잘못 읽었던 것 같습니다...!

2024-09-09 04:30 UTC, merged