[BE] refactor: 예외별 로그 레벨을 재조정하고 로깅에서의 중복을 제거한다.
woowacourse-teams/2024-review-me pull request #592
Opened 2024-09-10 10:49 UTC by skylar1220

- resolves #

---

### 🚀 어떤 기능을 구현했나요 ?
- 예외별 로그 레벨을 재조정하고 로깅에서의 중복을 제거했습니다.

### 🔥 어떻게 해결했나요 ?
- BadRequestException, NotFoundException 로그 레벨을 info로 통일했습니다.
- UnexpectedRequestException를 BadRequestException으로 통합했습니다.
- 전반적으로 입력값을 로그에 넣어야하는데 누락된 경우에 입력값을 로깅에 추가했습니다. (예:TextAnswerIncludedOptionItemException 로그에 questionId 포함 필요)
- 사용하지 않는 예외를 삭제했습니다.
- 사용하지 않는 일급 컬렉션을 삭제했습니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 로그 레벨 논의한 것과 비교하여 새로 책정한 로그 레벨이 적절한지 봐주세요!

### 📚 참고 자료, 할 말
https://github.com/woowacourse-teams/2024-review-me/discussions/590

2024-09-10 10:55 UTC, donghoony requested changes
요구사항은 하나지만 좀 많이 바꾸셔야 할 듯 합니다,,, 🥲 우선 전체적으로 고생 많으셨슴다 🫡

2024-09-10 10:55 UTC, donghoony commented on backend/src/main/java/reviewme/global/exception/BadRequestException.java
> +        log.info(logMessage);
ㅎㅎ.. 어디에서 예외가 발생해야하는지는 알아야겠죠? `@Slf4j`가 어떤 역할을 해주는지를 학습해도 좋겠네요!

(기존)
<img width="1151" alt="image" src="https://github.com/user-attachments/assets/d3c07184-fd9f-4fd6-99f0-4669c8433d1e">

(해당 커밋)
<img width="1160" alt="image" src="https://github.com/user-attachments/assets/4fdfe0c9-c8b9-4aea-94a6-24d11ecee4d3">

2024-09-10 10:55 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/exception/TextAnswerIncludedOptionItemException.java
exception 전체에 `@Slf4j` 붙이고, 최상단에서 로깅하지 않고 각각 로깅하도록 바꾸면 어떨까요~

2024-09-10 11:27 UTC, skylar1220 commented on backend/src/main/java/reviewme/global/exception/BadRequestException.java
> +        log.info(logMessage);
log.info()를 찍는 곳의 클래스가 명시가 되는 군요!ㅎㅎㅎㅎ
😇😇😇😇😇😇
다시 다 바꿔놓을게요...ㅠㅠㅠㅠ

2024-09-10 11:28 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/review/service/exception/TextAnswerIncludedOptionItemException.java
그게 맞죠....😂

2024-09-10 12:03 UTC, donghoony approved these changes
좋슴다 👍🏻 매번 로그 때문에 고생이네요 우리,,,

2024-09-14 11:26 UTC, nayonsoso requested changes
### 1
아루가 말한 로그 위치는 저도 처음 알게 되었네요,, 😳
그런데 '하위 예외 클래스에서 로그 레벨을 정하는 것' 보다는 
**'상위 클래스에서 로그 레벨을 정하고 하위 클래스는 그 레벨에 따라 로깅하는 것'** 이 좋을 것 같아서 해결책을 생각해봤어요. 
찾아보니 로그를 남길 때, 레벨을 인자로 받아서 로깅하는 방법도 있더라고요. 아래와 같이요!

```java
@Slf4j
public abstract class ParentException extends ReviewMeException{

    protected static final Level level = Level.ERROR;

    protected ParentException(String errorMessage) {
        super(errorMessage);
    }
}
```
```java
@Slf4j
public class BabyException extends ParentException {

    public BabyException(String errorMessage) {
        super(errorMessage);
        log.atLevel(level).log(errorMessage);
    }
}
```

그리고 아래와 같은 컨트롤러를 만들어서 실험해봤더니,..
```java
@GetMapping("/sancho")
public void sancho() {
    throw new BabyException("어디에서 찍힐까~요?");
}
```

이렇게 자식 예외 클래스에서 찍혔다는 것을 확인할 수 있었습니다.
![image](https://github.com/user-attachments/assets/9691c92e-08e2-4e28-bf1b-bf45b73d2a8f)

이 방법을 사용해서 하나의 예외에 해당하는 하위 예외들의 로그 레벨을 통일해주는 것은 어떨까요?

---

### 2 
리뷰를 하며 전체적인 예외를 살펴봤는데, 아래 부분들도 이번 PR 에서 수정한다면 좋을 것 같아요!

**패키지가 올바른 위치에 있지 않은 예외**
MissingOptionItemsInOptionGroupException
InvalidTextAnswerLengthException 
OptionGroupNotFoundByQuestionIdException
SectionInTemplateNotFoundException
TemplateNotFoundByReviewGroupException

**테스트에서만 사용되는 예외**
ReviewGroupNotFoundByCodesException

---

혹시 다른 의견이시라면 코멘트 남기고 디코로 멘션 주세용~

2024-09-14 11:35 UTC, donghoony commented
@nayonsoso 

> '상위 클래스에서 로그 레벨을 정하고 하위 클래스는 그 레벨에 따라 로깅하는 것' 이 좋을 것 같아

상위 레벨에서 카테고리화한 것에 레벨을 붙이면 하위 레벨의 로그레벨 변경이 자유롭지 못하게 되지 않을까요? 🤔

2024-09-14 16:31 UTC, Kimprodp requested changes
'로그 레벨을 부모 예외 클래스에서 관리하자' 라는 의견에 대한 코멘트 디스코드에 보냈지만 기록용으로 코멘트 남길게요. 그리고 PR은 위 의견 충합되면 approve 할게요!

---

_**'상위 클래스에서 로그 레벨을 정하고 하위 클래스는 그 레벨에 따라 로깅하는 것'** 에 대한 의견 :_

부모 클래스의 클래스명(예외명)을 봤을 때, 이름만으로 해당 클래스에서 적용되는 로그 레벨이 이해가 된다면, 일관성 유지에 도움이 될 것 같다. (e.g BedRequestException 예외는 이름 그대로 '잘못된 요청' 이기 때문에 info가 적절함)

다만, 자식 클래스에서 예외적으로 로그 레벨을 변경할 수 있는 유연성을 제공한다 해도, 자식 클래스에서 로그 레벨을 다르게 해야 하는 상황이 온다면 이 예외의 부모 클래스가 적절한지 다시 확인해봐야 할 것 같음 (e.g. BedRequestException 예외의 자식 클래스가 warn이나 Error가 되어야 한다면? BadRequestException이 맞는가 ?)

물론 어떤 상황이 앞으로 나올지 모르기 떄문에 예상할 수는 없지만, 이런 예외적인 부분(자식클래스의 로그 레벨이 부모 클래스에서 정의된 로그 레벨과 다르게 적용되어야 하는 상황)이 많아진다면 오히려 로그 레벨을 관리하는 데 더 복잡해지고 인지하기 어려워 질 것 같음

결론) 부모 클래스에서 로그 레벨을 관리하고자 한다면, 자식 클래스에서 예외사항으로 로그 레벨을 변경할 수 있게 하지 말고(하지 못하게 막고), 변경해야 하는 상황이 온다면 부모 클래스가 적절한지 확인하고 부모 클래스를 변경하는 것을 고려한다면 좋은 방법이 될 것 같다. (적절한 부모 클래스가 없다면 새로운 부모 클래스를 생성)

2024-09-14 16:31 UTC, Kimprodp commented on backend/src/test/java/reviewme/review/service/module/ReviewMapperTest.java
> -    private  OptionGroupRepository optionGroupRepository;
하핫 👍

2024-09-15 06:55 UTC, skylar1220 commented
### 산초 의견에 대한 생각
1. 코드 레벨에 대해서 문제가 발생했고, 문제 발생에 따라서 논의를 했고, 그 결과로 이제는 info, error 중 어떤 걸 붙여야하는지 공유가 충분히 되었기에 해결되었다고 생각해요. 즉, 이미 해결된 문제에 대해 추가 시스템적 방법을 적용할 필요는 없다. 만약 또 발생하면 그 때 추가 방안을 생각해보자! 의 입장입니다ㅎㅎ

### 부모 예외에서 로그 레벨을 지정할 때 불편한 점

1. 부모 예외를 만들 때 이게 어떤 로그 레벨일지를 먼저 생각하고 정하고 만들어야한다는 게 어떤 자식이 추가될지 모르는데 정해놓고 시작하는 느낌이 들어요.

현재는 로그 레벨을 이 기준으로 나눠놨어요.

- info: 포스트맨 악성 요청 등으로 발생 가능해서 중요한 예외는 아닌 것
- error(추후 warn도): 내부에 의한 것

현재에는 부모 예외들이 갖는 자식 예외들이 모두 하나의 로그 레벨 기준에만 해당되어서 부모 클래스에서 하나의 로그레벨을 갖는 것이 가능해요.

- BadRequest:(포스트맨 악성 요청으로 발생 가능) 길이, 형식이 잘못된 요청
- NotFound:(포스트맨 악성 요청으로 발생 가능) db에 없는 값을 요청할 때
- DataInconsistency: (포스트맨 악성 요청으로 발생 불가) 내부 데이터 정합성이 어긋날 때

하지만, 추후에 생길 부모 예외가 갖는 자식 예외들이 악성 요청에 의해 발생할 수 있는 것(info), 내부에 의한 것(warn 또는 error) 이 2개 중에 하나의 상황으로 묶이지 않을 수 있다고 생각해요. 즉, 부모 예외를 만들 때 이게 어떤 로그 레벨일지를 먼저 생각하고 정하고 만들어야하는 상황이 어색하게 느껴집니다!

2. atLevel에 들어가있는 level이 뭔지 확인하러 왔다갔다해야한다는 번거로움도 있다고 느낍니다!

2024-09-15 07:13 UTC, skylar1220 commented
@nayonsoso 
> 패키지가 올바른 위치에 있지 않은 예외
 
라고 생각한 이유가 무엇인지 궁금합니다!
몇 개 살펴보다보니 이런 결론들이 나와서 산초가 올바른 위치가 아니라고 생각한 이유를 들어보고 싶어요!

`MissingOptionItemsInOptionGroupException`
OptionGroup이 OptionItem을 하나라도 안 갖고있는 건 도메인적인 예외라고 생각해요!

`InvalidTextAnswerLengthException`
: textAnswer의 길이가 잘못된 것은 도메인적 예외라고 생각해요!

2024-09-15 13:32 UTC, nayonsoso commented
제가 패키지가 잘못되었다 판던헌 이유는,
예외는 의미보다 **'어디에서 호출되는가'를 기준으로** 나뉘어야 한다 생각했기 때문입니다. 그래야 패키지의 순환등이 문제가 생가지 않을 것이라 생각했습니다😲

2024-09-16 01:01 UTC, skylar1220 commented
@산초 패키지 순환참조 등을 고려했을때 호출되는 위치가 기준이 되겠군요!
나머지는 반영하였는데 아래의 예외들은 호출되는 위치를 고려하더라도 현재가 적절하다고 생각하는데요~
산초가 아래 예외들이 패키지 위치가 적절하지 않다고 생각한 이유가 궁금해요!

1. `InvalidTextAnswerLengthException`
- 패키지 위치: package reviewme.review.domain.exception;
- 사용되는 위치: package reviewme.review.service.module.TextAnswerValidator

review.service 패키지애서 text응답을 검증하면서 사용되기때문에 review.domain 패키지에 위치
 
<br>

2. `SectionInTemplateNotFoundException`
- 패키지 위치: package reviewme.template.domain.exception;
- 사용되는 위치: package reviewme.template.service.module.TemplateMapper;
template.service 패키지에서 templateSection 도메인의 속성인 template과 연관된 section을 찾을 수 없는 상황에 쓰이므로, template.domian 패키지에 위치

<br>

3. `TemplateNotFoundByReviewGroupException`
- 패키지 위치: package reviewme.template.domain.exception;
- 사용되는 위치: 
   - package reviewme.review.service.module;
   - package reviewme.template.service.module;

리뷰가 템플릿을 봐야하므로 review, template 두곳에서 모두 호출하는 예외라면 템플릿 패키지에 놓는 게 적절

2024-09-16 06:23 UTC, nayonsoso commented
저는 각각의 케이스를 따지기보다, **예외가 호출되는 위치**만을 고려했어요.

커비의 코멘트 중에서 아래 부분들을 보면
커비의 예외 패키지 위치 기준이 ‘_도메인의 속성과 관련되어있는 것이라면 domain.exception 에 위치해야 한다_’ 인 것 같아요.
> review.service 패키지애서 **text응답을 검증하면서 사용되기때문에** review.domain 패키지에 위치
> template.service 패키지에서 **templateSection 도메인의 속성**인 template과 연관된 section을 찾을 수 없는 상황에 쓰이므로, template.domian 패키지에 위치

그런데 도메인의 생성자에서 터지는 예외가 아닌 것들은, ‘도메인의 속성’이라기보다 ‘비지니스 정책’에 가깝다 생각해요. 
그래서 더더욱 service 에서 터지는 예외들은 service.excpetion 에 있어야 하고,
도메인의 생성자에서 터지는 예외들만 domain.exception 에 있어야 한다는 생각이에요!

2024-09-18 03:30 UTC, Kimprodp approved these changes
확인 완료 어프룹할게요~

2024-09-18 03:53 UTC, donghoony commented
산초 완전인정이오
산: 열정적인 산초
초: 고생했습니다

2024-09-19 00:39 UTC, nayonsoso approved these changes

2024-09-19 08:02 UTC, merged