[BE] refactor: 패키지 `mapper`, `validator` 분리
woowacourse-teams/2024-review-me pull request #598
Opened 2024-09-12 02:50 UTC by donghoony

- resolves #597 

---

### 🚀 어떤 기능을 구현했나요 ?
- `module` 패키지는 너무 광범위한 의미를 가져 폴더명만으로 뜻을 추론하기 어렵습니다. 보다 구체적인 네이밍을 통해 패키지를 분리합니다.

### 🔥 어떻게 해결했나요 ?
- 코드와 테스트를 옮겼습니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 다 옮겼겠죠 ??

2024-09-12 03:49 UTC, Kimprodp approved these changes
깔꼼하네요~ 👍

2024-09-12 03:50 UTC, Kimprodp commented
추가로 Template Service 부분도 module -> mapper로 하면 좋을 것 같습니다~

2024-09-14 07:23 UTC, skylar1220 approved these changes
안그래도 늘어나면 나눠야겠다고 생각했는데 빠르다 빨라👍

질문) 이렇게 나누고보니 service 패키지에 다른 애들은 다 service인데 Generator가 섞여있는 기분이 들어요. 각 하나씩밖에 없으니 나중에 더 늘어나면 패키지 분리를 생각해보는 게 좋으려나요?

2024-09-14 11:33 UTC, nayonsoso requested changes
구구구구구굳!
불편함을 느끼는 부분 PR 올려주는 아루 짱 좋습니다🥹

---

그리고 ReviewPreviewGenerator는 ReviewListMapper 에서만 사용되는 것 같은데, 
mapper 패키지 안으로 옮기는게 좋을 것 같어요~
혹시 다른 의견이시라면 디코로 멘션 주세요!

2024-09-19 08:05 UTC, donghoony commented
어휴 컨플릭~

2024-09-19 11:21 UTC, donghoony commented
rebase + force push 했슴다!

2024-09-19 11:27 UTC, skylar1220 approved these changes
변경사항 확인했어요👍👍

2024-09-19 15:15 UTC, nayonsoso approved these changes
어푸! 어푸! 🤿 어푸루루루룹!

2024-09-20 07:17 UTC, merged