[BE] chore: flyway 설정
woowacourse-teams/2024-review-me pull request #601
Opened 2024-09-12 04:49 UTC by skylar1220

- resolves #516 

---

### 🚀 어떤 기능을 구현했나요 ?
- DB Schema 파일을 생성하고, Flyway를 적용하였습니다.

### 🔥 어떻게 해결했나요 ?
- schema.sql을 추가했습니다.
   - 실제 작동에는 영향을 주지 않지만 명시용으로 추가해주었습니다.
- flyway 의존성 및 applicaion-dev.yml에 설정을 추가해주었습니다.
- develop의 ddl-auto를 validate로 변경하였습니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- secret의 develop 브랜치에 적용되어있는 applicaion-dev.yml 파일도 한번 봐주세요~

### 📚 참고 자료, 할 말
- 현재에는 설정만 추가해놓은 것이고, 스키마에 변경이 필요한 경우가 생기면 V1 sql 파일을 처음으로 생성하여 정상 동작하는지 확인할 수 있습니다.
- 위의 정상동작이 확인되면 prod 환경에도 flyway 설정을 추가할 계획입니다.

2024-09-14 11:39 UTC, nayonsoso commented
구구구구구굳! 
![image](https://github.com/user-attachments/assets/4f05ad71-2320-4224-b44a-95fb3d1940c9)


secret의 develop 브랜치에 적용되어있는 applicaion-dev.yml 파일도 확인 완료했습니다🫡
테이블 변경이 있을 때 dev 먼저 적용해보고 문제 없으면 prod 에 적용하는 플로우도 이해완 했습니다

2024-09-14 11:40 UTC, nayonsoso approved these changes
구구구구구굳! 
플라이웨이 공부하시고 적용하시느라 수고하셨습니다☺️
![image](https://github.com/user-attachments/assets/4f05ad71-2320-4224-b44a-95fb3d1940c9)


secret의 develop 브랜치에 적용되어있는 applicaion-dev.yml 파일도 확인 완료했습니다🫡
테이블 변경이 있을 때 dev 먼저 적용해보고 문제 없으면 prod 에 적용하는 플로우도 이해완 했습니다

2024-09-14 12:55 UTC, donghoony requested changes
한 번 확인해주시면 감사하겠슴다 👍🏻  고생했어요!

2024-09-14 12:55 UTC, donghoony commented on backend/src/main/resources/schema.sql
> +    visible_type          ENUM ('ALWAYS','CONDITIONAL') NOT NULL,
기존 테이블은 Hibernate가 만들어줘서 Enum을 가지고 있지만, 추가적으로 유연하게 진행하기 위해서는 ENUM 대신 VARCHAR로 두는 건 어떨까요? DB가 어플리케이션을 의존하고 있다고 보여지기도 해요~! 어차피 어플리케이션에서는 Enum이 String으로 들어가니깐요 😁

2024-09-14 12:55 UTC, donghoony commented on backend/src/main/resources/schema.sql
> +DROP TABLE IF EXISTS text_answer CASCADE;
DROP은 조금 위험하지 않을까요 🤔 단순한 명시 목적이면 이 부분은 없어도 좋겠네요!

2024-09-14 15:53 UTC, Kimprodp approved these changes
시크릿 레포 설정파일도 모두 확인했습니다. 고생했어요 ~~ 👍👍

2024-09-14 15:53 UTC, Kimprodp commented on backend/src/main/resources/schema.sql
> +DROP TABLE IF EXISTS text_answer CASCADE;
명시 목적에서 드랍사용 이유가 궁금합니다!

2024-09-15 00:38 UTC, skylar1220 commented on backend/src/main/resources/schema.sql
> +    visible_type          ENUM ('ALWAYS','CONDITIONAL') NOT NULL,
코멘트를 보고 Java에서의 enum을 DB에서 관리하는 방법에 대해 생각해봤어요~ 새삼 중복 데이터가 있는 구조라는 생각이 들어서 3번 참조테이블 방법도 떠올랐는데, 데이터 규모가 크지 않다면 Varchar 타입이 간단하겠네요! 

### 1. Enum 타입
#### 장점
- varchar에 비해서 저장 용량이 적고, 조회가 빠름 → 근데 우린 @Enumerated(EnumType.STRING)라서 이 장점이 없음
#### 단점
- enum이 추가, 변경되면 DDL이 변경되어야함. 

### 2. Varchar 타입
#### 장점
- 인덱스 적용하면 조회 성능도 챙길 수 있어서 간단한 구조로 하기 좋음
#### 단점
- 데이터 중복 발생, 이로인해 저장 공간이 더 많이 들게됨

### 3. 참조 테이블을 만드는 방법
#### 장점
- 데이터 중복을 없앨 수 있다. 저장공간이 절약됨.
- enum에 해당하는 데이터가 추가되거나 수정될 때 참조테이블만 수정하면 되니 변경에 대응하기 쉽다.
#### 단점
- 조회할 때마다 join이 일어나야한다.
- 테이블이 늘어나 구조가 복잡해진다.

2024-09-15 00:39 UTC, skylar1220 commented on backend/src/main/resources/schema.sql
> +DROP TABLE IF EXISTS text_answer CASCADE;
만약 처음부터 schema.sql로 스키마를 생성했다면...을 가정해서 넣은 부분인데,
위험성이 더 있겠네요. 반영완료!

2024-09-15 00:40 UTC, skylar1220 commented on backend/src/main/resources/schema.sql
> +DROP TABLE IF EXISTS text_answer CASCADE;
만약 처음부터 schema.sql로 스키마를 생성했다면...을 가정해서 넣은 부분인데, 위험성이 더 있겠네요. 제거했어요!

2024-09-15 01:44 UTC, donghoony commented on backend/src/main/resources/schema.sql
> +    visible_type          ENUM ('ALWAYS','CONDITIONAL') NOT NULL,
DDL보다는 어플리케이션단에서 추가하는 개 더 유연하겠습니다 👍

2024-09-15 01:46 UTC, donghoony approved these changes
학습하느라 고생했어요~ 공유 부탁합니다 흐흐

2024-09-15 01:48 UTC, merged