[BE] feat: 토큰을 사용해 리뷰 조회
woowacourse-teams/2024-review-me pull request #615
Opened 2024-09-14 15:17 UTC by donghoony

# 아직 구현 안 했습니다 !

이런 식으로 하면 어떨까? 하고 우선 뼈대 코드를 올려봅니다. API 수정 사항이기도 해서, API 문서가 나올 수 있을 정도로만 작업했어요.

변경 사항을 커밋을 따라가며 확인해주세요. 몇 가지 애매한 부분은 주석과 리뷰에서 적어둘게요!

2024-09-14 15:19 UTC, donghoony commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
>              @PathVariable long id,
요건 나중에 구현되면 지워질 예정입니다.

2024-09-14 15:19 UTC, donghoony commented on backend/src/main/java/reviewme/review/controller/ReviewRequestCodeArgumentResolver.java
> +        // WebConfig가 Repository를 알게 됩니다
이쪽 한 번만 의논해 주세요! 저는 Repository가 들어오면 의존성이 복잡해질 것 같아 서비스에서 검증 한 번 하는 게 낫다고 생각해요 !

2024-09-14 15:19 UTC, donghoony commented on backend/src/test/java/reviewme/api/ReviewApiTest.java
> +    void 토큰으로_자신이_받은_리뷰_한_개를_조회한다() {
`./gradlew build`의 결과로 생기는 `/resources/static/docs/index.html`을 확인해주세요!

2024-09-16 07:40 UTC, skylar1220 commented on backend/src/test/java/reviewme/api/ReviewApiTest.java
> +    void 토큰으로_자신이_받은_리뷰_한_개를_조회한다() {
오호 해당 파일에 반영이 되는군요!

2024-09-16 10:53 UTC, skylar1220 requested changes
아루 고생했어여어어어어~~~
api 문서 선행 개발이 이런거구나 싶었어요🤩

2024-09-16 10:53 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/review/controller/ReviewRequestCodeArgumentResolver.java
> +               parameter.getParameterType().equals(String.class);
String 타입으로 한 번 더 제한을 두는 건 생각 못했네요👍

2024-09-16 10:53 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/controller/ReviewRequestCodeArgumentResolver.java
> +        // WebConfig가 Repository를 알게 됩니다
토큰을 ReviewRequestCode로 변환해주는 역할은 여기서하고, 컨트롤러에서 받아서 유효한 코드인지 검증은 서비스에서 한다는 얘기겠죠? 안그래도 현재 방식이 서비스에서 검증하는 방식이고, 이걸 유지하는 것이 좋다고 생각합니다~

의존성도 걸리고, 추후 유지 보수를 생각해보았을 때도 
'리뷰 요청 코드 검증에 대해서 수정할 사항 있는데 어딜 봐야할까?' ArgumentResolver보다는 Service가 먼저 떠오를 거라 직관적이라고 생각해요!

2024-09-16 10:53 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +    }
이전에 v2를 만들었을 때, v1은 두고 v2를 만들어서 백엔드의 변경 사항이 먼저 있어도 프론트가 v2에 대한 준비가 되기 전까지 v1이 잘 동작하도록 해놓았었던 기억이 나요~  이번에도 같은 상황같은데 vx라고 표현이 되어있어서 어떤 의도인지 궁금해요!

2024-09-16 10:53 UTC, skylar1220 commented on backend/src/docs/asciidoc/review-detail.adoc
detail, list 모두 rest docs가 웹에서 잘 보입니다👍

2024-09-16 10:53 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +    @Deprecated(since = "1.0.2", forRemoval = true)
오오 뭔가 자바 공식 문서에서 봤을 것 같은 @Deprecated!! 이렇게 적용해 볼 수 있겠군요 뭔가 멋있..ㅋㅋㅋㅋ

2024-09-16 10:53 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +    }
기존에 헤더에 담아오던 GroupAccessCode가 빠진 이유가 있을까요?

2024-09-16 11:04 UTC, donghoony commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +    }
v3으로 가야 할 정도일까.. 생각되긴 하네요 🤔

2024-09-16 11:05 UTC, donghoony commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +    }
코드로 받아오게 되면 `groupAccessCode`가 필요없게 됩니다, 추가 API로 비밀번호 입력 시 토큰 발급이 생기게 되겠죠 ?

2024-09-18 23:09 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +    }
하긴 기능이 바뀌거나 추가된 게 아니라 토큰만 추가된 거니까 v3이라기엔 작은 변화긴하네요ㅎㅎ
근데 별개로 vx는 어떤 뜻인가요..? 몰라서 물어봄..

2024-09-18 23:15 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +    }
아하 /v2/groups/check 👈 요 비밀번호 확인 api 이후에 reviewRequestCode를 통한 토큰이 생기고,
그럼 이미 groupAccessCode(비밀번호)에 대한 검증까지 끝난 인증된 사용자라는 걸 토큰을 주고받으면서 아니까,
이 부분에서 groupAccessCode를 받아서 검증할 필요가 없다는 거군요! 이해 완🫡

2024-09-19 00:16 UTC, donghoony commented on backend/src/main/java/reviewme/review/controller/ReviewController.java
> +    }
v3으로 올리는 것에 대한 합의가 안 돼서, 우선 x버전이라고 임의로 넣어 두었어요. api 버전이 올라갈 필요성은 느끼긴 하는데,,, 고민이네요 ㅋㅋ

2024-09-19 08:06 UTC, donghoony commented
#600 세션을 적용하게 돼 이 부분은 반려되었습니다. API 먼저 구현하길 정~말 잘 했어요 ㅜㅜㅜ

2024-09-19 08:06 UTC, closed without merging