[BE] refactor: DB 접근을 최소화 하도록 개선
woowacourse-teams/2024-review-me pull request #617
Opened 2024-09-15 02:17 UTC by Kimprodp

- resolves #571 

---

### 🚀 어떤 기능을 구현했나요 ?
- 반복적으로 DB 접근이 있는 로직이 존재하여, 성능 개선을 위해 DB 접근을 최소화 할 수 있도록 개선했습니다.

### 🔥 어떻게 해결했나요 ?
- 반복문 이전에 필요한 자원을 모두 찾아서 전달하는 방식으로 했습니다.
- DB 조회 대신 스트림 연산이 발생하여, Map 형태로 전달하는 방식으로 변경했습니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 1. ReviewDetailMapper에 있는 주석은 이해를 위해 남겨두었습니다. 리뷰 반영 후 삭제 예정입니다.
- 2. ReviewListMapper 변경점에 커밋을 보면 첫번째(DB 접근 최소화)와 두번째(스트림 연산 최소화) 방식 중 어느것이 더 선호되는지 알려주세요. (가독성은 첫번째가 더 좋아보입니다.)

### 📚 참고 자료, 할 말
- 구현한 방식이 픽스되면 repo에 추가된 쿼리 테스트 작성할게요!

2024-09-16 05:40 UTC, skylar1220 requested changes
리팩토링에 신경쓰는 테드 배워야겠다...
질문 몇 개 남겼는데 확인 부탁해여~~

2024-09-16 05:40 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/review/service/module/ReviewDetailMapper.java
> +        }
(제가 헷갈린 걸수도 있어서 다시 한 번 체크해주세요!)
List<QuestionID> questionIds로 optionGroup을 가져왔고, 그걸 갖고 map을 만든게  Map<Long, OptionGroup> optionGroupsByQuestion입니다!
그렇다면 questionIds 중 하나를 뽑아서 optionGroupsByQuestion의 key로 조회하면 value가 없을 상황은 없다고 생각하는데 이 예외처리가 있어야하는 이유가 있을까요?

(ps. 빙글빙글 고려할 게 많아 어려운 예외 처리😂)

2024-09-16 05:40 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/question/repository/QuestionRepository.java
> +            LEFT JOIN template_section ts
inner join을 고려해볼 수 있지 않을까요?

2024-09-16 05:40 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/question/repository/QuestionRepository.java
> +            SELECT q.* FROM question q
q.id로 명시하는 게 좋겠습니다! 다른 repo에 있는 부분도 동일해요.
(저번에 q.*로 했다가 Question의 다른 long 타입인 position을 가져왔던 오류가 기억나요..😂)

2024-09-16 05:40 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/module/ReviewDetailMapper.java
> +        Set<Long> selectedOptionIds = review.getAllCheckBoxOptionIds();
Set이라 뒤에 contains가 있어도 시간복잡도가 O(n)👍

2024-09-16 05:40 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/module/ReviewDetailMapper.java
> +                .collect(Collectors.groupingBy(OptionItem::getOptionGroupId));
이 부분을 따로 뺄 수 있으면 좋을텐데 방법이 뭐가 없을까요... 저도 고민 좀 해보겠습니다😂

2024-09-16 05:40 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/module/ReviewListMapper.java
> ReviewListMapper 변경점에 커밋을 보면 첫번째(DB 접근 최소화)와 두번째(스트림 연산 최소화) 방식 중 어느것이 더 선호되는지 알려주세요. (가독성은 첫번째가 더 좋아보입니다.)

DB 쿼리 횟수는 둘 다 한 번으로 동일합니다.
연산횟수는 
1번 방법은 categoryOptionItems 갯수(강점옵션 5개) + 선택한 카테고리 optionItem(최대 2개) 갯수 
2번 방법은 checkBoxOptionIds 갯수(사용자가 작성시 선택한 옵션의 총합 최대 6개)이므로 크게 차이가 없어보여요!
그래서 가독성 좋은 1번이 더 낫지 않은가싶은데, 혹시 제 계산에서 틀린 부분이 있으면 알려주세요!

2024-09-19 08:52 UTC, nayonsoso reviewed
음~ 👩‍🍳 이라고 코멘트를 단 것은
'다소 가독성이 떨어지지만 저도 다른 개선방법을 생각해내기 어려워서 한 리액션'이었습니다.

---

그리고 바꾼 코드에 스트림 연산이 워낙 많더라고요..😓
**그래서 'DB 연산을 줄이고 스트림 연산을 늘리는 것 vs DB 연산을 늘리는 것' 중에서 뭐거 더 성능이 좋은지를 
과거 테드의 코드와 지금 PR 의 테드 코드로 간단하게 테스트를 해봤습니다.**

테스트 환경을 간단히 설명하자면,
h2 / 테스트 데이터셋 10000개정도 넣고 시작 / 이전 ReviewDetailMapper 와 지금 테드가 수정한 것 둘 다 10000번 호출 후 시간 측정
테스트 파일: [링크](https://github.com/woowacourse-teams/2024-review-me/blob/be/refactor/571-db-access-logic-refactor-test/backend/src/test/java/reviewme/sanchoTest/PerformanceTest.java)

![image](https://github.com/user-attachments/assets/3e4b79cf-b67d-4737-8596-1be86f5ad6c7)
그랬더니 확실히 바꾼 버전이 더 성능이 좋다는 것 확인했습니다👍
잘 바꾼 것 같아요👼🏻

2024-09-19 08:52 UTC, nayonsoso commented on backend/src/main/java/reviewme/question/repository/QuestionRepository.java
> +            ON sq.section_id = ts.section_id
[진짜 모르겠어서 하는 질문]
LEFT_JOIN 썼네요!
그런데 왜 LEFT_JOIN 인가요?

2024-09-19 08:52 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/repository/ReviewRepository.java
> +    List<Review> findAllByGroupId(long reviewGroupId);
함수명 변경 좋네요🙋🏻‍♀️

2024-09-19 08:52 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/module/ReviewDetailMapper.java
> +                        optionGroupsByQuestion, optionItemsByOptionGroup))
음~👩‍🍳 인자 여섯개!

2024-09-19 08:52 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/module/ReviewDetailMapper.java
> +                .stream()
음~ 👩‍🍳 3연 스트림!

2024-09-19 16:03 UTC, nayonsoso approved these changes

2024-09-20 01:13 UTC, donghoony requested changes
우선 하나 보내드립니다! 수고했어요요

2024-09-20 01:13 UTC, donghoony commented on backend/src/main/java/reviewme/question/repository/OptionItemRepository.java
> +            JOIN option_group og
`JOIN`, `LEFT JOIN`이 혼용되고 있네요. 이유가 있을까요?

2024-09-20 01:13 UTC, donghoony commented on backend/src/main/java/reviewme/review/repository/ReviewRepository.java
>      @Query("SELECT r FROM Review r WHERE r.reviewGroupId=:reviewGroupId ORDER BY r.createdAt DESC")
이번에 변경된 사항은 아니지만, """로 쿼리 감싸면 보기 좋겠어요~!

2024-09-20 01:13 UTC, donghoony commented on backend/src/main/java/reviewme/question/repository/OptionGroupRepository.java
> +            """, nativeQuery = true)
네이티브 쿼리 테스트 추가해주세요!

2024-09-20 01:13 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/module/ReviewDetailMapper.java
> +                .collect(Collectors.toMap(OptionGroup::getQuestionId, optionGroup -> optionGroup));
`optionGroup -> optionGroup` 대신 `Function::identity`는 어떨까요?

2024-09-20 12:10 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/service/module/ReviewDetailMapper.java
> +        }
다시 확인했습니다~ 없어도 될 것 같아요! 꼼꼼하군요👍👍

2024-09-21 02:17 UTC, skylar1220 commented on backend/src/main/java/reviewme/question/repository/QuestionRepository.java
> +            SELECT q.* FROM question q
앗 이건 long 타입이 아니라 question 타입이군요 잘못된 리뷰 죄송..ㅎㅎ

2024-09-21 02:29 UTC, skylar1220 commented
다른 RC 사항은 더 없는데요!
ReviewDetailMapper의 mapToReviewDetailResponse 메서드의 데이터 가져오는 부분 고민 쫌 더 해보고 
ReviewListMapper 방식이 1, 2번 중 결정되면 approve할게요~~~

2024-09-21 06:36 UTC, Kimprodp reviewed
리반완

2024-09-21 06:36 UTC, Kimprodp commented on backend/src/main/java/reviewme/question/repository/OptionItemRepository.java
> +            JOIN option_group og
이전에 사용했던 부분을 그대로 쓰다 보니 섞인 것 같네요. join으로 모두 통일했습니다요

2024-09-21 06:36 UTC, Kimprodp commented on backend/src/main/java/reviewme/question/repository/QuestionRepository.java
> +            LEFT JOIN template_section ts
쪼인으로 통일

2024-09-21 06:36 UTC, Kimprodp commented on backend/src/main/java/reviewme/question/repository/QuestionRepository.java
> +            ON sq.section_id = ts.section_id
이전에 사용했던 부분을 그대로 쓰다보니 섞인 것 같네요. join으로 모두 통일했습니다요

2024-09-21 06:36 UTC, Kimprodp commented on backend/src/main/java/reviewme/question/repository/QuestionRepository.java
> +            SELECT q.* FROM question q
question 객체를 반환하고 있는데 어떤 부분을 말씀하시는건가요??

2024-09-21 06:36 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/repository/ReviewRepository.java
>      @Query("SELECT r FROM Review r WHERE r.reviewGroupId=:reviewGroupId ORDER BY r.createdAt DESC")
반영 완료 👍

2024-09-21 06:36 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/service/module/ReviewDetailMapper.java
> +                .collect(Collectors.toMap(OptionGroup::getQuestionId, optionGroup -> optionGroup));
오우 몰랐네요 굿👍

2024-09-21 06:36 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/service/module/ReviewListMapper.java
가독성이 좋다고 하나 산초의 테스트를 보고 꿈 참게되네요, 생각보다 성능이 많이 개선되는 것 같아요. 우선 이렇게 가보고 가독성도 챙길 수 있는 방법이 있다면 다시 고민해보죠 👍👍

2024-09-21 06:36 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/repository/ReviewRepository.java
> +    List<Review> findAllByGroupId(long reviewGroupId);
산초의 미친 테스트 결과 감사합니다 (❁´◡`❁)

2024-09-21 06:36 UTC, Kimprodp commented on backend/src/main/java/reviewme/question/repository/OptionGroupRepository.java
> +            """, nativeQuery = true)
사용 중인 네이티브 쿼리에 대해 작성되지 않은 테스트들이 몇 개 더 있어서 싹다 테스트 작성했습니다~

2024-09-21 06:47 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/module/ReviewListMapper.java
앗 산초의 테스트는 reviewDetail에 대해서 1. 테드 리팩토링 전 2. 테드 리팩토링 후를 측정한 것이라,
여기서 고민하는 reviewList 1, 2번 방법과는 다른 문제인 것 같아요!

2024-09-21 06:53 UTC, donghoony approved these changes
아싸 이제 추상화랑 곁들여서 먹어보겠습니다 고생했어요 😋

2024-09-21 09:30 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/module/ReviewListMapper.java
하나의 리뷰 그룹에 대해 리뷰 목록을 조회하는 경우를 테스트해봤어요.


![스크린샷 2024-09-21 오후 6 24 25](https://github.com/user-attachments/assets/40f86714-555b-45bd-8975-38e6a2bef6b3)


이상하게도 스트림 연산이 많은 2번이 더 빠르더라고요. 이건 적은 스트림 연산 차이라 다른 조건들의 영향이 오히려 컸을 수도 있다는 걸로 감안해야할 것 같아요.
결과가 왜 반대인지는 모르겠지만 어쨌든 두 방법이 1회 조회시 4ms 밖에 차이가 나지 않아요. 

1000회씩 반복한 결과를 테스트하지 않고 1회 조회 결과로 비교한 이유는,
리뷰 목록을 조회하려는 사용자가 동시에 1000명이어도 db connection이나 쓰레드풀 갯수 내라면 어차피 이 메서드는 동시에 실행될 수 있다 → 1000번의 반복한 결과의 차이를 보는 것이 아니라 1번 실행 결과 차이가 실제 사용자가 느끼는 차이라고 생각했기때문이에요!

결론)
사용자가 느낄 시간차이가 미미하니 가독성이 좋은 1번으로 가자!

테스트 파일: [링크](https://github.com/woowacourse-teams/2024-review-me/blob/be/refactor/571-db-access-logic-refactor-test/backend/src/test/java/reviewme/sanchoTest/PerformanceTest2.java)

2024-09-22 01:33 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/service/module/ReviewListMapper.java
>이상하게도 스트림 연산이 많은 2번이 더 빠르더라고요.

DB접근 개선만 한 방식이 더 빠르다는거죠?
결과적으로 이 방식이 속도도 더 빠르고 가독성도 좋으니 1번 방식으로 하자는 말씀으로 이해했습니다!
좋은 테스트 결과 공유 감사해요 😊

2024-09-22 01:36 UTC, Kimprodp commented
@skylar1220 
1번 방식 (DB 접근 최소화만 적용)의 커밋만 롤백했어요. 확인 부탁합니다~

2024-09-22 01:39 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/module/ReviewListMapper.java
앗 아뇨 빠르기는 2번이 더 빠른데 미미하니 가독성 좋은 1번으로 가자였습니다😅

2024-09-22 01:46 UTC, skylar1220 requested changes
ㅎㅎ진짜 이거 한번만 더 확인 부탁해여 테드😂😂😂

2024-09-22 01:46 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/mapper/ReviewListMapper.java
> +                .toList();
categoryOptionItemsByReview를 만들고 그걸로 response를 만들지않고,
한번의 스트림으로 바로 response까지 만들 수 있겠어요! 깔꼼깔꼼!!

```suggestion
        List<ReviewCategoryResponse> categoryResponses = categoryOptionItems.stream()
                .filter(optionItem -> checkBoxOptionIds.contains(optionItem.getId()))
                .map(optionItem -> new ReviewCategoryResponse(optionItem.getId(), optionItem.getContent()))
                .toList();
```

2024-09-22 01:58 UTC, skylar1220 approved these changes
수고했어여 테드~~~ 수테수테~~👏👏👏
Mapper 실행 초반에 DB에서 냅다 데이터 가져와서 map으로 만드는 부분 덩어리는 나중에 쫌 더 고민해볼게요ㅎㅎ (이슈 등록해놨어요!)

2024-09-22 02:00 UTC, merged