[FE] feat: 리뷰 홈 페이지 반응형 구현
woowacourse-teams/2024-review-me pull request #633
Opened 2024-09-18 17:19 UTC by soosoo22

- resolves #625 

---

### 🚀 어떤 기능을 구현했나요 ?
- media 유틸을 사용해서 모바일, 태블릿, 데스크탑 환경에서의 리뷰 홈 페이지 반응형을 구현했습니다.
- 홈 페이지 내 AlertModal도 반응형으로 구현했습니다.
- 모바일 기기, 특히 아이폰 미니처럼 화면이 작은 디바이스를 고려해서, 425px과 320px 두 가지 브레이크포인트로 세세하게 반응형 스타일을 적용했습니다.

### 🔥 어떻게 해결했나요 ?

### 홈 페이지
화면의 너비가 768px 이하일 경우, 캐러셀을 보여주는 영역과 리뷰 정보 입력 폼을 세로로 배치했습니다.
- width - 768px 이하 : 캐러셀과 리뷰 폼이 세로로 배치
- width - 768px 초과 : 데스크탑 등 큰 화면에서는 기존과 같이 가로로 배치
<div>
<img width="400" alt="스크린샷 2024-09-19 오전 2 07 12" src="https://github.com/user-attachments/assets/de635486-19b2-475a-8778-ca6c327d95c6">
<img width="400" alt="스크린샷 2024-09-19 오전 2 11 42" src="https://github.com/user-attachments/assets/01b58679-9d08-4533-8a23-0d27820ffa4c">
</div>

### AlertModal
왼쪽 이미지는 비교적 작은 사이즈의 아이폰 5/SE에서의 AlertModal입니다. 화면 크기에 맞춰 모달 크기가 작아졌기 때문에 링크 복사 버튼을 "리뷰 요청 URL" 옆으로 배치했습니다.
- width - 768px 이하 : 복사 버튼이 "리뷰 요청 URL" 옆에 표시되도록 했습니다.
- width - 768px 초과 : 원래대로 모든 요소가 일렬로 표시됩니다. (리뷰 요청 URL => 링크 => 복사 버튼 순)

<div>
<img width="400" alt="스크린샷 2024-09-19 오전 1 43 41" src="https://github.com/user-attachments/assets/e8873ac9-10a9-4ac1-8e39-fd19159df138">
<img width="400" alt="스크린샷 2024-09-19 오전 1 48 43" src="https://github.com/user-attachments/assets/c5477f11-91e9-49b8-86a6-5a456f6ac15a">
</div>

`리뷰 요청 URL` 옆에 `CopyTextButton`을 하나 더 추가하고, 기본적으로 `display: none`으로 설정되어 있다가 화면 너비가 `768px 이하`로 줄어들면 `display: block`으로 변경되게끔 코드를 추가했습니다.
```tsx
    <S.ReviewZoneURLModal>
       <S.ModalTitle>아래 요청 URL을 확인해주세요</S.ModalTitle>
       <S.ReviewZoneURLModalItem>
         <S.RequestURLContainer>
           <S.DataName>리뷰 요청 URL</S.DataName>
           <CopyTextButton targetText={reviewZoneURL} alt="리뷰 공간 페이지 링크 복사하기" />
         </S.RequestURLContainer>
        <S.Data>{reviewZoneURL}</S.Data>
        <CopyTextButton targetText={reviewZoneURL} alt="리뷰 공간 페이지 링크 복사하기"></CopyTextButton>
      </S.ReviewZoneURLModalItem>
```

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 반응형 스타일이 적절하게 적용되었는지 확인해 주세요~

Q. 캐러셀 영역에 `리뷰미, 이렇게 사용해요`와 리뷰 입력 폼에 `함께한 팀원으로부터 리뷰를 받아보세요`가 수평이 안 맞아서 약간? 이상한 것 같은데 아무래도 하는게 좋겠죠..??
<img width="820" alt="스크린샷 2024-09-19 오전 2 11 42" src="https://github.com/user-attachments/assets/080d72ec-aa6b-4720-b0af-d1598569d1df">

### 📚 참고 자료, 할 말
- 확실히 캐러셀과 리뷰 입력 폼을 가로로 배치하는게 예쁜 것 같네요. 세로로 배치하니 리뷰 입력 폼 양옆에 빈공간이 너무 두드러지게 보이는 듯 해서 아쉽네요. 반응형 쉽지 않네.....🥹

2024-09-19 06:01 UTC, ImxYJL commented
아직 수정된 media 반영이 안 된 것 같아 일단 여기에만 코멘트 남깁니다ㅎㅎ

캐러셀 구역과 폼 구역이 가로 배치일 때 label 수평이 안 맞는 문제는 둘이 아예 다른 역할을 하고 있고 레이아웃이 똑같은 것도 아니라 수평을 맞춰줄 필요는 없다고 생각합니다.

아래는 건의사항입니다~~

- 캐러셀 구역과 폼 구역이 세로로 배치될 때, 폼 구역의 margin-top이 좀 더 있었으면 좋겠어요.
- URL 모달
  - 복사 버튼을 반응형으로 화면이 작을 때만 label 옆에 붙는데, 화면이 클 때도 이런 레이아웃이면 좋겠어요!
    그러면 굳이 버튼을 2개 사용하면서 display: none을 해 줄 필요가 없고 무엇보다 이 쪽이 더 자연스러운 레이아웃이라고 생각합니다.
  - 복사 버튼의 사이즈도 화면이 작아지면 더 작게 줄어들었으면 좋겠어요

2024-09-19 07:05 UTC, BadaHertz52 commented on frontend/src/pages/HomePage/components/ReviewMeOverview/styles.ts
> +  ${media.xxSmall`
위에 media.xxSmall이 있는데 여기에 다시 media.xxSmall로 gap을 준 이유가 있나요?

2024-09-19 07:05 UTC, BadaHertz52 commented on frontend/src/pages/HomePage/components/ReviewMeOverview/styles.ts
> +    font-size: 2.4rem; // theme.fontSize.medium 추후 사용
현재 media 유틸에서 theme 사용 가능합니다

2024-09-19 07:18 UTC, BadaHertz52 requested changes
홈페이지 캐러셀 반응까지 작업하느라 고생 많았어요 쑤쑤
해당 브랜치 풀 받아서 반응형 확인했어요. 👍

다음 사항에 대해서 봐야할 것 같아 request changes 남겨요

### media 유틸에 theme 적용
media 유틸 수정본이 머지 되면서 이제 media에 theme 사용이 가능해졌어요. theme 을 사용할 수 있는 부분은 theme을 사용했으면 해요

이거는 지금 반영하지 않아도 되지만 한번 생각해봤으면 하는 거에요. 

### 모바일에서 슬라이드 동작으로 캐러셀 움직이는 기능

모바일 반응형이 추가되었고 425px 이하에서는 캐러셀의 좌우 화살표 버튼이 사라졌으니 , 홈의 캐러셀에 슬라이드로 카드를 이동하는 기능 구현을 한 번 생각해 보면 좋겠네요.

2024-09-19 08:10 UTC, chysis requested changes
![image](https://github.com/user-attachments/assets/e1731cb8-7584-4b68-8a9f-49a2acbe519f)
▲ review zone url이 두 줄로 보여질 때, 경고 문구가 버튼과 딱 붙어 보이는 현상을 발견했어요.

![image](https://github.com/user-attachments/assets/cd43ba81-7026-44c5-83ce-09a9705d18e5)
height가 18rem으로 고정되어 있어 생긴 문제로 판단됩니다. 고정 높이를 넘어서게 되어 버튼과 딱 붙게 되었는데, height 속성을 제거하는 것을 제안해요!

2024-09-19 14:09 UTC, soosoo22 commented on frontend/src/pages/HomePage/components/ReviewMeOverview/styles.ts
> +  ${media.xxSmall`
첫 번째 media.xxSmall은 img 태그 안에서 적용되고 있고, 두 번째 media.xxSmall은 OverviewTitleContainer 안에서 적용되고 있어요.

```css
export const OverviewTitleContainer = styled.div`
  display: flex;
  gap: 1.3rem;
  align-items: center;
  justify-content: center;

  img {
    width: 7rem;
    height: 7rem;

  /* 중간 생략 */

    ${media.xxSmall} {
      width: 3.5rem;
      height: 3.5rem;
    }
  }

  ${media.xxSmall} {
    gap: 0.6rem;
  }
`;
```

2024-09-19 14:10 UTC, soosoo22 commented on frontend/src/pages/HomePage/components/ReviewMeOverview/styles.ts
> +    font-size: 2.4rem; // theme.fontSize.medium 추후 사용
적용 완료!

```css
  ${media.medium} {
    font-size: ${({ theme }) => theme.fontSize.medium};
  }
```

2024-09-20 07:29 UTC, BadaHertz52 commented on frontend/src/pages/HomePage/components/ReviewMeOverview/styles.ts
> +  ${media.xxSmall`
아하!

2024-09-20 07:32 UTC, ImxYJL approved these changes
수정사항까지 반영하느라 고생 많았어요~!

2024-09-20 07:32 UTC, BadaHertz52 approved these changes
수정 사항들 반영된거 확인했어요 🚀🚀🚀🚀🚀

2024-09-20 07:32 UTC, chysis approved these changes
피드백 반영한 것 확인했어요 :) 리뷰미의 첫인상이 더 좋아지겠네요

2024-09-20 07:33 UTC, merged