[BE] refactor: 필수가 아닌 질문이 작성되지 않을 경우 저장하지 않도록 변경
woowacourse-teams/2024-review-me pull request #641
Opened 2024-09-19 15:14 UTC by Kimprodp

- resolves #640 

---

### 🚀 어떤 기능을 구현했나요 ?
- 이슈의 내용을 참고해주세요.

### 🔥 어떻게 해결했나요 ?
- ReviewMapper에서 필수가 아닌 질문이 답변되지 않을 경우 매핑하지 않도록 변경했습니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 헛점이 없는지 확인해주세요!

### 📚 참고 자료, 할 말
- 제대로 확인하겠습니다..

2024-09-20 02:08 UTC, skylar1220 requested changes
니코내코니~~
죄송합니다 앞으로 더 잘 볼게요..ㅋㅋㅋㅋㅋㅋ

2024-09-20 02:08 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/review/service/module/ReviewMapper.java
> +        if (question.isRequired() || !answerRequest.text().isEmpty()) {
answerRequest.text()가 null일 경우 NPE가 납니다~ 이 경우도 고려해줘야겠네요!

2024-09-20 02:08 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/review/service/module/ReviewMapper.java
> +        if (question.isRequired() || !answerRequest.selectedOptionIds().isEmpty()) {
answerRequest. selectedOptionIds()가 null일 경우 위와 동일하게 NPE가 납니다~ 이 경우도 고려해줘야겠네요!

2024-09-20 02:08 UTC, skylar1220 commented on backend/src/test/java/reviewme/review/service/module/ReviewMapperTest.java
> +    }
선택형인 질문에 값이 들어간 경우, 선택형인 질문에 빈값이 들어간 경우를 넣고 값이 있는 질문만 저장되었는지 확인하는 게 적절해보여요! 그럼 이렇게 객관식 데이터는 없어지고, 선택형 빈값 o,x 에 따른 데이터가 필요해지겠네요!
```suggestion
    @Test
    void 필수가_아닌_질문에_답변이_없을_경우_답변을_생성하지_않는다() {
        // given
        ReviewGroup reviewGroup = reviewGroupRepository.save(리뷰_그룹());

        Question requiredTextQuestion = questionRepository.save(서술형_필수_질문());
        Question optionalTextQuestion = questionRepository.save(서술형_옵션_질문());
        Question optionalEmptyTextQuestion = questionRepository.save(서술형_옵션_질문());

        Section section = sectionRepository.save(항상_보이는_섹션(
                List.of(requiredTextQuestion.getId(), optionalTextQuestion.getId())));
        templateRepository.save(템플릿(List.of(section.getId())));

        String textAnswer = "답".repeat(20);
        ReviewAnswerRequest requiredTextAnswerRequest = new ReviewAnswerRequest
                (requiredTextQuestion.getId(), null, textAnswer);
        ReviewAnswerRequest optionalTextAnswerRequest = new ReviewAnswerRequest
                (optionalTextQuestion.getId(), null, textAnswer);
        ReviewAnswerRequest optionalEmptyTextAnswerRequest = new ReviewAnswerRequest
                (optionalEmptyTextQuestion.getId(), null, "");
        ReviewRegisterRequest reviewRegisterRequest = new ReviewRegisterRequest(reviewGroup.getReviewRequestCode(),
                List.of(requiredTextAnswerRequest, optionalTextAnswerRequest));

        // when
        Review review = reviewMapper.mapToReview(reviewRegisterRequest);

        // then
        assertThat(review.getTextAnswers())
                        .extracting(TextAnswer::getQuestionId).containsExactly(requiredTextQuestion.getId(), optionalTextQuestion.getId());
    }
```

2024-09-25 08:18 UTC, nayonsoso requested changes
수고 많았습니다~😊

2024-09-25 08:18 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/module/ReviewMapper.java
> +        if (question.isRequired() || !answerRequest.text().isEmpty()) {
@skylar1220 

사실 지금 프론트에서 '답변하지 않은 텍스트 문항'에 대해서 `""` 라는 문자열을 보내주기 때문에, text가 null일 시나리오는 없긴 합니다. 

그런데 제가 적었지만, 이건 너무 프론트 의존적인 생각인 것 같아요. 이런 맥락을 모르는 다른 개발자가 본다면 이해가 안될 코드일 것 같기도 하고요😅

그러니 `ReviewAnswerRequest`에 이런식의 상수 & 함수를 만들어서  '응답을 안할 때의 서술형 답변'을 검사하게 하는건 어떤가요?

```java
public record ReviewAnswerRequest(

        @NotNull(message = "질문 ID를 입력해주세요.")
        Long questionId,

        @Nullable
        List<Long> selectedOptionIds,

        @Nullable
        String text
) {
    private static final String NOT_ANSWERED_TEXT = "";

    public boolean isTextNotAnswered() {
        return NOT_ANSWERED_TEXT.equals(text);
    }
}
```

```suggestion
if (question.isRequired() || !answerRequest. isTextNotAnswered()) {
```

2024-09-25 08:18 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/module/ReviewMapper.java
> +        if (question.isRequired() || !answerRequest.selectedOptionIds().isEmpty()) {
이건 처리해줘야겠네요👍👍

2024-09-25 08:18 UTC, nayonsoso commented on backend/src/test/java/reviewme/review/service/module/ReviewMapperTest.java
> +        Question optionalTextQuestion = questionRepository.save(서술형_옵션_질문());
변수명 의미전달 짱짱 굳굳~

2024-09-25 08:18 UTC, nayonsoso commented on backend/src/test/java/reviewme/review/service/module/ReviewMapperTest.java
> +                (requiredTextQuestion.getId(), null, textAnswer);
```suggestion
        ReviewAnswerRequest requiredTextAnswerRequest = new ReviewAnswerRequest(
        requiredTextQuestion.getId(), null, textAnswer);
```

[완전 사소 / 반영 안해도 됨]

2024-09-25 08:18 UTC, nayonsoso commented on backend/src/test/java/reviewme/review/service/module/ReviewMapperTest.java
> +                        .extracting(TextAnswer::getQuestionId).containsExactly(requiredTextQuestion.getId()),
```suggestion
                () -> assertThat(review.getTextAnswers())
                        .extracting(TextAnswer::getQuestionId)
                        .containsExactly(requiredTextQuestion.getId()),
```
[짱사소 / 반영 안해도 됨]

2024-09-26 06:22 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/module/ReviewMapper.java
> +        if (question.isRequired() || !answerRequest.text().isEmpty()) {
dto로 넘기는 것 최고 좋은 생각 반완!!

2024-09-26 06:23 UTC, donghoony approved these changes
리뷰 도메인이 밉다😈

2024-09-26 06:27 UTC, nayonsoso approved these changes
테드와 그 후계자 커비 수고했습니다! 😁

2024-09-26 06:29 UTC, skylar1220 approved these changes
자힐
(TODO: 테스트 살짝 보완해야함)

2024-09-26 06:37 UTC, merged