[FE] 프로그레스 바 반응형으로 구현
woowacourse-teams/2024-review-me pull request #642
Opened 2024-09-19 15:14 UTC by chysis

- resolves #608 

---

### 🚀 어떤 기능을 구현했나요 ?
- 프로그레스 바를 반응형으로 구현했습니다.
- 큰 버전(medium 이상)과 작은 버전(small 이하)에서 보여줄 프로그레스 바의 UI 구조가 상당 부분 다르기 때문에 별도의 컴포넌트로 만들었습니다.

### 🔥 어떻게 해결했나요 ?
![image](https://github.com/user-attachments/assets/c9bfd7ee-94f0-4e66-b640-534e74701611)
▲ 큰 버전은 기존과 동일합니다. 

![image](https://github.com/user-attachments/assets/46c5cf77-52e9-43c3-bfe5-f93673dbb6f2)
![image](https://github.com/user-attachments/assets/33fd1544-2d63-4754-ba1d-da06686a4a8f)
▲ 작은 버전입니다. 현재 카드에 해당하는 버튼을 화면 중앙에 보여주고, 앞뒤로 카드가 남아 있다면 일부만 보여집니다.

![image](https://github.com/user-attachments/assets/fe0d2241-328d-4135-b7f7-87ec5d861bc5)
▲ 320px에서도 깨지지 않는 것을 확인했습니다.

### 기능 1. 현재 위치에만 집중할 수 있도록
- 모바일의 경우 한 눈에 모든 진행 상황을 파악하기 힘듭니다. 따라서 현재 카드에 해당하는 버튼이 항상 중앙에 위치하도록 했습니다.
- 앞뒤로 다른 카드가 있다면 해당하는 버튼의 일부가 보여집니다. 
- 현재 위치에 해당하는 버튼은 다른 버튼보다 1.1배 큽니다.

### 기능 2. 그래도 진행 상황을 보고 싶다면 스크롤
- 전체 진행 상황도 파악할 수 있도록 스크롤 가능합니다. 모바일 기기에서는 드래그 가능합니다.
- 조금 더 자연스러운 사용자 경험을 위해 `scroll-snap`을 적용했습니다. 어중간하게 버튼과 버튼 사이에서 스크롤이 멈추지 않고 버튼 단위로만 넘어갑니다 (아래 영상 참고).

https://github.com/user-attachments/assets/f877c5fb-6379-4c1f-a446-503478c8aa34

### 기능 3. 카드가 이동하면 프로그레스 바도 이동
- useRef와 scrollIntoView를 활용해 currentCardIndex가 변경될 때마다 해당하는 위치로 스크롤 되도록 구현했습니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 

### 📚 참고 자료, 할 말
- 현재 카드에 해당하는 버튼을 화면 중앙에 고정시키기 위해, 자리만 차지하고 보이지 않는 div를 앞뒤로 넣는 트릭을 사용했어요.

2024-09-20 05:01 UTC, BadaHertz52 commented on frontend/src/pages/ReviewWritingPage/progressBar/components/MobileProgressBar/styles.ts
> +interface StepButtonStyleProps {
프로그레스 바의 버튼 스타일에 대한 코드가 MobilePrgressBar, ProgressBar에서 중복으로 구현되어있네요.

프로그레스 바 버튼을 컴포넌트로 따로 빼서 두 프로그레스 바에서 사용하는 것은 어떨까요?

2024-09-20 05:10 UTC, BadaHertz52 requested changes
프로그레스 바 반응형으로 구현하느라 고생했어요 👏👏👏
에프이 코드 보면서 scroll 관련된 css 속성 공부도 하고 좋았어요 

해당 브랜치 풀 받아서 실행해봤는데, currentCardIndex가 변경될 때 해당 단계 프로그레 스 바 버튼이 가운데로 오지 않네요 🥲
![image](https://github.com/user-attachments/assets/0b5d8b43-779a-4591-bd87-bb724dc6b399)

코멘트로 남겼는데, ProgressBar, MobileProgressBar에서 반복되는 코드들을 컴포넌트로 분리하면 좋겠어요.

2024-09-20 05:47 UTC, soosoo22 reviewed
~~개인적으로 모바일 환경에서 프로그레스 바를 드래그로 움직일때, 첫번째 단계(카테고리 단계)에서 드래그를 많이 하면 마지막 단계(추가 리뷰 및 응원)로 넘어가게 돼요. 드래그를 일정 범위 이상 넘어가면 바로 다음 프로그레스 바로 넘어가게 하는 건 어떨까요? 한번에 2개의 프로그레스 바를 넘어가지 않게요.~~
사용자 입장에서는 프로그레스 바를 하나하나 넘기는 것보다는 전반적인 걸 한꺼번에 보는 게 더 괜찮을 것 같다는 의견에 납득 완료했습니다. 해당 의견은 철회합니다.

https://github.com/user-attachments/assets/15b2333d-2fd1-4264-81ec-e3c562aeb55e

2024-09-23 05:59 UTC, BadaHertz52 commented on frontend/src/pages/ReviewWritingPage/progressBar/components/MobileProgressBar/index.tsx
> +  useEffect(() => {
```suggestion
  useEffect(() => {
    if (stepRefs.current[currentCardIndex]) {
      const element = stepRefs.current[currentCardIndex];

      setTimeout(() => {
        element.scrollIntoView({
          behavior: 'smooth',
          inline: 'center',
        });
      }, 0);
    }
  }, [currentCardIndex, stepRefs]);
```

setTimeout을 사용하니, 다음 버튼 클릭 시 가운데로 오네요!! 😮
리뷰 작성 폼의 애니메이션과 프로그레스 바 애니메이션이 충돌 되어서 그런건지, 
정확한 이유는 모르겠네요 🥲

2024-09-23 06:00 UTC, BadaHertz52 commented on frontend/src/pages/ReviewWritingPage/progressBar/components/MobileProgressBar/index.tsx
> +  useEffect(() => {
GPT의 설명 첨부할게요

>카드가 처음 열릴 때 해당 요소가 아직 DOM에 완전히 렌더링되지 않았을 수 있습니다. 특히, React에서 상태가 변경되면서 비동기적으로 DOM이 업데이트되는데, scrollIntoView가 호출되는 시점에 해당 요소가 DOM에 아직 존재하지 않으면 작동하지 않을 수 있습니다.

2024-09-23 07:17 UTC, BadaHertz52 approved these changes
어려운 프로그레스 바 반응형 구현하느라 고생 많았어요 👏👏👏👏👏

모바일에서 잘 작동하는 거 확인했습니다 approve 할게요

2024-09-23 07:24 UTC, chysis commented on frontend/src/pages/ReviewWritingPage/progressBar/components/MobileProgressBar/styles.ts
> +interface StepButtonStyleProps {
컴포넌트로 따로 분리를 시도했으나 현재 `ProgressBar`과 `MobileProgressBar`의 StepButton 및 그 스타일 코드에 약간의 차이가 있어서 지금은 분리하지 않았습니다!

2024-09-23 07:39 UTC, ImxYJL reviewed
동적으로 움직이는 컴포넌트 구현하느라 고생이 많아요 😅
간단한 코멘트 몇 개 남겼어요 마지막까지 화이팅!

2024-09-23 07:39 UTC, ImxYJL commented on frontend/src/pages/ReviewWritingPage/progressBar/components/MobileProgressBar/index.tsx
> +        behavior: 'smooth',
만약 캐러셀에서도 비슷한 스크롤 코드를 사용한다면(아직 모르지만) scrollToTop처럼 별도로 분리해보면 좋을 것 같아욥

2024-09-23 07:39 UTC, ImxYJL commented on frontend/src/pages/ReviewWritingPage/progressBar/components/MobileProgressBar/index.tsx
> +      }, 0);
나중에 이런 함수들은 별도로 분리해서 이름을 지어주면 가독성이 더 좋아질 것 같아요~!

2024-09-23 07:39 UTC, ImxYJL commented on frontend/src/pages/ReviewWritingPage/progressBar/components/MobileProgressBar/styles.ts
> +  scroll-snap-type: x mandatory;
여기서 mandatory 속성을 준 이유가 궁금합니당

2024-09-23 07:39 UTC, ImxYJL commented on frontend/src/pages/ReviewWritingPage/progressBar/components/MobileProgressBar/index.tsx
> +            {index < stepList.length - 1 && <img src={NavigateNextIcon} alt="다음 화살표" />}
이렇게 꾸미는 용도에 가까운 이미지 파일에 alt는 비워 둬도 된다고 생각하는데, 나중에 접근성 미션을 하고 나서 얘기해봐도 될 것 같긴 하네요ㅋㅋㅋ

2024-09-23 07:39 UTC, ImxYJL commented on frontend/src/pages/ReviewWritingPage/progressBar/components/MobileProgressBar/styles.ts
> +  return defaultStyle(theme);
css 함수 분리 굿입니다~~~

2024-09-23 08:27 UTC, ImxYJL approved these changes
과연 리뷰미팀은 동적 프로그레스바를 완성해낼 수 있을 것인가..!

2024-09-25 06:00 UTC, chysis commented on frontend/src/pages/ReviewWritingPage/progressBar/components/MobileProgressBar/index.tsx
> +            {index < stepList.length - 1 && <img src={NavigateNextIcon} alt="다음 화살표" />}
단순히 꾸미는 용도에 가까워서 이미지 자체에 alt는 없어도 될 것 같아요.
대신 마지막 카드가 아닌 경우에는 '몇 개의 카드 중 몇 번째'와 같은 메시지를 따로 `role` 속성을 통해 부여할 수 있을 것 같네요 👍

2024-09-25 06:10 UTC, chysis commented on frontend/src/pages/ReviewWritingPage/progressBar/components/MobileProgressBar/styles.ts
> +  scroll-snap-type: x mandatory;
![image](https://github.com/user-attachments/assets/6beb3b7b-35f5-45c0-9ae9-080a75fb9987)
위 사진과 같이 깔끔하게 스냅이 되지 않는 경우를 막고, 항상 깔끔한 스냅만 일어나게 하기 위해 `mandatory` 속성을 추가했습니다.

2024-09-25 06:46 UTC, chysis commented
## 모바일 프로그레스 바의 변천사

처음 PR을 올렸을 때의 프로그레스 바에는 다음과 같은 문제가 있었어요.
- 프로그레스 바의 스크롤 애니메이션과 카드의 스크롤 애니메이션이 충돌하여 중간에 끊기거나 동작이 무시되는 현상
- 프로그레스 바 양쪽에 버튼의 끄트머리를 보여주기 위해 자동으로 계산된 값이 아닌 실험적으로 구한 값을 사용했기 때문에 align이 완전히 맞지 않는 문제

첫 번째 문제가 사용자 경험 상 굉장히 치명적이었기 때문에 다음과 같은 시도를 했습니다.

### 1. Carousel 컴포넌트 적용
- Carousel 컴포넌트를 적용해 보았습니다. 
- 하지만 기존과 같은 UI를 유지하기 위해 Carousel 컴포넌트에 style prop을 뚫어야 했습니다. flex 관련 속성이나 크기, 스크롤바 제거 등 여러 부가적인 스타일링을 Carousel에서 해야 했기 때문에 적절하지 않다고 판단했고, 재사용하지 않고 분리했습니다.

### 2. scrollIntoView가 아닌, 요소 크기 계산을 통해 translate 적용
- scrollIntoView를 사용하지 않고 스크롤을 직접 구현하기 위해 각 요소(ref)들의 width를 이용해 연산을 거치고, translate로 스크롤했습니다.
- 하지만 연산의 로직이 굉장히 복잡해졌고, 상대 크기를 사용해서 연산하기 때문에 이동을 반복할수록 오차가 커지는 문제가 생겼습니다.

### 3. 구현의 편리함과 UI 사이의 타협
- 우선 구현하는 것에 초점을 맞추어 UI을 일부 수정하는 방향으로 진행해보았습니다.
- StepButton의 끄트머리를 보여주는 대신 앞뒤로 다른 카드가 존재한다면 화살표를 보여주도록 했습니다.
![image](https://github.com/user-attachments/assets/a65342a9-07bf-49bf-b24c-b1941867c3b9)
![image](https://github.com/user-attachments/assets/76ceee2a-0b1c-48ad-b4fd-89dd9705e147)
- 이렇게 되면 스크롤하는 동안 화살표가 2개씩 보인다는 문제가 있습니다. 그러나 `scroll-snap`에 `mandatory` 속성을 지정했기 때문에 스냅이 깔끔하게 일어나서 우선 큰 문제가 되지는 않는다고 판단했습니다.

### 4. scrollIntoView 다시 데려오기
- 결국... `scrollIntoView`를 다시 데려왔습니다. 이 메서드는 브라우저 단에서 실행되고, translate와는 다른 레이어에서 처리되기 때문에 서로의 렌더링 사이클이 맞지 않을 수 있다는 문제가 있습니다.
- 위의 문제를 완화하기 위해 `useLayoutEffect`와 `requestAnimationFrame`, `cancelAnimationFrame`을 적용했습니다. 애니메이션 시점을 정밀하게 제어하고, 레이아웃 계산 완료 이후에 scrollIntoView를 실행해서 애니메이션이 끊김 없이 작동하도록 했습니다.
- 그럼에도 간헐적으로 애니메이션이 작동하지 않는 문제가 발생해서, setTimeout에 적절한 시간을 설정했습니다. 카드가 넘어가는 시간인 500ms를 설정했더니 너무 느렸고, 몇 번의 실험을 통해 너무 답답하지 않으면서도 씹힘 현상이 발생하지 않는 시간인 250ms로 설정했습니다.

### 앞으로의 숙제?
- 스크롤 중간에 화살표가 두 개씩 보이는 문제를 어떻게 해결할 수 있을지(이것도 UI의 일부분으로 보이도록 할지?)
- scrollIntoView를 다시 사용하긴 했지만 translate를 사용해서 문제를 깔끔하게 해결할 수 있는 방법을 찾아보기?

2024-09-25 07:13 UTC, BadaHertz52 requested changes
스크롤을 긴 터치 동작으로 하면 '>' 이 이미지가 두 개인 부분이 사용자 입장에서 버그처럼 느껴져서, 아래 처럼 바꿔봤어요
스크롤이 빠르면 가끔 두 개로 보여서 완벽하지는 않지만 한 번 고려해주세요

```tsx
//...
const [moveIndex, setMoveIndex] = useState<number | null>(null);

//..
useLayoutEffect(()=>{
//...  const scrollProgressBar = () => {
      setTimeout(() => {
        stepRefs.current[currentCardIndex].scrollIntoView({ behavior: 'smooth', inline: 'center', block: 'center' });
        setMoveIndex(null);
      }, 250);
      
},[])
//...
  const handleTouchMove = (index: number) => {
    if (moveIndex === index) return;
    setMoveIndex(index);
  };

  return (
    <S.ProgressBarContainer>
      <S.ProgressBar ref={progressBarRef}>
        {stepList.map((step, index) => (
          <S.StepWrapper
            key={step.sectionId}
            ref={(el) => (stepRefs.current[index] = el!)}
            $isCurrentStep={index === currentCardIndex}
            onTouchMove={() => handleTouchMove(index)}
          >
            {index > 0 ? (
              moveIndex === index ? (
                <span style={{ width: '24px', height: '24px' }}></span>
              ) : (
                <img src={NavigateNextIcon} alt="" />
              )
            ) : (
              <S.EmptyBlock />
            )}
            <S.StepButton
              $isDone={step.isDone}
              $isMovingAvailable={step.isMovingAvailable}
              $isCurrentStep={step.isCurrentStep}
              onClick={() => handleClick(index)}
              type="button"
            >
              {step.sectionName}
            </S.StepButton>
            {index < stepList.length - 1 ? (
              moveIndex === index ? (
                <span style={{ width: '24px', height: '24px' }}></span>
              ) : (
                <img src={NavigateNextIcon} alt="" />
              )
            ) : (
              <S.EmptyBlock />
            )}
          </S.StepWrapper>
        ))}
      </S.ProgressBar>
    </S.ProgressBarContainer>
  );
};
```

#### 동작 화면

https://github.com/user-attachments/assets/17f53ba5-5325-4097-9ec8-e63aef11435e

2024-09-26 02:09 UTC, BadaHertz52 approved these changes
브랜치 풀 받아서 모바일,태블릿에서 확인했어요 
깔끔하고 좋아요!!!! 프로그레스 바 반응형 작업하느라 정말 고생많았어요!!!! 

![MochiPeachGIF](https://github.com/user-attachments/assets/103111cd-5aba-40c4-9def-f01b05e6de19)

2024-09-26 02:16 UTC, soosoo22 approved these changes
지금 살짝 바쁜 관계로 일단 approve하겠습니다!
프로그레스 바 대장정이 이렇게 마무리되었네요! 정말 수고했어요 에프이!

2024-09-26 04:10 UTC, merged