[BE] 리뷰
woowacourse-teams/2024-review-me pull request #65
Opened 2024-07-19 14:02 UTC by donghoony

- resolves #64 

---

### 🚀 어떤 기능을 구현했나요 ?
- 응답으로 리뷰어의 정보를 보내지 않고, 리뷰 작성 시점을 추가로 보냅니다.

### 🔥 어떻게 해결했나요 ?
- ReviewResponse의 구조를 수정하고, TODO를 구현했습니다.
- 테스트가 활성화돼있지 않은 곳이 있어서 활성화하고 수정했습니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- Request-Response가 올바른 형식인지 확인해 주세요.

2024-07-21 13:11 UTC, skylar1220 approved these changes
요구사항에 맞게 수정이 잘 된 것 같아요! 주말 작업 수고 많았다..👍

2024-07-21 13:11 UTC, skylar1220 commented on backend/src/test/java/reviewme/review/ReviewServiceTest.java
>          CreateReviewContentRequest contentRequest = new CreateReviewContentRequest(
이번 변경 내용은 아니나, 이 부분은 해당 테스트에 필요하지 않은 given절인 것 같아 제거하면 좋을 것 같네요!

2024-07-22 04:47 UTC, Kimprodp requested changes
아루 고생했습니다~ 전체적으로 요구사항에 맞게 잘 작성하신 것 같아요.
코멘트 부분만 확인 부탁할게요!

2024-07-22 04:47 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/service/ReviewService.java
> +        Review review = reviewRepository.save(new Review(reviewer, reviewerGroup, LocalDateTime.now()));
`validateIsDeadlinePassed(reviewerGroup)` 내부에서 `LocalDateTime.now()`을 통해 데드라인을 검증하고 있는데요.
`LocalDateTime.now()`를 두 번 사용하는 것 보다 변수로 뽑아서 사용하는 것은 어떨까요?

2024-07-22 04:47 UTC, Kimprodp commented on backend/src/test/java/reviewme/review/ReviewServiceTest.java
service 패키지에서 빠진 것 같아요!

2024-07-22 04:53 UTC, donghoony commented on backend/src/test/java/reviewme/review/ReviewServiceTest.java
oops 이동했어요~

2024-07-22 04:56 UTC, donghoony commented on backend/src/test/java/reviewme/review/ReviewServiceTest.java
>          CreateReviewContentRequest contentRequest = new CreateReviewContentRequest(
수정했어요`

2024-07-22 22:34 UTC, nayonsoso commented
> 아루 고생했습니다~ 전체적으로 요구사항에 맞게 잘 작성하신 것 같아요. 코멘트 부분만 확인 부탁할게요!

테드 이거 리뷰어님 같아요..

2024-07-22 22:48 UTC, nayonsoso approved these changes
아루 수고했어요~
다른분들이 꼼꼼히 남겨주셔서 더 리뷰할게 없네요 ㅎㅎ
그대로 Approve 할게요!!

2024-07-23 05:36 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/ReviewService.java
> +        Review review = reviewRepository.save(new Review(reviewer, reviewerGroup, LocalDateTime.now()));
추후 수정 하겠읍니다.. 🥹

2024-07-23 05:36 UTC, Kimprodp approved these changes
(*/ω＼*)

2024-07-23 05:41 UTC, nayonsoso approved these changes
🐴

2024-07-23 05:41 UTC, merged