[BE] 세션을 활용해 리뷰를 조회한다.
woowacourse-teams/2024-review-me pull request #666
Opened 2024-09-23 06:09 UTC by donghoony

# 아직 구현 안 했습니다

지금 모킹을 통한 API 문서만 적용해둔 상태에요. `./gradlew clean build`를 통해 문서 확인해주세요 ~

2024-09-23 23:59 UTC, skylar1220 requested changes
MockMvc 쓰면서 세션 포함 테스트하느라 수고했어여😂😂
필터로 문제 해결한 것 다시봐도 대단해용 문제해결력 따봉!!
rest doc 관련한 거 몇 개만 확인해주세여~~

2024-09-23 23:59 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/review/service/dto/request/ReviewAuthRequest.java
> +        @NotBlank(message = "리뷰 요청 코드를 입력하세요.")
여기 개행 추가해야겠네요😋

2024-09-23 23:59 UTC, hyeonji1220 commented on backend/src/test/java/reviewme/api/ApiTest.java
> +            sessionCookie.setHttpOnly(true);
질문)
프로덕션에 httpOnly 같은 설정은 나중에 하게되나요?
프로덕션엔 없는데 왜 테스트에는 httpOnly 등의 설정을 해준 건지 궁금해요!

2024-09-23 23:59 UTC, hyeonji1220 commented on backend/src/test/java/reviewme/api/ApiTest.java
> +        HttpSession session = ((HttpServletRequest) request).getSession(false);
테스트의 경우 getSession을 false로 해서 세션이 없을 경우 새로운 세션 생성을 막는 이유가 궁금해요!

2024-09-23 23:59 UTC, skylar1220 commented on backend/src/docs/asciidoc/reviewgroup.adoc
> +operation::review-group-check-access[snippets="curl-request,request-fields,http-response"]
이 부분에 response-cookies가 빠진 것 같아요!

2024-09-23 23:59 UTC, skylar1220 commented on backend/src/docs/asciidoc/review-detail.adoc
>  operation::review-detail-invalid-group-access-code[snippets="http-response"]
이 부분은 이제 없는 부분이니 제거해도 좋겠네요!
냅뒀더니 rest docs에 이렇게 뜸..ㅎㅎ
<img width="761" alt="image" src="https://github.com/user-attachments/assets/9a43f0b7-049c-4170-a43e-cf5c658804d9">

2024-09-23 23:59 UTC, skylar1220 commented on backend/src/docs/asciidoc/review-list.adoc
>  operation::received-reviews-invalid-group-access-code[snippets="http-response"]
(위와 동일) 이 부분은 이제 없는 부분이니 제거해도 좋겠네요!

2024-09-24 01:15 UTC, donghoony commented on backend/src/test/java/reviewme/api/ApiTest.java
> +            sessionCookie.setHttpOnly(true);
톰캣이 세션을 만들 때 `httpOnly`를 붙여 줍니다요~!

2024-09-24 01:16 UTC, donghoony commented on backend/src/test/java/reviewme/api/ApiTest.java
> +        HttpSession session = ((HttpServletRequest) request).getSession(false);
해당 필터는 테스트할 때 세션이 존재하는 경우 Response에 쿠키를 담는 역할만을 합니다. 따라서 Request에 세션이 존재하지 않는 경우 `Set-Cookie`를 할 필요가 없어용

2024-09-24 01:18 UTC, donghoony commented on backend/src/docs/asciidoc/reviewgroup.adoc
> +operation::review-group-check-access[snippets="curl-request,request-fields,http-response"]
아래 남겨주신 `adoc` 전부 반영했습니다~

2024-09-24 15:30 UTC, Kimprodp requested changes
아루 고생햇슴다~ 코멘트만 확인 부탁해요!

2024-09-24 15:30 UTC, Kimprodp commented on backend/src/main/java/reviewme/config/CorsConfig.java
> +                .allowedMethods("GET", "POST")
👍👍

2024-09-24 15:30 UTC, Kimprodp commented on backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupService.java
> +            throw new ReviewGroupUnauthorizedException(reviewGroup.getId());
`checkGroupAccessCode `메서드가 현재는 리뷰 조회를 위해서만 호출되고 있지만, 추후 다른 기능에서 비밀번호를 검증할 때 사용할 수도 있을 것 같아요. 단순히 이 메서드만 놓고 보면 `ReviewGroupUnauthorizedException `예외의 메세지가 리뷰 조회에만 한정되어 있는 느낌입니다!
여기서는 단순히 비밀번호가 틀렸다는 메세지를 던지고 front 쪽에서 상황에 적절하게 알럿 메세지를 구성하는 방식은 어떤가요?

2024-09-24 15:30 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/service/ReviewListLookupService.java
> +    }
그룹 검증이 여기저기 중복이었는데 없어지니 깔꼼하네요 ~ 👍

2024-09-25 07:08 UTC, donghoony commented on backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupService.java
> +            throw new ReviewGroupUnauthorizedException(reviewGroup.getId());
`checkGroupAccessCode`라는 의미가 체크한다는 의미니 `403`을 던져주면 없다~ 고 인식할 수 있지 않을까요?

2024-09-25 08:56 UTC, skylar1220 approved these changes
드디어 F5를 누를 수 있다니~~ 아루&올리 수고했어요요요요👏👏👏

2024-09-25 08:56 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/config/CorsConfig.java
> +                .allowedOriginPatterns("*");
credential request의 경우 allowedOrigins는 와일드 카드를 사용하지 못하게 되어있는데 pattern은 와일드 카드를 써도 되나하는 고민이 드네요~

2024-09-25 08:56 UTC, donghoony commented on backend/src/main/java/reviewme/config/CorsConfig.java
> +                .allowedOriginPatterns("*");
테스트중입니다요~

2024-09-25 09:03 UTC, nayonsoso requested changes
> 기존 API를 모두 변경하면서 싹 고쳤습니다. v3로 올리는 게 나았을까요? v를 올리는 기준은 무엇일까요? prod에 어떻게 배포해야 할까요?

저번에 토미의 수업에서 나왔던 것과 완전 똑같은 상황이네요 ㅎㅎ
저도 정답은 모르지만, 여기에 대해서 생각을 정리해봤어요.
제가 생각한 API 에 버전을 두는 이유는 이러합니다.
- 사용자가 사용하는 동안 배포에 영향을 받으면 안된다.
- 하지만 API 의 요청 - 응답 형식 변경이 일어날 경우, 사용자가 에러를 마주할 수 있다. 
- 이를 방지하기 위해서 api 에 버전을 두어서, 이전 버전을 사용중이었던 사용자도 무사히 응답을 받을 수 있게 한다.

➡️ 즉, **"이전 버전의 웹을 사용하는 사용자들의 요청을 오류 없이 처리하기 위해서"** 입니다.

---

따라서  이상인 배포는 아래의 프로세스를 따라야합니다.

- 이번 PR 에서 바꾼 api 는 v3 으로 두고, v2 api 에 해당하는 내용을 남겨둔다.
- 백을 배포한다.
- 프론트에서 v2 로 된 것을 v3 로 바꾼다.
- 이제 v2 로 요청하는 프론트로 접속한 사용자들이 없다 싶으면, v2 엔드포인트를 없앤다.

---

그런데 솔직히 말하자면 지금 우리 사이트가 위 과정을 엄격하게 따를만큼 사용자가 끊임없이 사용하는 정도가 아닌지라.. 이 내용을 염두에 두고 사용자가 많아지면 그때 적용하면 될 것 같아요😅

결론 : v2 에 해도 괜찮았다고 생각합니다

2024-09-25 09:03 UTC, nayonsoso commented on backend/src/main/java/reviewme/config/CorsConfig.java
> +                .allowedMethods("GET", "POST")
👍👍

[참말로 모르겠어서 하는 질문] 요번 PR에서 하지 않고 TODO 로 남겨둔 이유가 따로 있나요?

2024-09-25 09:03 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/controller/ReviewRequestCode.java
> +}
이거 no usage 인데 살려둔 이유가 있으신가용!

2024-09-25 09:03 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/ReviewDetailLookupService.java
> -    }
**[내가 못 찾은 것일 수도 있음]**
여기도 그렇고 ReviewListLookupService 에서도 그룹 엑세스 코드에 대한 검증이 사라졌는데, 그럼 "지금의 요청이 리뷰 내용을 볼 수 있는 사람(=리뷰방 만든 사람)의 요청이라는 검증"을 어디에서 하고 있나요?

2024-09-25 09:03 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/dto/request/ReviewAuthRequest.java
> +}
이거 사용되지 않는 클래스같아요!

2024-09-25 09:03 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
> +        session.setAttribute("reviewRequestCode", request.reviewRequestCode());
[내가 잘못 이해하고 있는것일 수 있음🥹 잘못 생각했다면 짚어주세용]
세션에 reviewRequestCode 를 그대로 넘겨주고, 그것을 인증 수단으로 사용하고 있는 것 맞나요? 그런데 reviewRequestCode 는 공개되는 정보이니 이걸 인증수단으로 사용하는건 위험하지 않을까요?

2024-09-25 10:53 UTC, donghoony commented on backend/src/main/java/reviewme/review/controller/ReviewRequestCode.java
> +}
지웁니다요~

2024-09-25 10:59 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/ReviewDetailLookupService.java
> -    }
세션이 합니다. 세션은 서버에서 관리하고, 내부 데이터는 세션이 관리하고 있어요. 한 번 세션을 발급하면 유효한 사람임이 인증됩니다1

2024-09-25 11:00 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/dto/request/ReviewAuthRequest.java
> +}
꼼꼼싼초!

2024-09-25 11:00 UTC, donghoony commented on backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
> +        session.setAttribute("reviewRequestCode", request.reviewRequestCode());
쿠키는 무작위 난수가 프론트에 전달되고, 이를 톰캣 내부적으로 매핑합니다. 세션 데이터는 톰캣 안에서 관리되기 때문에 걱정하지 않아도 됩니다.
단, 쿠키가 탈취당할 경우 다른 사람이 내 행세를 할 수 있지만, 이는 토큰도 마찬가지예요

2024-09-25 11:20 UTC, nayonsoso commented on backend/src/main/java/reviewme/reviewgroup/controller/ReviewGroupController.java
> +        session.setAttribute("reviewRequestCode", request.reviewRequestCode());
제가 쿠키랑 세션을 헷갈렸던 것 같아요😅

2024-09-25 11:21 UTC, Kimprodp commented on backend/src/main/java/reviewme/reviewgroup/service/ReviewGroupService.java
> +            throw new ReviewGroupUnauthorizedException(reviewGroup.getId());
앗 저는 예외를 던지는것은 좋으나 예외 메시지에 대해서 말한거엿슴다

2024-09-25 11:22 UTC, nayonsoso approved these changes
Cors 테스트 좋네요👏👏
수고 많았어요 아루!🥳

2024-09-26 01:48 UTC, Kimprodp commented
https://github.com/woowacourse-teams/2024-review-me/pull/666#discussion_r1775046532
요 코멘트만 한번 확인 부탁애요~

2024-09-26 01:53 UTC, Kimprodp approved these changes
고생햇삼요~~!!

2024-09-26 02:00 UTC, skylar1220 commented
secret의 yml 파일들도 변경된 것 확인했습니다!! 고수고수!!

2024-09-26 02:01 UTC, merged