[BE] test: 깃헙 리뷰어 그룹의 테스트 추가 및 fixture 미적용 부분 보완
woowacourse-teams/2024-review-me pull request #68
Opened 2024-07-22 01:57 UTC by skylar1220

- resolves #67 

---

### 🚀 어떤 기능을 구현했나요 ?
- 깃헙 리뷰어 그룹의 테스트를 추가하고 fixture 미적용 부분을 보완했습니다.

### 🔥 어떻게 해결했나요 ?
- 깃헙 리뷰어 그룹의 레포지토리 테스트 추가
- ReviewServiceTest에 테스트 fixture를 적용

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 컨벤션 잘 지켜졌는지 봐주세요~

### 📚 참고 자료, 할 말
- 하기로 미리 얘기한 부분은 아닌데 지금 해놓는 게 나을 것 같아서 했습니당

2024-07-22 05:05 UTC, donghoony approved these changes
컨벤션만 잡고 미리 어프룹합니다 확인바라요~! 고생했습니다 ㅎㅎ

2024-07-22 05:05 UTC, donghoony commented on backend/src/test/java/reviewme/member/repository/GithubReviewerGroupRepositoryTest.java
> +        String githubId = "ted";
// given when then ?

2024-07-22 05:09 UTC, Kimprodp requested changes
컨벤션 확인 부탁함니다👍

2024-07-22 05:09 UTC, Kimprodp commented on backend/src/test/java/reviewme/member/repository/GithubReviewerGroupRepositoryTest.java
> +    @Test
테스트에 절 구분이 빠져있어요!

2024-07-22 05:10 UTC, skylar1220 commented on backend/src/test/java/reviewme/member/repository/GithubReviewerGroupRepositoryTest.java
> +        String githubId = "ted";
아차차... 확인 감사 🙏

2024-07-22 10:25 UTC, skylar1220 commented on backend/src/test/java/reviewme/member/repository/GithubReviewerGroupRepositoryTest.java
> +    @Test
혹시 절 구분이 빠져있다는 게 어떤 말이까요? 개행은 다 되어있는 것 같아서요!

2024-07-22 12:44 UTC, Kimprodp commented on backend/src/test/java/reviewme/member/repository/GithubReviewerGroupRepositoryTest.java
> +    @Test
given when then 절 말한 건데 아루가 이미 리뷰했네요~

2024-07-22 12:45 UTC, Kimprodp approved these changes

2024-07-22 23:40 UTC, nayonsoso commented on backend/src/test/java/reviewme/member/repository/GithubReviewerGroupRepositoryTest.java
> +        githubReviewerGroupRepository.save(new GithubReviewerGroup(githubId, reviewerGroup));
이 부분이 논리적으로는 맞지 않는 것 같아요..!
reviewerGroup의 fixture로 들어가는 member는 리뷰'이'입니다.
지금은 리뷰어를 넣고 있네요😲
개인적으로는 이런 실수를 방지하기 위해서 변수의 이름으로 의미를 표현하는걸 선호합니다!
예를 들어서 아래 코드 같이요

```suggestion
@Test
    void 깃허브_아이디와_리뷰어_그룹이_모두_일치하는_깃허브_리뷰어_그룹이_있는_경우를_확인한다() {
        // given
        String revieweeGithubId = "kirby";
        Member reviewee = new Member("커비", revieweeGithubId);
        String reviewerGithubId = "ted";
        Member reviewer = new Member("테드", reviewerGithubId);
        memberRepository.saveAll(List.of(reviewee, reviewer));

        ReviewerGroup reviewerGroup = 리뷰_그룹.create(reviewee);
        reviewerGroupRepository.save(reviewerGroup);
        githubReviewerGroupRepository.save(new GithubReviewerGroup(reviewerGithubId, reviewerGroup));

        // when
        boolean actual = githubReviewerGroupRepository.existsByGithubIdAndReviewerGroup(reviewerGithubId, reviewerGroup);
        
        // then
        assertThat(actual).isTrue();
    }
```

2024-07-22 23:43 UTC, nayonsoso requested changes

2024-07-22 23:43 UTC, nayonsoso commented on backend/src/test/java/reviewme/member/repository/GithubReviewerGroupRepositoryTest.java
> +    }
이 부분이 논리적으로는 맞지 않는 것 같아요..!
reviewerGroup의 fixture로 들어가는 member는 리뷰'이'여야 합니다.
지금은 리뷰'어'를 넣고 있네요😲
이를테면, 테드가 자기에 대해 리뷰해달라는 그룹에 테드를 넣은 상태같습니다!

개인적으로는 이런 실수를 방지하기 위해서 변수의 이름으로 의미를 표현하는걸 선호합니다!
예를 들어서 아래 코드 같이요

```suggestion
@Test
    void 깃허브_아이디와_리뷰어_그룹이_모두_일치하는_깃허브_리뷰어_그룹이_있는_경우를_확인한다() {
        // given
        String revieweeGithubId = "kirby";
        Member reviewee = new Member("커비", revieweeGithubId);
        String reviewerGithubId = "ted";
        Member reviewer = new Member("테드", reviewerGithubId);
        memberRepository.saveAll(List.of(reviewee, reviewer));

        ReviewerGroup reviewerGroup = 리뷰_그룹.create(reviewee);
        reviewerGroupRepository.save(reviewerGroup);
        githubReviewerGroupRepository.save(new GithubReviewerGroup(reviewerGithubId, reviewerGroup));

        // when
        boolean actual = githubReviewerGroupRepository.existsByGithubIdAndReviewerGroup(reviewerGithubId, reviewerGroup);
        
        // then
        assertThat(actual).isTrue();
    }
```

2024-07-23 01:35 UTC, skylar1220 commented on backend/src/test/java/reviewme/member/repository/GithubReviewerGroupRepositoryTest.java
> +    }
으악 리뷰어가 리뷰어를 만드는 상황을 만들어버렸군요!😂
찾아내줘서 고마워요 산쵸! (+ 직접 수정 코드까지😋)
확실히 reviewer, reviewee라고 변수명을 지정하는 것이 덜 헷갈리겠군요!

2024-07-23 01:40 UTC, nayonsoso approved these changes
귣귣~ 수고했어용🥰

2024-07-23 02:35 UTC, merged