[BE] refactor: 발생하는 모든 예외의 형식 통일
woowacourse-teams/2024-review-me pull request #69
Opened 2024-07-22 04:04 UTC by nayonsoso

- resolves #50 

---

### 🚀 어떤 기능을 구현했나요 ?
- 스프링에서 기본으로 처리하는 예외와 우리가 명시해서 처리하는 예외의 응답 형식을 통일했습니다.

### 🔥 어떻게 해결했나요 ?
- 스프링에서 제공하는 예외 처리 방식에 대해 공부한 후, 이를 적용했습니다.
- 블로그 글 참고(추후 추가)

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 예외 처리 방식이 이해가 되었는지
- 제가 놓친 예외는 없는지

### 📚 참고 자료, 할 말
- https://mangkyu.tistory.com/204

2024-07-22 11:35 UTC, skylar1220 requested changes
싼초~~~ 주말사이 공부하고 적용한 내용이 엄청난데요🫢
정리한 글 읽으면서 많이 배웠어요! 궁금한 점이 있어서 남겨놓았습니다!

2024-07-22 11:35 UTC, skylar1220 commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
>      }
기존 ProblemDetail만 반환하는 방식에서 ResponseEntityf로 한 번 더 감싸서 보내야하는 이유가 궁금해요!
한 번 더 감싸서 보내면서 상태코드가 두 번 들어가게되는 점도 함께 눈에 띄여서요~

2024-07-22 13:07 UTC, donghoony requested changes
산초 고생했습니다~! 예외 처리를 통일성있게 가져가는 것도 좋겠지만, 내부 메시지를 외부에 노출하는 것이 몇군데 보여서 리뷰 남겨요~

2024-07-22 13:07 UTC, donghoony commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +    }
전체 Exception을 잡는 것을 가장 아래로 내리면 어떨까요?

2024-07-22 13:07 UTC, donghoony commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
>      }
이건 여기에 한해서 그냥 `ProblemDetail` 내려줘도 될 것 같아요

2024-07-22 13:07 UTC, donghoony commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +    public ResponseEntity<Object> handleMethodArgumentNotValid(
`Object`를 사용하네요? 리턴값이 `ProblemDetail`인 듯하네요.. 🥹

2024-07-22 13:07 UTC, donghoony commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +                .body(ProblemDetail.forStatusAndDetail(statusCode, ex.getMessage()));
exception의 메시지를 그대로 내려도 괜찮을까요? `Internal` 오류이면 내부에서 그냥 처리를 하는 게 나을 것 같아요.

2024-07-22 13:07 UTC, donghoony commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +                .body(ProblemDetail.forStatusAndDetail(HttpStatus.INTERNAL_SERVER_ERROR, "서버 에러가 발생했습니다."));
변수 추출하는 게 보기 편할 것 같습니다 🥹

2024-07-22 13:08 UTC, donghoony commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +    public ResponseEntity<Object> handleMethodArgumentNotValid(
이건 `Override` 때문에 어쩔 수 없네요 🤔

2024-07-22 13:08 UTC, donghoony commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +                .body(ProblemDetail.forStatusAndDetail(statusCode, ex.getMessage()));
<img width="307" alt="image" src="https://github.com/user-attachments/assets/daf1cdd1-eacd-464e-884f-c6bed358bebd">

`vvv` 자원이 없다는 건 내부 구조를 노출할 수 있는 창구가 될 것 같았습니다.

2024-07-22 13:34 UTC, Kimprodp approved these changes
산초 멋지게 구현해줬네요! 정리 글도 잘 봤습니다. 덕분에 공부가 됐어요.
코드 보면서 모르겠는 부분만 코멘트 달았습니다~

2024-07-22 13:34 UTC, Kimprodp commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
>      }
ResponseEntity로 감싸면 헤더에도 상태코드를 지정할 수 있고, 감싸지 않으면 헤더에는 무조건 200ok로 나가게 되나요? 헤더에 상태코드를 지정하면 어떤 점이 좋은가요?

2024-07-22 13:34 UTC, Kimprodp commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +    public ResponseEntity<Object> handleMethodArgumentNotValid(
ResponseEntityExceptionHandler 의 메서드 중에서 handleMethodArgumentNotValid만 오버라이드 한 이유는 무엇인가요?

2024-07-23 00:01 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
>      }
> 기존 ProblemDetail만 반환하는 방식에서 ResponseEntity로 한 번 더 감싸서 보내야하는 이유가 궁금해요!

> 헤더에 상태코드를 지정하면 어떤 점이 좋은가요?

사실 "ResponseEntity로 감싸는 것"과 "ProblemDetail을 그냥 내려주는 것"은 동일한 응답을 합니다.
그런데 왜 굳이 ResponseEntity로 감쌌냐면요!

`ResponseEntityExceptionHandler`의 함수들은 ResponseEntity<Object> 를 응답하는데,
GlobalExceptionHandler에서 이를 재정의하지 않습니까?
그래서 클래스 전체적으로 통일을 하기 위해서 그랬습니다 ㅎㅎ

예를들어 아래와 같은 코드가 통일감이 없다 생각해서 그랬던 것입니다.
```java
@RestControllerAdvice
public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {
     // 여기에선 ProblemDetail을 리턴
    @ExceptionHandler(NotFoundException.class)
    public ProblemDetail handleNotFoundException(NotFoundException ex) {
        return ProblemDetail.forStatusAndDetail(HttpStatus.NOT_FOUND, ex.getErrorMessage());
    }

    // 여기에선 ResponseEntity<Object>를 리턴, 그런데 이건 오버라이드 한 것이므로 리턴 타입을 바꿀 수 없음
    @Override
    public ResponseEntity<Object> handleExceptionInternal(
            Exception ex, @Nullable Object body, HttpHeaders headers, HttpStatusCode statusCode, WebRequest request) {
        return ResponseEntity.status(statusCode)
                .body(ProblemDetail.forStatusAndDetail(statusCode, ex.getMessage()));
    }
}
```

2024-07-23 00:13 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +    }
전체 Excetion을 처리하는 ExceptionHandler를 가장 아래에 두는 것은 ExceptionHandler가 선언한 순서대로 우선순위를 갖기 때문이라고 알고있어요. 그렇다면 ExceptionHandler는 ExceptionHandler끼리 모여있는게 더 보기 편할 것 같다는 생각이 들어요!

2024-07-23 00:18 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +    public ResponseEntity<Object> handleMethodArgumentNotValid(
> ResponseEntityExceptionHandler 의 메서드 중에서 handleMethodArgumentNotValid만 오버라이드 한 이유는 무엇인가요?

MethodArgumentNotValid는 '컨트롤러에서 하는 request dto 검증'을 만족하지 않을 때 발생하는 에러입니다. 그리고 이 에러는 우리가 지정한 메세지를 보여주도록 커스텀할 필요가 있어요. e.g. 답변을 입력해주세요

커스텀이 필요하기 때문에 MethodArgumentNotValid는 오버라이드를 해준 것이고, 나머지 스프링 기본 예외들은 ResponseEntityExceptionHandler의 핸들링으로 처리되는 것만으로도 충분하다고 생각했어요🤗

2024-07-23 00:34 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +                .body(ProblemDetail.forStatusAndDetail(statusCode, ex.getMessage()));
헉 NoResourceFoundException같은 것은 내부 구조를 노출할 수도 있겠네요..!
그럼 404 라는 의미는 드러내되, '정적 파일이 없다'와 같은 구체적인 예외 메세지는 수정하도록 바꿔보겠습니다

2024-07-23 00:39 UTC, donghoony commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +    public ResponseEntity<Object> handleMethodArgumentNotValid(
MethodArgumentNotValidException.class 를 잡도록 하고 상속받지 않는건 어떤가요?

2024-07-23 00:47 UTC, donghoony commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +    public ResponseEntity<Object> handleMethodArgumentNotValid(
ref: https://github.com/donghoony/woowacourse-level-2-roomescape-payment/blob/step2-4/src/main/java/roomescape/presentation/RoomescapeControllerAdvice.java

2024-07-23 02:41 UTC, nayonsoso commented
### 변경 사항
DefaultHandlerExceptionResolver에서 처리될 예외를 처리하는 방법을 변경한다. 
ResponseEntityExceptionHandler를 extends하지 않고, ControllerAdvice 에서 ExceptionHandler로 핸들링한다.
처리할 예외 클래스들과 예외 메세지는 한글로 넣어준다.

### 예외 메세지 작성 기준
예외 메세지는 '서버의 구체적인 스펙을 드러내지 않으면서, 어떤 부분이 잘못되었는지는 알려주도록' 작성한다.
e.g. No static resource reviews {경로} (X) 
잘못된 경로의 요청입니다 (O)
-> 정적 자원이 없음을 드러내지 않으면서 ‘경로’가 잘못되었음은 알려주어, 클라이언트가 제대로된 요청을 할 수 있게 한다.

### HTTP 상태 코드를 내려주는 기준
스프링에서 정한 상태코드를 그대로 내려준다.
[예외와 상태코드가 정리되어있는 공식 문서](https://docs.spring.io/spring-framework/docs/6.1.11/javadoc-api/org/springframework/web/servlet/mvc/support/DefaultHandlerExceptionResolver.html)

### 표!

| 예외 클래스                                      | HTTP 상태 코드 | 발생하는 상황                                                                 | 산초가 넣은 예외 메시지 내용                                                          | 
|-------------------------------------------------|----------------|--------------------------------------------------------------------|-------------------------------------------------------------------------------|
| `HttpRequestMethodNotSupportedException.class`  | 405            | 요청한 HTTP 메서드를 지원하지 않는 경우 발생                        |                                          지원하지 않는 HTTP 메서드입니다. |  
| `HttpMediaTypeNotSupportedException.class`      | 415            | 요청한 미디어 타입을 지원하지 않는 경우 발생                        | 잘못된 media type 입니다.  |
| `HttpMediaTypeNotAcceptableException.class`     | 406            | 요청한 미디어 타입을 수용할 수 없는 경우 발생                        | 잘못된 media type 입니다.  |
| `MissingPathVariableException.class`            | 500            | 경로 변수 값이 누락된 경우 발생                                       | 필수 요청 데이터가 누락되었습니다.  |         
| `MissingServletRequestParameterException.class` | 400            | 요청 파라미터가 누락된 경우 발생                                      | 필수 요청 데이터가 누락되었습니다.   |    
| `MissingServletRequestPartException.class`      | 400            | 요청의 일부 파트가 누락된 경우 발생                                    | 필수 요청 데이터가 누락되었습니다.                                  |    
| `ServletRequestBindingException.class`          | 400            | 요청 바인딩 중에 오류가 발생한 경우                                    | 요청을 읽을 수 없습니다. |
| `MethodArgumentNotValidException.class`         | 400            | 메서드 인자가 유효하지 않은 경우 발생                                    | 요청 데이터의 형식이 잘못되었습니다. | 
| `HandlerMethodValidationException.class`        | 400            | 핸들러 메서드의 인자 검증이 실패한 경우 발생                              | 요청 데이터의 형식이 잘못되었습니다.  |
| `NoHandlerFoundException.class`                 | 404            | 요청한 핸들러를 찾을 수 없는 경우 발생                                     | 잘못된 경로의 요청입니다. |
| `NoResourceFoundException.class`                | 404            | 요청한 리소스를 찾을 수 없는 경우 발생                                     | 잘못된 경로의 요청입니다. |
| `AsyncRequestTimeoutException.class`            | 503            | 비동기 요청이 타임아웃된 경우 발생                                        | 요청을 받아오는 시간이 초과되었습니다   |
| `ErrorResponseException.class`                  | 500  | 다양한 오류 응답에 대한 예외                                             | 서버 에러가 발생했습니다.  |
| `MaxUploadSizeExceededException.class`          | 413            | 업로드 파일 크기 초과로 인한 예외 발생                                      | 최대 업로드 크기를 초과했습니다.  |
| `ConversionNotSupportedException.class`         | 500            | 특정 타입으로 변환할 수 없는 경우 발생                                     | 요청 데이터의 형식이 잘못되었습니다.  | 
| `TypeMismatchException.class`                   | 400            | 타입 불일치로 인한 예외 발생                                              | 요청 데이터의 형식이 잘못되었습니다.    |  
| `HttpMessageNotReadableException.class`         | 400            | HTTP 메시지를 읽을 수 없는 경우 발생                                        | 요청을 읽을 수 없습니다.     |
| `HttpMessageNotWritableException.class`         | 500            | HTTP 메시지를 작성할 수 없는 경우 발생                                       | 서버 에러가 발생했습니다.  |
| `MethodValidationException.class`               | 400            | 메서드 검증에 실패한 경우 발생                                              | 요청 데이터의 형식이 잘못되었습니다.  |
| `BindException.class`                           | 400            | 요청 바인딩 오류 발생                                                    | 요청 데이터의 형식이 잘못되었습니다. |

### References
- [HttpRequestMethodNotSupportedException](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/HttpRequestMethodNotSupportedException.html)
- [HttpMediaTypeNotSupportedException](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/HttpMediaTypeNotSupportedException.html)
- [HttpMediaTypeNotAcceptableException](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/HttpMediaTypeNotAcceptableException.html)
- [MissingPathVariableException](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/MissingPathVariableException.html)
- [MissingServletRequestParameterException](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/MissingServletRequestParameterException.html)
- [MissingServletRequestPartException](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/MissingServletRequestPartException.html)
- [ServletRequestBindingException](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/bind/ServletRequestBindingException.html)
- [MethodArgumentNotValidException](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/validation/MethodArgumentNotValidException.html)
- [HandlerMethodValidationException](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/validation/HandlerMethodValidationException.html)
- [NoHandlerFoundException](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/NoHandlerFoundException.html)
- [AsyncRequestTimeoutException](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/context/request/AsyncRequestTimeoutException.html)
- [MaxUploadSizeExceededException](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/multipart/MaxUploadSizeExceededException.html)
- [ConversionNotSupportedException](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/ConversionNotSupportedException.html)
- [TypeMismatchException](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/TypeMismatchException.html)
- [HttpMessageNotReadableException](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/converter/HttpMessageNotReadableException.html)
- [HttpMessageNotWritableException](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/converter/HttpMessageNotWritableException.html)
- [BindException](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/validation/BindException.html)

2024-07-23 05:18 UTC, nayonsoso commented
### 🐴 개인적으로 하고 싶은 말

1) 예외 응답 내용은 유연하게 가져가자
리뷰 메세지의 내용을 너무 구체적으로 주지 말자는 말에 동의했고, 그런식으로 코드를 만들기도 했습니다만 조금 걸리는 부분이 있습니다.
우리의 예외 메세지가 '지금' 필요한 사람은 누구일까요? 저는 당분간은 클라이언트라고 생각합니다. 
그래서 프론트가 예외 메세지를 한번에 이해하지 못하거나, 백에게 로그를 확인해달라는 요청을 자주 한다면 
'구체적으로 메세지를 주도록 바꿀 수 있다'고 열어두고 갔으면 좋겠습니다~

2) 예외 처리에 대한 테스트 작성을 해자
예외 처리는 중요도가 높은 것이라 생각해서, 테스트를 추가하는게 좋을 것 같습니다!

2024-07-23 05:57 UTC, donghoony approved these changes
산초짱

2024-07-23 05:57 UTC, donghoony commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +        return ProblemDetail.forStatusAndDetail(HttpStatus.UNSUPPORTED_MEDIA_TYPE, "잘못된 media type 입니다.");
`지원하지 않는 MediaType입니다` 는 어떨까요?

2024-07-23 05:57 UTC, donghoony commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +    // default error
`// Exception from Spring framework below` 정도로 자세하게 주석을 적으면 좋겠네요 ~!

2024-07-23 06:00 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +        return ProblemDetail.forStatusAndDetail(HttpStatus.UNSUPPORTED_MEDIA_TYPE, "잘못된 media type 입니다.");
브릴리언트 합니다🐴

2024-07-23 06:01 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +    // default error
억셉트 하겠습니다🐴

2024-07-23 15:02 UTC, skylar1220 approved these changes
예외의 경우와 메시지가 모두 잘 매칭되는 것 같아요! 고생 많았다 산쵸🫢

2024-07-23 15:25 UTC, merged