[BE] infra: flyway를 통한 인덱스 적용
woowacourse-teams/2024-review-me pull request #690
Opened 2024-09-25 06:58 UTC by skylar1220

- resolves #682 

---

### 🚀 어떤 기능을 구현했나요 ?
- flyway를 통해 DB에 인덱스를 적용합니다.

### 🔥 어떻게 해결했나요 ?
아래의 컬럼에 인덱스를 적용하는 sql문을 flyway를 통해 적용합니다.
- review 테이블의 review_group_id 컬럼
- review_group 테이블의 review_request_code 컬럼

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- sql문에 오류가 없겠죠? 하하

### 📚 참고 자료, 할 말
- flyway를 통한 첫 형상관리 두근

2024-09-25 07:02 UTC, donghoony commented on backend/src/main/resources/db/migration/V1__add_index.sql
> +CREATE INDEX review_idx_review_group_id ON review (review_group_id);
제안: DB 스키마 변경 있을 때 첫 줄에 주석으로 맥락 이야기하면 어떨까요? 코드 자체로는 변경에 대한 이유를 확 알기 어려울 수 있으니, 관련 이슈를 링크로 달거나 이유로 달면 좋겠어요

2024-09-25 07:03 UTC, donghoony approved these changes
인덱스 타고 빨리빨리 다니렴~

2024-09-25 10:53 UTC, skylar1220 commented on backend/src/main/resources/db/migration/V1__add_index.sql
> +CREATE INDEX review_idx_review_group_id ON review (review_group_id);
오오 친절한 문서가 되겠군요! 한 번 적용해봤어요~~

2024-09-25 13:01 UTC, donghoony requested changes
주석 확인해주세요~!

2024-09-25 13:01 UTC, donghoony commented on backend/src/main/resources/db/migration/V1__add_index.sql
> +CREATE INDEX review_idx_review_group_id ON review (review_group_id);
`sql`에서 주석을 `--`로 달지 않나요? 😨

2024-09-25 13:04 UTC, donghoony approved these changes

2024-09-25 23:59 UTC, skylar1220 commented on backend/src/main/resources/db/migration/V1__add_index.sql
> +CREATE INDEX review_idx_review_group_id ON review (review_group_id);
ㅎㅎ반영완료

2024-09-26 02:16 UTC, Kimprodp approved these changes
인덱스 맛있다

2024-09-26 02:16 UTC, nayonsoso approved these changes
커비.. 설명해줘잉😘

2024-09-26 02:18 UTC, merged