[FE] chore: 불필요한 홈 캐러셀 이미지 삭제
woowacourse-teams/2024-review-me pull request #692
Opened 2024-09-25 07:21 UTC by BadaHertz52

- resolves #691

---

### 🚀 어떤 기능을 구현했나요 ?
- 사용하지 않는 홈 페이지 캐러셀 이미지 파일들을 삭제했어요.

### 📚 참고 자료, 할 말
- 필요없는 것들은 바로 바로 삭제하자

2024-09-25 07:26 UTC, chysis approved these changes
확인했습니다!

2024-09-25 07:54 UTC, ImxYJL approved these changes
성능 측정할 때 불필요한 이미지도 포함한 데이터로 나와있겠네요... 개선 수치는 엇비슷하겠지만서도... 미안합니다 😥😥

2024-09-26 02:18 UTC, soosoo22 approved these changes
이미지 최적화하면서 불필요한 이미지가 추가되었나 보네요..ㅠㅠㅠ 
고생했어요 바다!

2024-09-26 03:59 UTC, chysis requested changes
수정사항에 대한 코멘트 남겼습니다!

2024-09-26 03:59 UTC, chysis commented on frontend/src/pages/DetailedReviewPage/index.tsx
> +  if (!groupAccessCode) return;
`undefined`를 반환하지 않고, `null`을 명시적으로 반환하도록 하는 것이 좋을 것 같아요.
```suggestion
  if (!groupAccessCode) return null;
```

2024-09-26 03:59 UTC, chysis commented on frontend/src/pages/ReviewListPage/index.tsx
> +      {groupAccessCode && storedReviewRequestCode && (
추후에 조건문 부분을 변수로 빼도 좋을 것 같네요

2024-09-26 04:57 UTC, BadaHertz52 commented on frontend/src/pages/DetailedReviewPage/index.tsx
> +  if (!groupAccessCode) return;
해당 부분은 목록 페이지가 무한 스크롤을 반영 분이 pr에 올라가 있어서, 해당 pr 머지 후 pull 받을 거라 임시로 고쳤어요

2024-09-26 04:58 UTC, BadaHertz52 commented on frontend/src/pages/ReviewListPage/index.tsx
> +      {groupAccessCode && storedReviewRequestCode && (
해당 부분은 목록 페이지가 무한 스크롤을 반영 분이 pr에 올라가 있어서, 해당 pr 머지 후 pull 받을 거라 임시로 고쳤어요

2024-09-26 07:07 UTC, chysis approved these changes
확인했습니다!

2024-09-26 07:08 UTC, merged