[BE] refactor: Answer 추상화 1단계
woowacourse-teams/2024-review-me pull request #766
Opened 2024-10-04 04:29 UTC by donghoony

### 🚀 어떤 기능을 구현했나요 ?
- 답변에 대한 추상화를 진행했습니다.

### 🔥 어떻게 해결했나요 ?
- 일단 중복 클래스를 만들었어요. 테이블 다섯 개고, 변경 사항은 flyway를 확인해주세요.
- 해당하는 Repository까지 다 만들었습니다.
- 추상화하는 과정이 꽤나 어려웠습니다. 이는 결국 의존성이 굉장히 얽혀있다는 이야긴데요, 앞으로 PR 날릴 때 불필요한 의존성이 존재하는지를 꼭 확인해야겠습니다.
- 우선 리뷰 등록 시, 새로운 테이블에 중복으로 적재합니다.
- 마이그레이션 진행할 때에는 새로운 테이블들의 ID 시작값을 기존 테이블보다 높게 잡습니다. 이후 구테이블 -> 신테이블로 신테이블의 가장 작은 ID보다 작은 ID를 가진 구테이블의 행들을 옮기면 됩니다.
- 새 테이블명은 `new` prefix가 존재합니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 모르겠어요,,, 의존성 때문에 리팩터링 진짜 제대로 해야겠다는 생각이 드네요. 객체 연관도 없지만, mapper/valiator가 의존성을 잔뜩 가지고 있는 God object인 느낌입니다.

### 📚 참고 자료, 할 말
- Mapper -> Validator를 거치는 게 필요할까요? Mapper에서도 repo 가져오고 validator에서도 repo 가져오고 하는데.. 쿼리 낭비가 일어나지는 않을까 걱정되긴 합니다. 아직 자세히 들여다보지는 않았어요

2024-10-04 12:17 UTC, nayonsoso requested changes
귣귣~ 까다로울 수 있는 부분들 잘 작성하셨네요☺️
수고 많았습니당~ 대단아루~~

2024-10-04 12:17 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/domain/abstraction/NewCheckboxAnswer.java
> +@EqualsAndHashCode(callSuper = true)
-제가 그냥 정리용으로 남겨둡니다!!-

이 애너테이션은 Lombok 라이브러리에서 제공하는 기능이에요. JPA나 객체 지향 프로그래밍에서 객체 간의 비교를 쉽게 할 수 있도록 equals()와 hashCode() 메서드를 자동으로 생성해주죠.

**기본적인 @EqualsAndHashCode**는 클래스 필드만 사용해 equals()와 hashCode() 메서드를 생성해주는데, 상속 관계에 있는 클래스에서는 상위 클래스의 필드도 비교하고 싶을 때가 있잖아요? 그럴 때 callSuper = true 옵션을 사용해요.

2024-10-04 12:17 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/domain/abstraction/NewCheckBoxAnswerSelectedOption.java
> +public class NewCheckBoxAnswerSelectedOption {
B 를 소문자로 써야 할 것 같아요 ~ 🐝

2024-10-04 12:17 UTC, nayonsoso commented on backend/src/main/resources/db/migration/V2__answer_abstraction.sql
> +)
세미콜론 미싱입니다!

2024-10-04 12:17 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/abstraction/mapper/AnswerMapperFactory.java
> +    }
여기 예외 메세지는 "QuestionType 에 해당하는 AnswerMapper 가 없다"는 뜻이므로 Unsupported answer type 이 아니라 question type 이 맞지 않을까욧?

2024-10-04 12:17 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/abstraction/mapper/NewReviewMapper.java
> +                ));
여기 둘 왜 `));` 개행이 다르나욧?

2024-10-04 12:17 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/abstraction/mapper/NewCheckboxAnswerMapper.java
> +}
예고 )) 형식 검증을 spring validator 로 넘기면 
```
if (answerRequest.text() != null) {
      throw new CheckBoxAnswerIncludedTextException(answerRequest.questionId());
  }
```
요 부분이 서비스 코드에서 사라집니다! 😎

2024-10-04 12:17 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/abstraction/mapper/NewTextAnswerMapper.java
> +        }
예고 ))
형식 검증을 spring validator 로 넘기면 이 부분도 없어질 것입니당😎

2024-10-04 13:41 UTC, donghoony commented on backend/src/main/java/reviewme/review/domain/abstraction/NewCheckBoxAnswerSelectedOption.java
> +public class NewCheckBoxAnswerSelectedOption {
반영했어요~

2024-10-04 13:41 UTC, donghoony commented on backend/src/main/resources/db/migration/V2__answer_abstraction.sql
> +)
오마이갓 고마워요~

2024-10-04 13:42 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/abstraction/mapper/NewReviewMapper.java
> +                ));
위에는 줄이 안넘어가고 아래는 넘어갑니다 ㅜㅜ

2024-10-04 13:43 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/abstraction/mapper/AnswerMapperFactory.java
> +    }
반영했어요~~

2024-10-04 17:29 UTC, donghoony commented on backend/src/main/java/reviewme/review/domain/abstraction/NewCheckboxAnswer.java
> +@EqualsAndHashCode(callSuper = true)
오잉? 제가 알기론 `callSuper`가 상위 클래스의 `Equals + HashCode`를 그대로 사용한다고 알고 있어요. `super().equals()`와 같이요~

2024-10-05 07:53 UTC, Kimprodp approved these changes
추상화 깔끔하네요~
마이그레이션이 끝나면 new가 기존 클래스들을 대체하겠네요.
절차지향과 객체지향 적인 부분은 다시 생각해보고 우선 마이그레이션 부터..

2024-10-05 07:53 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/service/abstraction/validator/AnswerValidatorFactory.java
> +                .orElseThrow(() -> new IllegalArgumentException("Unsupported answer class: " + answerClass));
이 부분은 나중에 따로 커스텀 에외로 만드나요?

2024-10-05 08:20 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/abstraction/validator/AnswerValidatorFactory.java
> +                .orElseThrow(() -> new IllegalArgumentException("Unsupported answer class: " + answerClass));
여기 일어나면 안 되는 부분이긴 합니다 🤔

2024-10-05 10:51 UTC, skylar1220 requested changes
추상화를 하겠다는 생각을 했다는 것! 배울 자세입니다😂
수고했고 좀만 더 수고해줘 아루.. 마이그레이션 완료까지 잘 마무리해봅시당!!
소소한 질문 남겼어용!

2024-10-05 10:51 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/review/service/abstraction/mapper/AnswerMapperFactory.java
> +                .orElseThrow(() -> new IllegalArgumentException("Unsupported question type: " + questionType));
이 예외가 터질일은 아예 없어야할 것 같습니다! 
IllegalArgumentException 말고 error 수준의 커스텀 예외 등이 필요하지 않을까요?

2024-10-05 10:51 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/review/service/abstraction/mapper/NewCheckboxAnswerMapper.java
기존 checkboxAnswerMapper 테스트를 복붙해와서 newCheckboxAnswerMapper 테스트도 추가하는 건 어떨까요?
더불어 support에 대한 테스트도요!

2024-10-06 13:00 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/domain/abstraction/NewCheckboxAnswer.java
> +@EqualsAndHashCode(callSuper = true)
@donghoony 

> By setting callSuper to true, you can include the equals and hashCode methods of your superclass in the generated methods. For hashCode, the result of super.hashCode() is included in the hash algorithm, and forequals, the generated method will return false if the super implementation thinks it is not equal to the passed in object.

이 설명을 보면, 부모 클래스의 equals and hash code 를 "포함" 하는 것 같습니다!

ref. https://projectlombok.org/features/EqualsAndHashCode

2024-10-06 13:58 UTC, nayonsoso approved these changes
반영한 부분 확인했습니다~
지금 보니 힘들다 테그가 달려있었네유 😖
복잡한 코드 수고 많았어요!!

2024-10-06 15:59 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/abstraction/mapper/AnswerMapperFactory.java
> +                .orElseThrow(() -> new IllegalArgumentException("Unsupported question type: " + questionType));
커스텀 예외를 추가했어요~

2024-10-06 15:59 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/abstraction/mapper/NewCheckboxAnswerMapper.java
매퍼에 필요한 테스트를 다시 작성했어요

2024-10-07 05:19 UTC, nayonsoso approved these changes
어푸!! 어푸!! 🤿🤿

2024-10-07 05:19 UTC, nayonsoso commented on backend/src/test/java/reviewme/review/domain/abstraction/NewReviewTest.java
> +
왕사소 리뷰 : 여기 개행 2개✌️

2024-10-07 05:19 UTC, nayonsoso commented on backend/src/test/java/reviewme/review/service/abstraction/mapper/AnswerMapperFactoryTest.java
> +        // given
음~ 맛있다🤤 이런게 있군요!

2024-10-07 05:19 UTC, nayonsoso commented on backend/src/test/java/reviewme/review/service/abstraction/mapper/NewCheckboxAnswerMapperTest.java
> +    }
이 친구는 사라질 수 있겠네요, 예의 주시 하겠습니다🤩

2024-10-07 05:19 UTC, nayonsoso commented on backend/src/test/java/reviewme/review/service/abstraction/mapper/NewTextAnswerMapperTest.java
> +    }
DITTO!

2024-10-07 05:19 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/abstraction/mapper/NewReviewMapper.java
> +        // END
👍

2024-10-07 05:20 UTC, Kimprodp requested changes
코멘트 확인 부탁이요~~

2024-10-07 05:20 UTC, Kimprodp commented on backend/src/test/java/reviewme/review/service/abstraction/validator/AnswerValidatorFactoryTest.java
> +    @DisplayName("지원하는 타입에 따른 밸리데이터를 가져온다.")
여기 있는 테스트들은 왜 DisplayName을 사용하였나요?

2024-10-07 05:20 UTC, Kimprodp commented on backend/src/test/java/reviewme/review/service/abstraction/validator/NewReviewValidatorTest.java
> +        NewTextAnswer notRequiredlTextAnswer = new NewTextAnswer(notRequiredTextQuestion.getId(), "답변".repeat(30));
오타가 있는 것 같슴다

2024-10-07 05:24 UTC, donghoony commented on backend/src/test/java/reviewme/review/service/abstraction/validator/AnswerValidatorFactoryTest.java
> +    @DisplayName("지원하는 타입에 따른 밸리데이터를 가져온다.")
미션하다 와서 싱싱미역 상태였습니다 ㅎㅎㅎㅋㅋㅋ

2024-10-07 05:24 UTC, donghoony commented on backend/src/test/java/reviewme/review/service/abstraction/validator/NewReviewValidatorTest.java
> +        NewTextAnswer notRequiredlTextAnswer = new NewTextAnswer(notRequiredTextQuestion.getId(), "답변".repeat(30));
`git blame`

2024-10-07 05:25 UTC, Kimprodp approved these changes
구웃!

2024-10-07 05:27 UTC, skylar1220 requested changes
퀴즈~

2024-10-07 05:27 UTC, skylar1220 commented on backend/src/test/java/reviewme/review/service/abstraction/mapper/NewReviewMapperTest.java
> +    @Autowired
ㄱㅎ ㅊㄱ ㅂㅌㅎㅇ🚀

2024-10-07 05:27 UTC, skylar1220 commented on backend/src/test/java/reviewme/review/service/abstraction/mapper/NewReviewMapperTest.java
> +    @Autowired
정답은 과학 최고 부탁해요였습니다~

2024-10-07 05:28 UTC, skylar1220 approved these changes

2024-10-07 05:28 UTC, donghoony commented on backend/src/test/java/reviewme/review/domain/abstraction/NewReviewTest.java
> +
좋와요~

2024-10-07 05:29 UTC, donghoony commented on backend/src/test/java/reviewme/review/service/abstraction/mapper/AnswerMapperFactoryTest.java
> +        // given
로그 확인하려고 찾아봤는데 이런 방법이 있더라고요~ 사용자에게는 예외 메시지가 구체적으로 보이지 않으니 이런 검증도 괜찮다고 봅니다

2024-10-07 05:31 UTC, donghoony commented on backend/src/main/java/reviewme/review/domain/abstraction/NewCheckboxAnswer.java
> +@EqualsAndHashCode(callSuper = true)
`super`까지 충족되어야 한다는 이야기네요 😮

2024-10-07 05:32 UTC, merged