[FE] feat: 리뷰 목록/리뷰 모아보기의 공통 UI 및 스위치 컴포넌트, 새 URL 및 디자인 적용
woowacourse-teams/2024-review-me pull request #776
Opened 2024-10-07 05:07 UTC by ImxYJL

- resolves #768 

---

### 🚀 어떤 기능을 구현했나요 ?
- 새 URL 추가: 리뷰 모아보기로 가는 URL 추가
  - 그에 따라 `Breadcrumb` 관련 로직도 수정했습니다.
- 리뷰 목록 및 리뷰 모아보기의 공통 UI 로직을 담는 `ReviewDisplayLayout` 제작
  - 리뷰 설명과 `OptionSwitch`를 제공하고, 메인 페이지 내용을 `children`으로 받아올 수 있습니다.
- 페이지 스위칭을 위한 `OptionSwitch`제작
- 목록 페이지에 새 디자인 반영
- 리뷰 모아보기 페이지인 `ReviewCollectionPage`의 기본 뼈대 제작
- 리뷰 목록 페이지 리팩토링에 따른 반응형 개선

### 🔥 어떻게 해결했나요 ?
- 

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- `OptionSwitch`를 2개 값만 받을 수 있음 + 하드코딩으로 짰는데 언젠가 배열 or 객체를 만들 수 있게끔 열어 두고 싶네요...😅
- 리뷰 모아보기 페이지의 이름을 임의로 지어봤습니다. (`ReviewCollectionPage`)
- 리뷰 목록에서 리뷰가 hover될 때의 디자인도 임의로 해봤습니다.
![image](https://github.com/user-attachments/assets/c736628c-b878-4b45-941d-9b4d587ae398)
- 반응형은 이런 느낌입니다.
![image](https://github.com/user-attachments/assets/7b140f4a-f97c-4903-ab1a-8914c49e130e)

### 📚 참고 자료, 할 말
- `ReviewDisplayLayout`에서 리뷰 설명과 `OptionSwitch`를 세로 정렬하는 반응형을 50rem부터 잡았습니다.
  모바일 환경(더 작은 width)에서만 적용하려고 했는데 500px 이하부터는 gap이 줄어들어서 이상하게 보이더라구요...
  기준점이 50rem이라 웬만한 태블릿에서는 가로 정렬로 보이긴 할 것 같습니다.

2024-10-08 06:03 UTC, chysis requested changes
바쁜 와중에 레이아웃 분리, breadcrumb, 스위치 컴포넌트까지 구현하느라 고생했어요! 몇 가지 수정하면 좋을 것 같아 코멘트 남겼는데 확인해주세요 :)👍👍

2024-10-08 06:03 UTC, chysis commented on frontend/src/components/common/Switch/styles.ts
> +export const CheckboxWrapper = styled.div<{ isChecked: boolean }>`
`isChecked`는 스타일링 관련 prop이라 `$isChecked`로 수정하는 것은 어떨까요?

2024-10-08 06:03 UTC, chysis commented on frontend/src/components/common/Switch/styles.ts
> +export const CheckboxLabel = styled.span<{ isChecked: boolean }>`
이 부분도 `$isChecked`로 수정하면 좋을 것 같아요!

2024-10-08 06:03 UTC, chysis commented on frontend/src/components/common/Switch/index.tsx
> +const Switch = ({ leftLabel, rightLabel, isLeftChecked, handleSwitchClick }: SwitchProps) => {
올리가 언급한 것처럼, 탭 개수가 충분히 늘어날 수 있을 것 같아 추후 리팩토링할 때 label 정보를 배열이나 객체로 받아도 좋을 것 같아요.

2024-10-08 06:03 UTC, chysis commented on frontend/src/components/layouts/ReviewDisplayLayout/index.tsx
> +      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
styled component를 사용하지 않고 div에 style을 준 이유가 있을까요?

2024-10-08 06:03 UTC, chysis commented on frontend/src/components/ReviewCard/styles.ts
> +  border-radius: 1rem;
목록 페이지의 ReviewCard의 border-radius가 기존의 0.8rem에서 1rem으로 바뀐 것 같아요. 디자인적으로 의도한 부분인지 궁금해요!

2024-10-08 06:03 UTC, chysis commented on frontend/src/components/layouts/ReviewDisplayLayout/index.tsx
> +      <S.Container>
여기서 styled component를 사용했군요!😅 커밋 단위로 보다 보니... 이전 코멘트는 신경 쓰지 않으셔도 됩니다

2024-10-08 06:03 UTC, chysis commented on frontend/src/components/layouts/ReviewDisplayLayout/styles.ts
> +  @media screen and (max-width: 50rem) {
media query 내부에서는 `px` 단위를 사용해야 해요! `rem`으로 적용되고 있어서 그런지 768px부터 옵션 스위치가 아래 줄로 내려가네요

2024-10-08 08:49 UTC, ImxYJL commented on frontend/src/components/layouts/ReviewDisplayLayout/styles.ts
> +  @media screen and (max-width: 50rem) {
나름 쿼리문 검색하고 적용했는데 지금 보니 그 어디에도 rem으로 쓴 곳이 없네요... 난 무엇을 봤던 것인가... (수정완)

2024-10-08 08:52 UTC, ImxYJL commented on frontend/src/components/common/Switch/styles.ts
> +export const CheckboxWrapper = styled.div<{ isChecked: boolean }>`
맞숩니다 수정하겠습니다. 그러고보니 styled emotion에 값을 넘겨줄 때도 인라인 스타일 대신 인터페이스로 만들어 전달하기로 했었는데 그것도 빼먹었네요 같이 수정할게요~~~

2024-10-08 09:01 UTC, ImxYJL commented on frontend/src/components/ReviewCard/styles.ts
> +  border-radius: 1rem;
기존에는 border-radius가 살짝 깎여 있었는데, 새로 적용된 디자인을 보면 더 둥그런 느낌이 들기도 하고 새 디자인을 기존 border에 적용하면 너무 딱딱해 보여서 border를 추가로 더 깎았습니다.

2024-10-09 06:42 UTC, ImxYJL commented on frontend/src/components/common/OptionSwitch/index.tsx
> +const OptionSwitch = ({ leftLabel, rightLabel, isReviewList, handleSwitchClick }: OptionSwitchProps) => {
확장성 + 태그 공사중입니다~~

2024-10-09 10:50 UTC, ImxYJL commented on frontend/src/components/common/OptionSwitch/index.tsx
> +const OptionSwitch = ({ leftLabel, rightLabel, isReviewList, handleSwitchClick }: OptionSwitchProps) => {
공통 컴포넌트는 리팩토링 완료했습니다!

2024-10-10 00:51 UTC, BadaHertz52 commented on frontend/src/components/ReviewCard/index.tsx
> +        <S.Footer>
main,footer가 시맨틱 태그로 레이아웃을 잡는 역할을 해서 그런지,
스타일 컴포넌트이기는 하지만, Main안에 Footer가 있는게 낯서네요.

2024-10-10 01:02 UTC, ImxYJL commented on frontend/src/components/ReviewCard/index.tsx
> +        <S.Footer>
저도 처음 봤을 때 조금 낯설었는데 임의로 고치기도 그래서 놔뒀었어요. 그런데 쓰다보니 스타일을 위한 레이아웃을 잡을 때 (네이밍 고민할 필요 없이) 생각보다 나쁘지 않게 쓸 수 있더라고요ㅋㅋㅋ 아마 이 컴포넌트에만 이렇게 스타일이 잡혀 있는데 통일성을 위해 바꾸는 게 나을까요?

2024-10-10 01:08 UTC, BadaHertz52 commented on frontend/src/hooks/useBreadcrumbPaths.ts
> +    breadcrumbPathList.push({ pageName: '리뷰 작성', path: -1 }, { pageName: '리뷰 작성 완료 페이지', path: pathname });
리뷰 작성에서 path -1 하면 간편하긴한데, 이 구조는 리뷰 작성 -> 리뷰 작성 완료 페이지로 가는 경로에서만 의도한대로 되겠지만 현재  url로 바로 리뷰 작성 완료 페이지를 접근할 수 있어서 이 경우에는 리뷰 작성 페이지가 아닌, 그 이전에 방문한 페이지로 이동하는 문제가 생겨요

가능하면 path에 리뷰 작성 페이지 router 경로를 달아주세요

2024-10-10 01:13 UTC, BadaHertz52 commented on frontend/src/pages/ReviewCollectionPage/index.tsx
> +        {Array(50)
```
 <div>리뷰 모아보기 페이지 children</div>
        {Array(50)
          .fill('스크롤바 없어서 생기는 layout shift 방지용 + Topbutton 확인용 더미 데이터입니다.')
          .map((data, index) => {
            return <p key={index}>{data}</p>;
          })}
```
이  부분은 api 가 적용되면 , 데이터를 불러와 목록, 리뷰 정리 컴포넌트 렌더링되는 건가요?

2024-10-10 01:16 UTC, BadaHertz52 requested changes
breadCrumb의 리뷰 작성 완료 경로시, 리뷰 작성 페이지에 대한 경로 문제가 있어서 request  cahgnes 남겼어요. 관련 코멘트 확인해주세요

2024-10-10 02:34 UTC, ImxYJL commented on frontend/src/hooks/useBreadcrumbPaths.ts
> +    breadcrumbPathList.push({ pageName: '리뷰 작성', path: -1 }, { pageName: '리뷰 작성 완료 페이지', path: pathname });
반영 완료했습니다~~~

2024-10-10 02:35 UTC, ImxYJL commented on frontend/src/pages/ReviewCollectionPage/index.tsx
> +        {Array(50)
넵 아마 에프이~쑤쑤가 Collection 페이지 작업한 게 여기 안에 들어가있을 거예요!

2024-10-10 04:49 UTC, soosoo22 approved these changes
올리! 리뷰 목록에서 모아보기로 이동할 수 있는 멋있는 탭을 만드셨군요! 목록 페이지 레이아웃과 디자인까지 하셨다니!! 정말 수고하셨습니다! 디자인 건의사항은 추후에 반영해도 좋으니 지금은 바빠서 살짝만 읽고 넘어가주세요~

### ☀️건의 사항☀️
1. 목록 보기 탭 위치
목록 보기 탭을 감싸는 div에 `position: relative`를 주고 목록 보기 탭에 `position: absolute`를 줘서 `right:0; bottom:0`을 줘서 "쑤쑤가 받은 리뷰 목록이에요"와 같은 라인에 맞출 수 있을 것 같아요!

<img width="967" alt="스크린샷 2024-10-10 오전 11 38 55" src="https://github.com/user-attachments/assets/d3eca634-26dc-40bc-80fa-531c7c5392b8">


2. 목록보기 탭에 글자 크기(CheckboxLabel)를 1.2rem에서 1.4rem으로 변경해도 괜찮을 것 같아요! 아주 살짝 작은감이 있어서요.

3. 목록보기 탭에서 모아보기 탭으로 이동 시, 살짝 애니메이션을 넣으면 좋을 것 같아요!
4. 리뷰 목록 페이지에서 리뷰 카드 디자인은 좀 더 고민해보고 코멘트 남길게요!!

2024-10-10 04:49 UTC, soosoo22 commented on frontend/src/components/ReviewCard/styles.ts
> +  background-color: ${({ theme }) => theme.colors.lightGray};
바로 반영하지 않아도 괜찮아요! 건의만 드립니다 올리!

### 🍀건의사항🍀
1. 리뷰 카드 안에 날짜를 기입해야 한다면 배경색은 없어도 괜찮을 것 같아요. 우측 하단에 혼자만 덩그러니 배경색이 있어서 살짝 아쉬운 것 같아요!
2. 리뷰 카드 안에 날짜를 기입하지 않고 리뷰 카드 상단에 날짜를 기입해서 해당 날짜에 받은 리뷰 카드들을 밑에 나열하는 방법이 있을 것 같아요. 그러고 카드 안에 날짜 영역은 모두 지우고요. 다만 이러면 문제점이 같은 날짜에 받은 리뷰가 많을 경우 날짜를 확인하고 때, 상단으로 이동해야 한다는 불편함이 있겠네요.

2024-10-10 04:49 UTC, soosoo22 commented on frontend/src/components/common/OptionSwitch/index.tsx
> +          <S.CheckboxButton type="button" $isChecked={option.isChecked}>
버튼 타입을 명시해주셨군요! 👍

2024-10-10 04:49 UTC, soosoo22 commented on frontend/src/hooks/useBreadcrumbPaths.ts
> +  const breadcrumbPathList: Path[] = [{ pageName: '리뷰 연결', path: `${ROUTE.reviewZone}/${reviewRequestCode}` }];
오! breadcrumb pageName도 변경해주셨군요!👍

2024-10-10 04:49 UTC, soosoo22 commented on frontend/src/pages/ReviewCollectionPage/index.tsx
> +        {Array(50)
넵~ 맞습니다! 모아보기 페이지에서 드롭박스, 아코디언, 차트 등이 들어갑니다!

2024-10-10 04:52 UTC, BadaHertz52 commented on frontend/src/components/ReviewCard/index.tsx
> +        <S.Footer>
저는 추후 리팩토링 과정에서 스타일 컴포넌트명 바꾸는 것을 추천해줘

2024-10-10 04:53 UTC, BadaHertz52 approved these changes
breadCrumb 경로 수정된거 확인했습니다!!

Footer 스타일 컴포넌트 네이밍은 코멘트 달아놨어요. 이 부분은 추후 리팩토링때, 확인 부탁드립니다

2024-10-10 04:56 UTC, chysis approved these changes
추가 변경 사항들 확인했어요! 리팩토링은 잠시만 뒤로 미루는 거로...😊
고생했어요 올리!

2024-10-10 04:57 UTC, merged