[BE] 중복 요청 방지 기능 구현
woowacourse-teams/2024-review-me pull request #781
Opened 2024-10-07 07:12 UTC by nayonsoso

---

### 🚀 어떤 기능을 구현했나요 ?
- 중복 요청 방지 기능을 구현했습니다.

### 🔥 어떻게 해결했나요 ?
- 커밋 따라서 쭉쭉 읽으시면 이해가 편하실거예요.
- 그리고 테스트 코드도 쭉 읽으면 완전 이해 완료하실 수 있습니다💡
- 요청을 받아서, 중복 로직 방지 로직을 수행하는 곳은 "인터셉터"입니다.
- 요청 거부 전략으로는 POST 요청에 대해서, 
- ‼️1초 동안 동일한 URI, public IP, User-Agent 의 조합으로 3번 초과 요청이 오면‼️
- 그 이후부터 429 응답을 내려줍니다.

![image](https://github.com/user-attachments/assets/fed8737b-ff9a-4bd4-8554-7fd3847a4913)
![image](https://github.com/user-attachments/assets/fe4fab2d-7696-44ca-8bea-31783a0a235d)

⬆️ 위 사진은 Jmeter (반복 요청을 보낼 수 있는 도구) 를 사용해서 1초동안 여러번의 요청을 보내본 결과입니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 중복 요청 거부 로직에 대해서, 이해가 어려운 부분들 있다면 바로 질문해주세요

### 📚 참고 자료, 할 말

2024-10-07 12:02 UTC, donghoony requested changes

2024-10-07 12:02 UTC, donghoony commented on backend/src/main/resources/application.yml
> +  port: 6379
라인 끝 개행 부탁해요~

2024-10-07 12:02 UTC, donghoony commented on backend/src/main/java/reviewme/config/RedisConfig.java
> +    private int port;
`@Value` 대신 `@ConfigurationProperties`를 사용하면 어떨까요? yml에서 직접 읽어올 수도 있고, 응집도가 올라간다고 생각해요

2024-10-07 12:02 UTC, donghoony commented on backend/src/main/java/reviewme/global/DuplicateRequestInterceptor.java
> +    private static final Duration DURATION = Duration.of(1, ChronoUnit.SECONDS);
`Duration.ofSeconds(1)` 은 어떨까요 ?

2024-10-07 12:02 UTC, donghoony commented on backend/src/main/java/reviewme/global/DuplicateRequestInterceptor.java
> +        return true;
이부분은 한 번 생각해보겠습니다 🤔

2024-10-07 12:02 UTC, donghoony commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +    @ExceptionHandler(TooManyDuplicateRequestException.class)
(네이밍) `Duplicate`는 없어도 될 듯합니다! `TooManyRequestException`으로도 충분하다고 생각해요

2024-10-07 12:02 UTC, donghoony commented on backend/src/main/java/reviewme/global/exception/TooManyDuplicateRequestException.java
> +        log.info("Too many duplicate request arrived: {}", requestKey);
`duplicate` 없어도 될 듯해요 2

2024-10-07 13:05 UTC, skylar1220 requested changes
산따최!!
어려워보이는데 구현해냈고나🚀🚀

2024-10-07 13:05 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/global/exception/TooManyDuplicateRequestException.java
> +        log.info("Too many duplicate request arrived: {}", requestKey);
소소한 제안)
arrived 대신 클라이언트-서버 관점의 단어로 received가 어떨까요?

2024-10-07 13:05 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/global/DuplicateRequestInterceptor.java
> +        }
찾아보니 있으면 기존 value에 1 증가 시켜주는 일을 해주는 `redisTemplate.opsForValue().increment(key)` 라는 메서드가 있는 것 같은데 직접 구현한 이유가 있을까요?

2024-10-07 13:05 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/global/DuplicateRequestInterceptor.java
> +    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) {
value로는 무조건 숫자가 오는 것 같은데 int 나 long이 아닌 object를 사용한 이유가 궁금해요~

2024-10-07 13:05 UTC, skylar1220 commented on backend/src/test/java/reviewme/global/DuplicateRequestInterceptorTest.java
> +        int maxFrequency = 3;
3부터 예외를 반환하니 maxFrequency를 경계값인 2로 하는 건 어떨까요?

2024-10-10 01:37 UTC, donghoony commented on backend/src/main/java/reviewme/global/DuplicateRequestInterceptor.java
> +    private static final Duration DURATION = Duration.of(1, ChronoUnit.SECONDS);
지금 보니 1초를 `DURATION`이라는 변수에 저장했네요. `SECOND`로 의미를 담는 건 어떨까요 ?

2024-10-10 01:37 UTC, donghoony commented on backend/src/main/java/reviewme/global/DuplicateRequestInterceptor.java
> +public class DuplicateRequestInterceptor implements HandlerInterceptor {
인터셉터 차원에서 로깅할 필요는 없을까요? 넘어가면 WARN 정도로 로그 찍어주면 좋겠어요!

2024-10-10 01:37 UTC, donghoony commented on backend/src/main/java/reviewme/global/DuplicateRequestInterceptor.java
> +        String userAgent = request.getHeader("User-Agent");
`HttpHeaders.USER_AGENT` 상수가 있습니다 👍🏻

2024-10-10 01:37 UTC, donghoony commented on backend/src/main/java/reviewme/global/DuplicateRequestInterceptor.java
> +        }
코드상으로 절대 일어날 수 없는 사항같은데, 무시해도 되지 않을까요? 클라이언트의 악의적인 요청 맥락이 아니라서, 충분히 저희가 핸들링할 수 있다고 생각해요.

2024-10-10 01:37 UTC, donghoony commented on backend/src/main/java/reviewme/global/DuplicateRequestInterceptor.java
> +        }
이거 좋네요 👍🏻

2024-10-10 01:49 UTC, Kimprodp requested changes
산초 커밋과 테스트를 읽으니 깔끔하게 이해가 잘 되네요👍👍
고생했습니다 코멘트만 확인 부탁해요~

2024-10-10 01:49 UTC, Kimprodp commented on backend/src/main/java/reviewme/global/DuplicateRequestInterceptor.java
> +    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) {
object는 override 메서드라 못바꾸지 않나요?

2024-10-10 01:49 UTC, Kimprodp commented on backend/src/main/java/reviewme/config/WebConfig.java
> +        registry.addInterceptor(new DuplicateRequestInterceptor(redisTemplate));
요긴 경로 설정 따로 안하면 디폴트가 전체 경로인가요?

2024-10-10 01:49 UTC, Kimprodp commented on backend/src/main/java/reviewme/global/exception/TooManyDuplicateRequestException.java
> +        super("짧은 시간 안에 너무 많은 동일한 요청이 일어났어요");
요청 제한 로직에 대한 정보를 클라이언트에 응답해도 괜찮을까요?  유추할 수 있는 정보는 제외하면 좋을 것 같다는 생각입니다~

2024-10-10 01:49 UTC, Kimprodp commented on backend/src/main/java/reviewme/global/DuplicateRequestInterceptor.java
> +            throw new TooManyDuplicateRequestException(key);
맥락상 key 말고 frequency 를 전달하는 것이 더 읽는 데 자연스러운 것 같아요~

2024-10-10 01:52 UTC, donghoony commented on backend/src/main/java/reviewme/global/DuplicateRequestInterceptor.java
> +        }
중간에 분기를 일으키지 않고, 아래와 같이 하면 어떤가요?
```java
redisTemplate.opsForValue().setIfAbsent(key, 0, DURATION);
redisTemplate.opsForValue().increment(key);
requestCount = redisTemplate.opsForValue().get(key);
```

2024-10-12 11:57 UTC, skylar1220 commented on backend/src/main/java/reviewme/global/DuplicateRequestInterceptor.java
> +    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) {
앗 설명이 부족했네요
`RedisTemplate<String, Object> redisTemplate;` 부분을 말합니다!

2024-10-14 23:45 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/DuplicateRequestInterceptor.java
> +    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) {
레디스의 '사용 확장성'을 생각했어요!
레디스에 반드시 Integer 이나 Long 과 같은 값을 담을게 아니라,
"세션의 정보"와 같은 것들도 담을 수 있게 될 것 같아요.
(무중단 배포로 sticky session 을 사용하지 않게 되면 곧 우리가 해야 할 일이기도 하고요😅)

그런데 지금 숫자로 value 를 한정하면, 나중에 다른 형태의 값을 저장할 때 기존 기능에 영향을 주게 될 것 같아요.
그래서 Object 를 저장하게 해준 것입니다!

2024-10-14 23:48 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +    @ExceptionHandler(TooManyDuplicateRequestException.class)
`TooManyRequestException` 은 요청 자체가 너무 많아서 서버가 처리할 수 없다는 뉘앙스인 것 같아요,
이 예외가 발생하는 상황은 그런게 아니니까 구분하기 위해서라도 Duplicate를 붙이고 싶어요!

2024-10-14 23:59 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/DuplicateRequestInterceptor.java
> +    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) {
추가))

저는 어플리케이션에 하나의 RedisTemplate 을 추가할 수 있을거라 생각했는데, 알고보니 아니었네요🫨 세션같은 정보를 저장할때는 그에 맞는 형식의 RedisTemplate 을 추가하도록 하고, 중복 요청정보를 저장할 때는 `RedisTemplate<String, Integer>` 로 저장하도록 하겠습니다!

그리고 여러개의 RedisTemplate을 사용하더라도 저장을 할 때는 하나의 레디스에 key 와 value 모두 String 으로 직렬화해서 사용해서 상관 없다고 합니다😊 커비가 짚어준 덕분에 더 효율적으로 코드를 작성하게 되었어요!!!! 커비 최고최고😍

2024-10-15 00:01 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/DuplicateRequestInterceptor.java
> +        }
이렇게 한 배경은...

redisTemplate.opsForValue().increment(key) 는 value 에 해당하는 값이 numeric 이 아니면 예외가 발생해요. 그런데 저는 RedisTemplate 의 value 는 확장성을 위해서 Integer 나 Long 이 아니라 Object 여야 한다고 생각해요!

였지만 커비의 제안으로 RedisTemplate<String, Integer> 로 형식을 바꾸게 됨으로써 저 메서드를 사용하도록 바꿨습니다🫡

2024-10-15 00:05 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/DuplicateRequestInterceptor.java
> +        String userAgent = request.getHeader("User-Agent");
음~ 맛있다~😋

2024-10-15 00:21 UTC, nayonsoso commented on backend/src/test/java/reviewme/global/DuplicateRequestInterceptorTest.java
> +        int maxFrequency = 3;
3번째 요청까지는 받고, 4번째 요청부터 리젝합니다!

2024-10-15 00:21 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/exception/TooManyDuplicateRequestException.java
> +        log.info("Too many duplicate request arrived: {}", requestKey);
반완~

2024-10-15 00:22 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/DuplicateRequestInterceptor.java
> +public class DuplicateRequestInterceptor implements HandlerInterceptor {
음~~ 맛있다😋 너무 좋은 관점이네요!!

2024-10-15 00:25 UTC, nayonsoso commented on backend/src/main/java/reviewme/config/WebConfig.java
> +        registry.addInterceptor(new DuplicateRequestInterceptor(redisTemplate));
네! 디폴트가 모든 경로로 알고 있어요.
그래도 명시하는편이 좋을까요?

2024-10-15 00:27 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/exception/TooManyDuplicateRequestException.java
> +        super("짧은 시간 안에 너무 많은 동일한 요청이 일어났어요");
저는 이 메세지가 "요청 제한 로직에 대한 정보"라기보다,
"너무 많이 요청했으니 잠시 있다가 다시 시도해주세요" 라는 식의 메세지라고 봤어요!
사용자를 도와주는 메세지라 괜찮다고 봅니다👀

2024-10-15 00:32 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/DuplicateRequestInterceptor.java
> +            throw new TooManyDuplicateRequestException(key);
key 를 전달하면 이렇게 로깅되는데,

Too many duplicate request received: RequestURI: /v2/groups, RemoteAddr: 127.0.0.1, UserAgent: Apache-HttpClient/4.5.14 (Java/21.0.4)

value(frequency) 를 전달하면 이렇게 로깅됩니다.

Too many duplicate request received: 4

key 를 전달하는게 더 맥락을 잘 전달한다고 생각해요~

2024-10-15 00:33 UTC, nayonsoso commented on backend/src/main/resources/application.yml
> +  port: 6379
Too many duplicate request received:

2024-10-15 00:33 UTC, nayonsoso commented on backend/src/main/java/reviewme/config/RedisConfig.java
> +    private int port;
반완!

2024-10-15 00:33 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/DuplicateRequestInterceptor.java
> +    private static final Duration DURATION = Duration.of(1, ChronoUnit.SECONDS);
반완완~

2024-10-15 00:33 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/exception/TooManyDuplicateRequestException.java
> +        log.info("Too many duplicate request arrived: {}", requestKey);
Ditto!

2024-10-15 00:43 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/DuplicateRequestInterceptor.java
> +        }
음~~ setIfAbsent 맛있다😋
제공되는 함수들로 로직을 개선할 수 있는지 더 꼼꼼히 확인해야겠네요😅
반영했습니다!

![image](https://github.com/user-attachments/assets/f4d10a97-0057-4bb5-8858-d48f6f3c3c09)
이런 노란줄이 뜨긴 하는데, 로직상 발생할 수 없으니 괜찮겠죠?

2024-10-15 00:56 UTC, donghoony commented on backend/src/main/java/reviewme/global/DuplicateRequestInterceptor.java
> +        }
바로 위에서 `setIfAbsent`를 해서 괜찮다고 생각하기는 해요 🤔

2024-10-15 00:57 UTC, donghoony commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +    @ExceptionHandler(TooManyDuplicateRequestException.class)
다른 단어를 선택하는 건 어떨까요? `duplicate`는 정말 완벽히 같은 복제본의 느낌인데, 본문이 다르더라도 많은 요청이 막힐 수 있는 부분이라서요. 🤔

2024-10-15 00:58 UTC, donghoony commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +    @ExceptionHandler(TooManyDuplicateRequestException.class)
`Many`와 `Duplicate`의 의미가 중복돼 클래스 이름이 어색해서 남긴 리뷰였습니다~

2024-10-15 01:05 UTC, donghoony commented on backend/src/main/java/reviewme/global/DuplicateRequestInterceptor.java
> +    private static final Duration DURATION = Duration.of(1, ChronoUnit.SECONDS);
MAX_FREQ, Duration도 config로 옮기면 어떤가요?

2024-10-15 01:21 UTC, donghoony commented on backend/src/main/java/reviewme/global/DuplicateRequestInterceptor.java
> +public class DuplicateRequestInterceptor implements HandlerInterceptor {
충분하겠습니다~

2024-10-15 05:36 UTC, nayonsoso commented on backend/src/test/resources/application.yml
> +  port: 6379
이 설정은 test/application.yml 에 들어갑니다.
딱히 의미 있는 설정은 아니지만, 
스프링 부트 테스트를 할 때 "빈등록" 성공을 위해서 작성해주었습니다.
(어플리케이션에서 yml 로부터 값을 읽어와서 빈을 등록하니깐요~)
조금 찝찝하긴 한데 이게 최선이라 생각해서 이렇게 해놨어요😅

2024-10-15 05:37 UTC, donghoony commented on backend/src/test/resources/application.yml
> +  port: 6379
테스트용 configuration에 `Properties`를 새로 만든 `Template`을 등록할 수도 있습니다

2024-10-15 05:41 UTC, Kimprodp commented on backend/src/main/java/reviewme/global/exception/TooManyDuplicateRequestException.java
> +        super("짧은 시간 안에 너무 많은 동일한 요청이 일어났어요");
그렇다면요 슨초 말대로 정상적인 요청이지만 어떤 이유로 중복되어서 짧은 시간 안에 요청이 들어온 경우 다시 안내하는 것을 의도하는 것이니, 마지막에 '잠시 후 다시 시도해주세요' 라는 문구를 추가하면 더 좋을 것 같아요!

2024-10-15 05:42 UTC, Kimprodp commented on backend/src/main/java/reviewme/config/WebConfig.java
> +        registry.addInterceptor(new DuplicateRequestInterceptor(redisTemplate));
아뇨 몰랐어용 지금 괜찮다고 봅니다!

2024-10-15 05:44 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/GlobalExceptionHandler.java
> +    @ExceptionHandler(TooManyDuplicateRequestException.class)
> 본문이 다르더라도 많은 요청이 막힐 수 있는 부분이라서요.
> Many와 Duplicate의 의미가 중복돼 클래스 이름이 어색해서 남긴 리뷰였습니다~

아하 그럴수도 있겠네요..! 이해됩니다 ㅎㅎ

`TooManyRequestException`로 하겠습니다~
찾아보니 429 자체에 "특정 사용자"라는 뉘앙스가 있기도 하네요 

![image](https://github.com/user-attachments/assets/76258aaa-402f-480a-8883-01770c62470d)

2024-10-15 05:58 UTC, Kimprodp approved these changes
신초 고생했읍니다. 빨리 적용하고 중복요청 보내보고 싶어요 👍👍

2024-10-15 06:48 UTC, donghoony approved these changes
따닥 미워

2024-10-15 06:50 UTC, skylar1220 approved these changes
어렵다.. 산초 최고🚀🚀🚀🚀

2024-10-15 06:53 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/exception/TooManyDuplicateRequestException.java
> +        super("짧은 시간 안에 너무 많은 동일한 요청이 일어났어요");
반완입니다~

2024-10-15 06:53 UTC, nayonsoso commented on backend/src/main/java/reviewme/global/DuplicateRequestInterceptor.java
> +    private static final Duration DURATION = Duration.of(1, ChronoUnit.SECONDS);
반완완~~

2024-10-15 07:32 UTC, merged