[BE] docs: 리뷰 모아보기 RestDocs 작성
woowacourse-teams/2024-review-me pull request #785
Opened 2024-10-07 13:36 UTC by nayonsoso

- resolves #782

---

### 🚀 어떤 기능을 구현했나요 ?
- 오늘 프엔 / 백엔 3대 2로 대결했던 API 문서 회의를 RestDocs 로 만들었습니다.

### 🔥 어떻게 해결했나요 ?
- URI 와 응답 객체를 생성했습니다.
- 컨트롤러와 서비스 코드 뼈대를 만들었습니다.
- RestDocs api test 에서 서비서 코드를 모킹해서 정해진 응답을 반환하게 stub 한 후, 실제 응답과 비교하는 테스트를 작성했습니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 이 PR을 기준으로 이후의 작업이 진행될 것 같으니, uri 나 ResponseDto 이름 같은 것들 만족스럽지 않은 부분들 있으시면 리뷰해주세요. (각자 하다가고치면 컨틀릭 발생🙀)

### 📚 참고 자료, 할 말
- 전체 테스트 실행 -> clean -> build 후 resources -> static 하위에 있는 index.html 로 직접 확인해주세용!

2024-10-07 22:40 UTC, skylar1220 requested changes
어떻게 구현할지 백엔드끼리도 합의되고 api 문서 작성 먼저 역시 좋네요!! 
회의부터 문서까지 수고했어요~~
I left 소소쓰 질문쓰~~

+ URL에 대해서는 같이 얘기해봐요!

2024-10-07 22:40 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/review/service/dto/response/list/ReceivedReviewSummaryResponse.java
> +public record ReceivedReviewSummaryResponse(
여러 리뷰들의 요약이라는 의미니 ReceivedReivew's'SummaryResponse는 어떨까요?

2024-10-07 22:40 UTC, skylar1220 commented on backend/src/main/java/reviewme/template/service/dto/response/SectionNameResponse.java
> +        long id
다른 reponse와 동일하게 id가 위에 있는 건 어떨까요?

2024-10-07 22:40 UTC, skylar1220 commented on backend/src/docs/asciidoc/index.adoc
review-gather.adoc 도 추가해야겠네요!

2024-10-07 22:40 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/dto/response/gathered/QuestionResponse.java
QuestionReponse라는 동일명의 response가 다른 패키지에 이미 존재해서 문제가 없으려나 생각이 들었는데요,
reponse는 재사용하지 않는다는 합의가 있었으니 위치한 패키지를 잘 보고 쓰면 되는 거겠죠..?
아니면 네이밍에 좀 더 의미를 담는 게 좋을까요?

2024-10-07 22:40 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/dto/response/gathered/GatheredReviewResponse.java
> +public record GatheredReviewResponse(
해당 응답은 섹션 내의 질문별 응답이네요!
그렇다면 QuestionReviewResponse 이런 네이밍은 어떨까요?

2024-10-08 01:24 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/dto/response/list/ReceivedReviewSummaryResponse.java
> +public record ReceivedReviewSummaryResponse(
밖에서 재사용될 걸 생각해서 `ReviewGroupSummary`는 너무 방대한 개념일까요?

2024-10-08 04:55 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/dto/response/list/ReceivedReviewSummaryResponse.java
> +public record ReceivedReviewSummaryResponse(
기존의 ReceivedReviewSummaryResponse
커비의 ReceivedReivewsSummaryResponse
아루의  ReviewGroupSummaryResponse
모두 좋은 의견들이네요~

1. Review vs Group
이 response dto 에 들어가는 값은 [리뷰이 이름 / 프로젝트 이름 / 받은 리뷰 전체 개수] 예요. 이 중, 리뷰이 이름 & 프로젝트 이름은 리뷰 그룹에 해당하고 받은 리뷰 전체 개수는 리뷰에 해당하는 정보라서 생각이 갈리는 것 같아요.
그런데 사용되는 방식을 보면, '❗️어떤 이름으로, 어떤 프로젝트에 대해서 받은 리뷰❗️가 몇개인지'를 알려주기 위해 사용되고 있어요. 이런 맥락을 봤을 때 저는 리뷰에 대한 정보에 더 가깝다고 생각해요!

2. Reviews vs Review
리뷰들에 대한 요약이니 Reviews 가 더 적절하다는 커비 의견에 설득되었습니당~ 반영할게요!

2024-10-08 04:57 UTC, nayonsoso commented on backend/src/main/java/reviewme/template/service/dto/response/SectionNameResponse.java
> +        long id
반영했습니다!

2024-10-08 04:58 UTC, nayonsoso commented on backend/src/docs/asciidoc/index.adoc
추가했습니다😊

2024-10-08 05:00 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/dto/response/gathered/QuestionResponse.java
동일한 이름의 클래스가 있으면 헷갈릴 것 같긴 한데요😅
그렇다고 '다른 패키지에 같은 이름의 패키지가 있으니 이름을 바꿔야지~'는 아닌 것 같습니다. 클래스 이름 지을 때 외부 요인이 이유가 되면 안될 것 같아요.
패키지 잘 보고 & 인자 잘 보고 하면 된다 생각해요!

2024-10-08 05:01 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/dto/response/gathered/QuestionResponse.java
이건 다르게 명명하는 게 낫겠습니다.

2024-10-08 05:05 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/dto/response/gathered/QuestionResponse.java
+ 추가)

아루의 오프라인 피드백 "패키지와 클래스 이름이 독립적이어야 한다는 말도 맞지만, 하나의 어플리케이션에서는 같은 이름의 클래스가 있다면 헷갈릴 수 있으니 이름 바꾸는게 좋을 것 같다"를 받고 SimpleQuestionResponse 로 변경했습니다~

2024-10-08 05:10 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/dto/response/gathered/GatheredReviewResponse.java
> +public record GatheredReviewResponse(
의미를 더 전달해야 한다는 것 동의합니다.
그래서 이렇게 바꿔봤어요,

- GatheredReviewsResponse ➡️ ReviewsGatherBySectionResponse
- GatheredReviewResponse ➡️ 
ReviewsGatherByQuestionResponse

2024-10-08 05:37 UTC, donghoony approved these changes
오프라인으로 이야기했습니다~!
주로 이야기한 내용으로는:
- `@Nested` 클래스명에 Non-ascii 문자가 들어가면 빌드가 안된다.
  - `@DisplayName`을 `@Nested`에 한해 사용한다.
- 문서 가독성 및 구조화
- Dto 네이밍

입니다~

2024-10-08 06:01 UTC, Kimprodp approved these changes
기대가 됩니다

2024-10-08 07:17 UTC, hyeonji1220 approved these changes

2024-10-08 07:36 UTC, merged