[FE] feat: 리뷰 모아보기 페이지의 공통 컴포넌트 구현 및 퍼블리싱
woowacourse-teams/2024-review-me pull request #790
Opened 2024-10-08 05:39 UTC by chysis

- resolves #773 

---

### 🚀 어떤 기능을 구현했나요 ?
- 리뷰 모아보기 페이지에서 사용되는 Dropdown, Accordion 공통 컴포넌트를 구현했습니다.
- 공통 컴포넌트를 사용해서 리뷰 모아보기 페이지를 작성했습니다.

### 🔥 어떻게 해결했나요 ?

### Dropdown vs Accordion
- 두 컴포넌트 모두 클릭했을 때 펼쳐지고, 내부에 content를 갖는다는 공통점이 있습니다.
- UI상 가장 큰 차이점은 z-index입니다. 드롭다운은 다른 요소 위로 펼쳐져서 영향을 주지 않고, 아코디언은 펼쳐진 만큼 자리를 차지합니다.
- 그밖에 색상, hover 처리 등 다양한 차이점이 있습니다.

### 목 데이터를 사용해서 임시 퍼블리싱
- 어제 백엔드와 함께 진행한 회의를 토대로 인터페이스를 설계했습니다. 회의한 구조에서 거의 바뀌지 않을 것이라 판단하여 목 데이터를 만들고, 이를 단순히 가져와 퍼블리싱 했습니다. 
- 드롭다운에서 섹션을 선택하면, 해당 섹션의 id로 서버에 요청을 보내서 세부 질문의 답변 내용을 한 번에 불러오게 됩니다(api 개발 뒤에에 react-query 사용해서 개발할 예정입니다). 그 중 첫 번째 질문(아코디언)은 펼쳐진 상태이고, 나머지는 닫혀있습니다. 
  - 객관식 질문인 경우 차트가 표시되고, 주관식 질문인 경우 답변 리스트가 출력됩니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 인터페이스 이름을 임의로 정했는데, 애매하거나 수정이 필요하다 생각되는 부분은 의견 남겨주세요!
- 지금은 목데이터를 단순히 출력만 하고 있지만, 엔드포인트가 나오면 fetch 모킹 및 react-query 적용할 예정입니다 :)

### 📚 참고 자료, 할 말
- 올리가 작업한 브랜치를 pull 받아서 작업했기 때문에 file changes가 많을 텐데, 머지되면 줄어들 예정이에요. 커밋 단위로 보는 게 편할 것 같아요

2024-10-08 11:36 UTC, ImxYJL requested changes
예쁜 공통 컴포넌트들 만드느라 수고 많았어요~~
약간의 수정사항과 궁금한 점들 남겼습니다!

2024-10-08 11:36 UTC, ImxYJL commented on frontend/src/components/common/Dropdown/styles.ts
> +  transform: ${({ $isOpened }) => ($isOpened ? 'rotate(180deg)' : 'rotate(0deg)')};
ANIMATION까지~~~
그리고 컨벤션에 나와있지는 않은데 저번에 styled에 props 넘길 때도 인터페이스 만들어서 넘기자고 했습니당

2024-10-08 11:36 UTC, ImxYJL commented on frontend/src/components/common/Accordion/index.tsx
> +  initiallyOpened?: boolean;
불리언 값이니까 `isInitiallyOpened`나 `isOpendAtFirst` 등으로 수정해보면 좋을 것 같아욥

2024-10-08 11:36 UTC, ImxYJL commented on frontend/src/components/common/Accordion/index.tsx
> +const Accordion = ({ title, initiallyOpened = false, children }: EssentialPropsWithChildren<AccordionProps>) => {
알고 계셨을 수도 있지만 저는 몰랐기 때문에~ details, summary 태그를 이용해 3분 아코디언을 만들 수 있다고 합니다. 적용해달라는 건 아닙니다ㅎㅎ ([링크](https://velog.io/@hyeonq/details-summary-%ED%83%9C%EA%B7%B8%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%B4-%EB%A7%8C%EB%93%A0-%EC%95%84%EC%BD%94%EB%94%94%EC%96%B8Accordion%EC%97%90-%EC%95%A0%EB%8B%88%EB%A9%94%EC%9D%B4%EC%85%98-%EC%9E%85%ED%9E%88%EA%B8%B0))
그리고 이왕 위/아래 버튼이 돌아가는 김에 아코디언을 펼쳤다 접었다 할 때도 샤라락 애니메이션이 있었으면... 이건 있으면 좋을지도....,

2024-10-08 11:36 UTC, ImxYJL commented on frontend/src/components/common/Dropdown/styles.ts
> +export const ItemContainer = styled.ul`
드롭다운을 ul/li 태그를 이용해 만들어주셨는데, 특별한 이유가 있었는지 궁금해요.
접근성/모바일 지원 측면에서 select/option 태그 사용을 권장하더라구요

2024-10-08 11:36 UTC, ImxYJL commented on frontend/src/components/common/Dropdown/index.tsx
> +        <S.SelectedOption>{selectedOption}</S.SelectedOption>
현재 선택된 옵션을 보여주는 내용 외에는 화살표 이미지만 있는데, 화살표 이미지는 꾸밈 요소이니 사실상 한 줄에 중요한 내용이 하나만 있는 것 같아요. 그래서 저라면 p 태그를 쓰고 inline-block을 썼을 것 같은데 이에 대한 에프이의 생각이 궁금합니다~

2024-10-08 11:36 UTC, ImxYJL commented on frontend/src/components/common/Dropdown/styles.ts
> +export const DropdownContainer = styled.div`
아직 공통 컴포넌트들의 반응형이 적용되지 않은 건가욥?

2024-10-08 11:36 UTC, ImxYJL commented on frontend/src/components/common/OptionSwitch/index.tsx
> +      </S.CheckboxWrapper>
여기 제 코드인데 앞에 `$`붙여놨습니다...하하
하드코딩도 고쳐둘게요... (누가 여기 고쳐달라고 리뷰 달까봐 선수치기)

2024-10-08 11:36 UTC, ImxYJL commented on frontend/src/hooks/useDropdown.ts
> +    setIsOpened(false);
오호 이렇게 내부 상태도 설정하고 외부 핸들러에 값도 전달할 수 있겠네용

2024-10-08 11:36 UTC, ImxYJL commented on frontend/src/hooks/useDropdown.ts
> +  }, [dropdownRef]);
👍

2024-10-08 11:36 UTC, ImxYJL commented on frontend/src/mocks/mockData/reviewCollection.ts
> +            '고액공제건강보험과 건강저축계좌를 만들어 노동자와 고용주가 세금공제를 받을 수 있도록 하면 결과적으로 노동자의 의료보험 부담이 커진다.',
더미 데이터 출처가 어디죠...?ㅋㅋㅋㅋ

2024-10-08 13:27 UTC, chysis commented on frontend/src/components/common/Dropdown/styles.ts
> +  transform: ${({ $isOpened }) => ($isOpened ? 'rotate(180deg)' : 'rotate(0deg)')};
맞네요! 이 부분은 수정하겠습니다

2024-10-08 13:44 UTC, chysis commented on frontend/src/mocks/mockData/reviewCollection.ts
> +            '고액공제건강보험과 건강저축계좌를 만들어 노동자와 고용주가 세금공제를 받을 수 있도록 하면 결과적으로 노동자의 의료보험 부담이 커진다.',
한국어 긴 문장을 검색했던 것 같네요....😅😅

2024-10-08 13:47 UTC, chysis commented on frontend/src/components/common/Dropdown/styles.ts
> +export const DropdownContainer = styled.div`
드롭다운의 경우엔 width가 240px로 고정되어 있어서, 별도의 반응형 구현을 하지 않았어요! 320px 모바일에서도 잘림 없이 잘 표시됩니다 :)

2024-10-08 15:48 UTC, chysis commented on frontend/src/components/common/Dropdown/styles.ts
> +export const ItemContainer = styled.ul`
select, option 태그의 경우 브라우저나 OS별 기본 속성이 강하게 적용되어 있어 자유로운 스타일링이 어렵다는 단점이 있어요. 특히 커스텀 레이아웃을 적용하기 힘들어서 div와 ul, li 태그를 사용해서 구현했어요!

2024-10-08 16:01 UTC, chysis commented on frontend/src/components/common/Dropdown/index.tsx
> +        <S.SelectedOption>{selectedOption}</S.SelectedOption>
p 태그와 inline-block을 어떻게 적용하는 것을 의미하는지 좀 더 설명을 들어볼 수 있을까요?

2024-10-09 06:22 UTC, ImxYJL commented on frontend/src/components/common/Dropdown/styles.ts
> +export const ItemContainer = styled.ul`
페이먼츠 때 select 스타일 커스텀하려고 고통받던 크루들이 생각나네요...😂
빠르게 구현한 뒤 ul/li에 추가 접근성 개선해주기 VS 기본적으로 지원해주지만 스타일 깎아야 하는 select/option 사용하기겠네요
저는 에프이의 선택에 맡기겠습니다~!

2024-10-09 06:23 UTC, ImxYJL commented on frontend/src/components/common/Dropdown/index.tsx
> +        <S.SelectedOption>{selectedOption}</S.SelectedOption>
드롭다운에서, 선택 가능한 요소들은 사실상 한 줄에 자기 하나만 있으니 의미론적으로 p 태그를 사용할 것이고, span -> p로 변한 만큼 스타일링에 문제가 있다면 inline-block을 적용했을 거라는 의미였습니다!

2024-10-09 06:31 UTC, ImxYJL commented on frontend/src/components/common/Dropdown/styles.ts
> +export const DropdownContainer = styled.div`
제가 말씀드린 부분은 아래 두 가지 케이스였습니다ㅎㅎ
![image](https://github.com/user-attachments/assets/a2562efc-10d9-4a24-b50b-8ed65b8bf28d)

둘 다 반응형 미적용까지는 아니지만 화면이 작아졌을 때 어색하게 느낄 수도 있는 부분인 것 같아 질문드려요.
1. 화면이 작아졌을 때, 드롭다운이 애매하게(?) 오른쪽에 계속 위치
2. 마찬가지로 화면이 작을 때, 아코디언의 title이 한 줄을 넘어가는 경우 남은 줄들이 가운데 정렬되어 있음 (내용은 잘 보입니다!)

2024-10-09 06:53 UTC, chysis commented on frontend/src/components/common/Dropdown/styles.ts
> +export const DropdownContainer = styled.div`
1. 화면이 작아져서 OptionSwitch가 다음 줄로 내려갔을 때는 드롭다운도 같이 왼쪽 정렬되어 있는 편이 자연스러운 것 같아요. 그 기준이 500px인 것으로 기억하고 있어서, 저도 동일하게 맞춰서 수정해볼게요. (디자인적 요소라 나중에 다시 변경될 수 있어요)

2. 이 부분은 놓치고 있었네요 :) 왼쪽 정렬되도록 수정할게요

2024-10-09 08:52 UTC, chysis commented on frontend/src/components/common/Accordion/index.tsx
> +const Accordion = ({ title, initiallyOpened = false, children }: EssentialPropsWithChildren<AccordionProps>) => {
PR 메시지 쓸 때 토글이 필요하면 details, summary를 사용했던 기억이 나네요! 👍
말씀해주신 태그들은 추후 접근성을 개선할 때 도입을 고려해보겠습니다! 아코디언 애니메이션은 저도 필요하다 생각했어서 바로 도입했어요~!!

2024-10-10 00:37 UTC, ImxYJL commented on frontend/src/components/common/Dropdown/styles.ts
> +export const DropdownContainer = styled.div`
지금 보니 왼쪽 정렬도 나름대로 휑해 보이네요 🤣 아예 width:100%를 주는 것은...?! 에프이 말대로 어차피 디자인 요소니  가볍게 생각해주세요~

2024-10-10 00:40 UTC, ImxYJL approved these changes
리뷰 반영 고생 많았어요 👍👍전 어프룹합니다~~~

2024-10-10 01:24 UTC, BadaHertz52 commented on frontend/src/components/common/Accordion/styles.ts
> +  margin-top: ${({ $isOpened, $contentHeight }) => ($isOpened ? '0' : `-${$contentHeight}px`)};
```suggestion
  margin-top: ${({ $isOpened, $contentHeight }) => ($isOpened ? '0' : `-${$contentHeight /10}rem`)};
```

10으로 나누어서 rem 단위로 바꿀 수 있는 방법도 있습니다

2024-10-10 01:27 UTC, BadaHertz52 commented on frontend/src/components/common/Dropdown/index.tsx
> +        <S.ItemContainer>
질문의 section의 수에 비례해 click 이벤트가 늘어가는 구조네요
ItemContainer에서 click 이벤트를 주고, 이벤트 위임을 통해서 해결하는 방식도 한 번 생각해 보면 좋을 것 같아요.

2024-10-10 01:41 UTC, BadaHertz52 commented on frontend/src/components/common/Dropdown/styles.ts
> +export const DropdownContainer = styled.div`
지금 Q와 질문이 같이 있는데, Q( 질문 마크)와 질문을 분리해서 아래처럼 하는 거 어떨까요?
![Accordion Item](https://github.com/user-attachments/assets/3d717c14-069c-465e-a074-47730f48950c)

2024-10-10 01:45 UTC, BadaHertz52 commented on frontend/src/pages/ReviewCollectionPage/index.tsx
> +            {GROUPED_REVIEWS_MOCK_DATA.reviews.map((review, index) => {
다양한 컴포넌트와 스타일 컴포넌트들로 인해 구조가 복잡해서, 이 부분을 컴포넌트로 했으면 좋겠네요

2024-10-10 01:47 UTC, BadaHertz52 commented on frontend/src/types/review.ts
> +export interface ReviewAnswer {
객관식답변도 리뷰 답변이라, 주관식에 특화된 타입명이면 좋겠어요

그리고 형광펜 관련 데이터를 받아와야해서 이 부분은 추후에 형광펜 기능 합쳐지면서 수정될 것 같아서, 해당 내용 공유합니다

2024-10-10 02:31 UTC, soosoo22 approved these changes
에프이! 드롭다운과 아코디언을 공통 컴포넌트로 분리해서 아름다운 모아보기 페이지를 만들어 주셨군요!! 너무 수고하셨습니다. 디자인 관련해서 몇 가지 건의 사항이 있어서 코멘트 남길게요!

## ☀️건의 사항☀️

#### 1. AccordionContainer 패딩 추가
 AccordionContainer에 `padding: 1rem`을 줘서 전체적으로 여백을 줬으면 좋겠어요.

#### 2. AccordionTitle에 primary 컬러 적용
질문과 답변이 구분이 가질 않아서, AccordionTitle의 primary 컬러를 넣었으면 좋겠어요.

#### 3. 아코디언 펼쳐졌을 때 배경 색상 변경
기존에는 접힌 아코디언 배경 색상이 lightGray였는데, white로 변경하고 펼쳐졌을때 약간의 그레이 색을 백그라운드로 넣어줬으면 좋겠어요. 웹 전반적으로 배경이 흰색이어서 아코디언을 펼쳤을 때도 흰색이면 약간 허전한 느낌이 들었어요.

```tsx
  background-color: ${({ theme, $isOpened }) => ($isOpened ? '#F8F8FA' : theme.colors.white)};
```

#### 4. 디바이스 크기가 425px 이하일 때 드롭다운 너비 100%로 수정
코멘트로도 남겼듯이 디바이스 크기가 425px 이하일때, 드롭다운 width를 100%로 변경하면 좋을 것 같아요!

#### 5. DropdownButton과 ItemContainer 사이 갭 추가
기존 디자인은 너무 붙어있는 느낌이 들어서 DropdownButton과 ItemContainer 사이에 약간의 갭이 있으면 좋겠어요! 
<img width="206" alt="스크린샷 2024-10-10 오전 11 20 18" src="https://github.com/user-attachments/assets/65b841c3-5f0f-4970-b40d-c851ebd98e27">

아래 디자인이 엄청 마음에 들진 않지만 일단.... 사알짝 수정해봤습니다. 참고가 되었으면 좋겠어용...
<img width="965" alt="스크린샷 2024-10-10 오전 11 01 11" src="https://github.com/user-attachments/assets/56f54116-7f61-4cae-a582-34d363d6b050">

2024-10-10 02:31 UTC, soosoo22 commented on frontend/src/components/common/Dropdown/styles.ts
> +export const DropdownContainer = styled.div`
### 🍀건의 사항🍀
- 디바이스 width가 425px이하일 때는 드롭다운 width를 100%로 변경해도 괜찮을 것 같아요. 기존처럼 목록보기, 모아보기 탭은 왼쪽 / 드롭다운은 오른쪽에 붙게 되면 가운데가 살짝? 허전한 느낌이 들어서요🥹
- 프로젝트명이 시작되는 시작점과 드롭다운, 아코디언 왼쪽 시작점을 맞춰줬으면 좋겠어요!
<img width="304" alt="스크린샷 2024-10-10 오전 10 37 21" src="https://github.com/user-attachments/assets/bd04fec6-6b41-47a3-aa7e-caa3bb75cff8">

2024-10-10 02:31 UTC, soosoo22 commented on frontend/src/components/common/Dropdown/index.tsx
> +        <S.ItemContainer>
바다의 의견 너무나 동의합니다👍

2024-10-10 02:31 UTC, soosoo22 commented on frontend/src/components/common/Dropdown/styles.ts
> +  width: 24rem;
위에서 말했던 것 처럼 디바이스 크기가 425px 이하일때는, width를 100%로 설정해도 좋을 것 같아요!

2024-10-10 02:31 UTC, soosoo22 commented on frontend/src/components/common/Dropdown/styles.ts
> +export const ItemContainer = styled.ul`
> select, option 태그의 경우 브라우저나 OS별 기본 속성이 강하게 적용되어 있어 자유로운 스타일링이 어렵다는 단점이 있어요.

에프이가 말한 것 처럼 select 태그로 할 경우, 스타일링에 제한이 있어서 오히려 div로 드롭박스를 구현한 부분은 좋았던 것 같아요👍

2024-10-10 02:31 UTC, soosoo22 commented on frontend/src/mocks/mockData/reviewCollection.ts
> +            '고액공제건강보험과 건강저축계좌를 만들어 노동자와 고용주가 세금공제를 받을 수 있도록 하면 결과적으로 노동자의 의료보험 부담이 커진다.',
목 데이터까지! 👍👍👍

2024-10-10 06:14 UTC, chysis commented on frontend/src/components/common/Dropdown/index.tsx
> +        <S.ItemContainer>
https://puki4416blog.netlify.app/how-to-react-event-handle/
https://dev.to/thawsitt/should-i-use-event-delegation-in-react-nl0

리액트가 알아서 이벤트를 위임하기 때문에(root로 끌어올려서 처리한다고 해요) 개발자가 별도로 이벤트 위임 패턴을 사용하지 않아도 된다는 주제의 글들을 찾아보았는데, 어떻게 생각하시나요?

2024-10-10 06:16 UTC, BadaHertz52 approved these changes
고생했습니다!1

2024-10-10 06:17 UTC, merged