[BE] feat: 받은 리뷰 요약 조회 API 구현
woowacourse-teams/2024-review-me pull request #796
Opened 2024-10-08 08:55 UTC by Kimprodp

- resolves #794 

---

### 🚀 어떤 기능을 구현했나요 ?
- 자신이 받은 리뷰 요약 조회 기능을 구현했습니다.

### 🔥 어떻게 해결했나요 ?
- `/v2/reviews/summary ` : 리뷰 그룹에 등록된 리뷰 수와 리뷰 그룹 정보를 반환합니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 꼼꼼히 봐주세요~

### 📚 참고 자료, 할 말

2024-10-08 08:59 UTC, donghoony approved these changes
👍🏻 테스트 하나만 작성해주세용~!

2024-10-08 08:59 UTC, donghoony commented on backend/src/main/java/reviewme/review/repository/ReviewRepository.java
> +    int countByReviewGroupId(long reviewGroupId);
인덱스 걸려있으면 빠를까요? 아래 JPQL과 쿼리 차이나 성능 차이가 있을까요?
```java
@Query("SELECT COUNT(r.id) FROM Review r WHERE r.reviewGroupId = :reviewGroupId)
```

2024-10-08 09:00 UTC, donghoony commented on backend/src/test/java/reviewme/review/service/ReviewSummaryServiceTest.java
> +        ));
`ReviewGroupFixture` 를 사용하면 어떨까요?

2024-10-09 04:23 UTC, skylar1220 requested changes
빠른 테드쓰~ 소소 제안쓰~

2024-10-09 04:23 UTC, skylar1220 commented on backend/src/test/java/reviewme/review/service/ReviewSummaryServiceTest.java
> +        );
reivewRepositoy.count 하면 다른 리뷰그룹의 리뷰까지 함께 가져오는 결과를 의미하니 이렇게 list의 크기로 검증하는 건 어떨까요?
```suggestion
        List<Review> reviews = List.of(
                new Review(template.getId(), reviewGroup.getId(), List.of()),
                new Review(template.getId(), reviewGroup.getId(), List.of()),
                new Review(template.getId(), reviewGroup.getId(), List.of())
        );
        reviewRepository.saveAll(reviews);

        // when
        ReceivedReviewsSummaryResponse actual = reviewSummaryService.getReviewSummary(
                reviewGroup.getReviewRequestCode());

        // then
        assertAll(
                () -> assertThat(actual.projectName()).isEqualTo(reviewGroup.getProjectName()),
                () -> assertThat(actual.revieweeName()).isEqualTo(reviewGroup.getReviewee()),
                () -> assertThat(actual.totalReviewCount()).isEqualTo(reviews.size())
        );
```

2024-10-09 04:23 UTC, skylar1220 commented on backend/src/test/java/reviewme/review/service/ReviewSummaryServiceTest.java
> +    void 리뷰_그룹에_등록된_리뷰_요약_정보를_반환한다() {
다른 reviewGroup의 review가 아닌 내 reviewGroup의 review 갯수만 반환하는지 확인하는 로직이  필요할 것 같아요~ 쓰고보니 repository의 countByReviewGroupId에 대한 테스트 메서드를 만드는 게 더 맞겠다는 생각도 드네요!

2024-10-09 05:39 UTC, Kimprodp commented on backend/src/test/java/reviewme/review/service/ReviewSummaryServiceTest.java
> +        ));
앗차차 수정할게요~

2024-10-09 05:39 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/repository/ReviewRepository.java
> +    int countByReviewGroupId(long reviewGroupId);
reviewGroupId에 인덱스 걸려있어서 현재 쿼리로 인덱스 걸리지 않나요?

2024-10-09 05:39 UTC, Kimprodp commented on backend/src/test/java/reviewme/review/service/ReviewSummaryServiceTest.java
> +        );
굿 깔끔 반영했어요~

2024-10-09 05:39 UTC, Kimprodp commented on backend/src/test/java/reviewme/review/service/ReviewSummaryServiceTest.java
> +    void 리뷰_그룹에_등록된_리뷰_요약_정보를_반환한다() {
지금 다른 레포지토리에서 JPA가 만들어준 메서드는 따로 테스트 하고 있지 않아서.. 우선 기존 테스트에 그룹 하나 추가하는 걸로도 알 수 있을 것 같아 추가했어요~

2024-10-09 05:49 UTC, skylar1220 approved these changes
리반확완👍

2024-10-11 05:08 UTC, nayonsoso approved these changes
수고 많았습니다~ ㅎㅎ
사소해서 커멘트 남기기조차 민망하지만 그냥 넘어가기에는 뭣한 부분 코멘트 남겼습니다~

2024-10-11 05:08 UTC, nayonsoso commented on backend/src/test/java/reviewme/review/service/ReviewSummaryServiceTest.java
> +                () -> assertThat(actual.projectName()).isEqualTo(reviewGroup1.getProjectName()),
개행해주세욧!

2024-10-11 05:08 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/ReviewSummaryService.java
> +        );
[이건 그냥 소감]
요런 컨벤션은 없었던 것 같긴 한데 시원시원한 개행이라 좋네요 ㅎㅎ

2024-10-11 07:25 UTC, merged