[BE] fix: delete 쿼리가 한 번만 나가도록 jpql을 사용한다.
woowacourse-teams/2024-review-me pull request #833
Opened 2024-10-11 09:20 UTC by skylar1220

- resolves #832 

---

### 🚀 어떤 기능을 구현했나요 ?
- delete 쿼리가 한 번만 나가도록 jpql을 사용한다.

### 🔥 어떻게 해결했나요 ?
- delete 쿼리가 한 번만 나가도록 jpql을 사용한다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 

### 📚 참고 자료, 할 말

2024-10-11 10:01 UTC, nayonsoso requested changes

2024-10-11 10:01 UTC, nayonsoso commented on backend/src/main/java/reviewme/highlight/domain/exception/NegativeHighlightIndexException.java
> +        super("하이라이트 위치는 0 이상의 수이어야 해요.");
귣귣

2024-10-11 10:01 UTC, nayonsoso commented on backend/src/main/java/reviewme/highlight/repository/HighlightRepository.java
> +    void deleteAllByIds(List<Long> answersByReviewQuestion);
아이 해브 어 퀘스티온~!!

전과 후에 delete 쿼리가 어떻게 바뀌는지 좀 더 설명해주실 수 있나요?🥹

2024-10-13 10:58 UTC, skylar1220 commented
https://github.com/woowacourse-teams/2024-review-me/pull/850 에서 함께 진행합니다

2024-10-13 10:58 UTC, closed without merging