[BE] fix: 질문을 position 순서대로 내려주도록 로직 수정
woowacourse-teams/2024-review-me pull request #834
Opened 2024-10-11 09:50 UTC by nayonsoso

AS-IS: Question을 position으로 정렬한 값을 받아서 Map<Question, List<Answer>> 으로 만든 다음, mapper 에 전달했다. 이때, map 은 순서를 보장하지 않으므로 mapper 에서 position 순서대로 내려지지 않았다.
TO-BE: 쿼리에서 정렬하지 않고, mapper에서 정렬하도록 바꿔주었다.

- resolves #831 

---

### 🚀 어떤 기능을 구현했나요 ?
- 질문이 position 순으로 정렬되지 않는 아래의 이슈를 해결했습니다. 
![image](https://github.com/user-attachments/assets/4329da6a-96f7-449a-8470-bbc827f9978f)

### 🔥 어떻게 해결했나요 ?
- AS-IS: Question을 position으로 정렬한 값을 받아서 Map<Question, List<Answer>> 으로 만든 다음, mapper 에 전달했다. 이때, map 은 순서를 보장하지 않으므로 mapper 에서 position 순서대로 내려지지 않았다.
- TO-BE: 쿼리에서 정렬하지 않고, mapper에서 정렬하도록 바꿔주었다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 

### 📚 참고 자료, 할 말

2024-10-12 11:58 UTC, donghoony requested changes
한 번만 확인하고, 더 쉬운 방법이 있다면 이쪽으로 가는 것도 좋겠습니다 👍🏻

2024-10-12 11:58 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/ReviewGatheredLookupService.java
>                  .collect(Collectors.toMap(Question::getId, Function.identity()));
`LinkedHashMap`으로 받아왔으면 추가 구현 없이 정렬되지 않았을까요 ?

2024-10-14 07:08 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/ReviewGatheredLookupService.java
>                  .collect(Collectors.toMap(Question::getId, Function.identity()));
음~ 맛있다😋

2024-10-14 07:39 UTC, donghoony approved these changes
어떤가요?

2024-10-14 07:39 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/ReviewGatheredLookupService.java
> +        }
```suggestion
        Map<Long, Question> questionIdQuestion = new LinkedHashMap<>();
        questions.forEach(question -> questionIdQuestion.put(question.getId(), question));
```

2024-10-14 08:34 UTC, Kimprodp requested changes
답변만 확인해주십셔!

2024-10-14 08:34 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/service/ReviewGatheredLookupService.java
> +        questions.forEach(question -> questionIdQuestion.put(question.getId(), question));
동일한 맥락으로 questionIdAnswers 도 순서가 보장되지 않을 수 있지 않나요?

2024-10-14 08:42 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/ReviewGatheredLookupService.java
> +        }
음 맛있다🤤 반영완했습니다!

2024-10-15 06:15 UTC, skylar1220 approved these changes
산초 `이게 왜 되지?` 질문만 답변 부탁드립니당ㅎㅎ

2024-10-15 06:15 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/ReviewGatheredLookupService.java
>                  .findReceivedAnswersByQuestionIds(reviewGroup.getId(), questionIdQuestion.keySet(),
이 부분도 그렇고 아래의 return 부분 mapping도 그렇고 그냥 linkedHashMap은 아니라 섞일 수 있는 가능성이 있는 거 아닌가 싶은데 현재 테스트 코드에서는 100번씩 repeatableTest 돌려도 정렬돼서 나오네요ㅎㅎ 혹시 원리를 아시는지..

2024-10-15 09:44 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/ReviewGatheredLookupService.java
> +        questions.forEach(question -> questionIdQuestion.put(question.getId(), question));
WoW... 마지막에 리턴을 할 때 그냥 map 으로 collect 하기 때문에 순서가 보장되지 않을 수도 있었네요!!
꼼꼼테드 고맙습니다🥹 테스트 코드도 보강했어요!

2024-10-15 09:48 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/ReviewGatheredLookupService.java
>                  .findReceivedAnswersByQuestionIds(reviewGroup.getId(), questionIdQuestion.keySet(),
히히 테드의 리뷰를 받고 반영했습니다~
그리고 "테스트 코드가 통과하는 것"은 사실 테스트 코드도 이상하게 되어있더라고요😅
제가 fixture 로 4개의 Question 을 만들고, 각각의 이름대로 정렬되어있는지를 테스트했었는데,
fixture 는 질문의 내용의 내용이 모두 같았으므로 의미가 없는 테스트였었습니다🥲
지금은 테스트도 수정했습니다!

2024-10-15 09:59 UTC, skylar1220 approved these changes
반영 확인 완! 이제 가지런히 정렬된 페이지를 볼 수 있겠곤요👏

2024-10-16 01:12 UTC, Kimprodp approved these changes
반완확 고생했어요 신초~

2024-10-16 01:59 UTC, merged