[BE] feat: UTF-8 필터 추가
woowacourse-teams/2024-review-me pull request #844
Opened 2024-10-12 13:22 UTC by donghoony

- resolves #842 

---

### 🚀 어떤 기능을 구현했나요 ?
- 응답의 인코딩을 UTF-8로 내리도록 필터를 추가했습니다.

### 🔥 어떻게 해결했나요 ?
- 서블릿 필터를 구현하고, 이를 `Component`로 등록했습니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 이거 테스트는 어떻게 해야할까요? 우선 아래와 같이 로컬 환경에서는 잘 나타납니다 😁;;
<p align=center><img src=https://github.com/user-attachments/assets/4ff29d7c-0d38-4f32-aac6-f3915e6e4cc5 width=50% /></p>

2024-10-13 00:58 UTC, Kimprodp approved these changes
필터 활용 굿이네용👍

2024-10-14 00:59 UTC, skylar1220 approved these changes
안해줘도 왜 지금까지는 안깨졌지? 싶었는데 이미 UTF-8 기본 설정 환경이어서 그랬겠구나 싶어요. 그럼에도 불구하고 여러 서버, 클라이언트 환경에 오류 없이 적용되게 명시적으로 하면 더 좋은 부분이겠군요👍👍

2024-10-14 08:39 UTC, nayonsoso commented
yml 에서 설정을 하는게 어떨지! 제안 드려요🙋🏻‍♀️

```yml
encoding:
  charset: UTF-8
```

스프링은 개발자가 "비지니스 로직에만 집중하게끔" 해주는 프레임워크라고 알고 있어요. 그런데 지금은 스프링에서 제공하는 설정으로 간단히 해결할 수 있는 것을 코드로 구현하고 있다는 생각이 들어요. 

예를 들어서 same site 나 HttpOnly 와 같은 것들도 코드로 구현할 수 있지만, yml 을 통해서 간단하게 설정했었어요. 그런 설정들과 비슷한 맥락에서 생각하면, yml 로 설정하는게 자연스럽지 않을까요?

2024-10-14 08:41 UTC, nayonsoso requested changes
놓치기 쉬운 부분을 끌어올려주는 아루~~ 아리가또 입니당..🥹
그런데 yml 에서 설정을 하는게 어떨지 제안 드려봐요🙋🏻‍♀️

```yml
encoding:
  charset: UTF-8
```

스프링은 개발자가 "비지니스 로직에만 집중하게끔" 해주는 프레임워크라고 알고 있어요. 그런데 지금은 스프링에서 제공하는 설정으로 간단히 해결할 수 있는 것을 코드로 구현하고 있다는 생각이 들어요. 

예를 들어서 same site 나 HttpOnly 와 같은 것들도 코드로 구현할 수 있지만, yml 을 통해서 간단하게 설정했었어요. 그런 설정들과 비슷한 맥락에서 생각하면, 인코딩도 yml 로 설정하는게 자연스럽지 않을까요?

2024-10-14 08:58 UTC, donghoony commented
<img width="642" alt="image" src="https://github.com/user-attachments/assets/a2b50a8a-3218-421b-ace6-a7a5f9d275ac">

2024-10-14 10:37 UTC, nayonsoso approved these changes
어푸어푸! 아루 덕분에 UTF-8 인코딩으로 보겠네요🎊

2024-10-14 10:52 UTC, merged