[BE] 도메인을 활용한 하이라이트 추가 및 수정 로직 리팩토링
woowacourse-teams/2024-review-me pull request #850
Opened 2024-10-13 08:57 UTC by skylar1220

- resolves #825 

---

### 🚀 어떤 기능을 구현했나요 ?
- 도메인을 활용해 하이라이트 추가 및 수정 로직을 리팩토링했습니다.

### 🔥 어떻게 해결했나요 ?
- 기한에 몰려 절차지향적으로 작성했던 코드를 도메인 관점으로 다시 접근해보았습니다!
- 정책적인 검증을 제외하고는 도메인을 만들어 위임했습니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 도메인으로 검증을 많이 이동했는데 그로인해 오히려 변경에 유연하지 않게된 곳이 있는지 봐주세요.
- 코드 수정량이 쫌 많습니다. 놓친 게 없는지 봐주세요.
- 지난번 기능 구현 pr에 달렸던 코멘트도 함께 반영했어요.

### 📚 참고 자료, 할 말
- 객체 지향을 다시 생각해보게 해줘서 고맙습니다 우리 팀원들😊 더 더 연습해봐야겠어요!

2024-10-13 15:39 UTC, donghoony requested changes
커비 고생했습니다... 객체 관점에서 보아서 리뷰가 좀 맵습니다. 이제는 완성했으니 제가 만들어 둔 코드를 조금 많이 참고해도 좋겠어요. 객체 간 의존성이나 `private`으로 늘어난 코드를 관리해보면 좋겠습니다~

2024-10-13 15:39 UTC, donghoony commented on backend/src/main/java/reviewme/review/domain/TextAnswer.java
> +        this.id = id;
이건 왜 필요한가요 ?

2024-10-13 15:39 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/domain/HighlightLine.java
> +            throw new IllegalArgumentException(); // TODO: 예외 구체화
예외 구체화는 이번 PR에서 진행했나유?

2024-10-13 15:39 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/domain/HighlightWithAnswer.java
> +    private long answerId;
하이라이트의 도메인이 다른 엔티티의 Id를 알아야 할까요? 🤔

2024-10-13 15:39 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/domain/HighlightWithAnswer.java
> +        List<String> lineGroup = Arrays.asList(answer.getContent().split("\n"));
`\n` 상수 추출이 가능하겠습니다

2024-10-13 15:39 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/domain/HighlightLine.java
> +        return ranges.stream().anyMatch(range -> range.isSameRange(startIndex, endIndex));
개행해 주세요.., 😢

2024-10-13 15:39 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/domain/HighlightRange.java
> +    }
`equalsAndHashCode`가 있는데 `isSameRange`가 필요하지 않을 듯합니다.

2024-10-13 15:39 UTC, donghoony commented on backend/src/test/java/reviewme/highlight/domain/HighlightContentTest.java
> +    void 중복된_하이라이트를_추가하는_경우_예외를_발생한다() {
여전히 예외 사항이라고는 생각이 안 드는데요.. 중복으로 들어오더라도 우리가 한 번에 처리하면 훨씬 품을 들이지 않고 구현할 수 있지 않을까? 라는 생각입니다. 트레이드 오프긴 하겠지만 같은 하이라이트가 들어오면 그냥 한 번만 칠해주면 되니깐요

2024-10-13 15:39 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/domain/HighlightLines.java
> +    public HighlightLines(TextAnswer answer, List<Integer> lineIndexs) {
`index`의 복수형은 `indexes`입니다요~

2024-10-13 15:39 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/service/HighlightService.java
> +    }
🤔... 여전히 인덴트가 많은데요. 객체를 분리한 의미가 퇴색되는 듯합니다.. 다른 방법은 없을까요? 제가 처음에 만들었던 코드에는 2 이상으로 안 넘어갔어서요.

2024-10-13 15:39 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/service/HighlightService.java
> +    }
\+ `private` 메서드가 너무 많습니다. 커비는 이 메서드가 많아지는 것을 경계했었나요?

2024-10-13 15:39 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/domain/HighlightContent.java
> +    public HighlightContent(TextAnswer answer, List<Integer> lineIndex) {
순수한 도메인이 다른 도메인을 의존하면 무슨 문제가 발생할까요? 제가 구현한 방법에서는 `String`만을 받는다고 커비한테 이야기했던 기억이 있는데요... 🤔

2024-10-13 15:39 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/domain/HighlightContent.java
> +    public HighlightContent(TextAnswer answer, List<Integer> lineIndex) {
\+ `lineIndex`는 `highlightContent`에게 어떤 의미를 갖나요? 다른 객체가 가져야 할 값을 잘못 가지고 있지는 않을까요? 직역하면 하이라이트한 본문인데, 라인 인덱스는 무엇인지 잘 와닿지 않았어요 😢

2024-10-14 02:16 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightLine.java
> +            throw new IllegalArgumentException(); // TODO: 예외 구체화
넵 이 커밋에서 수정했어요~ ebd712608eeac0d3f95afa347fcad55581206760

2024-10-14 02:19 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightLines.java
> +    public HighlightLines(TextAnswer answer, List<Integer> lineIndexs) {
호호 그랬군요...

2024-10-14 02:20 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightLine.java
> +        return ranges.stream().anyMatch(range -> range.isSameRange(startIndex, endIndex));
반완!

2024-10-14 02:20 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightWithAnswer.java
> +        List<String> lineGroup = Arrays.asList(answer.getContent().split("\n"));
반완!

2024-10-14 02:22 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightRange.java
> +    }
반완!

2024-10-14 08:13 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightContent.java
> +    public HighlightContent(TextAnswer answer, List<Integer> lineIndex) {
1. 도메인이 아닌 content만 string으로 갖고있도록 변경하였습니다😅
2. 살펴보니 굳이 객체로 만들지 않아도 되는 도메인같아서 삭제하였습니다!

2024-10-14 08:14 UTC, skylar1220 commented on backend/src/test/java/reviewme/highlight/domain/HighlightContentTest.java
> +    void 중복된_하이라이트를_추가하는_경우_예외를_발생한다() {
공감합니다~ 예외 처리없이 set으로 자동으로 걸러주도록 변경하였습니다!

2024-10-14 08:15 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightWithAnswer.java
> +    private long answerId;
듣고보니 이 도메인의 역할이 무엇인가 생각이 들었어요. 엔티티의 id와 리스트를 매핑해주는 객체라는 생각이 들어 도메인으로 분리하는 게 적절하지 않았다싶어요. 해당 도메인을 삭제하고 map으로 관리하도록 변경하였습니다!

2024-10-14 08:34 UTC, donghoony commented on backend/src/test/java/reviewme/highlight/domain/HighlightContentTest.java
> +    void 중복된_하이라이트를_추가하는_경우_예외를_발생한다() {
😁👍🏻👍🏻👍🏻👍🏻

2024-10-14 12:35 UTC, nayonsoso requested changes
왕 사소한 부분들에 대해서 코멘트 남겼습니다~ 👍

2024-10-14 12:35 UTC, nayonsoso commented on backend/src/main/java/reviewme/highlight/domain/exception/HighlightIndexExceedLineLengthException.java
> +        super("하이라이트 위치는 줄의 글자 수 이내이어야 해요.");
[짱사소 & 선택반영]
하이라이트 위치가 텍스트의 범위를 벗어났어요.
or 
하이라이트 위치가 답변의 범위를 벗어났어요.

어떤가요? "줄의 글자수" 보다 더 일반적으로 쓰일 말이 좋을 것 같아요!

2024-10-14 12:35 UTC, nayonsoso commented on backend/src/main/java/reviewme/highlight/repository/HighlightRepository.java
> +    void deleteAllByIds(List<Long> answerIds);
JpaRepository 의 함수 네이밍 규칙을 생각하면 조금 헷갈릴 것 같아요.
(마치 Highlight 의 id 를 기준으로 하는 것 같아서)

deleteAllByAnswerIds는 어떨까요?

2024-10-14 12:35 UTC, nayonsoso commented on backend/src/test/java/reviewme/highlight/domain/HighlightLineTest.java
> +    }
```suggestion
    @Test
    void 하이라이트_대상_라인의_글자수보다_큰_시작_종료_인덱스_범위를_추가하려고_하면_예외를_발생한다() {
        // given
        String content = "12345";
        HighlightLine highlightLine = new HighlightLine(1, content);

        // when && then
        assertThatCode(() -> highlightLine.addRange(content.length(), content.length() + 1))
                .isInstanceOf(HighlightIndexExceedLineLengthException.class);
    }
```

[왕사소]
지금의 `assertThatCode(() -> highlightLine.addRange(4, 5))`에 사용되는 4와 5가 의미하는바가 무엇인지를 더 잘 드러낼 수 있을 것 같아요!

2024-10-14 12:35 UTC, nayonsoso commented on backend/src/test/java/reviewme/highlight/domain/HighlightLinesTest.java
> +        assertThatCode(() -> new HighlightLines(answer.getContent(), List.of(1, 3)))
when && then 🤔
boolean 을 반환할 것처럼 생겼네요.!

---

그리고 `List.of(1, 3)` 를 `List.of(2)`로 바꾸는게 더 타이트한 경계값인 것 같아요~

2024-10-14 12:35 UTC, nayonsoso commented on backend/src/test/java/reviewme/highlight/domain/HighlightLinesTest.java
> +        );
이 부분 정말 잘 작성한 것 같아요😊
HighlightLines 가 뭘 하는건지 이해가 잘 되네요~
명세의 역할을 하도록 테스트 코드를 잘 작성하셨네요💯

2024-10-14 12:35 UTC, nayonsoso commented on backend/src/main/java/reviewme/highlight/service/HighlightService.java
> +        highlightValidator.validate(highlightsRequest, reviewGroupId);
이 라인을 long reviewGroupId 선언 라인 바로 아래로 옮기는건 어떨까요?
빨리 검증하는게 좋다 생각해요!

2024-10-14 13:16 UTC, Kimprodp requested changes
껄비~

리뷰하다가 파트를 나누는 것이 좋을 것 같아서 우선 Validator 부분만 리뷰해서 올립니다.
계속해서 서비스 부분 리뷰 할게요.

2024-10-14 13:16 UTC, Kimprodp commented on backend/src/main/java/reviewme/highlight/service/validator/HighlightValidator.java
> -        validateLineIndex(request);
```java
private final TextAnswerRepository textAnswerRepository;
```

사용하지 않는 필드가 있어요~

2024-10-14 13:16 UTC, Kimprodp commented on backend/src/main/java/reviewme/highlight/service/validator/HighlightValidator.java
>          validateReviewGroupContainsQuestion(request, reviewGroupId);
이미 이전에 리뷰 그룹을 찾았던 것 같은데.. 이 메서드 내부에서 동일한 리뷰 그룹을 id를 통해 또 찾을 필요가 있을까요?

2024-10-14 13:16 UTC, Kimprodp commented on backend/src/main/java/reviewme/highlight/service/validator/HighlightValidator.java
>          validateReviewGroupContainsQuestion(request, reviewGroupId);
메서드명은 리뷰 그룹에 질문이 포함되었는지 여부를 검증하는 것 같은데, 내부에서는 템플릿에 있는 질문인지만을 검증하고 있네요. 검증의 의도는 무엇이었나요?
만약 그룹에 있는 답변에 대한 질문을 찾는거라면 답변들 중에서 질문을 찾아야 하지 않을까요?
실제로 답변이 없는 질문에 하이라이트 요청이 오는 것이 이상하다고 생각해요.

2024-10-14 13:16 UTC, Kimprodp commented on backend/src/main/java/reviewme/highlight/service/validator/HighlightValidator.java
>          validateReviewGroupContainsAnswer(request, reviewGroupId);
하이라이트서비스에서는 request의 getUniqueAnswerIds() 메서드를 사용했던 것 같은데 이 메서드 내부에서도 사용할 수 있지 않을까요?
```java
        List<Long> submittedAnswerIds = request.highlights()
                .stream()
                .map(HighlightRequest::answerId)
                .toList();
```

2024-10-14 13:16 UTC, Kimprodp commented on backend/src/main/java/reviewme/highlight/service/validator/HighlightValidator.java
> -        validateLineIndex(request);
validator의 검증 단계별 메서드를 쭉 봤는데요. 검증 단계가 상당히 비효율적으로 보입니다.

현재 검증 순서는 이렇게 보여요.
1. 요청 온 질문이 리뷰 그룹에 존재하는 질문인지 확인 (하지만 템플릿 내에 존재하는 질문인지를 확인하고 있음)
2. 요청 온 답변이 리뷰 그룹에 포함된 답변인지 확인
3. 요청의 답변이 요청의 답변에 포함된 질문인지 확인

이제 제안 사항 입니다.
요청(request)이 올바른 요청인지 '요청 자체'를 먼저 검증해봅시다.
1. 요청의 답변들이 요청의 질문에 대한 답변인지 확인
2. 요청의 답변이 리뷰 그룹에 포함된 답변인지 확인 (여기까지만 해도 질문이 리뷰 그룹에 있는 템플릿에 포함된 질문인지는 확인안해도 될 것 같아요)

2024-10-14 14:37 UTC, Kimprodp requested changes
커비 리팩터링 하느라 고생많았습니다요.

코멘트 확인 후 다시 요청 주시면 확인할게요~

2024-10-14 14:37 UTC, Kimprodp commented on backend/src/main/java/reviewme/highlight/service/HighlightService.java
> +        highlightValidator.validate(highlightsRequest, reviewGroupId);
나영의 의견에 동의해요~
요청 자체를 먼저 올바른 요청인지 먼저 검증해봅시다

2024-10-14 14:37 UTC, Kimprodp commented on backend/src/main/java/reviewme/highlight/service/HighlightService.java
> +        Map<Long, HighlightLines> highlightLinesByAnswerId = new HashMap<>();
map 사용 시 변수 네이밍이 위에는 answer/ LineIndexes  형태인데 이번에는 뒤에가 먼저 나오고 by~ 가 있어서 헷갈릴 수 있을 것 같습니다요
통일 하는 것이 좋아 보여요~

2024-10-14 14:37 UTC, Kimprodp commented on backend/src/main/java/reviewme/highlight/service/HighlightService.java
> +        List<Long> answerIds = textAnswers.getIdsByQuestionId(questionId);
요청에서 answerIds를 추출해서 TextAnswers로 만들고 다시 TextAnswers에서 questionId를 기준으로 id를 다시 뽑아올 필요가 있을까요?

1. 요청은 하나의 질문에 해당하는 답변들만 오기 때문에 TextAnswers 내부의 getIdsByQuestionId 연산은 비효율적인 것 같아요.
2. 어차피 '요청온 질문에 대한 모든 하이라이트 삭제'가 목적이니, validator에서 요청 자체를 검증했다면 이렇게 하지 않고 그냥 `highlightsRequest.getUniqueAnswerIds()` 한 결과로 delete 해도 되지 않을까요?

2024-10-14 14:37 UTC, Kimprodp commented on backend/src/main/java/reviewme/highlight/domain/HighlightLines.java
> +    private final List<HighlightLine> lines;
상수와 필드 사이 개행 어때요?

2024-10-14 14:37 UTC, Kimprodp commented on backend/src/main/java/reviewme/highlight/service/HighlightService.java
>      }
어차피 key에 HighlightLines만 만들면 되니 제안 해봅니다요
```java
return highlightsRequest.highlights().stream()
        .collect(Collectors.toMap(
            HighlightRequest::answerId,
            highlightRequest -> mapHighlightLine([인자전달])
        ));
```

2024-10-14 14:37 UTC, Kimprodp commented on backend/src/main/java/reviewme/highlight/service/HighlightService.java
> +                                       TextAnswer answer, List<Integer> answerLineIndex) {
`List<Integer> answerLineIndex` 인자로 전달받지 않고, `highlightRequest.getLineIndexes()` 사용할 수 있지 않나요?

2024-10-14 14:37 UTC, Kimprodp commented on backend/src/main/java/reviewme/highlight/domain/HighlightLines.java
> +                throw new InvalidHighlightLineIndexException(submittedLineIndex, lineCount);
줄 번호는 %d 이하여야해요. 라는 예외 메시지명은 줄 번호가 고정으로 제한되어 있는 것처럼 느껴져요.
단순히 '줄 번호는 답변의 라인보다 클 수 없어요' 라는 식의 메시지는 어떤가요?

2024-10-14 14:37 UTC, Kimprodp commented on backend/src/main/java/reviewme/highlight/domain/HighlightLines.java
> +        for (long submittedLineIndex : lineIndexes) {
long인 이유는 무엇인가요?

2024-10-14 14:37 UTC, Kimprodp commented on backend/src/main/java/reviewme/highlight/domain/HighlightLines.java
> +            if (submittedLineIndex > lineCount - 1) {
lineIndexes가 비어있거나, 음수거나, 중복된 인덱스가 있거나 이런 경우들을 검증이 필요하지 않을까요?

2024-10-14 14:37 UTC, Kimprodp commented on backend/src/main/java/reviewme/highlight/domain/HighlightLine.java
> +public class HighlightLine {
이 클래스에서 HighlightRange를 가지고 있고, Highlight에서도 HighlightRange를 가지고 있는데요.
이 클래스는 어떤 목적으로 존재하나요?..

2024-10-14 14:37 UTC, Kimprodp commented on backend/src/main/java/reviewme/highlight/domain/Highlight.java
> +
이 엔티티는 단순히 테이블에 저장하기 위한 용도인가요? 여기서 해야 할 책임이 일부 다른 클래스로 나눠져 있다는 느낌을 받는데.. 지금 도메인 구조가 비슷한 책임을 가진 도메인이 많아서 좀 헷갈립니다 😢

2024-10-14 22:17 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/domain/TextAnswer.java
> +        this.id = id;
테스트하면서 추가했는데 삭제하겠습니다~

2024-10-14 22:18 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/service/HighlightService.java
> +    }
클래스 분리의 신호였겠네요...! mapper로 분리해보았습니다

2024-10-14 22:18 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/domain/exception/HighlightIndexExceedLineLengthException.java
> +        super("하이라이트 위치는 줄의 글자 수 이내이어야 해요.");
첫번째 것 좋네요!! 역시 언어의 마술사 산쵸

2024-10-14 22:20 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/repository/HighlightRepository.java
> +    void deleteAllByIds(List<Long> answerIds);
좋아요! 반완!

2024-10-14 22:20 UTC, skylar1220 commented on backend/src/test/java/reviewme/highlight/domain/HighlightLineTest.java
> +    }
👍👍반완!

2024-10-14 23:58 UTC, skylar1220 reviewed
새로운 pr에 코멘트 적용해보겠습니다~

2024-10-14 23:58 UTC, hyeonji1220 commented on backend/src/test/java/reviewme/highlight/domain/HighlightLinesTest.java
> +        assertThatCode(() -> new HighlightLines(answer.getContent(), List.of(1, 3)))
이번에 테스트를 수정하면서 반완!

2024-10-14 23:58 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/highlight/service/HighlightService.java
> +        highlightValidator.validate(highlightsRequest, reviewGroupId);
반완!

2024-10-14 23:58 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/highlight/service/validator/HighlightValidator.java
> -        validateLineIndex(request);
반완!

2024-10-14 23:58 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/highlight/service/validator/HighlightValidator.java
>          validateReviewGroupContainsQuestion(request, reviewGroupId);
반완!

2024-10-14 23:58 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/highlight/service/HighlightService.java
> +        highlightValidator.validate(highlightsRequest, reviewGroupId);
반완!

2024-10-14 23:58 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/highlight/service/HighlightService.java
> +        Map<Long, HighlightLines> highlightLinesByAnswerId = new HashMap<>();
key-value 형식으로 통일할게요!

2024-10-14 23:58 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightLines.java
> +    private final List<HighlightLine> lines;
반완😅

2024-10-14 23:58 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightLines.java
> +                throw new InvalidHighlightLineIndexException(submittedLineIndex, lineCount);
좋네요 반완!

2024-10-14 23:58 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightLines.java
> +        for (long submittedLineIndex : lineIndexes) {
없네요..ㅎㅎ int로 수정완!

2024-10-14 23:58 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightLines.java
> +            if (submittedLineIndex > lineCount - 1) {
비어있는 경우는 notNull로 dto에서 검증이 되어 들어오고, lineIndex 자체가 중복인 건 괜찮아서 음수인 경우 추가만 해주면 될 것 같아요!

추가)
lineIndex 자체가 중복인 건 괜찮아서를 추가로 설명하자면,
line index+range까지 같으면 문제인데, line index는 기존 list.get(인덱스)로 해서 중복된 것도 한번만 저장이 되고, range도 set으로 관리 중이라 마찬가지로 중복된 것은 하나만 저장됩니다.

2024-10-14 23:58 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightLine.java
> +public class HighlightLine {
1. 도메인에게 검증 등의 책임을 주기위한 역할이었어요. 라인의 글자수보다 종료 위치가 넘지는 않는지 등의 서비스보다는 도메인적으로 고정되어있는 검증들 말이죠.
2. 더불어 엔티티로 포장하는 과정이 너무 복잡해지는 걸 막기위해 1차 매핑해놓은 것이기도 해요.
그런데 2번 이유는 중간 매핑이 하나 더 들어갔다는 점이 복잡한가 싶은 고민이 드네요..

2024-10-14 23:58 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/domain/Highlight.java
> +
highlihgt가 db 저장을 위한 유일한 엔티티입니다. 위의 답변과 비슷하게 고민이 되는데 단순 도메인은 네이밍을 다르게 하면 괜찮을까요..?

2024-10-14 23:58 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/service/HighlightService.java
> +        List<Long> answerIds = textAnswers.getIdsByQuestionId(questionId);
request의 answerId에는 수정 사항이 있는 answerId만 포함되지만 사실은 question에 해당하는 모든 answerId의 하이라이트를 삭제해야해요. 하지만 테드가 남겨준 것처럼 TextAnswers 객체를 이용할 필요는 없어서 아래처럼 바꿔볼게요!
```java
        Set<Long> allAnswerIds = answerRepository.findIdsByQuestionId(highlightsRequest.questionId());
        highlightRepository.deleteAllByAnswerIds(allAnswerIds);
```

2024-10-14 23:58 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/service/validator/HighlightValidator.java
>          validateReviewGroupContainsQuestion(request, reviewGroupId);
요청에 포함된 질문 id가 리뷰 그룹의 템플릿이 제공하는 질문 중에 있는 질문 id인지 검증하는 부분이었어요!
네이밍의 문제라고 생각해서 `validateReviewGroupTemplateContainsQuestion`로 바꿔보았어요~

2024-10-14 23:58 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/service/validator/HighlightValidator.java
>          validateReviewGroupContainsAnswer(request, reviewGroupId);
반완!

2024-10-14 23:58 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/service/validator/HighlightValidator.java
> -        validateLineIndex(request);
어차피 답변이 질문에 해당되고, 동시에 리뷰 그룹에 해당되면 → 질문도 리뷰 그룹에 해당됨이 자동 검증(삼단논법 같군요..)
이렇게 해도 같은 검증이 되겠네요 반완!

2024-10-14 23:58 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/service/HighlightService.java
> +                                       TextAnswer answer, List<Integer> answerLineIndex) {
로직이 바뀌면서 해당 부분 삭제되어서 바뀐 걸로 다시 확인 부탁해요~~

2024-10-14 23:58 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/service/HighlightService.java
>      }
로직이 바뀌면서 해당 부분 삭제되어서 바뀐 걸로 다시 확인 부탁해요~~

2024-10-15 01:02 UTC, skylar1220 commented
https://github.com/woowacourse-teams/2024-review-me/pull/859 코멘트 반영해서 여기서 새로 진행합니다!

2024-10-15 01:04 UTC, skylar1220 commented
https://github.com/woowacourse-teams/2024-review-me/pull/859 코멘트 반영해서 여기서 새로 진행합니다!

2024-10-15 01:04 UTC, closed without merging