Fe/test/849/highlight and cookie
woowacourse-teams/2024-review-me pull request #854
Opened 2024-10-13 13:09 UTC by BadaHertz52

- resolves #849

---

### 🚀 어떤 기능을 구현했나요 ?
-  인증 쿠키 확인하는 목 핸들러(`withAuthCookie `) 생성 및 적용
- 형광펜 api 요청 시, response 없는 fetch 오류도 잡을 수 있게 수정
- api 요청 오류 시  토스트 모달 띄우는 연결 작업 진행할 수 있게 준비 
useMutation을 사용해 api 요청 보내고, success, error 작업할 수 있게 했습니다
- 형광펜 api 테스트 추가

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- [ErrorBounday에 대한 pr](https://github.com/woowacourse-teams/2024-review-me/pull/853) 코드 변경 사항이 포함되어있습니다

### 📚 참고 자료, 할 말
- 원래는 api 테스트만 하려고 했는데, 하다보니 인증 쿠기 목핸들러 만들고 , useMutation 사용하고 그러다보니 토스트 모달 핸들링 생각하고 그러다보니 ErrorBoundary 만들게 되었습니다 💦💦💦
- api 요청 시, response 없을 경우 오류도 try-catch로 잡아야합니다. 이렇지 않은 api 핸들러들은 앞으로  수정하는 것으로 !!

2024-10-15 07:49 UTC, ImxYJL requested changes
휴일에 쉬지도 못하고 😅 고생했어요!
간단한 네이밍 위주로 리뷰 남겼습니다~!

2024-10-15 07:49 UTC, ImxYJL commented on frontend/src/apis/highlight.ts
> +      credentials: 'include', // 인증 정보를 포함
여기 주석은 없어도 될 것 같아용

2024-10-15 07:49 UTC, ImxYJL commented on frontend/src/components/highlight/HighlightEditorContainer.tsx
> +  const handleErrorModal = (isError: boolean) => setErrorModal(isError);
이 함수가 결국 `isError` 상태를 세팅하는 거라 `setErrorModalState`처럼 set이라는 단어가 직관적으로 들어갔으면 좋겠어요!

2024-10-15 07:49 UTC, ImxYJL commented on frontend/src/components/highlight/HighlightEditorContainer.tsx
> +  const [openErrorModal, setErrorModal] = useState(false);
isOpen~으로 바꿔야 할 것 같습니당

2024-10-15 07:49 UTC, ImxYJL commented on frontend/src/hooks/highlight/useHighlight.tsx
> +  const updateEditorAnswerMap = (newEditorAnswerMap: EditorAnswerMap) => setEditorAnswerMap(newEditorAnswerMap);
여기도 가능하다면 set~으로 만들면 좋을 것 같아요

2024-10-15 07:49 UTC, ImxYJL commented on frontend/src/mocks/handlers/cookies.ts
> +export const withAuthCookie = <T>(cookies: Record<string, string>, callback: () => T) => {
함수 이름으로 authorizeWithCookie는 어떤가요?

2024-10-15 07:49 UTC, ImxYJL commented on frontend/src/hooks/highlight/useMutateHighlight/test.tsx
> +    document.cookie = `${MOCK_AUTH_TOKEN_NAME}=2024-review-me`;
테스트 범위가 "정상적으로 쿠키값을 넣을 수 있는지"도 포함하는 건가요?
어차피 모킹된 값을 넣는 만큼 쿠키가 유효하다고 가정하고 테스트를 진행할 수도 있을 것 같아서요.
만약 그렇다면 쿠키 설정/해제 코드도 별도의 테스트 유틸로 분리해보면 좋을 것 같아용

2024-10-15 07:49 UTC, ImxYJL commented on frontend/src/mocks/handlers/cookies.ts
> + */
👍

2024-10-15 08:07 UTC, BadaHertz52 commented on frontend/src/components/highlight/HighlightEditorContainer.tsx
> +  const handleErrorModal = (isError: boolean) => setErrorModal(isError);
useState에서 상태를 변경하는 setState과 헷갈릴거라고 생각해, set~으로 시작하는 함수명은 지양하는 편이에요.

error 관련 코드들은 토스트 모달이 들러올 때, 모달과 연결하기 위한 길잡이?를 하는 역할이라, 구체적인 코드느 모달 연결 구현하는 크루에게 일임하고 뼈대만 잡았어요

2024-10-15 08:09 UTC, BadaHertz52 commented on frontend/src/hooks/highlight/useHighlight.tsx
> +  const updateEditorAnswerMap = (newEditorAnswerMap: EditorAnswerMap) => setEditorAnswerMap(newEditorAnswerMap);
set~으로 시작하는 함수명을 지양하는 이유는 위에 코멘트로 적은 것과 같아요.

2024-10-15 08:31 UTC, BadaHertz52 commented on frontend/src/hooks/highlight/useMutateHighlight/test.tsx
> +    document.cookie = `${MOCK_AUTH_TOKEN_NAME}=2024-review-me`;
해당 유틸함수 구현해서 적용했습니다

2024-10-16 06:05 UTC, ImxYJL approved these changes
리뷰 반영까지 빠르게 해주셨네요!! 수고 많으셨습니다 😋

2024-10-16 07:07 UTC, chysis reviewed
고생했어요! 파일명 관련해서 제안할 부분이 있어서 코멘트 남겼습니다. 확인 부탁해요

2024-10-16 07:07 UTC, chysis commented on frontend/src/mocks/handlers/cookies.ts
> + */
👍

2024-10-16 07:07 UTC, chysis commented on frontend/src/utils/testUtils.ts
testUtils라는 이름이 테스트용 쿠키를 추가하는 일을 하는지 모를 것 같은데, `testWithAuthCookie`라는 이름을 파일명에서도 그대로 사용하는 것은 어떤가요?

2024-10-16 07:19 UTC, BadaHertz52 commented on frontend/src/apis/highlight.ts
> +      credentials: 'include', // 인증 정보를 포함
반영 완료!

2024-10-16 07:25 UTC, BadaHertz52 commented on frontend/src/utils/testUtils.ts
혹시 추후에 테스트 유틸이 생기지 않을까하는 생각으로 파일명을 포괄적으로  잡았어요
그래서 export default가 아닌 export로 해당 함수를 내보내고 있어요

2024-10-16 08:34 UTC, soosoo22 approved these changes
바다! 사소하지만 수정하면 좋을 부분들을 코멘트로 남길게요!

1. PR 제목 - '목 핸들렁' => '목 핸들러' 로 교체
2. src/hooks/highlight 폴더 안에 파일들이 모두 `.tsx`로 되어 있어서 `ts`로 변경해도 괜찮지 않을까요~

2024-10-16 08:34 UTC, soosoo22 commented on frontend/src/hooks/highlight/useMutateHighlight/index.tsx
> +      handleErrorModal(true);
미리 토스트 작업까지!! 👍👍

2024-10-16 08:34 UTC, soosoo22 commented on frontend/src/mocks/handlers/cookies.ts
> + */
👍

2024-10-16 13:23 UTC, soosoo22 reviewed
> `HighlighterButton` 윗 부분이 잘리고 있어서 위치를 살짝만 아래로 내려도 괜찮을 것 같아요! 그리고 지우기 버튼과 삭제하기 버튼 위치가 동등한 라인에 있으면 좋을 것 같아요😊 어떨 땐 멀리 떨어졌다가 또 어떨 땐 겹쳐 보이더라구요.

쑤쑤 이 부분은 형광펜 위치 버그 수정 pr에서 확인하면 돼요. 위치 버그와 테스트관련 내용을 분리하고 있어요.

2024-10-17 06:01 UTC, chysis approved these changes
확인했습니다! 고생했어요👍

2024-10-17 06:35 UTC, merged