[FE] design: 리뷰 작성 페이지 모달 글자 가운데 정렬
woowacourse-teams/2024-review-me pull request #856
Opened 2024-10-14 05:17 UTC by BadaHertz52

- resolves #855

---

### 🚀 어떤 기능을 구현했나요 ?
- 리뷰 작성 페이지 모달을 웹, 모바일에서 사용해 보니 왼쪽 정렬을 택했을 때 빈 공간이 걸려서, 리뷰 작성 페이지 모달의 글자가 가운데 정렬되게 수정했습니다  

### 🔥 어떻게 해결했나요 ?
#### 강점 선택 해제 시
- 모바일 
![스크린샷 2024-10-14 135454](https://github.com/user-attachments/assets/d3e0a03c-a648-44d7-80b8-bd8864eb077e)
- 웹
![image](https://github.com/user-attachments/assets/306c335e-cd99-45d1-9e7e-a67ca28d2c55)

#### 리뷰  제출
- 모바일 
![스크린샷 2024-10-14 135440](https://github.com/user-attachments/assets/1bf67bd0-494e-4908-85e7-548fb43c1084)
- 웹
![image](https://github.com/user-attachments/assets/0a20f48d-9531-4000-87de-d5033b0cd608)

#### 경로 이탈 시 
- 모바일 
![스크린샷 2024-10-14 135250](https://github.com/user-attachments/assets/ee36f01f-4b33-4d03-aa47-33b4f54a161b)
- 웹 
![스크린샷 2024-10-14 135255](https://github.com/user-attachments/assets/7bfcbb51-2be9-4f6d-8ec7-6953516f70f9)

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 가운데 정렬을 했지만, 반응형을 하다보면 문장이 어색하게 끊기는 경우가 있습니다. 최대한 잡으려고 했지만, 어색한 부분이 있다면 말씀해주세요! 

### 📚 참고 자료, 할 말

2024-10-14 12:54 UTC, ImxYJL approved these changes

2024-10-14 12:54 UTC, ImxYJL commented on frontend/src/pages/ReviewWritingPage/modals/components/StrengthUnCheckModal/style.ts
> +    width: 23rem;
동적으로 너비를 계산하던 코드 대신 고정 너비가 온 이유가 궁금해요!

2024-10-15 08:36 UTC, BadaHertz52 commented on frontend/src/pages/ReviewWritingPage/modals/components/StrengthUnCheckModal/style.ts
> +    width: 23rem;
해당 모달에서 첫번째 줄은 글자가 가득차지만, 두번째 줄은 가득차지 않아서 가운데 정렬 시 , 가운데 정렬에서 첫번째 줄을 끝 까지 가나가 넘어가는 부분이 가운데로 왔어요 . (아래 같은 느낌?)

그래서 해당 모달에서 모바일에서 첫번째와 두번째에서 가운데 정렬이 되어도 어색하지 않게 사이즈를 잡았어요 
이 사이즈를 계산해서 찾는 거는 어려워서, 직접 하드 코딩하기는 했습니다🥲
```tsx
선택을 해제하시면 앞서 작성한 답변이 
모두 사라져요
       변경하시겠어요?
```

2024-10-16 06:07 UTC, chysis requested changes
고생했어요! 고정 폭 때문에 영역을 뚫고 나가는 문제를 발견했어요. 코멘트 확인 부탁합니다!!

2024-10-16 06:07 UTC, chysis commented on frontend/src/pages/ReviewWritingPage/modals/components/StrengthUnCheckModal/style.ts
> +    width: 23rem;
![image](https://github.com/user-attachments/assets/1f192adb-65ed-45ff-8be4-f3ef39462966)
▲ 고정 너비 적용 전

![image](https://github.com/user-attachments/assets/bc5e647a-15f1-41ff-92b3-5d8c3aefc72b)
▲ 고정 너비 적용

문구가 바뀔 일이 거의 없을 것 같아서 고정 너비도 괜찮네요 :)

2024-10-16 06:07 UTC, chysis commented on frontend/src/pages/ReviewWritingPage/modals/components/SubmitCheckModal/style.ts
>      min-width: 27rem;
![image](https://github.com/user-attachments/assets/648c92a2-f27e-48ad-ae10-44e5736180d5)

320px에 가까운 `xSmall` 크기의 모바일에서 min-width값이 27rem으로 고정되어 있어 메시지 영역이 모달을 뚫고 나가는 현상이 발생합니다!

2024-10-16 06:54 UTC, soosoo22 approved these changes
모달 확인했습니다~ 에프이가 남긴 피드백만 반영되면 완벽한 것 같습니다!

2024-10-16 07:17 UTC, BadaHertz52 commented on frontend/src/pages/ReviewWritingPage/modals/components/SubmitCheckModal/style.ts
>      min-width: 27rem;
✅ 반영 완료
기존에 60vw로 했던 기준을 375px로  변경했어요.

2024-10-16 08:46 UTC, chysis approved these changes
수정 사항 확인했습니다! 텍스트 치우침 없이 잘 보이네요👍👍

2024-10-16 08:47 UTC, merged