[FE] fix: 모아보기 페이지 버그 수정
woowacourse-teams/2024-review-me pull request #858
Opened 2024-10-14 15:27 UTC by chysis

- resolves #848 

---

### 🚀 어떤 기능을 구현했나요 ?
- 총 받은 리뷰가 0개라면 페이지 전체에 '널~' 을 띄웁니다.
- 섹션의 질문별로 답변이 없다면 해당 아코디언 내부에 '널~'을 띄웁니다.
  - 원래 아코디언도 띄우지 않으려 했지만, 한 섹션에 필수가 아닌 질문과 필수 질문이 섞여있는 경우엔 답변이 있는 질문에 대해서는 데이터를 보여줘야 합니다. 따라서 아코디언별로 답변이 있는지 확인합니다.
- 질문 이름(아코디언 title)에 ${revieweeName}이 포함된 경우가 있는데, 문자열 치환 작업을 사전에 거치도록 했습니다.
- 서술형 질문에 개행 문자만 입력한 경우 빈 disc를 출력하던 문제를 수정했습니다.

### 🔥 어떻게 해결했나요 ?
### 데이터 내려주는 방식 - 고민의 흔적
리뷰 목록과 모아보기 페이지에서 공통으로 사용하고 있는 `ReviewDisplayLayout` 컴포넌트가 있는데, 해당 컴포넌트에서 리뷰이/프로젝트/총 리뷰 개수 정보를 불러오고 있습니다. 그리고 레이아웃 컴포넌트의 children으로 오는 모아보기 페이지 컴포넌트에서 총 리뷰 개수 정보가 필요한 상황이에요.

children으로 데이터를 내려주기 위해 여러 가지 방법을 고민해보았어요. 

1. cloneElement를 사용하면 children에 props로 데이터를 넘겨줄 수 있는데, 공식 문서에서 권장하기 않는 방식입니다.
2. render props 패턴을 적용해서 `(totalReviewCount: number) ⇒ React.ReactNode` 타입의 함수를 렌더링해서 데이터를 넘겨줄 수도 있어요. 하지만 공통으로 사용되는 레이아웃 컴포넌트에서 이 패턴은 적당하지 않다고 판단했습니다.
3. ContextAPI를 사용해서도 레이아웃 컴포넌트의 하위에서 데이터에 접근할 수 있어요. 하지만 리렌더링 이슈와 함께 context를 사용하는 컴포넌트가 많아질수록 결합도가 높아지기 때문에 보류해두었습니다.
4. recoil을 사용해서 전역 상태로 관리해도 되지만, 전역 상태의 사용은 되도록 지양합니다.
5. 해당 데이터를 요청하는 훅이 react query로 구현되어 있고, staleTime도 설정되어 있어 캐싱이 가능합니다. react query는 context에 비해 자주 변경되는 데이터를 다룰 때 더 적합하다고 생각했고, 모아보기의 경우 새로운 리뷰가 등록되면 최신 데이터를 다시 보여줘야 하기 때문에 데이터가 필요할 때마다 훅에 접근하는 것이 적합하다고 생각했습니다!

**결론**: 데이터를 내려주지 않고 `useReviewInfoData` 훅에 데이터가 필요할 때마다 접근합니다.

### ReviewEmptySection
리뷰가 없는 경우 '널~'을 띄워주는 컴포넌트인데요, 지금은 두 가지로 사용됩니다.

1. 총 리뷰가 0개인 경우
2. 특정 질문에 대한 리뷰가 0개인 경우(모아보기에서)

두 가지 경우를 분리하기 위해 '널~'과 함께 보여주는 문구를 props로 뚫어서 선택할 수 있게 했습니다.

![image](https://github.com/user-attachments/assets/b17724d3-b66d-41ed-a1e7-1d1f1adb039b)
▲ 총 리뷰가 0개인 경우

![image](https://github.com/user-attachments/assets/8d3b2724-fe35-44bd-946e-71e6e85f3c40)
▲ 특정 질문에 대한 답변이 0개인 경우

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 

### 📚 참고 자료, 할 말

2024-10-16 00:20 UTC, BadaHertz52 commented on frontend/src/components/highlight/HighlightEditor/index.tsx
> +        <S.LineListWrapper
AnswerList라는 ul 태그인 스타일 컴포넌트([edtiorAnswerMap.values()].map의 부모)를 만들고, Answer라는 li태그 스타일 컴포넌트를 만드는게
시맨틱 구조로 좋을 것 같습니다

2024-10-16 00:21 UTC, BadaHertz52 commented on frontend/src/pages/ReviewCollectionPage/index.tsx
> +import ReviewEmptySection from '../../components/common/ReviewEmptySection';
절대경로 사용 추천드립니다

2024-10-16 00:26 UTC, BadaHertz52 commented on frontend/src/pages/ReviewCollectionPage/index.tsx
> +  const { revieweeName, projectName, totalReviewCount } = useReviewInfoData();
useReviewInfoData가 api요청을 하는 훅이라 
여기서 부르면 목록 페이지에서 부른 api가 또 불러져서, 다른 방법을 논의해보는 것이  좋을 것 같습니다

2024-10-16 07:07 UTC, soosoo22 reviewed
처음에 목록 페이지에서 모아보기 페이지로 이동할 때, 두번째 아코디언이 열렸다가 닫히더라구요. 처음부터 닫혀있는 상태면 어떨까요??

https://github.com/user-attachments/assets/f14893da-24af-47a3-ab7d-b460e53a7785

2024-10-16 07:10 UTC, ImxYJL reviewed
받은 답변이 없을 때 UI 처리에 대해 코멘트 남겼어요!~~

그리고 `ReviewDisplayLayout` 구조에 대해 다소 장문의😌 코멘트도 남깁니다

훅을 사용해 데이터를 가져오는 방식 자체는 좋다고 생각합니다. 최대한 Layout 코드를 건드리지 않으면서 데이터를 받기 위한 최선의 방식을 선택했다고 느껴졌어요!

다만 현재 페이지 구조를 봤을 때 `ReviewInfoData`의 흐름이 끊긴다는 느낌을 받았어요.
`ReviewDisplayLayout`에서 API를 호출해 정보를 받아온 뒤 그 데이터를 그 자식인 `ReviewInfoSection`에 내려주고 있습니다.
하지만 `children`으로 들어오는 모아보기 페이지에서는 PR 본문대로 데이터를 내려주기 어려운 문제가 있습니다.

`children`으로 올 수 있는 페이지가 명확히 정해진 상황에서 위와 같은 이유로 데이터를 props로 전달할 수 없다는 게 어색하게 느껴졌습니다.
레이아웃 컴포넌트는 여태까지의 공통 컴포넌트와 달리 특정 페이지 형식과 연관이 깊기 때문에 이 레이아웃이 어떤 페이지를 다루는지, 어떤 데이터를 갖고 있는지를 props 넘겨주기를 통해 드러내주는 게 가독성이 좋다고 생각했습니당
그래서 리팩토링 방향을 크게 두 가지 생각해봤어요 (지금은 넘 바빠서ㅋㅋㅋ리팩토링은 레벨 5에서 차차 하는 것으로 생각했어요. 어차피 제가 만든 레이아웃이기도 해서😂)

### ReviewDisplayLayout을 정말 뼈대만 제공하는 컴포넌트로 바꾼다.
각 페이지에서 필요한 데이터는 각자 알아서 호출하거나 훅을 통해 가져온다.

#### 장점
 - 목록보기, 모아보기 페이지를 독립적으로 운용할 수 있음
 - 각 페이지에서 필요한 데이터를 각자 알아서 불러올 수 있음

#### 단점
 - props 전달을 통해 데이터 흐름을 파악하기 어려워짐


### ReviewDisplayLayout 안에서 목록 페이지와 모아보기 페이지를 직접 렌더한다.
#### 장점
- 이 레이아웃을 어떤 페이지들이 공유하는지 직관적으로 확인할 수 있음 (부모-자식 관계 강화)
 - `ReviewDisplayLayout`이 내려 주는 리뷰 정보(`ReviewInfoData`)를 사용하는 페이지들에게 props로 바로 전달 가능
   
#### 단점
 - children보다 확장성이 낮아짐
 - 위 페이지들을 조건부 렌더링 or 라우팅하는 로직을 별도로 리팩토링해서 써야 함
   - `children`으로 오는 페이지들은 어차피 url이 달라지니까 `outlet`을 사용해 라우팅하도록 바꿔 볼 수도 있을 것 같습니다

2024-10-16 07:10 UTC, ImxYJL commented on frontend/src/components/common/ReviewEmptySection/index.tsx
> +const ReviewEmptySection = ({ content }: ReviewEmptySectionProps) => {
이 널페이지는 당초 한 페이지에 준하는 면적을 커버하기 위해 만들어져서 그런지 아코디언에서 사용하기에는 자리를 많이 차지한다는 생각이 들었어요. 크기를 줄여볼 수도 있겠지만 개인적으로 널은 빼고 받은 답변이 없다는 텍스트만 심플하게 띄워주는 방식을 건의합니다!

2024-10-16 07:10 UTC, ImxYJL commented on frontend/src/pages/ReviewCollectionPage/index.tsx
> +  const { revieweeName, projectName, totalReviewCount } = useReviewInfoData();
바다가 남겨준 코멘트에 대한 코멘트를 남기겠습니다ㅋㅋㅋ

2024-10-16 07:10 UTC, ImxYJL commented on frontend/src/pages/ReviewCollectionPage/index.tsx
> +    if (review.question.type === 'CHECKBOX') {
이렇게 객관식 질문인지를 체크하는 조건문이 프로젝트 전반에 걸쳐 많이 사용되고 있어서, 보다 직관적으로 `isObjectiveQuestion`같은 유틸을 만들어서 쓰면 좋겠다는 생각이 들었는데... 이제 와서 적용하기에는 이미 늦었을지도 모르겠네요ㅋㅋㅋㅋㅋㅋ

2024-10-16 07:47 UTC, soosoo22 commented on frontend/src/pages/ReviewListPage/components/PageContents/index.tsx
> +import ReviewEmptySection from '../../../../components/common/ReviewEmptySection';
위에서 바다가 코멘트 남긴 것 처럼 절대 경로를 사용하면 될 것 같습니다~

2024-10-16 07:57 UTC, BadaHertz52 commented on frontend/src/pages/ReviewCollectionPage/index.tsx
> +  const { revieweeName, projectName, totalReviewCount } = useReviewInfoData();
EssentialPropsWithChildren 에서 children이 props를 받을 수 있도록  해보는 거 시도해보면 어떨까요? 이게 될지는 모르겠지만 좋은 시도가 될 것 같아요! 
```tsx
// 특정 컴포넌트 타입을 children으로 받기 위해 제너릭을 활용한 예시

const ReviewDisplayLayout: React.FC<EssentialPropsWithChildren<ReviewDisplayLayoutProps, (props: ChildrenProps) => EmotionJSX.Element>> = ({ isReviewList, children }) => {
  return (
    <div>
      {children({ isReviewList })} {/* children을 함수로 호출 */}
    </div>
  );
};


```

2024-10-16 10:57 UTC, ImxYJL commented on frontend/src/pages/ReviewCollectionPage/index.tsx
> +  const { revieweeName, projectName, totalReviewCount } = useReviewInfoData();
다들 지금은 현행 방법+요 PR대로 가고 나중에 리팩토링하는 건 어떻게 생각하시나용

2024-10-16 15:55 UTC, chysis commented on frontend/src/components/highlight/HighlightEditor/index.tsx
> +        <S.LineListWrapper
시맨틱 태그를 사용해서 구조를 수정했어요

2024-10-16 15:57 UTC, chysis commented on frontend/src/pages/ReviewCollectionPage/index.tsx
> +import ReviewEmptySection from '../../components/common/ReviewEmptySection';
common으로 옮기면서 index를 빼먹었네요! 수정했습니다

2024-10-18 08:57 UTC, chysis commented
## 수정사항
### 리뷰 목록/모아보기에 공통으로 사용되는 레이아웃에 Context API 도입
- 목록/모아보기 레이아웃에 있는 ReviewInfoSection과, children으로 오는 모아보기 페이지에서 같은 데이터를 필요로 합니다. 
- children으로 데이터를 내려주는 여러 가지 방식을 고민했고, 삽질 끝에 Context API를 적용했습니다. 레이아웃을 provider로 감싸서 ReviewInfoSection과 모아보기 페이지에서 `useContext`로 데이터를 사용하고 있습니다.

### 아코디언 관련 리팩토링
- 모아보기 페이지에 처음 들어가면 닫힌 아코디언에서 열렸다가 닫히는 것처럼 보이는 문제가 있었습니다. boolean 변수를 사용해서 첫 렌더링 시에는 애니메이션이 재생되지 않도록 수정했습니다.
- 질문과 답변이 더 구분되어 보이도록 구분선을 추가했습니다.
- 질문을 semibold로 보여줍니다.
- 질문 앞에 있는 'Q. ' 부분을 질문과 분리해서, 화면이 작아졌을 때 어색하게 보이지 않도록 수정했습니다.
![image](https://github.com/user-attachments/assets/f6a28953-0d88-4e53-97be-dbf7c1f56a24)
▲ 참고

### Git 충돌 해결 과정에서...
- 이 PR이 올라오고 나서 여러 PR이 머지되었고, 그 사이에 계속 수정을 거쳤기 때문에 develop을 pull해오니 충돌이 있었습니다. auto-merging 과정에서 삭제된 파일이 여러 개 있어서(형광펜 관련 파일 구조가 바뀌면서 발생한 문제) 하나씩 비교해 가며 누락된 파일을 따로 추가했습니다. 
- 한 번 확인하긴 했는데 혹시나.. 누락된 기능이나 파일이 더 있다면 알려주세요. 빠르게 복구하겠습니다ㅜㅠ

2024-10-19 08:40 UTC, ImxYJL requested changes
리팩토링이랑 충돌 해결하느라 고생했던 걸 알아서 하루빨리 머지하고 싶지만... 궁금한 점과 소소한 개선 사항이 있어 RC 남깁니다 😅 새벽 시간대만 아니라면 빨리 어프룹하러 올게요!!

2024-10-19 08:40 UTC, ImxYJL commented on frontend/src/pages/ReviewCollectionPage/components/PageContents/index.tsx
> +              <Accordion title={parsedQuestionName} key={index} isInitiallyOpened={index === 0 ? true : false}>
삼항 연산자를 `isInitiallyOpened={!!(index === 0)}`로 간결하게 바꿔볼 수 있을 것 같아욥

2024-10-19 08:40 UTC, ImxYJL commented on frontend/src/components/layouts/ReviewDisplayLayout/ReviewInfoDataProvider.tsx
> +// export const ReviewInfoDataContext = createContext<ReviewInfoData | null>(null);
여기 주석 있어요~~

2024-10-19 08:40 UTC, ImxYJL commented on frontend/src/components/layouts/ReviewDisplayLayout/components/ReviewInfoSection/index.tsx
> +  };
`ReviewInfoDataContext`를 만들 때 기본값을 주고 있어서, context를 사용하는 쪽에서 별도의 초기값을 줄 필요는 없을 것 같아요!

2024-10-19 08:40 UTC, ImxYJL commented on frontend/src/components/layouts/ReviewDisplayLayout/index.tsx
> +export default ReviewDisplayLayoutWithProvider;
여기서 defualt export를 파일 이름과 달리 Provider로 하고 있는데, 파일명과 default export를 맞추지 않아도 문제가 없는지 궁금합니다!

2024-10-19 08:40 UTC, ImxYJL commented on frontend/src/pages/ReviewCollectionPage/components/PageContents/index.tsx
> +    return <HighlightEditor questionId={review.question.id} answerList={review.answers!} handleErrorModal={() => {}} />;
`handleErrorModal`은 추후에 토스트 에러 로직이 들어가는 부분인가요?

2024-10-19 15:23 UTC, chysis commented on frontend/src/pages/ReviewCollectionPage/components/PageContents/index.tsx
> +              <Accordion title={parsedQuestionName} key={index} isInitiallyOpened={index === 0 ? true : false}>
`index===0` 자체가 boolean 값이기 때문에 !!를 사용하지 않아도 될 것 같아요!

2024-10-19 15:27 UTC, chysis commented on frontend/src/pages/ReviewCollectionPage/components/PageContents/index.tsx
> +    return <HighlightEditor questionId={review.question.id} answerList={review.answers!} handleErrorModal={() => {}} />;
네 맞습니다~!

2024-10-19 15:34 UTC, chysis commented on frontend/src/components/layouts/ReviewDisplayLayout/components/ReviewInfoSection/index.tsx
> +  };
맞네요! 이 부분도 반영하겠습니다

2024-10-19 15:38 UTC, chysis commented on frontend/src/components/layouts/ReviewDisplayLayout/index.tsx
> +export default ReviewDisplayLayoutWithProvider;
파일명과 export되는 변수명이 달라도 문법적인 오류는 없지만, 코드를 읽는 다른 개발자에게 혼란을 줄 수 있다는 점 때문에 맞추는 게 좋아요. 변수명을 구현 당시에 임시로 정해두고 다시 확인하지 못했네요😅

Provider로 감싼 형태 자체를 외부에서 사용하는 것이 맞기 때문에 변수명을 수정했습니다.

2024-10-20 03:46 UTC, ImxYJL approved these changes
리뷰까지 반영하느라 고생 많았어요!! 더 이상의 PR이 쌓이기 전에 어프룹합니다ㅋㅋㅋㅋ

2024-10-20 03:46 UTC, ImxYJL commented on frontend/src/components/layouts/ReviewDisplayLayout/index.tsx
> +};
수정된 네이밍 자연스럽네요👍

2024-10-20 09:41 UTC, BadaHertz52 commented on frontend/src/components/highlight/HighlightEditor/index.tsx
> +        <S.LineListWrapper
형광펜 메뉴,툴팁 구현 시, 해당 PR이 머지전이라 에프이가 수정한 부분 참고해서 해봤었는데 항목 구분하는 마커와 답변이 일렬로 정렬되지 않아서  답변 항목별 점찍는 것을 제가 따로 구현하게 되어었어요.
여기 [커밋](https://github.com/woowacourse-teams/2024-review-me/pull/874/commits/04d11293524e449ab0b1d0d7eea1c4e5e212096a) 참고하시면 됩니다

2024-10-20 09:58 UTC, BadaHertz52 commented on frontend/src/components/layouts/ReviewDisplayLayout/index.tsx
> +export default ReviewDisplayLayoutWithProvider;
ReviewDisplayLayout 안에서 ReviewInfoDataProvider를 사용하지 않고, ReviewDisplayLayoutWithProvider를 따로 만든 이유가 있나요?

2024-10-20 10:02 UTC, BadaHertz52 commented on frontend/src/hooks/useAccordion.ts
> +      setIsFirstRender(false);
isFirstRender 상태값을 업데이트하는 것은, setContentHeight 할 때 같이 하지 않은 이유가 있나요?
contentRef.current.clientHeight를 기준으로 판별하는 거라면 contentHeight, isFirstRender상태를 같이 업데이트해도 될것 같아서요.

2024-10-20 10:07 UTC, BadaHertz52 commented on frontend/src/pages/ReviewCollectionPage/components/PageContents/index.tsx
> +const ReviewCollectionPageContents = () => {
파일명은 PageContents 인데 컴포넌트명은 ReveiwCollectionPageContents이네요

2024-10-20 10:08 UTC, BadaHertz52 commented on frontend/src/pages/ReviewListPage/components/PageContents/index.tsx
> +  if (!isSuccess) return null;
무스 실패 시, 에러 대응도 있어야 겠네요

2024-10-20 10:13 UTC, BadaHertz52 commented
다른 질문 카테고리를 선택하면, 이전에 아코디언 열림/닫힘이 그대로 유지되는 것이 의도된 기능인지 궁금해요

https://github.com/user-attachments/assets/621d8485-bf2d-4c17-a1c6-78772cf8e58f

2024-10-20 10:19 UTC, BadaHertz52 requested changes
에프이 context 구현하느라 고생했어요 

컴포넌트명과 파일명이 다른 것이 있고, 답변에 개행이 있어 여러줄 인 경우 li 마크 관련 오류(해당 오류는 아래에서 확인)와 카드 섹션이 바뀌어도 아코디언 펼침/닫힘이 유지되는 것에 대한 질문이 있어서 request changes 남길게요 

#### 마크 오류  
마크 오류는 관련 코멘트에 남긴 커밋을 참고하시면 됩니다. 현재 파일구조가 변경되어 에프이 PR에서 커밋 내용을 반영해 오류를 잡는게 충돌 해결에 좋을 것 같아요

2024-10-20 15:50 UTC, chysis commented on frontend/src/hooks/useAccordion.ts
> +      setIsFirstRender(false);
isFirstRender는 contentHeight가 계산되고 그 값이 적용된 이후에 바뀌어야 해요. 두 상태를 동시에 업데이트하면 batch update 때문에 원하는 대로 동작되지 않는 문제가 있었어요. 따라서 layoutEffect로 contentHeight를 먼저 계산한 뒤에 useEffect로 isFirstRender를 업데이트 했습니다!

2024-10-20 15:50 UTC, chysis commented on frontend/src/pages/ReviewCollectionPage/components/PageContents/index.tsx
> +const ReviewCollectionPageContents = () => {
이 부분도 수정하겠습니다~!

2024-10-20 16:21 UTC, chysis commented on frontend/src/components/layouts/ReviewDisplayLayout/index.tsx
> +export default ReviewDisplayLayoutWithProvider;
처음엔 하나의 컴포넌트에서 provider를 감쌌는데 children으로 오는 목록/모아보기 페이지에서 context에 접근이 안 되는 문제가 있었어요.
useContext를 사용하는 경우, 해당 context의 provider가 렌더링된 이후에 하위 컴포넌트들이 접근할 수 있어요. 그 시점을 보장하기 위해 별도의 컴포넌트에서 provider를 사용했습니다!

2024-10-20 16:50 UTC, chysis commented on frontend/src/components/highlight/HighlightEditor/index.tsx
> +        <S.LineListWrapper
![image](https://github.com/user-attachments/assets/18098729-7276-4289-8e4e-ca29223c2d29)
해당 커밋에서 AnswerListItem의 margin-left가 0.8rem인 상태입니다. border와 너무 붙어있는 느낌이라 임의로 2rem으로 설정해두었어요.

![image](https://github.com/user-attachments/assets/b03b16f5-9dea-4eec-8f0b-d0e638276d6c)

2024-10-20 16:57 UTC, chysis commented
다른 섹션 카테고리를 선택했을 때 아코디언의 열림 상태가 초기화되지 않았던 것은 key값으로 map의 index를 설정했기 때문이었어요. index로만 설정하면 지금처럼 재렌더링이 안 되는 문제가 있어서 사용하면 안 되는데.. 부끄럽네요😅

현재 선택된 섹션의 value와 index를 조합해서 해결했습니다.

2024-10-21 07:41 UTC, BadaHertz52 commented on frontend/src/hooks/useAccordion.ts
> +      setIsFirstRender(false);
애니메이션 적용 문제로, 시간을 두고 업데이트해야하는군요

2024-10-21 07:43 UTC, BadaHertz52 approved these changes
context api 구현해 오류 수정하느라 고생했어요!

2024-10-21 07:53 UTC, soosoo22 approved these changes
context 구현하느라 고생했어요! 에프이!
이것때문에 엄청 고민하는 걸 봤었는데 무사히 마무리했네요👍

받은 리뷰가 없을 때의 처리가 완벽하게 이루어지지 않은 것 같아서 코멘트 남깁니다!!


https://github.com/user-attachments/assets/7f3c7f87-cdf0-4a76-ba36-b246ff942794

2024-10-21 07:53 UTC, soosoo22 commented on frontend/src/components/common/Accordion/styles.ts
> +  transition: ${({ $isFirstRender }) => ($isFirstRender === true ? 'none' : '0.3s ease-in')};
isFirstRender를 추가해서 처음에 모아보기로 이동했을 때, 아코디언 애니메이션을 없앴군요!

2024-10-21 08:47 UTC, merged