[BE] refactor: 도메인을 활용한 하이라이트 추가 및 수정 로직 리팩토링 2차
woowacourse-teams/2024-review-me pull request #859
Opened 2024-10-15 00:51 UTC by skylar1220

- resolves #825 

---

### 🚀 어떤 기능을 구현했나요 ?
- 도메인을 활용해 하이라이트 추가 및 수정 로직을 리팩토링했습니다.

### 🔥 어떻게 해결했나요 ?
- 정책적인 검증을 제외하고는 도메인을 만들어 위임했습니다.
- validator, mapper를 활용해 서비스에서 비즈니스 로직을 파악하기 쉽게 하였습니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 검증을 책임대로 나눠서 유지 보수가 쉽게하기 위해 엔티티가 아닌 도메인을 생성해 활용하고 있습니다. 하지만 지난 코멘트에서 네이밍이나 역할이 헷갈린다는 내용이 있어서 우선 패키지 분리를 해놓았는데 여전히 헷갈리는 부분이 있는지 궁금해요.

### 📚 참고 자료, 할 말
- 수차례 리뷰하게 해서 미안합니다😂

2024-10-15 01:16 UTC, donghoony requested changes
거의 다 왔네요 😁 많이 나아졌다고 생각해요. 리뷰하면서 어? 모먼트도 많이 줄었습니다 👍🏻 웬만하면 반영하기를 원하지만 의도가 어땠는지 함께 이야기해주면 좋겠습니다~

2024-10-15 01:16 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/domain/HighlightRange.java
>          }
둘 다 같은 예외로 처리되면 별로일까요? 어쨌든 같은 인덱스와 관련된 예외인데 너무 구체적으로 나뉘지 않았나 해서요

2024-10-15 01:16 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/domain/HighlightLine.java
> +public class HighlightLine {
하이라이트된 라인이니 `HighlightedLine`은 어떤가요 ?

2024-10-15 01:16 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/domain/HighlightLine.java
> +    private final String lineContent;
`highlightLine.lineIndex`? 앞에 `line`을 안 쓰면 가독성이 떨어질까요?

2024-10-15 01:16 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/domain/HighlightLine.java
> +        int providedEndIndex = lineContent.length() - 1;
`-1` 하지 말고, 등호로 표현하는 건 어떤가요?

2024-10-15 01:16 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/domain/HighlightLines.java
> +        this.lines = mapLines(content);
한줄로 표현하는 것보다 여기에서 풀어 쓰면 안될까요..? 😁 👍🏻👍🏻👍🏻👍🏻

2024-10-15 01:16 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/domain/HighlightLine.java
> +    public void setRange(int startIndex, int endIndex) {
`setter` 네이밍인데 다른 건 어떨까요? `add`와 같은 것도 괜찮겠습니다

2024-10-15 01:16 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/service/dto/HighlightsRequest.java
> +    }
`.stream().distinct()`, `toList()` ?

2024-10-15 01:16 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/domain/Highlight.java
> +    public Highlight(long answerId, int lineIndex, HighlightRange range) {
생성자 추가했으니 기존 생성자를 체이닝하면 어떨까요? 개인적으로는 지금 이 생성자가 주 생성자가 되었으면 하는 바람입니다~

2024-10-15 01:16 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/service/mapper/HighlightMapper.java
> +    }
장풍 ?

2024-10-15 01:16 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/service/mapper/HighlightMapper.java
> +public class HighlightMapper {
모든 엔티티, 응답에 대해 `Mapper`가 생성되는 현재 구조.. 고민해야겠습니다

2024-10-15 01:16 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/domain/HighlightLine.java
> +import reviewme.highlight.entity.HighlightRange;
개인적으로는 패키지 나누는 게 더 신경쓰이긴 해요, 도메인이면 엔티티를 몰라야 하는데 나뉘어 있으니 `import`로 참조하겠네요

2024-10-15 01:33 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightRange.java
>          }
서버 입장에서는 사실 크게 상관없을 것 같아요. 예외명이나 메시지가 하나로 통일되어도 로그에 start, endIndex가 포함되어있으니 문제 파악은 가능하니까요.
그렇다면 두 예외를 나눴을 때 좋은점은 클라이언트가 뭘 잘못했길래 예외인지 정보를 전달할 수 있다는 점이었는데, 생각해보니 이것도 start, endIndex를 예외 메시지에 담아 클라이언트에게 전달하면 굳이 예외를 두개로 나누지 않아도 되겠네요! 하나로 합치겠습니당

2024-10-15 01:44 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightLine.java
> +public class HighlightLine {
좋네요 반완!

2024-10-15 01:45 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightLine.java
> +    private final String lineContent;
그냥 index가 낫겠네요 반완!

2024-10-15 03:13 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightLine.java
> +        int providedEndIndex = lineContent.length() - 1;
반완!

2024-10-15 03:17 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightLines.java
> +        this.lines = mapLines(content);
생성자에 매핑 로직이 길게 들어가면 매핑 로직 때문에 초기화 작업 자체를 파악하기 어렵다고 생각했어요.
```java
```

2024-10-15 03:21 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightLine.java
> +    public void setRange(int startIndex, int endIndex) {
행위에 집중하느라 setter 메서드명인걸 놓쳤네요 반완!

2024-10-15 03:22 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/domain/HighlightLines.java
> +        this.lines = mapLines(content);
- `HighlightedLine`에 `index`가 필요없다고 생각해요. 그렇다면 아래와 같이 하나의 stream 처리가 가능하지 않은가요?
```java
this.lines = Arrays.stream(content.split(LINE_SEPARATOR))
            .map(HighlightedLine::new)
            .toList()
```

2024-10-15 03:29 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightLines.java
> +        this.lines = mapLines(content);
HighlightedLine을 나중에 Highlight 엔티티를 생성할 때 사용하는데 이 때 index를 바로 꺼내서 쓸 수 있게하기 위해 필요했어요!

```java
            for (HighlightRange range : line.getRanges()) {
                Highlight highlight = new Highlight(answerId, line.getIndex(), range);
                highlights.add(highlight);
            }
```

2024-10-15 03:50 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/domain/HighlightLines.java
> +        this.lines = mapLines(content);
도메인 그 자체에서는 필요하지 않은 값 아닌가요 ??

2024-10-15 04:10 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/domain/HighlightLines.java
얘는 안 바뀌었어요~

2024-10-15 04:11 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/domain/HighlightedLine.java
>      private final String lineContent;
이것도 같이 한 말이었습니다 ㅎㅎ... 👍🏻👍🏻👍🏻👍🏻👍🏻

2024-10-15 04:11 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/domain/HighlightLines.java
> +            mappedLines.add(new HighlightedLine(i , lineContents[i]));
???? 😁 😮  
```suggestion
            mappedLines.add(new HighlightedLine(i, lineContents[i]));
```

2024-10-15 05:01 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightLines.java
lineIndex 말하는 거 맞을까요? 여기는 start, end 등 다른 인덱스도 함께 있어서 구분을 위해 lineIndex라고 명시하는 게 낫겠다 생각했어요

2024-10-15 05:03 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightLines.java
> +            mappedLines.add(new HighlightedLine(i , lineContents[i]));
반완..ㅎㅎ

2024-10-15 05:05 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/domain/Highlight.java
> +    public Highlight(long answerId, int lineIndex, HighlightRange range) {
메서드 체이닝을 놓쳤네요 반완!

2024-10-15 05:06 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightedLine.java
>      private final String lineContent;
content 말하는 것 맞죠?ㅎㅎ 반완!

2024-10-15 05:12 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/service/dto/HighlightsRequest.java
> +    }
오오 같은 중복제거를 하면서도 set으로 제한두지 않을 수 있겠군요 반완!

2024-10-15 05:15 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightLine.java
> +import reviewme.highlight.entity.HighlightRange;
도메인이 엔티티를 몰라야하는 이유가 무엇인가요..?😂

2024-10-15 05:36 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightLines.java
> +        this.lines = mapLines(content);
도메인 자체에서 필요하지 않은값22군요..! 뺄 수 있을 것 같아요! 반완!!

2024-10-15 05:40 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/service/mapper/HighlightMapper.java
> +    }
아아 이 장풍 어떡하죠.... 메서드 분리를 하자니 너무 타고타고 들어가는 메서드인게 걸리고....

2024-10-15 05:54 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/service/mapper/HighlightMapper.java
> +    }
일단 메서드 분리 해봤습니당

2024-10-15 05:59 UTC, donghoony approved these changes
일단 어프룹

2024-10-15 05:59 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/entity/Highlight.java
> +        this(answerId, lineIndex, new HighlightRange(startIndex, endIndex));
안 쓰는 생성자입니다~

2024-10-15 05:59 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/domain/HighlightLines.java
`HighlightedLines` 👀

2024-10-15 06:02 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/entity/Highlight.java
> +        this(answerId, lineIndex, new HighlightRange(startIndex, endIndex));
반완!

2024-10-15 06:02 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightLines.java
반완!

2024-10-15 07:36 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/highlight/domain/HighlightLine.java
> +import reviewme.highlight.entity.HighlightRange;
도메인이 엔티티보다 상위의 개념이군요. 그런데 그런 도메인이 엔티티를 의존한다는 측면에서 걸리는 것이었네요.
현재 도메인과 엔티티를 크게 구분하여 사용하고 있지 않기때문에 패키지 통합했습니다!

2024-10-15 08:18 UTC, Kimprodp requested changes
하이라이트를 전체 삭제해야 하는 경우 (빈 값으로 오는 경우)에 대한 테스트만 부탁해요~

2024-10-15 09:01 UTC, nayonsoso requested changes
초간단🍰 리뷰들을 남기게 되었네요~
전체적으로 코드도 훨씬 깔끔해졌고, 객체를 분리하니 test 의 의도도 알기 편했어요☺️
그런데 반복적으로 리뷰하게 되는 부분들이 있는데, 제출 전에 한번 검토하고 PR 올려도 좋을 것 같아요!

---

mapper 로직이 이번 구현에서의 핵심이었던 것 같은데, 저 역시 다른 분들과 동일하게
"변경되기 쉬운 조회 로직인데 코드가 그 중요성 이상으로 길고 복잡한 것 같다"는 생각은 드네요.
그래도 기가막힌 대안이 떠오르지 않는 것 같습니다😅
커비의 코드가 아니라, 구조의 문제인 것 같은데 그냥 적어봅니당 ㅎㅎ

2024-10-15 09:01 UTC, nayonsoso commented on backend/src/main/java/reviewme/highlight/service/HighlightService.java
> +        highlightRepository.deleteAllByAnswerIds(allAnswerIds);
[왕사소 & 취향이라 생각하면 반영 안해도 됨]
변수명 allAnswerIds 보다 answerIds 어떤가요?
allAnswerIds 는 "DB 에 존재하는 모든 답변의 ID"라고 느껴져요~

2024-10-15 09:01 UTC, nayonsoso commented on backend/src/main/java/reviewme/highlight/service/validator/HighlightValidator.java
>          validateQuestionContainsAnswer(request);
[초간단🍰]
validateReviewGroupContainsAnswer 와 validateQuestionContainsAnswer 의 호출 순서와
private 메서드 선언 순서가 일치되면 좋을 것 같아요,

2024-10-15 09:01 UTC, nayonsoso commented on backend/src/main/java/reviewme/highlight/service/dto/HighlightsRequest.java
> +    }
[초간단🍰]
클래스 시작 개행

2024-10-15 09:01 UTC, nayonsoso commented on backend/src/test/java/reviewme/highlight/domain/HighlightedLineTest.java
> +        HighlightedLine highlightedLine = new HighlightedLine(content);
확실히 클래스를 분리하니 테스트 코드 작성이 보기 좋아지네요😊

2024-10-15 09:01 UTC, nayonsoso commented on backend/src/test/java/reviewme/highlight/domain/HighlightedLinesTest.java
> +    ReviewRepository reviewRepository;
[🍰]
private 자꾸 놓치는 것 같아요~

2024-10-15 09:01 UTC, nayonsoso commented on backend/src/test/java/reviewme/highlight/service/HighlightServiceTest.java
> +        long questionId = questionRepository.save(QuestionFixture.서술형_필수_질문()).getId();
[🍰]
static?

2024-10-15 09:01 UTC, nayonsoso commented on backend/src/test/java/reviewme/highlight/service/mapper/HighlightMapperTest.java
> +
[🍰]
private

2024-10-15 09:01 UTC, nayonsoso commented on backend/src/test/java/reviewme/highlight/service/mapper/HighlightMapperTest.java
> +        long questionId = questionRepository.save(QuestionFixture.서술형_필수_질문()).getId();
[🍰]
static import

2024-10-15 09:01 UTC, nayonsoso commented on backend/src/test/java/reviewme/highlight/service/validator/HighlightValidatorTest.java
> +        long questionId2 = questionRepository.save(QuestionFixture.서술형_필수_질문()).getId();
Ditto!

2024-10-15 09:05 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/service/HighlightService.java
> +        highlightRepository.deleteAllByAnswerIds(allAnswerIds);
고민했었는데 산초도 그렇게 생각했다니 반영 갑니다~~

2024-10-15 09:16 UTC, nayonsoso approved these changes
드디어 어프루부! 고생했습니다 커비😊
코드가 정말정말 좋아진 것 같아요!

2024-10-16 01:12 UTC, Kimprodp approved these changes
테스트 어제 확인했는데 어프룹 까먹었음..

리리팩터링은 다음에 고민해봅시다 👍👍

2024-10-16 01:13 UTC, merged