[FE] fix: 리뷰 작성 완료 페이지에 url로 직접 접근하는 행위 방지
woowacourse-teams/2024-review-me pull request #866
Opened 2024-10-16 08:06 UTC by chysis

- resolves #864 

---

### 🚀 어떤 기능을 구현했나요 ?
- 리뷰 작성 완료 페이지에 url로 직접 접근하는 행위를 방지했습니다.

### 🔥 어떻게 해결했나요 ?
- 리뷰 작성 페이지에서 제출 버튼을 누를 때 navigate와 함께 state로 `isValidAccess` 플래그를 전달합니다. 리뷰 작성 완료 페이지에서는 state가 비어있거나, `isValidAccess`가 false일 때 홈페이지로 리다이렉션합니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 

### 📚 참고 자료, 할 말

2024-10-16 12:16 UTC, ImxYJL approved these changes
앞으로 리뷰미의 볼륨이 늘어난다 해도 프리하게 접근할 수 있는 작성 페이지 쪽보다는 쿠키 검증을 거치는 리뷰 확인 쪽이 아닐까 싶어요. 

작성 관련 페이지들이 늘어난다면 이렇게 접근 경로 체크할 일이 늘어날 수도 있으니 별도의 라우팅 관리 로직을 분리해서 관리하는 게 좋겠지만, 그렇지 않을 것 같아욥

그래서 에프이 구현대로 작성 페이지-작성 완료 페이지에서 
간단하게 체크하고 넘어가는 것으로 충분할 것 같습니다~~

2024-10-17 01:48 UTC, BadaHertz52 requested changes
홈으로 리다이렉션되는 것에 대한 ux 우려가 있어요. 해당 코멘트 확인 부탁드려요

2024-10-17 01:48 UTC, BadaHertz52 commented on frontend/src/pages/ReviewWritingCompletePage/index.tsx
> +  useEffect(() => {
제가 유저라면 url로  리뷰 완료 페이지 들어왔을때, 아무런 설명없이 바로 홈으로 리다이렉션이 되면 당황스러울 것 같아요. 

저희가 ux를 생각해 오류가 나도 유저가 오류를 스스로 대응할 수 있는 선택권(홈,새로고침버튼)을 주었듯이, 유효하지 않은 리뷰 작성 완료 페이지에 접근하면 해당 접근이 유효하지 않다는 문구와 함께 홈으로 가는 이동 버튼을 제공하면 어떨까 싶어요

2024-10-17 01:56 UTC, BadaHertz52 commented on frontend/src/pages/ReviewWritingPage/form/hooks/answers/useSubmitAnswers.ts
> +    navigate(`/${ROUTE.reviewWritingComplete}/${reviewRequestCode}`, { state: { isValidAccess: true } });
리뷰 작성 -> 리뷰 작성 완료 -> 리뷰 작성 시에  다시 리뷰 작성 완료 페이지로 문제 없이 갈 수 있는데, 이 부분이 의도된 것인지 궁금해요


https://github.com/user-attachments/assets/7487d0ad-51fb-474e-b6da-7a6882d0c8a6

2024-10-18 09:12 UTC, chysis commented on frontend/src/pages/ReviewWritingPage/form/hooks/answers/useSubmitAnswers.ts
> +    navigate(`/${ROUTE.reviewWritingComplete}/${reviewRequestCode}`, { state: { isValidAccess: true } });
홈으로 돌아가기 버튼을 누른 경우에는 뒤로가기가 막혀 있는데, 위 영상처럼 이동할 때는 인지하지 못하고 있었네요. 수정해보겠습니다 :)

2024-10-19 17:00 UTC, chysis commented
## 수정사항
### 1. Breadcrumb 수정
- 현재는 number 타입의 path를 쓰지 않고 있어서 타입을 수정했습니다.
- location을 사용해서, 현재 페이지가 리뷰 작성 완료 페이지라면 뒤로가기로 돌아갈 수 없게 수정했습니다.

### 리뷰 작성 완료 페이지
- 유효한 접근인 경우: 리뷰 작성 폼 제출 버튼 클릭 시
- 유효한 접근이 아닌 경우, ErrorSection을 보여주어 사용자가 새로고침 또는 홈으로 이동할 수 있게 수정했습니다.

[url 직접 접근 막기.webm](https://github.com/user-attachments/assets/0303c629-2c4e-4ef6-bb2a-b270e7081e58)
▲ 살짝 화질구지입니다..

혹시나 추가적인 버그 발견 시 제보 부탁합니다

2024-10-20 04:03 UTC, ImxYJL commented on frontend/src/components/common/Breadcrumb/index.tsx
> +  path: string;
순수 궁금증) 왜 기존 Path 타입에 number도 있었을까요? 지나치면서 궁금했었는데 이제야 질문을...ㅎ

2024-10-20 04:03 UTC, ImxYJL commented on frontend/src/pages/ReviewWritingCompletePage/index.tsx
> +        handleReload={() => navigate(0)}
유효하지 않은 접근에 새로고침이 필요할까? 싶은 생각이 들었어요. 어차피 유효하지 않은 접근이었다면 아무리 새로고침해도 계속 똑같은 페이지를 보게 될 것이기 때문에...
다른 UI들을 살펴보니 바로 홈으로 리다이렉트시키지는 않지만, 선택지를 홈으로 돌아가기 하나만 주고 있었어요~

2024-10-20 09:29 UTC, chysis commented on frontend/src/components/common/Breadcrumb/index.tsx
> +  path: string;
breadcrumb 리팩토링 이전에는 navigate(0), navigate(-1)도 함께 사용되었어요 :0

2024-10-20 10:24 UTC, BadaHertz52 commented on frontend/src/components/common/Breadcrumb/index.tsx
>      if (typeof path === 'number') {
path가 string 타입만 있다면 `typeof path === 'number'`는 필요없어지겠네요

2024-10-20 10:37 UTC, BadaHertz52 commented on frontend/src/components/common/Breadcrumb/index.tsx
> +    navigate(path, { replace: location.pathname.includes(`/${ROUTE.reviewWritingComplete}`) });
완료 페이지에서 뒤로가기를 막기 보다, 작성 -> 작성 완료 로 넘어갈 때 주는 state를 작성 완료 페이지 마운트 시useNavigate로 페이지 이동은 하지 않으면서 (pathname이 현재와 같으면 페이지 이동을 하지 않는다고 해)`state:null`로 바꾸  작성->작성 완료 -> 작성 에서 다시 이전 으로 돌아기로 작성 완료로 가도 유효하지 않은 접근이라는 것을 보여주면 어떨까요? 이러면 새로 고침 시에도 유효하지 않은 접근으로 처리할 수 있을 것 같아요

2024-10-20 17:10 UTC, chysis commented on frontend/src/components/common/Breadcrumb/index.tsx
>      if (typeof path === 'number') {
현재는 제거된 상태입니다

2024-10-21 08:04 UTC, soosoo22 approved these changes
빠르게 작성 완료 페이지 url 직접 접근을 막아주셨군요! 에프이 수고했어요!

2024-10-21 08:04 UTC, soosoo22 commented on frontend/src/hooks/useBreadcrumbPaths.ts
> +      { pageName: '리뷰 작성 완료', path: pathname },
센스....👍

2024-10-21 08:04 UTC, soosoo22 commented on frontend/src/pages/ReviewWritingCompletePage/index.tsx
> +        handleReload={() => navigate(0)}
저도 올리와 같은 의견입니다. 새로고침을 해도 계속 같은 페이지에 머물기 때문에 "새로고침 하기" 버튼은 없애도 괜찮을 것 같아요!

<img width="1065" alt="스크린샷 2024-10-21 오후 5 03 10" src="https://github.com/user-attachments/assets/03bf3c74-da21-498a-901e-8ab659bf2362">

2024-10-22 01:19 UTC, chysis commented on frontend/src/components/common/Breadcrumb/index.tsx
> +    navigate(path, { replace: location.pathname.includes(`/${ROUTE.reviewWritingComplete}`) });
해당 방법은 추후 다시 적용해보겠습니다! 시도해봤는데 제대로 동작하지 않아서 우선 보류해두었어요

2024-10-22 01:24 UTC, chysis commented
![image](https://github.com/user-attachments/assets/73245b62-812a-43b6-a9f0-ba591cad42d5)
▲ 리뷰 작성 완료 페이지에 url로 바로 접근한 경우

- 홈으로 이동하기 버튼이 primary로 보이도록 수정했습니다.
- breadcrumb을 통해 다른 페이지로 이동한 뒤, 뒤로 갔을 때 replace가 적용되어 있어 돌아가지 않습니다. replace 속성을 동적으로 주는 것보다 state로만 작동하는 것이 더 자연스러울 것 같아서, 이 부분은 더 고민해봐야 할 것 같아요.

2024-10-22 07:16 UTC, BadaHertz52 approved these changes
고생했어요 에프이 👍

2024-10-22 07:16 UTC, merged