[FE] feat: 형광펜 메뉴 및 툴팁 구현
woowacourse-teams/2024-review-me pull request #874
Opened 2024-10-18 08:02 UTC by BadaHertz52

- resolves #872

---

### 🚀 어떤 기능을 구현했나요 ?
-  기존에 있는 형광펜 버튼들을 모아 놓은 형광펜 메뉴 구현
- 디바이스의 터치 지원에 따른, 형광펜 사용방법이 담긴 툴팁 구현
- 글자 선택/드래그 방향 계산 버그 수정
- 모아보기 페이지 주관식 답변에서 개행별로 마크찍히는 버그 수정

### 🔥 어떻게 해결했나요 ?

https://github.com/user-attachments/assets/e230b55d-9ecd-4b89-8448-797c82527157

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
-  시간이 북족해 툴팁 메세지, 디자인을 다 같이 정하지 않고 구현해서 메세지,디자인이 괜찮은 지 봐주세요

### 📚 참고 자료, 할 말
- 쑤쑤가 형광펜 API 에러 핸들링인 토스 모달 작업 중이라, 충돌 범위가 커서  형광펜 리팩토링은 추후에 진행할게요

2024-10-18 08:12 UTC, BadaHertz52 commented
### 형광펜 스위치 버튼 디자인 수정
![스크린샷 2024-10-18 170937](https://github.com/user-attachments/assets/e156746e-517e-4594-b583-11bbce95e564)
![스크린샷 2024-10-18 170943](https://github.com/user-attachments/assets/9b9ba10f-6bb7-4437-b58d-b25409a16006)

2024-10-19 10:56 UTC, BadaHertz52 commented
### API 오류 수정
서버에서는 'ranges'로 주고 클라이언트에서는 'rangeList'로 다루는 것에 따른 타입 오류를 수정했어요.
이제 서버에서 내려주는 형광펜 정보 잘 반영됩니다! 
해당 오류 수정하면서, 리뷰 모아보기 목 데이터에 형광펜 정보 있게 변경했어요.

🌟형광펜 정보에 따라 주관식 답변을 순차적으로 형광펜 적용 부분/미적용 부분으로 잘라야해서, 형광펜 rangeList는 endIndex를 기준으로 오름차순으로 정렬되어야합니다.

2024-10-20 05:28 UTC, ImxYJL requested changes
### 제보
모바일에서, *까지 포함해서 드래그한 뒤 형광펜을 치거나 삭제를 시도하면 해당 동작이 먹히지 않습니다. 노트북에서는 *를 포함해 드래그하면 형광펜 메뉴가 아예 뜨지 않고요. 지금  * 가 이미지로 들어가 있어서 어떻게 보면 당연한 현상이지만 사용성을 위해서는 *는 드래그할 수 없게 막아버리는 게 좋을 것 같습니다.

### 리뷰
PR 본문에 리팩토링의 가능성이 나와 있어서 전반적인 흐름...만 읽어봤습니다. (절대 핑계입니다.) RC는 위의 제보에 대해 얘기해보고 싶어서 남겼읍니다

저번 버전도 좋았는데, 드래그한 영역에 체크됐던 내역이 있다면 형광펜과 지우개를 둘 다 보여주는 개선된 UI가 여러 케이스를 커버할 수 있을 것 같아 더 편리해졌네요!

화면 크기별 툴팁 안내 문구가 다른 것도 좋고, 형광펜 on/off쪽 디자인도 펜 모양을 없애니까 더 깔끔해진 것 같아요.

### 건의
소소한 건의사항으로는, 모바일 환경에서 툴팁을 보면 좁은 width에 많은 글자가 뭉쳐 있다 보니 본문과 툴팁의 구분감이 약한 느낌이 들었어요. 그래서 그림자를 조금 더 진하게 주면 좋을 것 같아요!

또 모바일에서는 텍스트 왼쪽 정렬이 더 예쁠 것 같기도 합니당

2024-10-20 05:28 UTC, ImxYJL commented on frontend/src/components/highlight/components/HighlightEditor/hooks/useCheckHighlight.ts
>  const useCheckHighlight = () => {
이 훅이 단순히 형광펜이 쳐진 영역을 리턴하는 게 아니라 형광펜이 쳐진 영역의 범위를 체크하는 훅이라, 이름에 부가적으로 Range 같은 정보가 들어가면 좋겠...지만 지금도 이해하는 데 어려움은 없습니다ㅎㅎ

2024-10-20 05:28 UTC, ImxYJL commented on frontend/src/components/highlight/components/HighlightButton/index.tsx
>        <span className={SR_ONLY}>하이라이트 추가 버튼</span>
뒷북이지만 😅 `aria-label` 등을 사용하는 대신 `SR_ONLY` 클래스를 별도로 설정한 이유가 궁금해용

2024-10-20 05:28 UTC, ImxYJL commented on frontend/src/types/highlight.ts
>    rangeList: HighlightRange[];
서버와 속성명을 맞추지 못한 이유가 있었나욥?

2024-10-20 05:28 UTC, ImxYJL commented on frontend/src/constants/highlight.ts
> +})();
왜 하이라이트된 영역별로 메뉴 너비를 따로 설정해주고 있지? 싶었는데 케이스에 따라 메뉴에서 보여줘야 하는 요소가 달라져서 그런 거군요ㅋㅋㅋㅋ

2024-10-20 05:28 UTC, ImxYJL commented on frontend/src/components/highlight/components/Tooltip/style.ts
> +  top: calc(1.6rem * 2);
동적인 🔺이었군요

2024-10-20 05:28 UTC, ImxYJL commented on frontend/src/components/highlight/components/Tooltip/index.tsx
> +        </S.Message>
👍👏

2024-10-20 05:28 UTC, ImxYJL commented on frontend/src/components/highlight/components/HighlightEditor/index.tsx
> +            <S.Marker src={DotIcon} alt="점" />
이 * 이미지에 대한 별도의 alt 설명이 필요할까요?

2024-10-20 07:59 UTC, BadaHertz52 commented on frontend/src/components/highlight/components/HighlightButton/index.tsx
>        <span className={SR_ONLY}>하이라이트 추가 버튼</span>
당시에 접근성에 대한 합의가 이루어지지 않고 구조상 해당 버튼에 대한 설명이 안에 들어있는게 좋지 않나 생각했어서, 별로도 관리하는 방향으로 진행했어요.
지금은 aria-label만으로 충분하다고 생각해 이를 사용하는 것으로 변경되었어요.

2024-10-20 08:00 UTC, BadaHertz52 commented on frontend/src/types/highlight.ts
>    rangeList: HighlightRange[];
프론트는 배열에 's'를 사용한 복수형을 쓰지 않기로 했지만, 백엔드쪽에서는 복수형을 사용중이라 타입명에서 차이가 나요

2024-10-20 08:06 UTC, BadaHertz52 commented on frontend/src/components/highlight/components/HighlightEditor/index.tsx
> +            <S.Marker src={DotIcon} alt="점" />
li의 marker를 대신하고 있는 거라, 당시에는 답변 항목 구분자로 의미가 있다고 생각했어요. 
올리 코멘트 받고 찾아보니 스크린 리더기에서는 marker를 읽어주지 않는다고 하네요. 현재는 빈문자열로 변경했어요

2024-10-20 08:09 UTC, BadaHertz52 commented
### 변경 사항
1. li marker용 이미지에 드래그 막음
2.  툴팁 디자인 변경
툴팁의 삼각형이 border로 구현된거라, 그림자나 삼각형을 감싸는 다른 border 구현이 힘든 상황입니다.
삼각형의 제거하거나, 입체적인 느낌을 주는 것에 가장 어색하지 않은 그림자를 사용해야하는 상황입니다.
![스크린샷 2024-10-20 162717](https://github.com/user-attachments/assets/bd051ff8-4132-4bda-80bc-5de5a314c7c0)

2024-10-20 15:00 UTC, donghoony commented on frontend/src/types/highlight.ts
>    rangeList: HighlightRange[];
부연설명을 하자면, 백엔드에서는 자료구조를 변수명에 담지 않습니다 ㅎㅎ.. `str`, `list`와 같은 것을 변수명에 적게 되면 나중에 변수 타입이 달라졌을 때 불일치할 수 있기 때문이예요

2024-10-21 07:44 UTC, ImxYJL commented on frontend/src/types/highlight.ts
>    rangeList: HighlightRange[];
설마 했는데 프리코스때 받았던 피드백과 같은 이유였군요ㅋㅋㅋㅋ

2024-10-21 08:03 UTC, ImxYJL approved these changes
수정사항 전부 확인했습니다~~ 툴팁 그림자는 이 정도만 해도 충분할 것 같아요!

2024-10-21 08:53 UTC, soosoo22 approved these changes
처음엔 형광펜으로 색칠된 영역을 꾹 누르면, 삭제할 수 있다는 부분을 사용자가 알 수 있을까? 싶었는데 툴팁으로 형광펜에 대한 설명을 해주니 처음 사용하는 사용자 입장에서 단번에 이해할 수 있겠네요!


색칠하기와 지우기를 같은 라인에 배치한 부분이 정말 좋네요!
<img width="229" alt="스크린샷 2024-10-21 오후 5 25 32" src="https://github.com/user-attachments/assets/9919c90c-f5f5-4cb6-ba2c-2aa90bc01322">

2024-10-21 12:05 UTC, chysis reviewed
형광펜 메뉴에서 추가/삭제가 동시에 뜨니 확실히 사용하기도 편해졌고, 사용자 입장에서 여러 가지 케이스를 고민하지 않아도 돼서 좋은 것 같아요.

[형광펜 오류.webm](https://github.com/user-attachments/assets/ce8a211f-8774-4c79-9399-89af9724e1eb)
로컬에서 실행해보다가 한 가지 버그를 발견해서 제보합니다! 덧칠할 때 순방향이면 영상과 같은 버그가 없지만 역방향일 때만 저러는 것 같아요.

버그는 알려야 할 것 같아서 RC 남깁니다!

2024-10-21 12:05 UTC, chysis commented on frontend/src/components/highlight/components/HighlightMenu/style.ts
> +export const Menu = styled.div<{ $position: Position; $width: number }>`
리팩토링 시 style props를 interface로 정의하면 될 것 같아요

2024-10-21 12:05 UTC, chysis commented on frontend/src/components/highlight/components/Tooltip/index.tsx
> +        <S.Message role="tooltip">
role 속성도 함께 챙겨주었네요👍

2024-10-21 12:05 UTC, chysis commented on frontend/src/components/highlight/components/HighlightEditor/style.ts
> +  margin-left: 0.8rem;
[지난 커밋](https://github.com/woowacourse-teams/2024-review-me/pull/858/commits/cad22aee197dc1e48e35d0e8ba420c0b63e6427d)에서 margin-left 값을 0.8rem에서 2rem으로 수정했었는데, 이 브랜치에서 확인해 보니 0.8rem일 때도 너무 달라붙어 있다는 느낌이 안 드네요...! 

이 부분이 충돌될 것 같아서 코멘트 남깁니다! 0.8rem도 괜찮으면 이대로 가도 좋을 것 같아요.

![image](https://github.com/user-attachments/assets/ac2c6264-301c-4878-aeaf-785e9f44a859)
▲ 2rem

![image](https://github.com/user-attachments/assets/ef7de2ef-29db-4e4a-8e90-6bd2feeee15f)
▲ 0.8rem

2024-10-21 12:05 UTC, chysis commented on frontend/src/components/highlight/components/HighlightEditor/style.ts
> +  }
list style 말고도 `::marker` 속성을 사용할 수 있군요 :0

2024-10-21 12:06 UTC, chysis requested changes
코멘트 확인 부탁해요 :)

2024-10-21 13:45 UTC, BadaHertz52 commented on frontend/src/components/highlight/components/HighlightEditor/style.ts
> +  margin-left: 0.8rem;
저는 답변과 마크가 일렬로 되어있어서 0.8rem도 괜찮은 것 같아서 0.8rem으로 갈게요

2024-10-21 13:45 UTC, BadaHertz52 commented
에프이 관련 오류 잡았습니다. 오류 잡으면서 리팩토링하다가 잘못 건드렸네요 

![스크린샷 2024-10-21 223327](https://github.com/user-attachments/assets/4eb3fc6f-91c4-4131-a094-0aa717222206)

2024-10-21 14:05 UTC, chysis commented
[오류2.webm](https://github.com/user-attachments/assets/6c931b35-fdc2-46d9-bb88-1b6b16a1611a)
수정 내용 확인했는데 이번에는 처음 형광펜을 칠할 때 위와 같은 문제가 있었어요!

2024-10-21 14:15 UTC, BadaHertz52 commented
## 찐막 형광펜 버튼 위치 오류 수정 
` anchorLineIndex`을 사용해야하는데 ` anchorIndexInLine`을 사용해서 계산했네요.... ㅎㅎㅎ 

https://github.com/user-attachments/assets/91a617b4-5252-4234-a240-d6a518dc8bbd

2024-10-21 14:19 UTC, chysis approved these changes
탈도 많고 기능도 많은 형광펜 메뉴 구현이 드디어 끝났네요! 오류 없는 것 확인했습니다. 고생했어요

2024-10-21 14:20 UTC, merged