[FE] feat: 형광펜 추가 또는 삭제 실패 시, Toast 메시지 표시
woowacourse-teams/2024-review-me pull request #879
Opened 2024-10-19 12:35 UTC by soosoo22

- resolves #835 

---

### 🚀 어떤 기능을 구현했나요 ?
- 모아보기에서 형광펜 API 요청 실패 시 추가 또는 삭제 실패를 사용자에게 알려주는 Toast 메시지 기능을 구현했습니다. 형광펜을 추가하거나 삭제할 때, alert이나 모달을 사용하는 것 보단 일정 시간 동안 표시되고 자동으로 사라지는 Toast를 사용하는 것이 적합하다고 판단했습니다.
- 실패 메시지는 `형광펜 추가에 실패했어요. 다시 시도해주세요.` 및 `형광펜 삭제에 실패했어요. 다시 시도해주세요.`로 설정했습니다.

### 🔥 어떻게 해결했나요 ?
- Toast를 최상단에 위치시키기 위해, createPortal을 이용해서 Toast를 body와 동일한 위치로 옮겼습니다.
- position은 top, bottom 두 가지 상황을 고려했습니다.
```tsx
 return (
    <>
      <ErrorBoundary fallback={ErrorFallback}>
        <HighlightEditor {...props} handleErrorModal={handleErrorModal} handleModalMessage={handleModalMessage} />
      </ErrorBoundary>
      {isOpenErrorModal &&
        createPortal(
          <Toast
            icon={{ src: WarningIcon, alt: '경고 아이콘' }}
            message={modalMessage}
            duration={5}
            position="top"
            handleOpenModal={handleErrorModal}
          />,
          document.body,
        )}
    </>
  );
```

> 기존에 있는 ModalPortal을 사용하지 않은 이유는?

- ModalPortal을 사용하면 아래 코드가 실행되어 스크롤이 없어집니다. 토스트는 모달과 달리 화면의 스크롤을 막을 필요가 없기 때문에 Modal과는 성격이 다르다고 판단해서 사용하지 않았습니다.
```tsx
 const preventBodyScroll = () => {
    document.body.style.overflow = 'hidden';
  };
```

형광펜 추가 또는 삭제 실패 시, 서로 다른 문구를 출력하려면 요청하는 작업의 타입에 따라 오류 메시지를 다르게 설정해야 합니다. onError를 사용해서 각각의 오류 상황에 맞는 메시지를 업데이트하는 방식으로 구현했습니다.

```tsx
// 형광펜 추가 작업
  const addHighlightByDrag = () => {
    // ....
    mutateHighlight(newEditorAnswerMap, {
      onError: () => {
        handleModalMessage(HIGHLIGHT_ERROR_MESSAGES.addFailure);
      },
    });
  };

// 형광펜 삭제 작업
  const removeHighlightByLongPress = async () => {
    // ...
    mutateHighlight(newEditorAnswerMap, {
      onError: () => {
        handleModalMessage(HIGHLIGHT_ERROR_MESSAGES.deleteFailure);
      },
    });
  };
```

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 형광펜 추가 혹은 실패 시, toast가 제대로 뜨는지 다시 한번 확인 부탁합니다:)

### 질문
1. 형광펜 추가 실패 시, toast가 뜨고 형광펜 모드가 off로 바뀌는데 이게 맞는걸까요?

https://github.com/user-attachments/assets/b7a7d08d-b84e-45cd-8e0f-93b2577f6f4e

2. Toast 색상
전자와 후자 중, 개인적으로 생각하기엔 전자는 놓치기 쉬울 것 같고, 후자가 더 돋보이는 느낌이 듭니다. 다들 어떻게 생각하시나요🤔
<img width="708" alt="스크린샷 2024-10-19 오후 8 45 30" src="https://github.com/user-attachments/assets/8614ae4b-9c2f-4e07-a832-21f4211cec2d">

### 📚 참고 자료, 할 말
리뷰미 화이팅..

2024-10-20 12:53 UTC, BadaHertz52 commented on frontend/src/components/highlight/components/HighlightEditorContainer/index.tsx
> +        createPortal(
모달에서 스크롤 이벤트가 문제라면, props로 스크롤 이벤트 실행 여부를 판단할 변수를 내려주면 될 것 같아요. ModlaPortal을 만든 이유는 모달을 하나의 dom의 하위요소에서 관리하기 위함이었어요. (여러 모달을 띄워야하는 경우 index 조정이 쉽고, 여러 모달을 띄우지 않게하는 통제도 쉬워요)

2024-10-20 13:26 UTC, BadaHertz52 commented on frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlight.ts
> +        handleModalMessage(HIGHLIGHT_ERROR_MESSAGES.addFailure);
useMutation 에서는 공통된 오류를 처리하고, mutate에서는 오류별 메세지를 따로 관리하는 거 좋네요 👍

2024-10-20 13:31 UTC, BadaHertz52 commented
쑤쑤, api 오류 시 형광펜 에디터 꺼지는 오류 [해결](https://github.com/woowacourse-teams/2024-review-me/pull/874/commits/7af66178b02accc6bd4100fe714b98ae071aab1b)했고, 형광펜 메뉴,툴팁 pr에 올려져 있어요

2024-10-20 13:36 UTC, BadaHertz52 commented
![스크린샷 2024-10-20 220038](https://github.com/user-attachments/assets/15c4ca82-fa20-450d-afdb-9684c90f1c8d)
검은색으로 한다면, 뒤에 그림자가 비슷한 생각이라 색이 번지는 느낌이 나요.

2024-10-20 13:39 UTC, BadaHertz52 requested changes
쑤쑤 토스트 모달 잘 나오는 거 확인했어요

createPortal관련 문제가 있어서 request  changes 남겨요
이외의 코멘트도 확인 부탁드려요

2024-10-21 13:58 UTC, chysis reviewed
지금은 토스트를 별도의 포탈로 띄우고 있는데(저번에 그 방향으로 얘기했었죠😅), 코드를 살펴보니 기존에 사용하던 ModalPortal을 사용해도 괜찮을 것 같아요. 다만 토스트는 스크롤 이벤트를 막지 않기 때문에 바다의 코멘트처럼 boolean 변수를 두면 괜찮을 것 같아요. 쑤쑤의 의견이 궁금합니다...!

2024-10-21 13:58 UTC, chysis commented on frontend/src/components/highlight/components/HighlightEditorContainer/index.tsx
> +        createPortal(
처음엔 모달과 토스트는 성격이 꽤 달라서 별도의 portal을 사용하는 쪽이 관심사 분리나 관리 측면에서 좀 더 좋지 않을까 생각했어요. 하지만 생각해 보니 모달이 여러 개 뜰 때도 각각 분리된 div로 들어가서, ModalPortal을 사용하되 스크롤 실행 여부만 변수로 판단해도 괜찮을 것 같네요

![image](https://github.com/user-attachments/assets/e013ca8a-507c-4d95-a6c1-b9d54058ba23)

2024-10-21 14:07 UTC, ImxYJL reviewed
쑤쑤 토스트도 구현하고 다른 로직에 적용까지 하느라 고생했어요~~~
Rc하긴 뭐한 초간단 코멘트만 달아봅니다!

2024-10-21 14:07 UTC, ImxYJL commented on frontend/src/components/common/Toast/index.tsx
> +interface ToastModalProps {
컴포넌트는 toast인데 props 인터페이스는 modal이 붙어있네용

2024-10-21 14:07 UTC, ImxYJL commented on frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlight.ts
> +    console.log('new', newEditorAnswerMap.get(2));
콘솔있어요~~!!

2024-10-21 14:07 UTC, ImxYJL commented on frontend/src/components/highlight/components/HighlightEditor/hooks/useHighlight.ts
> +        console.log(startIndex, endIndex);
🐤

2024-10-21 14:07 UTC, ImxYJL commented on frontend/src/components/highlight/components/HighlightEditorContainer/index.tsx
> +        createPortal(
저도 모달과 토스트는 별개로 봐서, 토스트만을 위한 포탈을 새로 만들어도 좋을 것 같다고 생각합니다~~

2024-10-21 14:34 UTC, soosoo22 commented on frontend/src/components/highlight/components/HighlightEditorContainer/index.tsx
> +        createPortal(
ModalPortal을 사용하면 스크롤이 막히기 때문에 Toast와는 다소 성격이 다르다고 생각했어요. 그런데 여러 모달이 뜨는 상황이라면 하나의 dom에서 관리하는게 더 수월하겠네요~

disableScroll props를 넘겨줘서 스크롤을 막는 함수가 실행되지 않게 수정했습니다~

2024-10-21 14:42 UTC, soosoo22 commented on frontend/src/components/common/Toast/index.tsx
> +interface ToastModalProps {
ToastModal에서 Toast로 컴포넌트 이름을 변경했는데 인터페이스 이름도 변경하는 걸 잊어버렸네요...🥹

2024-10-21 14:51 UTC, soosoo22 reviewed
## 변경사항

ModalPortal 사용
- ModalPortal에는 스크롤을 막는 함수가 있어서, 토스트에서 까지 스크롤을 막지는 않아도 된다고 생각했습니다. 그래서 ModalPortal을 사용하지 않고 별개의 createPortal을 사용했습니다. 그러나 모달이 여러 개 뜰 경우 하나의 DOM으로 관리하는 것이 더 효율적일 것 같다는 피드백을 반영하여, disableScroll을 ModalPortal의 props로 전달해 스크롤 막는 함수를 제어가 가능하도록 수정했습니다.

toast 위치 및 box-shadow 조정
- bottom: 5%로 top button과 위치를 맞추고, box-shadow를 조정했습니다.

<img width="480" alt="스크린샷 2024-10-21 오후 11 54 48" src="https://github.com/user-attachments/assets/5228b8e8-c77b-4c75-8436-8cce51bfdf4c">

2024-10-22 01:49 UTC, ImxYJL commented
`ModalPortal`의 네이밍을 여기서 짚고 넘어가야 할까요? 일단 저는 그대로 써도 나쁘지 않겠다는 생각입니다. 변경해도 좋고요~
다만 이름을 바꾼다면 `ModalPortal`을 쓰는 곳이 여러 군데 있어서 그 부분까지 수정해야 할 것 같아요. (쓰는 곳이 한정되어 있긴 하지만요)

2024-10-22 07:19 UTC, BadaHertz52 commented
토스트와 모달을 분리한다면, ModalPortal을 Portal로 네이밍을 변경하는 것을 어떨까요? (ModalPortal의 id도 같이 변경되어야 해요)

2024-10-22 08:02 UTC, soosoo22 reviewed
## 변경사항

네이밍 변경 : ModalPortal => Portal (사유 : 모달과 토스트 둘 다 사용되고 있기 때문)
Portal 폴더 위치 변경 : common/modals/Portal => common/Portal (위와 같은 사유)

2024-10-22 08:14 UTC, BadaHertz52 approved these changes
토스트 구현하느라 고생했어요

2024-10-22 10:07 UTC, ImxYJL approved these changes
포탈 이름까지 바꾸느라 수고했어요~~

2024-10-22 11:09 UTC, chysis commented
고생했어요 쑤쑤!

2024-10-22 11:09 UTC, chysis approved these changes
고생했어요 쑤쑤!

2024-10-22 11:10 UTC, merged