[FE] feat: 작성 페이지의 버튼 활성화 상태 및 현재 섹션 정보를 스크린 리더가 인식하도록 개선
woowacourse-teams/2024-review-me pull request #883
Opened 2024-10-20 05:34 UTC by soosoo22

- resolves #880 

---

### 🚀 어떤 기능을 구현했나요 ?
- `이전, 다음, 작성 내용 확인, 제출` 버튼에 활성화 및 비활성화 상태를 스크린 리더가 읽어줄 수 있도록 aria-label 속성을 추가했습니다.
- 현재 섹션의 순번과 섹션 이름을 스크린 리더가 읽어줄 수 있도록 프로그레스 바의 StepButton에 aria-label 속성을 추가했습니다.

### 🔥 어떻게 해결했나요 ?
#### 버튼 활성화 및 비활성화 상태
- 이전, 다음, 작성 내용 확인, 제출 버튼에 aria-label 속성을 추가해서 스크린 리더가 어떤 버튼인지 인식할 수 있도록 했습니다.
- 다음 버튼은 다른 버튼들과 달리 활성화 및 비활성화 상태를 가집니다. `isAbleNextStep` 상태를 기반으로 활성화 여부를 판단하며. 이 정보를 `aria-label` 속성에 반영하여 현재 버튼의 상태를 스크린 리더 사용자에게 안내합니다.

```tsx
 return (
    <Button
      disabled={!isAbleNextStep}
      styleType={styledType}
      type={'button'}
      onClick={() => handleCurrentCardIndex('next')}
      aria-label={isAbleNextStep ? `활성화된 다음` : `비활성화된 다음`}
      {...rest}
    >
      다음
    </Button>
  );
```

#### 현재 섹션 읽어주기
- 프로그레스 바 버튼에 `aria-label` 속성을 추가해서 스크린 리더가 현재 섹션의 번호를 읽어줄 수 있도록 구현했습니다. 프로그레스 바는 모바일과 데스크탑 환경 두 가지 버전으로 제공되고 있으므로 각각에 맞춰 분리하여 작업했습니다.

모바일
- StepButton에 aria-label 속성을 추가해서 현재 섹션 정보를 스크린 리더가 읽어줍니다.

```tsx
  const MobileProgressBar = ({ currentCardIndex, handleCurrentCardIndex }: MobileProgressBarProps) => {
  // ...
  return (
    <S.ProgressBarContainer>
      <S.ProgressBar ref={progressBarRef}>
        {stepList.map((step, index) => (
          <S.StepWrapper key={step.sectionId} ref={(el) => (stepRefs.current[index] = el!)}>
            {index > 0 ? <S.DottedLine /> : <S.EmptyBlock />}
            <S.StepButton
              // ...
              aria-label={`전체 ${stepList.length}개 섹션 중 ${index + 1}번째 섹션, ${step.sectionName}`} // 추가
            >
              {step.sectionName}
            </S.StepButton>
            {index < stepList.length - 1 ? <S.DottedLine /> : <S.EmptyBlock />}
          </S.StepWrapper>
        ))}
      </S.ProgressBar>
    </S.ProgressBarContainer>
  );
};

export default MobileProgressBar;

```

https://github.com/user-attachments/assets/50418d5e-62f4-4f04-9d0e-dbd0a61874e8

데스크탑
- 현재 섹션에 속해 있는 경우, aria-label에 예를 들어, "현재 섹션은 전체 3개 섹션 중 2번째 섹션입니다. 문제 해결 능력" 내용을 추가했습니다. 그렇지 않은 경우는 섹션 이름만 읽어줍니다.
```tsx
  return (
    <S.ProgressBarContainer>
      <S.ProgressBar role="status" aria-live="polite">
        {stepList.map((step, index) => {
          return (
            <React.Fragment key={step.sectionId}>
              <S.StepButton
                // ...
                aria-label={
                  step.isCurrentStep
                    ? `현재 섹션은. 전체 ${stepList.length}개 섹션 중. ${index + 1}번째 섹션입니다. ${step.sectionName}`
                    : `${step.sectionName}`
                }
              >
                {step.sectionName}
              </S.StepButton>
              {index < stepList.length - 1 && <img src={NavigateNextIcon} alt="다음 화살표" />}
            </React.Fragment>
          );
        })}
      </S.ProgressBar>
    </S.ProgressBarContainer>
  );
```

https://github.com/user-attachments/assets/941778e3-a4f9-4dc9-bb55-eee9016a1afc

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 

### 📚 참고 자료, 할 말

2024-10-21 03:55 UTC, BadaHertz52 commented on frontend/src/pages/ReviewWritingPage/progressBar/components/ProgressBar/index.tsx
> +                aria-label={
- 갤럭시 talkback에서는  '현재 섹션은' 이라는 문구가 나오지 않고, "전체 n으 섹션 중, k번째 섹션, 섹션 이름" 이라는 문구만 들리네요 
- 현재 해당 섹션이 비활성화인 상태일 때, 이를 읽어주지 않고 있어요 
- 섹션이라는 말보다, '질문 카드'와 같이 사용자 친화적인 문구는 어떨까요?

2024-10-21 03:58 UTC, BadaHertz52 commented on frontend/src/pages/ReviewWritingPage/progressBar/components/ProgressBar/index.tsx
> +                aria-label={
저는 currentCardIndex가 바뀌면 현재 카드가 어떤 것지 자동으로 읽어주기를 바랬는데 해당 기능은 구현에서 제외된 걸까요?

2024-10-21 04:04 UTC, BadaHertz52 commented on frontend/src/pages/ReviewWritingPage/slider/components/CardSliderController/index.tsx
> +      aria-label={`이전`}
aria-label 없어도  버튼 이름을 읽어준다면, aria-label은 없어도 되지 않을까요?

2024-10-21 04:08 UTC, BadaHertz52 commented on frontend/src/pages/ReviewWritingPage/slider/components/CardSliderController/index.tsx
> +      aria-label={isAbleNextStep ? `활성화된 다음` : `비활성화된 다음`}
갤럭시 talkback은 aria-label없이 버튼 활성화,비활성화 여부를 읽어주네요

2024-10-21 04:12 UTC, BadaHertz52 requested changes
쑤쑤 스크린 리더기 사용하면서 구현하느라 고생했어요

갤럭시 talkback을 사용해 확인해봤어요. 사용 시 기능 구현이 더 되었으면 좋겠는점 보완했으면 좋겠는 점을 코멘트로 적었으니 확인부탁드려요

2024-10-21 11:49 UTC, ImxYJL requested changes
개선점들 코멘트로 남겼어요~!
반영했으면 하는 것도 있고 단순 제안인 것들도 있는데 알아서 잘 걸러주실거라 믿습니다ㅋㅋㅋ
마지막까지 화이팅~~@

2024-10-21 11:49 UTC, ImxYJL commented on frontend/src/pages/ReviewWritingPage/progressBar/components/MobileProgressBar/index.tsx
> +              aria-label={`전체 ${stepList.length}개 섹션 중 ${index + 1}번째 섹션, ${step.sectionName}`}
첫 번째 섹션이라고 읽어주면 좋을 텐데 한 번째 섹션이라고 읽어주네요 🤣

2024-10-21 11:49 UTC, ImxYJL commented on frontend/src/pages/ReviewWritingPage/progressBar/components/MobileProgressBar/index.tsx
> +              aria-label={`전체 ${stepList.length}개 섹션 중 ${index + 1}번째 섹션, ${step.sectionName}`}
모바일 프로그레스 바에서는 간단하게 -섹션 하고 끝나는데, 일반 프로그레스 바에서는 -입니다. 로 마무리하고 있네용

2024-10-21 11:49 UTC, ImxYJL commented on frontend/src/pages/ReviewWritingPage/progressBar/components/ProgressBar/index.tsx
> +                aria-label={
저도 섹션보다 더 직관적이고 쉬운 이름을 사용했으면 합니다!
또 비활성화된 progress는 tab에서는 제외돼도 스크린 리더에서는 읽어줘야 할 것 같아요. "단점 피드백, 비활성화" 이런 느낌으로용

2024-10-21 11:49 UTC, ImxYJL commented on frontend/src/pages/ReviewWritingPage/slider/components/CardSliderController/index.tsx
> +      aria-label={isAbleNextStep ? `활성화된 다음` : `비활성화된 다음`}
버튼이 비활성화된 상태에서는 모바일 환경에서 단독으로 버튼을 탭할 수 없어서 버튼 상태에 대해 쉽게 알기가 어렵더라고요ㅠㅠ 스크린 리더 사용자가 더 쉽게 사용하려면 aria-live="assertive" 등으로 버튼 상태가 변할 때마다 바로 알려주는 게 좋을 것 같아요!

2024-10-21 11:49 UTC, ImxYJL commented on frontend/src/pages/ReviewWritingPage/slider/components/CardSliderController/index.tsx
> +      aria-label={isAbleNextStep ? `활성화된 다음` : `비활성화된 다음`}
뒤에 "버튼"과 추가 설명도 붙여주면 더 자연스러울 것 같아용
"활성화된 다음 버튼, 다음으로 넘어가려면 클릭하세요" 라던가 "비활성화된 다음 버튼, 리뷰 작성을 완료해주세요" 처럼?
흠 근데 label 말투는 -다 체니까 또 수정해야 할지도...

2024-10-21 15:53 UTC, soosoo22 commented on frontend/src/pages/ReviewWritingPage/progressBar/components/ProgressBar/index.tsx
> +                aria-label={
현재 위치해 있는 프로그레스 바 버튼을 focus하면 현재 카드 섹션이 몇 번째 섹션인지 알려주면 되겠지 싶었는데 생각해보니 자동으로 읽어줘야 하는 군요!...

2024-10-21 16:01 UTC, soosoo22 commented on frontend/src/pages/ReviewWritingPage/slider/components/CardSliderController/index.tsx
> +      aria-label={`이전`}
읽어주는군요! `aria-label={"이전"}` 을 추가해도 `이전, 이전 버튼`이 아니라 `이전, 버튼` 이라고 읽어주네용

2024-10-21 16:17 UTC, soosoo22 commented on frontend/src/pages/ReviewWritingPage/slider/components/CardSliderController/index.tsx
> +      aria-label={isAbleNextStep ? `활성화된 다음` : `비활성화된 다음`}
> 갤럭시 talkback은 aria-label없이 버튼 활성화,비활성화 여부를 읽어주네요

아이폰 사파리에서는 비활성화 버튼이라면 "다음, 흐리게 표시됨, 버튼" 으로 읽어주고 있네요. "흐리게 표시됨" 이라는 표현을 듣고 바로 비활성화 버튼이라는 걸 알 수 있을까요? 단순 궁금증입니다!

https://github.com/user-attachments/assets/899328cb-21ae-468a-88b6-6bd98c153fe2

2024-10-21 16:47 UTC, chysis reviewed
눌렀을 때 모달이 뜨는 버튼의 경우엔 모달이 뜬다는 안내 문구가 추가되면 좋을 것 같아요. 우선 코드는 확인했고, 오전 중으로 스크린 리더로 읽어보겠습니다~!

2024-10-21 16:47 UTC, chysis commented on frontend/src/pages/ReviewWritingPage/slider/components/CardSliderController/index.tsx
> +      aria-label="작성 내용 확인"
작성 내용 확인의 경우 누르면 모달이 뜬다는 내용을 함께 안내해주면 어떨까요?

2024-10-21 16:47 UTC, chysis commented on frontend/src/pages/ReviewWritingPage/slider/components/CardSliderController/index.tsx
> +      aria-label="제출"
제출 버튼도 누르면 모달이 뜬다는 내용을 안내해주면 좋을 것 같아요!

2024-10-21 23:28 UTC, soosoo22 commented on frontend/src/pages/ReviewWritingPage/slider/components/CardSliderController/index.tsx
> +      aria-label={isAbleNextStep ? `활성화된 다음` : `비활성화된 다음`}
> 버튼이 비활성화된 상태에서는 모바일 환경에서 단독으로 버튼을 탭할 수 없어서 버튼 상태에 대해 쉽게 알기가 어렵더라고요ㅠㅠ 스크린 리더 사용자가 더 쉽게 사용하려면 aria-live="assertive" 등으로 버튼 상태가 변할 때마다 바로 알려주는 게 좋을 것 같아요!

맥북 보이스 오버로 탭하면서 확인하다 보니 모바일을 고려하지 못한 것 같네요😭

2024-10-21 23:29 UTC, soosoo22 commented on frontend/src/pages/ReviewWritingPage/progressBar/components/MobileProgressBar/index.tsx
> +              aria-label={`전체 ${stepList.length}개 섹션 중 ${index + 1}번째 섹션, ${step.sectionName}`}
통일할게요...🥹

2024-10-21 23:58 UTC, soosoo22 commented on frontend/src/pages/ReviewWritingPage/slider/components/CardSliderController/index.tsx
> +      aria-label="작성 내용 확인"
모달이 뜨는 경우도 알려줘야 겠네요!
`aria-label="작성 내용 확인 버튼. 클릭 시 작성한 내용을 한눈에 볼 수 있는 모달이 열립니다." ` 추가했습니다~

2024-10-22 01:00 UTC, soosoo22 reviewed
## 변경사항

1. 다음 버튼을 누르고 다음 카드 섹션으로 넘어가면, 자동으로 `현재 질문 카드는 전체 3개 카드 중, 2번째 카드입니다. 문제 해결 능력` 을 읽어줍니다.

https://github.com/user-attachments/assets/4c68acbe-f7ac-4f81-af98-818c3af46618

https://github.com/user-attachments/assets/0b7de5c0-5845-4cfe-8922-0d8b2f6753c2



2. 작성 내용 확인, 제출 버튼과 같이 모달이 열리는 버튼은 aria-label을 통해 클릭 시, 모달이 열림을 알려줍니다.

3. 사파리에서는 활성화 유무를 `다음, 흐리게 버튼` 이런 식으로 읽어줘서 활성화 유무를 읽어주기 위한 aria-label 추가했습니다.
 ~- `aria-live="assertive"` 코드를 추가해서 활성화 상태가 변경되면 자동으로 읽어주는 기능을 추가했습니다.~ 
`aria-live` 속성을 추가하여 버튼의 활성화 상태 변경을 자동으로 읽도록 했으나, 다음과 같은 이유로 철회했습니다:

- 체크박스 버튼 선택 시, 체크박스의 상태가 아닌 다음 버튼의 활성화 상태가 먼저 읽혀 혼란을 유발.
- 다음 버튼 클릭 후, 카드 섹션이 넘어갈 때 비활성화 상태 알림이 질문보다 먼저 나와서 흐름이 어색해짐.


5. 프로그레스 바 버튼의 활성화, 비활성화 상태를 읽어주는 aria-label 추가

https://github.com/user-attachments/assets/fd52c956-497f-409b-b405-151fb475d443



### 고민
다음 버튼의 활성화 상태가 변경되면 자동으로 읽어주는 기능을 추가해야 하는가?
- 스크린 리더 사용자는 실시간으로 버튼이 활성화되었는지 단번에 확인하기 어렵기 때문에 체크박스를 선택하고 다음 버튼이 활성화 되면 활성화 된 버튼이라고 알려주는 게 좋다고 생각해요... 다만 활성화 상태가 변경될때마다 계속 알려주면 오히려 듣기 거북하지 않을까.... 싶네요🥹
=> 아무래도 스크린 사용자 입장에서는 알려주는 것이 좋다고 생각합니다~ 추가했습니다~ 3번이요~

2024-10-22 01:27 UTC, ImxYJL commented
변경사항 테스트해봤는데, 이런 궁금증이 있어요
1. 객관식을 선택할 때마다 현재 어떤 섹션에 있는지를 알려주는데, 의도한 동작인가요?
2. 버튼이 활성화될 때 바로 읽어주는 기능을 제안했는데 어떻게 생각하시는지 궁금해요 
3. 첫 번째 강점을 묻는 객관식을 선택하고 난 뒤 화면이 상단으로 이동하고 있어요

2024-10-22 01:47 UTC, soosoo22 commented
> 1. 객관식을 선택할 때마다 현재 어떤 섹션에 있는지를 알려주는데, 의도한 동작인가요?

전혀 의도하지 않았구요.. 제가 useEffect 의존성 배열에 stepList를 넣어서 객관식을 선택할때마다 stepList가 변경되면서 스크린 리더가 변경된 currentCardIndexDescription을 읽으면서 일어난 이슈였습니다...😭

의존성 배열에서 stepList 제거했습니다~
```tsx
  useEffect(() => {
    if (stepList.length > 0 && stepList[currentCardIndex]) {
      setCurrentCardIndexDescription(
        `현재 질문 카드는, 전체 ${stepList.length}개 카드 중, ${currentCardIndex + 1}번째 카드입니다. ${stepList[currentCardIndex].sectionName}`,
      );
    }
  }, [currentCardIndex, stepList]);
```

> 2. 버튼이 활성화될 때 바로 읽어주는 기능을 제안했는데 어떻게 생각하시는지 궁금해요

간과한 부분인 것 같네요🥹 스크린 리더 사용자 입장에선 활성화, 비활성화 상태를 자동으로 알려줌으로써 보다 편하게 리뷰미 서비스를 사용할 수 있을 것 같네요:)


> 3. 첫 번째 강점을 묻는 객관식을 선택하고 난 뒤 화면이 상단으로 이동하고 있어요

이것도 1번 이슈를 해결하고 난 뒤, 없어졌습니다~

2024-10-22 07:32 UTC, BadaHertz52 commented on frontend/src/pages/ReviewWritingPage/progressBar/components/MobileProgressBar/index.tsx
>                type="button"
지금 현재 button에 disabled 속성이 없어서, 기본값이 true로 작용해 스크린 리더기가 비활성화 버튼임에도  "비활성화된 ~~'활성화하려면 두 번 탭하세요" 라고 읽어요. disabled 속성을 추가해야겠어요.

disabled 속성이 있으면 스크린 리더기가 활성화/비활성화를 판단해서 적절한 멘트를 주기때문에 aria-label에는 활성화 ,비활성화 보다는 현재 열린 카드인지를 판단해 말해주는 것을 어떨까요?

2024-10-22 07:36 UTC, BadaHertz52 commented on frontend/src/pages/ReviewWritingPage/slider/components/CardSliderController/index.tsx
> +      aria-live="assertive"
`aria-live="assertive"` 속성 때문인지, "리뷰 작성 페이지들어가면 다음 버튼이 비활성화되었습니다"라고 읽어주네요. 해당 페이지에 어떤 질문이 있는 지 모른 상태에서 비활성화 여부를 읽어주는 플로우라 좀.. 당황스러웠어요.

2024-10-22 08:23 UTC, soosoo22 commented on frontend/src/pages/ReviewWritingPage/progressBar/components/MobileProgressBar/index.tsx
>                type="button"
저도 동의합니다! disabled 속성 추가했습니다👍

```tsx
 <S.StepButton
                // ...
                aria-label={step.isCurrentStep ? `현재 질문 카드는, ${step.sectionName}입니다` : `${step.sectionName}`}
                disabled={!step.isMovingAvailable}
              >
                {step.sectionName}
 </S.StepButton>
```

2024-10-22 11:24 UTC, soosoo22 commented on frontend/src/pages/ReviewWritingPage/slider/components/CardSliderController/index.tsx
> +      aria-live="assertive"
다음 버튼의 활성화 상태에 따라 자동으로 읽어주는 기능이 필요할 것 같아서 추가했는데 그런 이슈가 있군요...

2024-10-22 14:08 UTC, soosoo22 reviewed
# ⭐️ 최최종 ⭐️

1. `다음` 버튼에 활성화 및 비활성화 상태를 알려주기 위한 `aria-label` 속성 추가
```tsx
      aria-label={isAbleNextStep ? '다음 버튼이 활성화되었습니다' : '다음 버튼이 비활성화되었습니다.'}
```
2. 모달이 열리는 버튼의 경우(작성 내용 확인, 제출) 클릭 시 ,어떤 동작이 이루어지는지 `aria-label`에 구체적으로 설명 추가
```tsx
      aria-label="제출 버튼입니다, 클릭 시 작성한 내용을 제출합니다"
      aria-label="작성 내용 확인 버튼입니다, 클릭 시 작성한 내용을 한눈에 볼 수 있는 모달이 열립니다"
```

3. 현재 위치한 카드의 이름을 `aria-label`에 추가하고, `disabled` 속성을 사용하여 스크린 리더가 버튼의 활성화 여부를 자동으로 인식하고 읽어줄 수 있도록 설정
```tsx
    aria-label={step.isCurrentStep ? `현재 질문 카드는, ${step.sectionName}입니다` : `${step.sectionName}`}
    disabled={!step.isMovingAvailable}
```

4. 이전 또는 다음 버튼을 눌러 카드가 이동할 때, 현재 카드의 위치를 읽어주는 기능 추가

```tsx
  useLayoutEffect(() => {
    setCurrentCardIndexDescription(
      `현재 질문 카드는, 전체 ${stepList.length}개 카드 중, ${currentCardIndex + 1}번째 카드입니다. ${stepList[currentCardIndex].sectionName}`,
    );
// ...
  }, [currentCardIndex]);

      <span className="sr-only" aria-live="polite">
        {currentCardIndexDescription}
      </span>
```

2024-10-23 01:27 UTC, ImxYJL commented
#### 다음 버튼
- 지금 다음 버튼이 활성화된 상태에서, 갤럭시 talkback에서는 "다음 버튼이 활성화되었습니다. 활성화하려면 두 번 탭하세요." 라고 알려줘서 사용자 입장에서는 당황스러울 수 있겠다는 생각이 들어요. 이것도 갤럭시 이슈일까요ㅋㅋㅋ

#### 현재 섹션 읽기
최초 진입(카테고리 선택) 시에는 현재 n번째 섹션입니다~ 로 잘 읽어주는데, 2번째 섹션부터는 다음 버튼으로 넘어가도 읽어주지 않습니다... 

이하는 쑤쑤가 프로그레스 바 접근성 담당은 아니지만 😅 나중에라도 참고하기 위해서 코멘트 남깁니당.
#### 프로그레스 바
현재 선택된 섹션을 누르면 "활성화하려면 두 번 탭하세요" 라고 알려주는데, 프로그레스 바 특성상 활성화보다는 "클릭하면 해당 카드로 이동합니다." 등을 안내하는 게 조금 더 자연스러울 것 같아용

다만 이건 버튼 기본 동작인 것 같아 어떻게 무시하는지는 잘 모르겠네요...

2024-10-23 04:06 UTC, ImxYJL approved these changes
이것저것 살펴보느라 고생했어요! 일단 어프룹할게요~~~~

2024-10-23 04:06 UTC, chysis approved these changes
꽤 건드릴 곳이 많았을 텐데 접근성 개선하느라 고생했어요!

2024-10-23 04:06 UTC, BadaHertz52 approved these changes
최종 데모데이 QA를 위해 일단 approve 할게요. 코멘트 보고 수정/보완 사항있으면 pr 날려주세요

2024-10-23 04:06 UTC, merged