[FE] feat: 리뷰 작성 페이지 기능 구현
woowacourse-teams/2024-review-me pull request #89
Opened 2024-07-24 01:51 UTC by chysis

- resolves #72 

---

### 🚀 어떤 기능을 구현했나요 ?
- 질문 목록과 키워드 목록을 API로 불러온다.
- 키워드 버튼은 최소 1개, 최대 5개 선택 가능하다.
- 리뷰는 최소 20자, 최대 1000자 입력 가능하다.
- 임시로 만든 '저장' 버튼을 제거한다.
- 모든 폼이 선택되었을 때만 '제출' 버튼이 활성화되도록 버튼 유효성 검사 로직을 추가한다.
- 각 질문에 안내 문구 및 placeholder를 추가한다.
- textarea의 크기를 고정시키고, 스크롤 가능하도록 변경한다.
- textarea의 현재 글자수를 화면에 표시한다.
- 제출 버튼을 클릭할 경우 경고 문구와 함께 confirm을 띄운다.
- confirm에서 확인 버튼을 클릭 시 '작성 완료 페이지'로 이동하도록 라우터를 설정한다.

### 🔥 어떻게 해결했나요 ?
- 피그마에 작성한 화면 정의서를 바탕으로 기능을 구현했습니다.
![image](https://github.com/user-attachments/assets/d06434c6-dd88-4346-a6c6-30cc5ca4d44b)
▲ 리뷰 작성 폼

![image](https://github.com/user-attachments/assets/366d93f0-27eb-4ebd-838e-a7e3f45c4bb7)
▲ 키워드 선택 폼

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 상태를 우선 백엔드 측에서 안내한 API 타입에 맞추어 더미 데이터로 만들었습니다. 추후 API 연동 가능해질 때 주석을 해제하고, 코드를 약간 수정하면 됩니다.
- 위에서 언급한 기능 구현 사항들이 잘 지켜졌는지 확인해주세요.

### 📚 참고 자료, 할 말
- 데이터를 동적으로 불러오기 때문에 상태 관리가 조금 더 복잡해진 것 같아요. 좋은 경험이었습니다 :)

2024-07-24 01:53 UTC, chysis commented on frontend/src/components/common/Button/styles.ts
> +  }}
styled component 내부에서 switch문을 사용해 조건부 스타일링을 했습니다.

2024-07-24 02:30 UTC, BadaHertz52 commented on frontend/src/components/common/Button/styles.ts
> +  ${({ theme, buttonType }) => {
현재 코드는 버튼 타입이 늘어날 수록 하나의 스타일에 대한 코드의 길이가 길어지는 문제가 있어요.

버튼 타입별로 스타일을 따로 만들고 버튼 컴포넌트에서 버튼 타입별로 다른 버튼 스타일을 return하는 방식은 어떨까요?

2024-07-24 02:30 UTC, BadaHertz52 commented on frontend/src/pages/ReviewWriting/components/ReviewItem/index.tsx
> +    if (value.length <= 1000) {
100이 매직넘버로 들어가있네요.
constants/review.ts 의 메세지에도 100이 들어가있는데, 100을 상수화해보는 거는 어떨까요?

2024-07-24 02:30 UTC, BadaHertz52 commented on frontend/src/pages/ReviewWriting/components/ReviewItem/index.tsx
> +        onChange={(e) => handleInputChange(e)}
```tsx
onChange={handleInputChange}
```
이렇게 적어도 될 것 같아요.

2024-07-24 02:30 UTC, BadaHertz52 commented on frontend/src/pages/ReviewWriting/index.tsx
> +    console.log(reviewData);
console.log를 남겨둔 이유가 있을까요?

2024-07-24 02:31 UTC, BadaHertz52 requested changes
하루만에 기능을 완성하다니 고생했어요 에프이👏👏👏👏
개인적으로 사소한 부분에서 수정되었으면 좋겠다는 부분이 있어 관련 코멘트 남겼어요.
확인 부탁드려요

2024-07-24 05:33 UTC, chysis commented on frontend/src/pages/ReviewWriting/index.tsx
> +    console.log(reviewData);
서버와 통신하기 전까지, 제출할 때 입력한 폼 정보를 쉽게 확인할 수 있도록 console을 남겼어요.

2024-07-24 06:24 UTC, chysis commented on frontend/src/pages/ReviewWriting/components/ReviewItem/index.tsx
> +    if (value.length <= 1000) {
급하게 만들다 보니 상수화를 안 했네요😅 
리뷰 답변의 최대/최소 글자수와 키워드 최대/최소 선택 가능 개수, 그리고 관련 메시지도 상수화했어요.

[4dbeacb](https://github.com/woowacourse-teams/2024-review-me/pull/89/commits/4dbeacbf8dce393fcde20c4d331af9833c5ce7c0)

2024-07-24 06:25 UTC, chysis commented on frontend/src/pages/ReviewWriting/components/ReviewItem/index.tsx
> +        onChange={(e) => handleInputChange(e)}
간단하게 가져갈 수 있네요👍👍

2024-07-24 07:09 UTC, ImxYJL requested changes
짧은 시간이었는데 이렇게 두둑한 changed files라니... 고생 많았어요~~~!
소소한 것들 위주로 코멘트 남겼습니다!

2024-07-24 07:09 UTC, ImxYJL commented on frontend/src/pages/ReviewWriting/index.tsx
> +      alert('키워드는 최대 5개까지 선택할 수 있어요.');
최대 키워드 개수에 대한 상수화는 아직일까요?!

2024-07-24 07:09 UTC, ImxYJL commented on frontend/src/pages/ReviewWriting/index.tsx
> -    // NOTE: 모킹 데이터
여기는 가독성을 위해 중괄호를 사용한 리턴을 한 건가요? 확실히 if문 안이 길긴 하네요!

2024-07-24 07:09 UTC, ImxYJL commented on frontend/src/pages/ReviewWriting/index.tsx
> +    navigate('/user/review-writing-complete', { replace: true });
뒤로가기 막아둔 것 굿굿!

2024-07-24 07:09 UTC, ImxYJL commented on frontend/src/pages/ReviewWriting/index.tsx
> +                answerValue={answers.find((answer) => answer.questionId === question.id)?.answer || ''}
이 answerValue 값은 추후 임시 저장을 구현했을 때 샤용하는 값인가요?

2024-07-24 07:09 UTC, ImxYJL commented on frontend/src/pages/ReviewWriting/index.tsx
> +  const isValidAnswerLength = !answers.some((id) => id.answer.length < REVIEW.answerMinLength);
`isValidAnswerLength`이라고 하면 뭔가 개별 답변에 대한 유효성이라는 생각이 드는데, All 등의 단어를 추가해보는 건 어떨까요??

2024-07-24 08:33 UTC, chysis commented on frontend/src/pages/ReviewWriting/index.tsx
> +                answerValue={answers.find((answer) => answer.questionId === question.id)?.answer || ''}
answerValue는 `ReviewItem`에 입력된 값을 그 부모인 `ReviewWriting`에서 관리하기 위해 사용되는 값이에요. 폼을 제출하기 위해 부모 컴포넌트로 상태를 끌어올리는 방식이라 생각하시면 될 것 같아요!

2024-07-24 08:41 UTC, chysis commented on frontend/src/pages/ReviewWriting/index.tsx
> -    // NOTE: 모킹 데이터
저도 모르는 사이에 중괄호를 사용했네요...😅 컨벤션을 잘 기억할게요

2024-07-24 08:42 UTC, chysis commented on frontend/src/pages/ReviewWriting/index.tsx
> +      alert('키워드는 최대 5개까지 선택할 수 있어요.');
`keywordMaxCount`가 최대로 선택할 수 있는 키워드 개수예요! alert의 경우에는 모달을 대체해서 임시로 만들어둔 코드라 추가적으로 상수화를 진행하지는 않았어요.

2024-07-24 08:47 UTC, chysis commented on frontend/src/pages/ReviewWriting/index.tsx
> +  const isValidAnswerLength = !answers.some((id) => id.answer.length < REVIEW.answerMinLength);
상태의 이름인 `answers`를 따라서 `isValidAnswersLength`로 수정해보았어요. 변수명 같은 경우엔 차차 리팩토링할 생각입니다 :)

2024-07-24 15:21 UTC, chysis commented on frontend/src/components/common/Button/styles.ts
> +  ${({ theme, buttonType }) => {
당장은 타입이 세 종류밖에 없어서 충분하다고 생각하지만, 앞으로의 확장 가능성을 고려했을 때 스타일을 분리하는 것도 좋은 방법인 것 같아요. 리팩토링 했습니다~

[4a99207](https://github.com/woowacourse-teams/2024-review-me/pull/89/commits/4a9920708787d207680232fb8a64d41afbfb7f61)

2024-07-24 21:42 UTC, soosoo22 approved these changes
수고했어요 에프이!

2024-07-24 21:42 UTC, soosoo22 commented on frontend/src/apis/review.ts
> +export const getDataToWriteReview = async (reviewerGroupId: number) => {
[코드 컨벤션](https://github.com/woowacourse-teams/2024-review-me/wiki/%5BFE%5D-%EC%BD%94%EB%93%9C-%EC%BB%A8%EB%B2%A4%EC%85%98)에 api 호출 함수명은 일반 기능 함수명과 구분 짓기 위해 끝에 Api를 붙이기로 했어요!
`API 호출 함수명은 *Api로 끝나게 한다.`

2024-07-24 21:42 UTC, soosoo22 commented on frontend/src/pages/ReviewWriting/components/KeywordButton/index.tsx
> +const KeywordButton = ({ isSelected, children, ...props }: PropsWithChildren<KeywordButtonProps>) => {
```suggestion
const KeywordButton = ({ isSelected, children, ...props }: React.PropsWithChildren<KeywordButtonProps>) => {
```

PropsWithChildren import 하지 않아도 돼요~

2024-07-24 21:43 UTC, soosoo22 requested changes
리뷰 반영하고 알려주세용~

2024-07-25 00:44 UTC, BadaHertz52 commented on frontend/src/constants/review.ts
>    answerMaxLengthMessage: '최대 1000자까지 입력 가능해요.',
answerMaxLengthMessage에도 1000이 들어가서 1000을 상수화한 변수를 템플릿 리터럴로 사용하면 좋을 것 같아요.
그러면 최대 글자수에대한 하나의 상수값만 변경하면 되니까요.

이거는 나중에 리뷰에 대한 상수들이 더 들어왔을 때 리팩토링을 하면서 진행해도 좋을 것 같네요 😊

2024-07-25 00:45 UTC, BadaHertz52 commented on frontend/src/pages/ReviewWriting/components/ReviewItem/index.tsx
> +        onChange={(e) => handleInputChange(e)}
이 부분은 ```onChange={(e) => handleInputChange(e)} ``` 이 형태로 남겨두신 이유가 있을까요?

2024-07-25 00:47 UTC, BadaHertz52 approved these changes
에프이 수정된 코드 잘 봤어요.
handleChange에 대해서 코멘트를 남겼는데 이 부분 한번 확인 부탁드려요.

고생하셨습니다.!

2024-07-25 01:03 UTC, ImxYJL approved these changes
리팩토링까지 하느라 수고 많았어요~!~!!

2024-07-25 01:21 UTC, chysis commented on frontend/src/pages/ReviewWriting/components/ReviewItem/index.tsx
> +        onChange={(e) => handleInputChange(e)}
handler로 전달되는 인자를 명시한다는 정도인데 큰 이유는 아니에요!

2024-07-25 01:22 UTC, chysis commented on frontend/src/apis/review.ts
> +export const getDataToWriteReview = async (reviewerGroupId: number) => {
`-Api` suffix를 놓치고 있었네요! 감사합니다 :)

2024-07-25 01:23 UTC, chysis commented on frontend/src/pages/ReviewWriting/components/KeywordButton/index.tsx
> +const KeywordButton = ({ isSelected, children, ...props }: PropsWithChildren<KeywordButtonProps>) => {
React에서 제공하는 타입으로 수정했어요 :)

2024-07-25 01:23 UTC, chysis commented on frontend/src/constants/review.ts
>    answerMaxLengthMessage: '최대 1000자까지 입력 가능해요.',
메모해둘게요! 👍

2024-07-25 01:55 UTC, soosoo22 approved these changes
리뷰 반영 수고했어요~

2024-07-25 01:58 UTC, merged