[FE] feat: 리뷰 목록 페이지 구현
woowacourse-teams/2024-review-me pull request #90
Opened 2024-07-24 01:55 UTC by soosoo22

- resolves #73 

---

### 🚀 어떤 기능을 구현했나요 ?
- 리뷰 목록 페이지 구현
- 리뷰 목록 데이터 인터페이스 정의

### 🔥 어떻게 해결했나요 ?
- `ReviewPreviewCard`
  - 리뷰 미리보기 카드 컴포넌트를 구현했습니다.
  - 추후 메인 페이지에 PIN으로도 활용될 수 있어서 `src/components/` 폴더 안에 생성했습니다.
  - 리뷰 미리보기를 위한 카드 컴포넌트로, 리뷰 그룹 정보, 생성일, 내용 미리보기, 키워드 및 공개 여부를 표시합니다.
   
- `ReviewPreviewListPage`
  - 리뷰 목록 페이지를 구현했습니다.
  - `ReviewPreviewCard` 컴포넌트를 사용해서 리뷰 목록을 렌더링했습니다.
  - `SearchSection` 컴포넌트 추가
  - `mockReviewPreviews` 데이터 추가

결론 : 리뷰 목록 페이지에서 검색 및 필터링 기능을 지원하기 위해 `SearchSection`을 추가하고, mock 데이터를 기반으로 `ReviewPreviewCard` 컴포넌트를 활용하여 리뷰 목록을 렌더링하도록 구현했습니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 리팩 방향에 대해서 조언을 주신다면 정말 감사할 것 같습니다~😊

### 📚 참고 자료, 할 말
- 🍀 네잎클로버의 꽃말이 행운이라고 합니다. 근데 세잎클로버의 꽃말은 행복이라고 해요. 우리는 그 수많은 행복을 짓밟고 행운을 찾아 떠납니다. 우리 모두 지금의 행복을 소중히 여기며, 행운이 찾아오기를 기다립시다~

2024-07-24 02:31 UTC, chysis reviewed
쑤쑤! 리뷰 목록 페이지 구현하느라 고생 많으셨어요😊
몇 가지 간단한 코멘트를 남겼으니 선택적으로 반영해주시면 좋을 것 같아요 :)

2024-07-24 02:31 UTC, chysis commented on frontend/src/components/common/DropDown/index.tsx
> +    <S.Wrapper onChange={handleChange}>
옵션이 여러 개 있는 경우 `Wrapper`보다는 `Container`가 적절할 것 같은데, 쑤쑤의 생각은 어떤가요?

2024-07-24 02:31 UTC, chysis commented on frontend/src/components/common/SearchInput/styles.ts
> +  &::placeholder {
placeholder를 따로 스타일링할 수 있군요!
몰라서 따로 스타일 설정을 못 했는데 하나 배워가요😊😊

2024-07-24 02:31 UTC, chysis commented on frontend/src/components/ReviewPreviewCard/index.tsx
> +          <img src={isPublic ? UnLock : Lock} />
`img` 태그에 접근성도 챙겨주면 좋을 것 같아요!

2024-07-24 02:31 UTC, chysis commented on frontend/src/components/ReviewPreviewCard/styles.ts
> +  border-top-right-radius: 0.8rem;
`border-radius: 0.8rem 0.8rem 0 0;`으로 한 번에 표시해줄 수 있을 것 같아요 :)

2024-07-24 04:13 UTC, BadaHertz52 commented on frontend/src/components/ReviewPreviewCard/index.tsx
> +          <img src={isPublic ? UnLock : Lock} />
img에 alt가 없네요

2024-07-24 04:33 UTC, BadaHertz52 requested changes
쑤쑤 새로운 페이지를 빨리 구현했네요 👏👏👏👏
수정방향에 대해서 코멘트를 남겨놨어요. 확인 부탁해요.

2024-07-24 04:33 UTC, BadaHertz52 commented on frontend/src/components/common/DropDown/styles.ts
> +  padding: 8px;
잡았다'px'

2024-07-24 04:33 UTC, BadaHertz52 commented on frontend/src/pages/ReviewPreviewListPage/components/SearchSection/index.tsx
> +  onChange: (value: string) => void;
새롭게 추가된 컨벤션에 따라서 `handleChange`로 바꿔주세요.

2024-07-24 04:33 UTC, BadaHertz52 commented on frontend/src/pages/ReviewPreviewListPage/index.tsx
> +const options = ['최신순', '오래된순'];
options가 상수로 사용되는 건가요?
상수라면 대문자로 사용해주세요.

2024-07-24 04:33 UTC, BadaHertz52 commented on frontend/src/components/ReviewPreviewCard/index.tsx
> +        <S.HeaderContainer>
HeaderContainer가 Header보다 상위에 있는 네이밍이라고 생각해요.
컴포넌트 트리상 Header가 HeaderContainer 의 부모 컴포넌트라서 네이밍상 안맞는 느낌이 드네요. 쑤쑤의 생각은 어떤가요?

2024-07-24 07:40 UTC, ImxYJL requested changes
이번 주 스케줄이 촉박했는데 빠른 시간 안에 만드느라 고생했어요~~ 간단한 코멘트 몇 개 남겼습니다!

2024-07-24 07:40 UTC, ImxYJL commented on frontend/src/components/ReviewPreviewCard/index.tsx
> +  keywords: { id: number; content: string }[];
키워드 관련 타입이나 인터페이스는 따로 없나요? 리터럴을 의도했다면 그 이유가 궁금해요!

2024-07-24 07:40 UTC, ImxYJL commented on frontend/src/pages/ReviewPreviewListPage/components/SearchSection/index.tsx
> +        <SearchInput $width="48rem" $height="100%" placeholder={placeholder} />
여기는 많은 스타일링이 들어가지 않아서 인라인으로 스타일 처리를 해 준 건지 궁금합니다!

2024-07-24 07:40 UTC, ImxYJL commented on frontend/src/pages/ReviewPreviewListPage/components/SearchSection/index.tsx
> +        <Button buttonType="secondary" text="검색" />
Button에 `aria-label`을 줘 보는 건 어떨까요? 
이미 Button을 button이라는 시맨틱 태그로 만들긴 했지만 이 버튼이 정확히 무슨 일을 하는지는 `aria-label`으로 지정해주는 것이 좋은 것 같습니다. 스크린 리더가 button 태그의 자식 (<button>안녕</button> 에서의 안녕)은 읽는데 이렇게 text로 버튼 텍스트 값을 주는 경우에는 안 읽는다고 해서요~

2024-07-24 23:37 UTC, soosoo22 commented on frontend/src/components/common/DropDown/index.tsx
> +    <S.Wrapper onChange={handleChange}>
여러개의 요소를 감싸고 있기 때문에 `Container`가 더 적절할 것 같네요! 감사해요~

2024-07-25 04:12 UTC, ImxYJL approved these changes
일단 어프루브 할게요! 리뷰 반영하느라 수고 많았어요~!~!

2024-07-25 04:30 UTC, BadaHertz52 approved these changes
오늘 4시 백엔드와의 연동을 위핸 우선 approve 할게요.
충돌되는 부분 해결한 후 머지해주세요.

2024-07-25 06:47 UTC, chysis approved these changes
고생하셨어요! 😊

2024-07-25 07:17 UTC, chysis approved these changes

2024-07-25 07:17 UTC, merged

2024-07-28 11:38 UTC, soosoo22 commented on frontend/src/components/common/DropDown/styles.ts
> +  padding: 8px;
아이고😅

2024-07-28 12:03 UTC, soosoo22 commented on frontend/src/components/ReviewPreviewCard/index.tsx
> +        <S.HeaderContainer>
생각해보니 `HeaderContainer`가 `Header`보다 하위에 있는 부분이 어색하네요.

`HeaderContent`로 바꾸어 볼게요~
```html
<Layout>
 <Header>
  <HeaderContent />
 </Header>
 <Main />
</Layout>
```

2024-07-28 12:08 UTC, soosoo22 commented on frontend/src/components/ReviewPreviewCard/index.tsx
> +  keywords: { id: number; content: string }[];
키워드 인터페이스가 정의되어 있네요~~
아래와 같이 수정했어요~~

```ts
export interface Keyword {
  id: number;
  content: string;
}

export interface ReviewPreview {
  id: number;
  isPublic: boolean;
  reviewerGroup: {
    id: number;
    name: string;
    thumbnailUrl: string;
  };
  createdAt: string;
  contentPreview: string;
  keywords: Keyword[];
}

```

2024-07-28 12:31 UTC, soosoo22 commented on frontend/src/pages/ReviewPreviewListPage/components/SearchSection/index.tsx
> +        <Button buttonType="secondary" text="검색" />
img 태그에 `alt` 주듯이 button 태그에도 `aria-label` 주는 것이 좋아보이네요~
고마워요!

2024-07-28 12:53 UTC, soosoo22 commented on frontend/src/pages/ReviewPreviewListPage/components/SearchSection/index.tsx
> +        <SearchInput $width="48rem" $height="100%" placeholder={placeholder} />
이미 공통 컴포넌트로 분리되어 있어서 사용한 거긴 합니다만 생각해보면  props를 사용함으로써 스타일링과 관련된 값을 컴포넌트에 동적으로 전달할 수 있다는 장점이 있을 것 같네요.

```ts
const SearchInput = ({ placeholder, $width, $height }: SearchInputProps) => {
  return <S.Input type="text" placeholder={placeholder} $width={$width} $height={$height} />;
};
```