[BE] refactor: Config 패키지 분리, 스타일 적용
woowacourse-teams/2024-review-me pull request #957
Opened 2024-11-09 04:48 UTC by donghoony

### 🚀 어떤 기능을 구현했나요 ?
- Config 폴더 안에 너무 많은 일을 하고 있어서, 내부 패키지를 분리했습니다. `WebConfig`를 삭제하고, 각각의 자리에서 필요한 Config를 사용하도록 합니다. 글로벌 컨픽이라는 건 현재는 크게 없다고 보았어요.
- `Logger`를 사용하는 곳이 좀 있어서 제거하고 `@Slf4j`를 적용했습니다.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 리뷰 그룹의 `SessionResolver`를 추가하는 `WebConfig`도 `reviewgroup` 패키지로 이동했어요. 이부분 어색하지 않은지만 확인해주세요.

### 📚 참고 자료, 할 말
- 정돈된 코드가 좋아요, 백로그 하나씩 쳐내보겠습니다

2024-11-09 12:55 UTC, skylar1220 approved these changes
> 리뷰 그룹의 SessionResolver를 추가하는 WebConfig도 reviewgroup 패키지로 이동했어요. 이부분 어색하지 않은지만 확인해주세요.

ReviewGroupWebConfig은 reviewgroup 컨트롤러로 들어오는 과정에서만 사용되니 충분히 맞다고 느껴져요~

2024-11-09 17:07 UTC, Kimprodp approved these changes
깔끔합니다 👍

2024-11-09 17:07 UTC, Kimprodp commented on backend/src/main/java/reviewme/global/exception/FieldErrorResponse.java
> +public record FieldErrorResponse(String field, Object value, String message) {
이건 왜 이렇게 변경했나요?

2024-11-10 03:02 UTC, nayonsoso requested changes
> Config 폴더 안에 너무 많은 일을 하고 있어서, 내부 패키지를 분리했습니다.

좋네요😄👍

—-

사실 처음에는 config 패키지가 설정만을 위한 패키지 같아서 RequestLimitInterceptor 와 TooManyRequestException 가 config 하위로 간다는게 어색하게 느껴지기도 했었는데요!

config 를 넓은 의미로 ‘어플리케이션의 설정’ 으로 본다면, 비니지스 로직과 설정을 분리하기 위한 것들로 해석될 수 있으니, 지금의 변화도 괜찮다 생각합니다😄👍 과도한 요청을 거부하는 것은 비지니스 로직은 아니니까요! 

——-

> 리뷰 그룹의 SessionResolver를 추가하는 WebConfig도 reviewgroup 패키지로 이동했어요. 이부분 어색하지 않은지만 확인해주세요.

그래서 위와 비슷한 논리로, ‘리뷰 그룹의 SessionResolver를 추가하는 WebConfig’ 는 어플리케이션 자체에 대한 구성이므로 이전 위치가 더 적절했다고 생각해요.!

2024-11-10 04:22 UTC, donghoony commented
- `Interceptor`/`ArgumentsResolver` 자체는 도메인 패키지 내부에 있는 게 자연스럽습니다. 하위 계층을 사용하기 때문입니다. (`ReviewGroupSessionResolver`의 경우 `ReviewGroupService`를 사용함)
- 다만 이를 스프링 빈으로 등록하는 `Config`는 도메인 하나에 귀속된다고 보기 어렵습니다.

따라서 `WebConfig`는 외부에 두고, 각각의 `Interceptor`/`Resolver`는 도메인 아래에 둡니다.

2024-11-10 04:25 UTC, nayonsoso approved these changes

2024-11-10 04:26 UTC, donghoony commented on backend/src/main/java/reviewme/global/exception/FieldErrorResponse.java
> +public record FieldErrorResponse(String field, Object value, String message) {
한줄로 둬도 안 넘어서 그냥 펼쳤습니다 ㅎㅎ,,

2024-11-10 04:29 UTC, merged