[BE] refactor: question 타입과 답변 내용 일치 검증 및 매핑 로직 개선
woowacourse-teams/2024-review-me pull request #958
Opened 2024-11-11 10:44 UTC by nayonsoso

- resolves #572 

---

### 🖼️ 배경
사실 처음에는 [이전 PR](https://github.com/woowacourse-teams/2024-review-me/pull/668)을 적용할 생각이었습니다.
그런데 하다보니 다른 방법이 더 좋겠다 싶어서 방향을 완전 바꿨습니다.. ㅎㅎ

이 이슈가 생겨난 이유에 대해서 생각해봤습니다.
처음 의도는  ‘형식 검증을 비지니스 로직에서 분리하자’는 것이었습니다.
그런데 구현을 하고 보니 dto 에서 이를 검증하더라도,
‘**질문의 유형에 해당하지 않은 응답 포함되었는지**’에 대한 검증이 추가로 필요한 것을 깨달았습니다.

- 이전에 dto에서 하려 했던 것은 question 에 상관없이 하나의 유형에 대한 응답만 있는지 검사
- 이와 별개로, question 과 관련된 유형에 대한 응답만 있는지 검사가 필요한 상황 

그런데 이 둘은 **중복된 검증**인 듯 해서, 후자의 검증만 남겨도 되겠다고 생각했습니다.

그래서 이제부터는 ‘어떻게 변경에 영향을 받지 않으면서 검증을 할 수 있을까?’가 고민되었습니다.
그래서 아루가 만들어준 추상화를 활용하는 방법으로 구현해봤습니다.

### 🔥 어떻게 해결했나요 ?
- AnswerMapper 에서 위 검증을 하게 했습니다.
- 저도 하면서 'mapper인데 이런 검증을 하는게 맞나?' 싶었는데, 지금의 구조에서는 validator 에서 할 수 있는 방법이 없었습니다😓
- 왜냐하면 지금 로직이 mapper - validator - save 인데, mapper 에서 Answer 를 반환하면 이후의 과정에서 
'request에 의도하지 않은 값이 온 상황'을 알 방법이 없기 때문입니다.
(이후에는 request가 아니라 domain을 보고 검증하므로)
- 혹시 더 좋은 방법이 있다면 코멘트로 남겨주세요🙇🏻‍♀️

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
1. AnswerMapper 를 인터페이스에서 추상 클래스로 바꿨는데요, 적절하다고 생각하시나요?
이유1) 오버라이드를 할 이유가 없는 함수를 final 로 두려고
이유2) 외부에서 호출해서 사용할 필요가 없는 함수를 protected 로 두려고
이유3) AnswerMapper 와 TextAnswerMapper / CheckboxAnswerMapper 는 논리적으로 `HAS` 보다 `IS` 관계라 생각해서

2. 템플릿 패턴을 적용하게 되었는데, (이게 목적은 아니었고 결과적으로 이게 되었어요) 읽기에 괜찮나요?
 
### 📚 참고 자료, 할 말
하하 어떤가요?

2024-11-11 11:13 UTC, donghoony requested changes
백로그 쳐내기 좋네요 👍🏻 코멘트 확인해주세용!

2024-11-11 11:13 UTC, donghoony commented on backend/src/test/java/reviewme/review/service/mapper/AnswerMapperFactoryTest.java
> +        protected boolean isAnswerEmpty(ReviewAnswerRequest request) {
개행 봐주세요~

2024-11-11 11:13 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/mapper/AnswerMapper.java
> +    }
`supports`를 `abstract`로 제공하지 않는 이유가 있나요? `getQuestionType`이 다른 곳에서 안 쓰이면 합치는 게 조금 더 낫겠다는 생각이 드네용~

2024-11-11 11:13 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
> +        return request.selectedOptionIds() != null && request.text() == null;
느슨하게 `selectedOptionIds`만 검증하는 걸 제안합니다. 아래 두 가지 이유인데요,

1. 서버 입장에서는 둘 다 오면 타입 따라서 검증하고 그 타입만 가져다 쓰면 된다고 생각해요. 설령 그게 잘못된 요청이더라도, 서버 입장에서는 잘못된? 악용된? 요청을 가릴 필요가 없다고 생각해요 (형식이 맞다면). 아래 두 로직 중 a가 조금 더 자연스럽다고 생각해요. 타입이 늘어나면 늘어나는 것에 대해서 모두 대응할 수 있지도 않고요.

  a. (객관식 타입이네? -> 객관식 Id 가져다 써야지~)
  b. (객관식 타입이네? -> 주관식 없나 볼까? -> 객관식 Id 가져다 써야지~)
(만약 타입이 더 많아지면: 객관식 확인 -> 객관식이 아닌 타입 **전부** 널 확인 -> 객관식 가져다쓰기)

2. `request`에 `text`가 존재한다는 걸 `CheckboxAnswerMapper`가 몰랐으면 좋겠습니다.

2024-11-11 11:13 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
> +        return request.selectedOptionIds() != null && request.selectedOptionIds().isEmpty();
질문, 반영 전에 코멘트 먼저 부탁합니다)

`null`이면 `false`를 리턴하면 안 되지 않나요? 문제 상황이라고 생각해서요

2024-11-11 11:13 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/mapper/ReviewMapper.java
> -
👍🏻

2024-11-11 11:13 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/mapper/AnswerMapper.java
> +    protected abstract Answer doMap(ReviewAnswerRequest answerRequest);
`doMap`보다 `mapInternal`과 같은 용어는 어떤가요? (단순 제안, 조금 더 명료한 네이밍이지 않나 해서요)

2024-11-11 11:13 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/mapper/AnswerMapper.java
> +        if(isAnswerEmpty(answerRequest)) {
```suggestion
        if (isAnswerEmpty(answerRequest)) {
```

2024-11-11 11:13 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/mapper/AnswerMapper.java
> +    protected abstract boolean isAnswerMatchesQuestionType(ReviewAnswerRequest request);
`containsQuestionTypeAnswer` 정도는 어떤가요?

2024-11-11 11:13 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/mapper/TextAnswerMapper.java
> +    }
뉴진스가 부릅니다 ditto

2024-11-11 11:13 UTC, donghoony commented on backend/src/test/java/reviewme/review/service/mapper/TextAnswerMapperTest.java
> +        TextAnswer actual = (TextAnswer) mapper.mapToAnswer(request);
캐스팅 살짝 위험할 수 있을 것 같은데, Mapper에 제네릭을 넣으면 해결되려나요?

2024-11-11 11:19 UTC, nayonsoso commented on backend/src/test/java/reviewme/review/service/mapper/AnswerMapperFactoryTest.java
> +        protected boolean isAnswerEmpty(ReviewAnswerRequest request) {
사실 이친구가 테스트에서 크게 중요한게 아님에도 라인만 잡아먹는 것 같아서 붙여버렸어요😅
그래도 역시 통일감 있게 띄는게 좋겠죠?

2024-11-11 11:24 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/mapper/AnswerMapper.java
> +    }
그것도 좋겠네요!

2024-11-11 11:38 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
> +        return request.selectedOptionIds() != null && request.text() == null;
> request에 text가 존재한다는 걸 CheckboxAnswerMapper가 몰랐으면 좋겠습니다.

이 말 때문에 마음이 이쪽으로 많이 기우는데요,
그런데 한가지 걸리는게 있어요🥲

사실 저도 이 부분에 대해서 '너무 빡빡하게 검증을 안하는게 좋지 않을까?' 라는 생각이 들기도 했었어요.
그럼에도 이렇게 구현한 이유는, 전에 말했던 '소프트웨어의 성질'을 따라야 한다고 생각했기 때문이에요.
_**대강 맞더라도, 서버와 약속한 형식과 100% 일치하는게 아니라면 예외를 응답해야 한다고 생각해요.**_
그것이.. api 명세이기 때문입니다.. 

![image](https://github.com/user-attachments/assets/54113587-3174-423c-a5eb-6768ec542c4c)

그래서 여기에 대해서는 다른 팀원들의 생각도 들어보고 싶어요!
@skylar1220 @Kimprodp

2024-11-11 12:23 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
> +        return request.selectedOptionIds() != null && request.selectedOptionIds().isEmpty();
이 함수는 자체로 의미가 있는 함수가 아니라, 아래의 mapToAnswer 안에서 호출되는 함수입니다.
그래서 _**앞서 null 이 아닌 것이 검증이 된 상태일테니**_ 위 로직이 가능하다고 생각해서 저렇게 만들었어요😅


```java
public final Answer mapToAnswer(ReviewAnswerRequest answerRequest) {
    if (!isAnswerMatchesQuestionType(answerRequest)) {
        throw new QuestionTypeAnswerMismatchException(answerRequest.questionId());
    }
    if (isAnswerEmpty(answerRequest)) { // 여기서 호출됨
        return null;
    }
    return doMap(answerRequest);
}
```

이게 템플릿 패턴의 장점이자 단점 같아요😞
공통되는 하나의 절차를 지정해놓고, 그 부품들을 하위 클래스에서 정의하니 
하위 클래스의 각각의 함수만 봤을 때는 전체 그림을 이해하기가 힘들어지네요.

만약 이를 해결하기 위해서 하위 클래스에서 절차를 지정하게 하면 
(즉, 위의 mapToAnswer 함수 전체를 하위 클래스에서 구현하기 하면)
그건 또 중복 코드같다고 느껴질 것 같아요🥲

뭐든 장단점이 있는 것 같은데, 제가 느끼기에 지금은 상위 클래스에서 절차를 지정해주는 지금의 방식이
mapper 의 동작을 이해하기에 더 쉽게 해주는 것 같아요~ 그래서 이 구조를 유지하고, 위 함수도 유지하고 싶어요.
아루의 생각은 어떤가요?

2024-11-11 12:26 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/mapper/AnswerMapper.java
> +    protected abstract Answer doMap(ReviewAnswerRequest answerRequest);
으엉 사실 doMap 으로 만들어두고 별로라고 생각하긴 했어요
이건 더 생각을 해볼게요..!

2024-11-11 12:31 UTC, nayonsoso commented on backend/src/test/java/reviewme/review/service/mapper/TextAnswerMapperTest.java
> +        TextAnswer actual = (TextAnswer) mapper.mapToAnswer(request);
`TextAnswerMapper extends AnswerMapper<TextAnswer>`
/ `CheckboxAnswerMapper extends AnswerMapper<CheckboxAnswer>`
이렇게 만들어서 제네릭을 사용해봤는데, 아래 코드에서 문제가 발생하더라고요😲

```java
@Component
@RequiredArgsConstructor
public class AnswerMapperFactory {

    private final List<AnswerMapper> answerMappers; // ❗️여기

    public AnswerMapper getAnswerMapper(QuestionType questionType) {
        return answerMappers.stream()
                .filter(answerMapper -> answerMapper.supports(questionType))
                .findFirst()
                .orElseThrow(() -> new UnsupportedQuestionTypeException(questionType));
    }
}
```
제네릭은 한번 정의가 되면 자식도 안되고 부모도 안되고 딱 그 타입만 받을 수 있어서 
TextAnswerMapper와 CheckboxAnswerMapper를 List로 받지 못하는 문제가 있었어요,

그리고 코드상에서 캐스팅은 저 테스트 코드에서만 있고, 프로덕션 코드에서는 Answer를 바로 저장하니 문제 없을 것 같아아요~

2024-11-11 12:32 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/mapper/TextAnswerMapper.java
> +    }
뉴진스가 부릅니다 ditto 에 대한 뉴진스가 부릅니다 ditto

2024-11-11 12:34 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/mapper/AnswerMapper.java
> +    protected abstract boolean isAnswerMatchesQuestionType(ReviewAnswerRequest request);
이건 이 함수가 어떤 역할을 하느냐에 따라서 달라질 것 같아요.
아루가 제안한대로 '질문에 대항하는 내용이 있는가'를 검증하려면 `containsQuestionTypeAnswer`가 더 적절하겠지만,
아직은 이 부분이 결정되지 않았으니 [이 부분](https://github.com/woowacourse-teams/2024-review-me/pull/958#discussion_r1836501570)이 결정되면 바꿔보도록 할게요!

2024-11-11 12:38 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
> +        return request.selectedOptionIds() != null && request.text() == null;
1. 100% 일치하지 않는 것에 대한 책임은 누가 지나요?
2. 100% 일치하지 않았을 경우 피해는 누가 보나요? 정말 피해가 맞나요?
3. 해당 경우를 고려하지 않았을 때의 사이드이펙트와 구현하는 데에 드는 자원을 생각했을 때 트레이드오프할 만큼 100% 일치하는 것이 중요한가요?

저는 1: 온전히 서버가 검증해야 함, 2: 서버가 봄, 단 그건 피해라고 보기 어려움, 3: 일치하는 것이 그렇게 중요하지 않음 (위 댓글의 `a`에 해당함)

이라서 좀 강하게 의견 내고싶긴 하네요 🤔

2024-11-11 12:43 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/mapper/AnswerMapper.java
> +    protected abstract boolean isAnswerMatchesQuestionType(ReviewAnswerRequest request);
현재 기존 메서드명도 `정답이 타입과 일치하는가?` 인데요 🤔

2024-11-11 12:44 UTC, donghoony commented on backend/src/test/java/reviewme/review/service/mapper/TextAnswerMapperTest.java
> +        TextAnswer actual = (TextAnswer) mapper.mapToAnswer(request);
프로덕션에서 캐스팅할 일 없으면 오케입니다 👍🏻

2024-11-11 12:53 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
> +        return request.selectedOptionIds() != null && request.text() == null;
약간 뭐랄까.. '이 선을 넘어도 될까?'의 느낌이라고 해야 할까요?
빡빡한 검증을 하지 않아도 되는건가? 이래도 되나? 싶은거죠 ㅎㅎㅠ
죄책감? 그런게 느껴진다고 해야할까요? 근거가 없는 생각일수도 있는데;; 무튼 그런 느낌이 들어요~~

2024-11-11 12:55 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
> +        return request.selectedOptionIds() != null && request.text() == null;
검증을 한 것이죠..? 무시하는 것도 하나의 방법이지 않을까요? 😁😁😁😁

2024-11-11 13:06 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
> +        return request.selectedOptionIds() != null && request.text() == null;
타협안 : 
- 처음 목표였던 "하나의 타입만 있는지"를 dto 에서 검증한다.
- 서비스에서는 questionType 에 해당하는 answer 만 검증한다.

2024-11-13 17:15 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
> +        return request.selectedOptionIds() != null && request.selectedOptionIds().isEmpty();
다른분들 의견 들어볼게요~!

2024-11-14 00:27 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
> +        return request.selectedOptionIds() != null && request.selectedOptionIds().isEmpty();
이 부분을 크게 느꼈어요. 
> 하위 클래스의 각각의 함수만 봤을 때는 전체 그림을 이해하기가 힘들어지네요.

그리고
> 앞의 `isAnswerMatchesQuestionType`에서 `request.selectedOptionIds() != null`를 했으니까 여기서는 이 조건이 당연히 만족한 상황이라고 가정한다.

1. 이걸 알기 위해서는 상위 메서드로 가서 이전에 호출된 메서드를 확인하고... 의 과정이 필요했고, 이해하는데 시간이 좀 걸렸어요! 
2. 나중에 변경이 필요할 때 앞, 뒤 맥락을 잘 고려하지 않으면 빈 틈이 생길 수도 있을 것 같아요.

따라서 앞의 맥락을 고려하지 않고 `isAnswerEmpty`에서 selectedOptionIds 자체와 내부요소가 null인지를 모두 검사하는 건 어떨까 싶어요~ 중복이 심하면 문제겠지만 지금정도의 `request.selectedOptionIds() == null` 조건 검사정도 중복은 괜찮다고 생각해서요!

2024-11-14 00:32 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
> +        return request.selectedOptionIds() != null && request.text() == null;
또또 두 타입을 한 번에 받는 dto 형식으로 인한 문제점이네요😂
머리로는 아루의 의견이 이해가는데, 저역시 마음으로는 산초의 찝찝함이 있어요.
하지만!
산초의 타협안으로 위 문제는 해결가능하겠네요. 타협안 한표합니다!

2024-11-14 00:33 UTC, skylar1220 requested changes
산초 고생많았어요 추상화를 최대한 활용한게 너무 좋네요!! 
전체적으로 이해를 하고(이해는 잘 됐어요!) 우선 코멘트로 얘기 진행중이어서 제 의견이 필요한 부분만 남겼습니다! 금요일 저녁에 꼼꼼히 보고 마저 남길게요😂

2024-11-14 14:42 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
> +        return request.selectedOptionIds() != null && request.text() == null;
저는 한 쪽으로 진행했으면 좋겠습니다,, 다 우리가 하거나 아니면 무시하거나요.

2024-11-14 17:07 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
> +        return request.selectedOptionIds() != null && request.text() == null;
계속해서 고민을 해봤습니다🧘
제 안의 선을 넘기까지..! 시간이 걸렸습니다.

결론적으로, 
- **이 검증이 해결할 수 있는 문제가 없다는 점**
다른 검증들과 비교했을 때, 이 검증은 역할이 없습니다.

- 이 검증이 **기동성(≒빠르게 코드를 만들고 부수기)을 떨어트리고 있다는 점**
크게 중요하지 않은 것 때문에 코드와 유지보수가 복잡해지고 있다는 생각이 들었습니다.

때문에 아루의 의견에 마음이 기울었습니다.

이 부분을 검증하지 않게 코드를 바꾼다면 많은것이 바뀔 것입니다.
아래의 템플릿 논의도 해결됩니다🤝
리뷰하기 쉽도록 커밋 잘 나눠서 이 PR에 붙여보겠습니다.

2024-11-14 17:13 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
> +        return request.selectedOptionIds() != null && request.text() == null;
노파심에 하는 이야긴데, 산초가 방어적으로 생각하는 게 설계 관점에서 크게 도움이 된 적이 여럿 있어요. 데이터 정합성은 특히나 외래 키를 들지 않는 경우에는 반드시 필요한 부분이기도 하고요.

이 부분에서 제가 조금 강하게 의견을 표출했던 부분은 1. 정합성과 관련없었고 2. 우리가 알아서 하면 되는 일이라서였습니다. 산초가 이전에 이야기해줬던 의견들을 모두 부정하는 것이 아니여요~

2024-11-14 17:57 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/mapper/AnswerMapper.java
> +    protected abstract boolean isAnswerMatchesQuestionType(ReviewAnswerRequest request);
다른 타입 동시에 들어오는지 검증하는 것이 삭제되었으므로 resolve 합니다~

2024-11-14 17:57 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/mapper/AnswerMapper.java
> +    protected abstract Answer doMap(ReviewAnswerRequest answerRequest);
다른 타입 동시에 들어오는지 검증하는 것이 삭제되었으므로 resolve 합니다~

2024-11-14 17:59 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
> +        return request.selectedOptionIds() != null && request.selectedOptionIds().isEmpty();
이 부분에 대해서도 탬플릿 패턴이 없어졌기 때문에 resolve 합니다 ㅎㅎ
같이 고민해줘서 고마워요!!
커비 의견은 템플릿 패턴 살렸으면 꼭 반영했었을거예요😇

2024-11-14 18:26 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
> +            return null;
변경하고 왔습니다🤗
변경을 하고 나니 책임이 확실히 보이네요.
특히나 TextMapper / ChechboxMapper 가 명확해져서 보기 좋습니다!!

그런데 책임이 명확해지니 어색하게 느껴지는 부분이 있었습니다.
지금은 "비어있는 답변을 저장하지 않기" 라는 정책에 해당하는 로직이 mapper 에 있습니다.
그런데 이건 mapper의 책임이 아니라는 생각이 들었습니다.

왜 이런 일이 생겼는가 해서 ReviewRegisterService 를 보니,

```java
public long registerReview(ReviewRegisterRequest request) {
      Review review = reviewMapper.mapToReview(request);
      reviewValidator.validate(review);
      Review registeredReview = reviewRepository.save(review);

      return registeredReview.getId();
  }
```
이 로직이 들어갈 틈이 없었습니다...

그래서 mapper -> validator -> save 의 흐름이 적절했나? 하는 의문이 듭니다.
이 PR에서 조정하기에는 대공사가 될 듯 해서 이 작업은 하지 않았습니다만,
구현을 하면서 들었던 어색한 느낌을 공유하고자 말씀드려봅니다💁🏻‍♀️

2024-11-15 05:20 UTC, donghoony requested changes
제대로 확인하고 몇 가지 수정 제안해요~

2024-11-15 05:20 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/mapper/AnswerMapper.java
> +    protected abstract Answer mapToAnswer(ReviewAnswerRequest answerRequest);
굳?이 `protected`를 줄 필요가 있나 싶어용. 상속받는 친구가 쓸 것이긴 한데 외부에 보여질 메서드니까 `public`은 어떤지 제안합니다 (`public`, `private` 두 가지로 통일하면 좋겠다는 의미)

2024-11-15 05:20 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/dto/request/ReviewAnswerRequest.java
> +    public boolean isSelectedOptionIdsEmpty() {
`hasNoText` && `hasNoSelectedOptions` ?

2024-11-15 05:20 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
> +        if(answerRequest.isSelectedOptionIdsEmpty()) {
띄어쓰기요~

2024-11-15 05:20 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/mapper/ReviewMapper.java
>          return answerMapper.mapToAnswer(answerRequest);
```suggestion
        QuestionType questionType = question.getQuestionType();
        return answerMapperFactory.getAnswerMapper(questionType)
                .mapToAnswer(answerRequest);
```
하나의 제안입니다 무시해도 괜찮아요 (AnswerMapper를 변수로 굳이 둘 필요가 없다?)

2024-11-15 05:20 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/mapper/TextAnswerMapper.java
> +        if(answerRequest.isTextEmpty()) {
복?붙했나요?? 띄어쓰기 똑같은데 :rage1:

2024-11-15 05:20 UTC, donghoony commented on backend/src/test/java/reviewme/review/service/mapper/CheckboxAnswerMapperTest.java
> +        assertThat(actual).isNull();
`mapToAnswer`가 `null`을 리턴하는 경우 어떻게 되는가? 에 대한 정답이 `ReviewMapper:60`까지 들어가야 알 수 있어요. 다른 방법이 없을 지 생각해봐야겠습니다 🤔

2024-11-15 06:57 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/mapper/AnswerMapper.java
> +    protected abstract Answer mapToAnswer(ReviewAnswerRequest answerRequest);
protected 를 씀으로써 'mapper 패키지 안에서만 사용될 함수' 임을 드러낼 수 있으니 
저는 지금이 좋다고 생각해요!

2024-11-15 07:00 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/dto/request/ReviewAnswerRequest.java
> +    public boolean isSelectedOptionIdsEmpty() {
영어 문장으로 본다면
answerRequest is selected optionIds empty 보다
answerRequest has no text 가 더 자연스럽겠네요👍

함수 이름을 지을 때 사용되는 곳에서 자연스럽게 읽히는지도 고려해야 한다는 것을 배워갑니당...

2024-11-15 07:00 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
> +        if(answerRequest.isSelectedOptionIdsEmpty()) {
긁적....

2024-11-15 07:01 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/mapper/TextAnswerMapper.java
> +        if(answerRequest.isTextEmpty()) {
하.하.하. 우연이 아닐까요? 🙄

2024-11-15 07:02 UTC, nayonsoso commented on backend/src/test/java/reviewme/review/service/mapper/CheckboxAnswerMapperTest.java
> +        assertThat(actual).isNull();
맞아요 ㅠㅠ
흐름을 모르면 여기서 갑자기 왜 매핑을 안하고 null 을 반환하는지 헷갈릴 것 같아요

2024-11-15 07:06 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/mapper/ReviewMapper.java
>          return answerMapper.mapToAnswer(answerRequest);
좋아보여서 반영합니다😄

2024-11-15 11:26 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/mapper/AnswerMapper.java
> +    protected abstract Answer mapToAnswer(ReviewAnswerRequest answerRequest);
어음,, 퍼블릭으로 두면 안 될까요? 추가적인 인지부하를 피하고 싶어요 ㅎㅎ,,

2024-11-15 13:38 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/mapper/AnswerMapper.java
> +    protected abstract Answer mapToAnswer(ReviewAnswerRequest answerRequest);
**💬 기록용으로 남기는 우리의 디스코드 대화 💬**

산초 : 
접근 제한자를 문제 삼아서 다시 코드를 보니, 우리 코드에서 엄격하게 지키고 있지 않네요.! 그럼 기존에 팀이 하던대로 하는게 맞는 것 같습니다. 
하지만 만약 제게 온전히 결정권이 있다면, 패키지 외부에서 접근할 수 있는 함수들을 명확히 하는 방향(default를 활용하는)으로 코드를 바꿨을 것 같습니다. 지금은 개발 초기 단계가 아니라, 변경으로 인해서 접근제한자가 바뀌는 경우가 적을 것이라 생각해요. 그래서 아루가 걱정했던 인지부하도 크지 않을 것 같고요. 그리고 도메인간 패키지 뿐 아니라, service.mapper 와 service 사이도 노출하는 것과 아닌 것을 명확히 구분할 필요가 있다 생각해요. 패키지 차원의 캡슐화를 생각하면요. 
물론 이렇게 해서 얻을 수 있는 효과가 크진 않습니다.. 우리가 개발자가 많은 팀인 상태에서, 패키지간 구분을 명확히 함으로써 다른 개발자의 실수를 막을 수 있는 것도 아니고요😅 하지만 **이렇게 하는 것이 패키지와 접근제한자의 탄생 이유나, 접근 제한자의 존재 이유를 지키는 방향이라고 생각해요.** 하지만 다시 돌아와서, 우리 팀에서 지금 엄격하게 지키고 있지 않고, 이 PR에서 프로젝트 전반의 접근제한자 컨벤션을 어기면서까지 할 필요는 없다고 생각해서 public 으로 하고 넘어가겠습니다.

아루 : 
탄생 이유, 존재 이유를 가지고 파고들면 안 쓸 이유가 없죠.
근데 우리는 그 쪽에 집중하는 것보다 **변하고 보수하기 쉬운 쪽에 집중해야 합니다.**
그래야 나중에 요구사항이 변했을 때, 혹은 리팩터링 과정에서 패키지를 옮길 때 코드의 변화를 최소화할 수 있어요
트레이드 오프긴 한데, 웹 서비스의 유지보수 관점이라면 펍/프라이빗이 좋다고 보여지고 
라이브러리나 프레임워크의 성격이 강한 프로젝트라면 지켜주는 게 좋겠네요.

산초가 내린 결론 : 팀의 컨벤션 & 유지보수성을 생각해서 mapper 에 있는 함수들을 public 으로 변경

2024-11-15 13:54 UTC, donghoony approved these changes
고생했어요 🚀

2024-11-16 06:33 UTC, skylar1220 requested changes
산초의 이 리팩토링 흐름이 좋았어요. 

타입 분기를 answerMapper 속으로 이동 > 템플릿 패턴 적용 > 고정된 패턴 없이 각 mapper들이 알아서 매핑을 구현하게 자유도를 높임 > 유연하게  확장 가능

직접 옮겨보고, 문제점을 느끼고 개선하는 자세를 저도 배워야겠어요..!

null 반환해서 상위에서 filter하는 부분이 이해가 안가서 그 부분 하나만 보려고 rc해요!

2024-11-16 06:33 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
> +            return null;
변경 후, mapper에 유일하게 남은 검증 책임이 `비어있는 답변을 저장하지 않기`군요.

> mapper -> validator -> save 의 흐름이 적절했나?

mapper를 하고 validator를 하는 흐름이 어색하게 _느껴지긴_ 한데, 일어나야하는 _순서상_ 은 맞다고 생각해요. 
1. 형식 검증은 dto에서 끝냄
3. 따라서 형식에 문제가 없으니 도메인 객체로 만들 수 있음
4. 도메인 객체로 만드는 과정에서 도메인에서 검증할 부분은 도메인으로 넘기고, 정책상 잘못된 부분은 validator로 검증함. 

하지만 우리 api의 request 형태상 이런 문제가 발생하네요.
1. request에 질문 타입(text)과 일치하지 않는 타입의 답변(checkBox)에는 null이 들어올 수밖에 없음
2. dto 안에서 질문타입과 일치하는 답변이 null인지 확인하는 것은 dto의 과한 책임이라 분명 형식 검증이지만, 서비스로 올라올 수밖에 없음

즉, mapper -> validator -> save 흐름 자체에는 문제가 없다. null을 허용하는 우리의 request 정책(?)의 문제다.

그래서 결론적으로 어떻게 해야하나!
고민중입니다ㅎㅎ 일단 제가 어색함을 느낀 이유 중간 정리였습니다😎

2024-11-16 06:33 UTC, hyeonji1220 commented on backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
> +        return request.selectedOptionIds() != null && request.text() == null;
아래와 같은 포인트들에 공감해 동의합니다~

1. 빠르게 코드를 만들고 부수기를 떨어트리고 있다.
2. (브라우저가 아닌 곳에서) 형식을 맞춰서 보낸 요청을 저장하나, 형식이 잘못된 요청을 저장하나 그저 '저장되는 데이터가 늘어난다' 이외에는 서버 측면에서 부담이 가는 사이드 이펙트가 없다.

2024-11-16 06:33 UTC, hyeonji1220 commented on backend/src/test/java/reviewme/review/service/mapper/CheckboxAnswerMapperTest.java
> +        assertThat(actual).isNull();
> answerMapper에서는 답변이 없으면 null을 리턴하고
> 그 결과를 reviewMapper에서 null이면 저장하지 않는다.

이 흐름 자체가 문제겠네요. 그런데 어디부터 손을 보는 게 적절한건지 고민이에요.

1번) 근본적으로 보면 null을 허용하는 dto 정책일 수도 있다는 생각
vs 
2번) 일단 현재 dto는 두고 현재의 문제인, 답변이 없는 상황 자체에서 예외를 발생하는 것이 자연스러우니 그 흐름대로 구현하는 방법 생각해보기

2024-11-16 06:33 UTC, skylar1220 commented on backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
> +            return null;
질문) 

이렇게 1,2,3번 순서대로 실행될때,
어차피 questionType을 통해 mapper를 checkboxAnswerMapper로 지정되어 들어갈건데 2번에서 바로 예외를 터뜨리면 안되는 상황이 있나요?
왜 2번에서 null을 반환하고 상위(3번)에서 거를까요?

이전에 이 논의를 했던 것 같은데 기억이 잘 안나서요~~
```java
@Component
public class CheckboxAnswerMapper extends AnswerMapper {

    @Override
    public boolean supports(QuestionType questionType) {
        return questionType == QuestionType.CHECKBOX;
    }

    @Override
    public CheckboxAnswer mapToAnswer(ReviewAnswerRequest answerRequest) {
        if (answerRequest.hasNoSelectedOptions()) {
            return null; // 2번
        }
        return new CheckboxAnswer(answerRequest.questionId(), answerRequest.selectedOptionIds());
    }
}

```

```java
public class ReviewMapper {

    private List<Answer> getAnswersByQuestionType(ReviewRegisterRequest request) {
        ...

        return request.answers()
                .stream()
                .map(answerRequest -> mapRequestToAnswer(questionMap, answerRequest))
                .filter(Objects::nonNull) // 3번
                .toList();
    }

    private Answer mapRequestToAnswer(Map<Long, Question> questions, ReviewAnswerRequest answerRequest) {
        ...

        AnswerMapper answerMapper = answerMapperFactory.getAnswerMapper(question.getQuestionType());
        return answerMapper.mapToAnswer(answerRequest); // 1번
    }
}

```

2024-11-19 12:56 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
> +            return null;
> 2번에서 바로 예외를 터뜨리면 안되는 상황이 있나요?

네, 도메인으로 변환을 하는 과정 중에 예외를 터뜨리면 안됩니다.

필수가 아닌 질문에 답을 하지 않을 경우 빈 답변이 옵니다.
빈 답변을 도메인으로 변환하려 하면 도메인의 생성자에서 예외가 발생합니다. [참고](https://github.com/woowacourse-teams/2024-review-me/blob/develop/backend/src/main/java/reviewme/review/domain/CheckboxAnswer.java)

필수가 아닌 질문에 답을 하지 않은 경우 예외를 발생시키는 것은 말이 되지 않습니다.
필수가 아닌 질문에 답을 하지 않은 것이 이상한 상황은 아니기 때문입니다.
따라서 null 을 반환하게 하여 매핑 과정에서 무시하게 했습니다.

커비와 아루가 [이 코멘트](https://github.com/woowacourse-teams/2024-review-me/pull/958#discussion_r1843202032)에서 말한 것처럼, 저도 이 흐름이 베스트는 아니라고 생각합니다.
하지만 개인적으로 이 PR이 담고 있는 것이 너무 길어지는 것 같아 다른 PR 에서 해결하는 것이 좋겠습니다.!

2024-11-20 04:44 UTC, skylar1220 approved these changes
null 반환에 대해서 답변 남긴거 확인했어요!
(얘 참 찝찝하네요😂 나중에 '왜 이렇게 null을 반환하게 했지?'하고 생각할 게 상상되는 부분..)
고생 많았어요 산쵸!!

2024-11-20 14:51 UTC, Kimprodp requested changes
하나만 확인해주세용~

그리고 본문에서
이유1) 오버라이드를 할 이유가 없는 함수를 final 로 두려고
이유2) 외부에서 호출해서 사용할 필요가 없는 함수를 protected 로 두려고
이 내용은 어디에 해당된느건가요..? 이해를 못했습니다

2024-11-20 14:51 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/service/mapper/TextAnswerMapper.java
> +        if (answerRequest.hasNoText()) {
이것만 검증하면 질문의 타입이 TEXT 이고, text와 selectedOptionIds 둘 다 있는 요청일때 TextAnswer 생성되지 않나요? (반대의 경우도 동일)

둘 다 들어온 경우에는 등록을 하면 안되지 않을까 합니다. (정상적이지 않은 요청)

2024-11-20 17:56 UTC, donghoony commented on backend/src/main/java/reviewme/review/service/mapper/TextAnswerMapper.java
> +        if (answerRequest.hasNoText()) {
https://github.com/woowacourse-teams/2024-review-me/pull/958#discussion_r1836501570

이거 확인해주세용~!

2024-11-21 05:51 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/mapper/TextAnswerMapper.java
> +        if (answerRequest.hasNoText()) {
> 그리고 본문에서
이유1) 오버라이드를 할 이유가 없는 함수를 final 로 두려고
이유2) 외부에서 호출해서 사용할 필요가 없는 함수를 protected 로 두려고
이 내용은 어디에 해당된느건가요..? 

처음에는 AnswerMapper에서 '질문의 타입에 해당하는 답변이 오지 않았을 때의 검증'을 잘 하기 위해서 템플릿 메서드 패턴을 사용했었습니다. 그리고 이때 final 함수가 필요했습니다. 그런데 코멘트를 반영하며 이 검증을 하지 않게 되면서 삭제했습니다😊 커밋 : https://github.com/woowacourse-teams/2024-review-me/pull/958/commits/4b2bbd1c888872921fa85201f725234c19f1aad2

그리고 protected 키워드도 사용하지 않기로 바꿨는데, 이 코멘트 참고하면 됩니다!

2024-11-21 23:21 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
> +        return request.selectedOptionIds() != null && request.text() == null;
사실 지금 저 검증이 의미가 없는 건 맞습니다. API 형식을 정했고 그에 대한 검증은 해야 한다고 생각해요.
다만, 지금 이렇게 고민이 벌어지고 있는 이유. 즉, 이 검증을 하는 것에 타협안을 둔다는 것이 요청이 검증을 힘들게 하진 않나? 고민해볼 필요가 있다고 생각합니다. 위 내용처럼 **질문 타입이 늘어날수록 검증도 추가**되어야 해요. 그럼 검증이 꼭 필요한가? 보다는 **요청이 확장성 있게 고려되지 않은 것이 아닐까?** 라는 생각이 듭니다.

잘못된 요청에 피해가 없는 것처럼 보이더라도 원하지 않는 요청에 데이터가 저장이 될 수 있어요. 서버는 몰라도 API 요청자는 저장되지 않길 바라는 요청이 서버에 저장될 수 있을 수 있다고 생각합니다.

최근 다시 공유된 개발자 머피 법칙에도 비슷한 경우가 있어요. 우리의 API를 호출하는 사람은 클라이언트 뿐만이 아닙니다. 누군가가 하나만 보내도 되는건지, 둘 다 보내야 되는건지 헷갈려서 요청을 보낼 수도 있고  그 과정에서 여러 요청을 보낼 수 있습니다.
![image](https://github.com/user-attachments/assets/d0f3c16d-bbe2-4b64-a601-3619167e5f09)


그래서 결론,
제 의견은 현재 단계에서는 검증을 추가하는 것이 맞고, 추후 질문 타입이 증가할수록 검증도 늘어나는 부분에 대한 고민은 요청에 대한 형식이나 방법을 다시 생각하면 좋겠어요. (당장 아니더라도) 지금 단계에서 원래 있던 검증이고 굳이 제외할 필요는 없다고 생각해요.

2024-11-21 23:24 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/service/mapper/TextAnswerMapper.java
> +        if (answerRequest.hasNoText()) {
https://github.com/woowacourse-teams/2024-review-me/pull/958#discussion_r1853074890
관련해서 의견 남겼어요~ 다음 의견에 대한 결론이 제 결론과 다르더라도 어프룹 할게요. 확인만 해주세요~

2024-11-21 23:27 UTC, Kimprodp commented on backend/src/main/java/reviewme/review/service/mapper/TextAnswerMapper.java
> +        if (answerRequest.hasNoText()) {
추가로 산초에게 질문을 하나만 더할게요, (단순 궁금)

"AnswerMapper 를 인터페이스에서 추상 클래스로 바꿨는데요, 적절하다고 생각하시나요?" 이 부분에서
**이유 3**은 저도 공감합니다. 
그리고 **이유 1**과 **이유 2**는 사라진 상태인데요. 그럼 **이유 3**만으로 추상 클래스가 적절하다고 생각되어 바뀌는 부분인가요? 타입만 변경되고 다른건 변경되는 게 없어보여요.

2024-11-22 12:16 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/mapper/CheckboxAnswerMapper.java
> +        return request.selectedOptionIds() != null && request.text() == null;
> 우린 API 형식을 정했고 그에 대한 검증은 해야 한다고 생각해요.

사실 api 명세라는 것도 우리의 협으로 만들어지는 것입니다. 그래서 “중요하지 않은 검증에 코드가 길어지는 것을 막기 위해 유연한 요청을 받겠다” 고 합의를 한다면 그게 또 다른 api 명세가 되는 것이라 생각해요. 그러니까 우리의 지금 상황은 api 명세 위반이 아니라 api 명세 변경에 가깝다 생각합니다.

그리고 다른 개발자들이 실수로 api 호출하는 것은 우리 팀 정도의 규모에서는 일어나지 않을 것이므로, 고려하지 않아도 될것이라 생각합니다👍 사실 이건 트레이드 오프 영역이긴 한데, 우리의 **_현재 상황에 더 이득이 되는 것을 생각했을 때_** 빡빡한 검증을 하지 않음으로써 얻는 간편함이 더 크다 생각해요.

2024-11-22 12:30 UTC, nayonsoso commented on backend/src/main/java/reviewme/review/service/mapper/TextAnswerMapper.java
> +        if (answerRequest.hasNoText()) {
사실 이 경우 인터페이스로 하던, 추상클래스로 하던 문제가 되진 않아요.
그런데 저는 의미상 추상클래스에 더 가깝다 생각했습니다.
인터페이스는 다중 구현이 가능하므로 '기능'이나 '명세'에 초점이 맞춰져있다면 (HAS-A)
추상클래스는 단일 상속만 가능하므로 '소속'을 의미한다고 생각합니다. (IS-A)

그런데 지금 다시 생각하니, AnswerMapper 가 중복 코드를 줄이는 구현을 제공하지 않는 이상
추상클래스로 할 이유도 없는 것 같긴 합니다😅
생각을 바꾼 계기는, 자바의 컬렉션을 생각해봤을 때 ArrayList 가 
인터페이스 List 를 구현함으로써 기능에 대한 명세를 지키고, 
AbstractList 를 상속함으로써 중복되는 구체 메서드를 재사용했다는 것을 떠올렸어요.
그러므로 다시 인터페이스로 바꾸도록 하겠습니다😊

2024-11-22 15:14 UTC, Kimprodp approved these changes
고생했습니다 초~ 꼼꼼하게 확인해주어 고맙습니다

2024-11-22 15:32 UTC, merged