[BE] feat: 하이라이트 벌크 삽입 추가
woowacourse-teams/2024-review-me pull request #961
Opened 2024-11-13 12:15 UTC by donghoony

- resolves #878 

---

### 🚀 어떤 기능을 구현했나요 ?
- 하이라이트를 하나의 쿼리로 삽입하도록 수정합니다.

### 🔥 어떻게 해결했나요 ?
- JdbcTemplate의 `batchUpdate`를 사용했습니다. 자세한 사항은 #878 을 확인해주세요.

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- `Impl`은 Spring에서 이렇게 적어야 한다고 해서.. 안 적으면 제대로 잡아오지를 못하더라고요. `JpaRepository`를 `Repository`로 변경하고, `saveAll` 메서드를 `JdbcTemplate`를 활용한 것을 사용하도록 했어요.

### 📚 참고 자료, 할 말
- #878

2024-11-14 14:15 UTC, Kimprodp requested changes
궁금증만 해소해주십쇼~

2024-11-14 14:15 UTC, Kimprodp commented on backend/src/main/java/reviewme/highlight/repository/HighlightRepository.java
> +    boolean existsById(long id);
save, existsById 구현 없는데 동작 하나요? 어떻게 하는거지..

2024-11-14 14:15 UTC, Kimprodp commented on backend/src/main/java/reviewme/highlight/repository/HighlightRepository.java
> +
saveAll 같이 HighlightJdbcRepository 에서 구현된 메서드는 직접 들어가야지만 존재하는지 알 수 있으니 불편하네요. HighlightRepository 에서 사용 가능한 메서드를 다 바로 확인하면 좋을 텐데..

2024-11-14 16:36 UTC, nayonsoso approved these changes
> JdbcTemplate의 batchUpdate를 사용했습니다. 자세한 사항은 이슈를 확인해주세요.

확인했습니다😊
덕분에 saveAll 의 성능 문제에 대해서 알게 되었네요.
사실 saveAll 을 하더라도 “영속성 컨텍스트의 쓰기 지연” 때문에 
한번에 DB 로 전달될 것이므로 오버헤드가 크지 않을것이라 생각했어요.
그런데 한번에 DB 에 전달하더라도 DB 에서는 순차적으로 실행될테니 bulk insert 보다는 성능이 안좋겠네요😓

> Impl은 Spring에서 이렇게 적어야 한다고 해서.. 안 적으면 제대로 잡아오지를 못하더라고요.

와우 바꿔서 돌려봤는데 진짜 못잡아오네요🙄

---

추가로, 지금의 코드에서는 벌크 insert하는 sql이 로그에 안남는데, 이건 괜찮으려나요?
application.yml 아 아래 두라인 추가하니 로그에 남긴 합니다!
```yml
logging:
  level:
    springframework: DEBUG
    // 아래 두 라인
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
```

2024-11-14 16:36 UTC, nayonsoso commented on backend/src/main/java/reviewme/highlight/repository/HighlightJdbcRepositoryImpl.java
> +    }
이슈에서는 NamedParameterJdbcTemplate를 언급했는데, 여기에선 사용하지 않은 이유가 있나요?

2024-11-14 16:36 UTC, nayonsoso commented on backend/src/main/java/reviewme/highlight/repository/HighlightRepository.java
> +public interface HighlightRepository extends Repository<Highlight, Long>, HighlightJdbcRepository {
JpaRepository 에서 Repository 로 바꾼 것은, 
JpaRepository에서 기본으로 제공하는 saveAll 와 HighlightJdbcRepository 에서 선언한 saveAll 것 사이에 충돌을 피하기 위해서 맞나요?

사실 다른 XXXRepository 들이 다 JpaRepository를 상속하고 있어서, **_통일감이 없다_** 는 느낌을 받았어요🥲
그래서 HighlightRepository 가 JpaRepository를 상속하면서 HighlightJdbcRepository의 saveAll 을 사용할 수 있는 방법이 있을까 알아보니
메서드 **_이름을 다르게 하는 방법_** 밖에 없네요 (e.g. saveInBatch)
그런데 이렇게 한다면 ‘데이터베이스에 저장되는 방식에 따라서 서비스에서 다른 함수를 호출하게’ 하는 것이므로 좋지 않은 것 같아요😱
서비스는 그런걸 알 필요가 없으니깐요..
**_그렇게 아루의 지금 방법이 좋겠다고 납득하게 되었습니다👍_**

2024-11-14 16:41 UTC, nayonsoso commented on backend/src/main/java/reviewme/highlight/repository/HighlightRepository.java
> +    boolean existsById(long id);
Repository 인터페이스에 대한 프록시를 생성할 때 
Spring Data JPA가 메서드 이름을 분석하여 자동으로 쿼리를 생성하고 실행한다고 합니다!

2024-11-14 16:59 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/repository/HighlightRepository.java
> +    boolean existsById(long id);
산초가 이야기한것처럼 `Repository`의 메서드 이름으로 쿼리를 만들어줍니다요~!

2024-11-14 16:59 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/repository/HighlightRepository.java
> +
이건 저도 고민.. 계층을 두는 게 좋을까요?

2024-11-14 17:17 UTC, nayonsoso approved these changes
NamedParameterJdbcTemplate 확인 완!
수고했습니다~~ 🙌

2024-11-14 17:18 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/repository/HighlightJdbcRepositoryImpl.java
> +    }
36d558c :+1

2024-11-14 17:19 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/repository/HighlightRepository.java
> +public interface HighlightRepository extends Repository<Highlight, Long>, HighlightJdbcRepository {
> JpaRepository 상속에서 Repository 상속으로 바꾼 것은, JpaRepository에서 기본으로 제공하는 saveAll 와 HighlightJdbcRepository 에서 선언한 saveAll 것 사이에 충돌을 피하기 위해서 맞나요?

네, 그리고 테스트에서 `findAll`와 같은 메서드가 사용되는 걸 보고 (테스트에서만 사용되는 메서드를 정의한 것과 같음) 경계하게 되어 아예 내렸습니다. 충돌을 피하기 위해서 진행하긴 했지만, 후자의 이유가 조금 더 강합니다.

2024-11-15 13:49 UTC, nayonsoso commented on backend/src/main/java/reviewme/highlight/repository/HighlightRepository.java
> +
> saveAll 같이 HighlightJdbcRepository 에서 구현된 메서드는 직접 들어가야지만 존재하는지 알 수 있으니 불편하네요. 

저는 이게 크게 불편하게 느껴지지 않았어요. 이대로도 괜찮다 생각해요!

2024-11-16 03:39 UTC, Kimprodp commented on backend/src/main/java/reviewme/highlight/repository/HighlightRepository.java
> +    boolean existsById(long id);
아하 이해했슴다 단순 Repository 상속이라 안되는줄 알았는데 다 해주는구나..

2024-11-16 03:41 UTC, Kimprodp commented on backend/src/main/java/reviewme/highlight/repository/HighlightRepository.java
> +
보는건 그냥 찾아보면 될텐데 아마 서비스단에서 직접 레포를 사용해야 할 때 불편할 것 같아요. 이 부분은 다음에 고민하도록 해볼게요

2024-11-16 03:42 UTC, Kimprodp approved these changes

2024-11-16 06:53 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/repository/HighlightRepository.java
> +
질문)
> 계층을 두는 게 좋을까요?

계층을 둔다는 게 어떤 의미일까요?

제안)
default 메서드를 활용하는 방법은 어떨까요?

```java
// HighlightRepository
default void batchSaveAll(Collection<Highlight> highlights) {
    saveAll(highlights);
}
```

2024-11-16 07:04 UTC, skylar1220 requested changes
> HighlightJdbcRepository 에서 구현된 메서드는 직접 들어가야지만 존재하는지 알 수 있으니 불편하네요

테드의 이 부분에 대해 질문 + 제안 딱 하나 있습니다!!

2024-11-16 12:04 UTC, donghoony commented on backend/src/main/java/reviewme/highlight/repository/HighlightRepository.java
> +
해당 Repo가 배치를 하는지 여부를 Repository가 알아야 하나요 ? 🤔

2024-11-16 13:35 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/repository/HighlightRepository.java
> +
흠 왜 불편함을 느꼈나 다시 생각해봤어요..!

제가 느꼈던 건 HighlightJdbcRepository의 saveAll을 파악하는데 어려움이 있다
→ `repository가 의존하는 계층이 너무 깊어서 파악하기 어렵지 않나` 때문이었다는 걸 다시 깨달았습니다😂

repository 계층이 하나로 모두 깊지않게 관리하려면, 
서비스가 `Highlight(Jpa)Repository`와 `HighlightJdbcRepository`를 모두 의존하고, batch Insert 할때는 `HighlightJdbcRepository.saveAll`을 호출하면 되긴 하겠죠. 하지만 그렇게 하면 인지 부하의 문제가 또 있겠네요(batch insert할때는 HighlightJdbcRepository 쓰는 거 기억해야함!!)

2024-11-17 00:48 UTC, skylar1220 commented on backend/src/main/java/reviewme/highlight/repository/HighlightRepository.java
> +
> 아루: 지금 충분히 변경에 열려 있다고 생각해서 그대로 두는 건 어떤가요

변경에 열려있다는 점에는 동의해요! 다만, 호출하는 repository의 계층이 깊어서 항상 저 부분을 파악할 때 직관적이지 않다는 느낌을 받을 것 같다는 생각에 계속 걸렸어요. 하지만 이 역시 예상이니 현재 방식대로 적용해보고 리팩토링 하는 것 좋습니다!

2024-11-17 00:50 UTC, skylar1220 approved these changes
벌크 인서트의 여러 방식을 비교해준 덕분에 저도 공부할 수 있었어요👍👍
하이라이트의 병목 원인 중 하나가 해결됐네요!!
호출하는 repository의 계층이 깊은 문제는 지켜보도록 해요😀

2024-11-17 07:00 UTC, donghoony commented
Secret의 dev, prod-write db에 `rewriteBatchedStatements=true`를 추가했습니다.

2024-11-17 07:00 UTC, merged